import { LESSON_ID_APARTMENT } from '../../core/constants.js';

export const lessonId = LESSON_ID_APARTMENT;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Apartment & Problems",
        lessonTitle: "Unit 10 - Apartment Hunting & Building Problems in Gaza Palestinian Arabic",
        contentVersion: 2026071501,
    },

    overview: {
        title: "Unit 10 - Apartment Hunting & Building Problems",
        description:
            "Students learn how to look for an apartment, ask about rent, floor, rooms, neighbours, balcony view, and common building problems in natural Gaza Palestinian Arabic.",
        goals: [
            "Ask about available apartments, floor, rent, deposit, and number of apartments per floor.",
            "Describe parts of a building: apartment, building, hallway, rooftop, balcony, kitchen, bathroom, and living room.",
            "Ask about neighbours, noise, humidity, electricity, internet, heater, elevator, and repairs.",
            "Use location words naturally: inside, outside, above, below, next to, in front of, behind, between.",
            "Speak politely with a landlord, neighbour, or technician using real Gaza-style expressions.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can view an apartment and ask 8-10 practical questions.",
            "The student can compare two apartments using floor, rent, view, and problems.",
            "The student can report a building problem politely and ask when it can be fixed.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "shaqqa",
                ar: "شَقَّة",
                en: "apartment / flat",
                enArabeezy: "sha2qa",
                hint: "Plural: شُقَق. My apartment = شِقِّتِي. Use it for rented or owned flats.",
                exampleAr: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة قَرِيب مِن الجَامْعَة.",
                exampleArabeezy: "e7na bindawwer 3ala sha2qa qareeb min el-jam3a.",
                exampleEn: "We are looking for an apartment near the university.",
            },
            {
                id: "3imara",
                ar: "عِمَارَة / بِنَايَة",
                en: "building",
                enArabeezy: "3imara / binaye",
                hint: "Both are natural. Plural: عِمَارَات / بِنَايَات.",
                exampleAr: "العِمَارَة هَادِي فِيهَا أَرْبَع طَوَابِق.",
                exampleArabeezy: "el-3imara hadi feeha arba3 Tawabeq.",
                exampleEn: "This building has four floors.",
            },
            {
                id: "tabaq",
                ar: "طَابِق",
                en: "floor",
                enArabeezy: "Tabaq",
                hint: "Examples: أَوَّل طَابِق، تَانِي طَابِق، الطَّابِق التَّالِت. We say التالت because it means the third floor, not the number three alone.",
                exampleAr: "الشَّقَّة عَالطَّابِق التَّالِت.",
                exampleArabeezy: "esh-sha2qa 3aT-Tabaq et-talet.",
                exampleEn: "The apartment is on the third floor.",
            },
            {
                id: "kam_shaqqa",
                ar: "كَم شَقَّة فِي الطَّابِق؟",
                en: "How many apartments are on the floor?",
                enArabeezy: "kam sha2qa fi eT-Tabaq?",
                hint: "Practical question when viewing a building.",
                exampleAr: "لَوْ سَمَحْت، كَم شَقَّة فِي الطَّابِق؟",
                exampleArabeezy: "law sama7t, kam sha2qa fi eT-Tabaq?",
                exampleEn: "Excuse me, how many apartments are on the floor?",
            },
            {
                id: "ijar",
                ar: "إِيجَار",
                en: "rent",
                enArabeezy: "ijar",
                hint: "Monthly rent. Ask: قَدِّيش الإِيجَار بِالشَّهْر؟",
                exampleAr: "قَدِّيش الإِيجَار بِالشَّهْر؟",
                exampleArabeezy: "addeesh el-ijar bish-shahr?",
                exampleEn: "How much is the rent per month?",
            },
            {
                id: "ta2meen",
                ar: "تَأْمِين",
                en: "deposit",
                enArabeezy: "ta2meen",
                hint: "Money paid before renting. Different from health insurance.",
                exampleAr: "الإِيجَار شَهْر، وَالتَّأْمِين شَهْر.",
                exampleArabeezy: "el-ijar shahr, w et-ta2meen shahr.",
                exampleEn: "The rent is one month, and the deposit is one month.",
            },
            {
                id: "aqd_ijar",
                ar: "عَقْد إِيجَار",
                en: "rental contract",
                enArabeezy: "3aqd ijar",
                hint: "Use when asking about rules, deposit, and repairs.",
                exampleAr: "التَّصْلِيح مَكْتُوب فِي عَقْد الإِيجَار.",
                exampleArabeezy: "et-taSli7 maktoob fi 3aqd el-ijar.",
                exampleEn: "The repair is written in the rental contract.",
            },
            {
                id: "sa7eb_el_beit",
                ar: "صَاحِب البَيْت",
                en: "landlord / owner",
                enArabeezy: "sa7eb el-beit",
                hint: "For a woman: صَاحْبِة البَيْت.",
                exampleAr: "صَاحِب البَيْت وَرَّانَا تَلَات شُقَق.",
                exampleArabeezy: "sa7eb el-beit warrana talat shuqaq.",
                exampleEn: "The landlord showed us three apartments.",
            },
            {
                id: "jar",
                ar: "جَار / جَارَة",
                en: "neighbour",
                enArabeezy: "jar / jara",
                hint: "Plural: جِيرَان. Ask: كِيف الجِيرَان؟",
                exampleAr: "كِيف الجِيرَان فِي العِمَارَة؟",
                exampleArabeezy: "keef el-jeeran fi el-3imara?",
                exampleEn: "How are the neighbours in the building?",
            },
            {
                id: "salon",
                ar: "صَالُون",
                en: "living room",
                enArabeezy: "salon",
                hint: "Room for sitting with family or guests.",
                exampleAr: "الصَّالُون وَاسِع وَفِيه ضَوّ حُلْو.",
                exampleArabeezy: "eS-Salon wase3 w feeh Daw 7ilu.",
                exampleEn: "The living room is spacious and has nice light.",
            },
            {
                id: "ghurfet_nom",
                ar: "غُرْفِة نَوم",
                en: "bedroom",
                enArabeezy: "ghurfet nom",
                hint: "Useful when counting rooms: غُرْفِة نَوم وَاحْدَة / غُرْفِتِين نَوم.",
                exampleAr: "الشَّقَّة فِيهَا غُرْفِتِين نَوم وَصَالُون.",
                exampleArabeezy: "esh-sha2qa feeha ghurfitain nom w salon.",
                exampleEn: "The apartment has two bedrooms and a living room.",
            },
            {
                id: "matbakh",
                ar: "مَطْبَخ",
                en: "kitchen",
                enArabeezy: "maTbakh",
                hint: "Plural: مَطَابِخ.",
                exampleAr: "المَطْبَخ جَنْب الصَّالُون.",
                exampleArabeezy: "el-maTbakh jamb eS-Salon.",
                exampleEn: "The kitchen is next to the living room.",
            },
            {
                id: "7ammam",
                ar: "حَمَّام",
                en: "bathroom",
                enArabeezy: "7ammam",
                hint: "Plural: حَمَّامَات.",
                exampleAr: "الحَمَّام جُوَّا الشَّقَّة، قُدَّام المَطْبَخ.",
                exampleArabeezy: "el-7ammam juwwa esh-sha2qa, quddam el-maTbakh.",
                exampleEn: "The bathroom is inside the apartment, in front of the kitchen.",
            },
            {
                id: "balkon_barande",
                ar: "بَلَكُون / بَرَنْدَة",
                en: "balcony",
                enArabeezy: "balkon / barande",
                hint: "Both are used. Ask: البَرَنْدَة وِين بِتْطُلّ؟ = Where does the balcony look out?",
                exampleAr: "البَرَنْدَة بِتْطُلّ عَالشَّارِع.",
                exampleArabeezy: "el-barande bitTull 3ash-share3.",
                exampleEn: "The balcony looks out onto the street.",
            },
            {
                id: "iTlala",
                ar: "إِطْلَالَة",
                en: "view",
                enArabeezy: "iTlala",
                hint: "Common with balcony/roof: إِطْلَالَة عَالبَحْر / عَالشَّارِع.",
                exampleAr: "إِطْلَالَة البَلَكُون حُلْوَة بِالمَسَا.",
                exampleArabeezy: "iTlalet el-balkon 7ilwe bil-masa.",
                exampleEn: "The balcony view is nice in the evening.",
            },
            {
                id: "saTe7",
                ar: "سَطْح",
                en: "rooftop",
                enArabeezy: "saTe7",
                hint: "The roof of the building. Often used for laundry, tanks, or sitting outside.",
                exampleAr: "السَّطْح فَوْق، وَمُمْكِن نِنْشُر غَسِيل هُنَاك.",
                exampleArabeezy: "es-saTe7 foq, w mumkin ninshor ghaseel hunak.",
                exampleEn: "The rooftop is upstairs, and we can hang laundry there.",
            },
            {
                id: "mamarr",
                ar: "مَمَرّ",
                en: "hallway",
                enArabeezy: "mamarr",
                hint: "Inside a building or apartment. Also: المَمَرّ بَيْن الشُّقَق. Use with location words: جُوَّا العِمَارَة، بَيْن الشُّقَق.",
                exampleAr: "المَمَرّ بَيْن الشُّقَق ضَيِّق شُوَيّ.",
                exampleArabeezy: "el-mamarr bain esh-shuqaq Dayyeq shway.",
                exampleEn: "The hallway between the apartments is a little narrow.",
            },
            {
                id: "mis3ad",
                ar: "مِصْعَد / أَسَنْسِير",
                en: "elevator",
                enArabeezy: "miS3ad / asanseer",
                hint: "أَسَنْسِير is very common in speech. Ask if it works before renting.",
                exampleAr: "الأَسَنْسِير شَغَّال وَلَا خَرْبَان؟",
                exampleArabeezy: "el-asanseer shaghghal wala kharban?",
                exampleEn: "Is the elevator working or broken?",
            },
            {
                id: "daraj",
                ar: "دَرَج / سِلِّم",
                en: "stairs / staircase",
                enArabeezy: "daraj / sillem",
                hint: "دَرَج is stairs in general. سِلِّم is the building staircase.",
                exampleAr: "إِذَا الأَسَنْسِير خَرْبَان، بِنِطْلَع عَالدَّرَج.",
                exampleArabeezy: "iza el-asanseer kharban, biniTla3 3ad-daraj.",
                exampleEn: "If the elevator is broken, we go up the stairs.",
            },
            {
                id: "kahraba",
                ar: "كَهْرَبَا",
                en: "electricity",
                enArabeezy: "kahraba",
                hint: "Ask about cuts: الكَهْرَبَا بِتِقْطَع كْتِير؟",
                exampleAr: "الكَهْرَبَا بِتِقْطَع كْتِير فِي المِنْطَقَة؟",
                exampleArabeezy: "el-kahraba biti2Ta3 kteer fi el-minTa2a?",
                exampleEn: "Does the electricity cut off a lot in the area?",
            },
            {
                id: "internet",
                ar: "إِنْتَرْنِت",
                en: "internet",
                enArabeezy: "internet",
                hint: "Common questions: الإِنْتَرْنِت قَوِي؟ فِي أَلْيَاف؟",
                exampleAr: "الإِنْتَرْنِت قَوِي فِي الطَّابِق التَّالِت؟",
                exampleArabeezy: "el-internet qawi fi eT-Tabaq et-talet?",
                exampleEn: "Is the internet strong on the third floor?",
            },
            {
                id: "sakhan",
                ar: "سَخَّان",
                en: "water heater",
                enArabeezy: "sakhkhan",
                hint: "Ask if it works: السَّخَّان شَغَّال؟",
                exampleAr: "السَّخَّان شَغَّال وَلَا بَدُّه تَصْلِيح؟",
                exampleArabeezy: "es-sakhkhan shaghghal wala biddo taSli7?",
                exampleEn: "Is the heater working or does it need repair?",
            },
            {
                id: "7anafiye",
                ar: "حَنَفِيَّة",
                en: "tap / faucet",
                enArabeezy: "7anafiye",
                hint: "Plural: حَنَفِيَّات. It drips = بْتِنْقُط.",
                exampleAr: "حَنَفِيَّة الحَمَّام بْتِنْقُط طُول اللَّيْل.",
                exampleArabeezy: "7anafiyyet el-7ammam bitinqoT Tool el-lel.",
                exampleEn: "The bathroom tap drips all night.",
            },
            {
                id: "masoora",
                ar: "مَاسُورَة",
                en: "pipe",
                enArabeezy: "masoora",
                hint: "Plural: مَوَاسِير. Common with plumbers and leaks. Use location words: تَحْت المَغْسَلَة، وَرَا الحِيطَة.",
                exampleAr: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط.",
                exampleArabeezy: "el-masoora ta7t el-maghsale bitinqoT.",
                exampleEn: "The pipe under the sink is dripping.",
            },
            {
                id: "maghsale",
                ar: "مَغْسَلَة",
                en: "sink",
                enArabeezy: "maghsale",
                hint: "Bathroom or kitchen sink. Plural: مَغَاسِل.",
                exampleAr: "المَغْسَلَة فِي المَطْبَخ مَسْدُودَة.",
                exampleArabeezy: "el-maghsale fi el-maTbakh masdoode.",
                exampleEn: "The kitchen sink is blocked.",
            },
            {
                id: "masdood",
                ar: "مَسْدُود / مَسْدُودَة",
                en: "blocked / clogged",
                enArabeezy: "masdood / masdoode",
                hint: "Male: مَسْدُود. Female: مَسْدُودَة.",
                exampleAr: "المَغْسَلَة مَسْدُودَة وِبِدَّهَا سَبَّاك.",
                exampleArabeezy: "el-maghsale masdoode w biddha sabbak.",
                exampleEn: "The sink is blocked and needs a plumber.",
            },
            {
                id: "binqoT",
                ar: "بْيِنْقُط / بْتِنْقُط",
                en: "it drips / leaks",
                enArabeezy: "binqoT / bitinqoT",
                hint: "For taps, pipes, roofs, or ceilings.",
                exampleAr: "السَّقْف بْيِنْقُط لَمَّا الدُّنْيَا تِشْتِي.",
                exampleArabeezy: "es-saqf binqoT lamma ed-dunya tishti.",
                exampleEn: "The ceiling drips when it rains.",
            },
            {
                id: "kharban",
                ar: "خَرْبَان / خَرْبَانَة",
                en: "broken / not working",
                enArabeezy: "kharban / kharbane",
                hint: "Male: خَرْبَان. Female: خَرْبَانَة. Plural: خَرْبَانِين.",
                exampleAr: "الأَسَنْسِير خَرْبَان مِن اِمْبَارِح.",
                exampleArabeezy: "el-asanseer kharban min embare7.",
                exampleEn: "The elevator has been broken since yesterday.",
            },
            {
                id: "bishtaghel",
                ar: "بِشْتَغِل / مِش شَغَّال",
                en: "it works / it is not working",
                enArabeezy: "bishtaghel / mish shaghghal",
                hint: "For elevator, heater, internet, light, washing machine.",
                exampleAr: "السَّخَّان مِش شَغَّال بَس الأَسَنْسِير بِشْتَغِل.",
                exampleArabeezy: "es-sakhkhan mish shaghghal bas el-asanseer bishtaghel.",
                exampleEn: "The heater is not working, but the elevator works.",
            },
            {
                id: "salle7",
                ar: "صَلَّح / بَدُّه تَصْلِيح",
                en: "fixed / it needs repair",
                enArabeezy: "Salla7 / biddo taSli7",
                hint: "Question: صَلَّحْتُه؟ Answer: لِسَّا نَفْس المُشْكِلَة / هَلِّق أَحْسَن.",
                exampleAr: "السَّخَّان بَدُّه تَصْلِيح قَبْل مَا نِسْكُن.",
                exampleArabeezy: "es-sakhkhan biddo taSli7 qabel ma niskon.",
                exampleEn: "The heater needs repair before we move in.",
            },
            {
                id: "sabbak",
                ar: "سَبَّاك",
                en: "plumber",
                enArabeezy: "sabbak",
                hint: "For sink, tap, pipe, heater, or dripping.",
                exampleAr: "إِمْتَى بِتِقْدَر تِبْعَت سَبَّاك؟",
                exampleArabeezy: "emta btigdar tib3at sabbak?",
                exampleEn: "When can you send a plumber?",
            },
            {
                id: "fanni",
                ar: "فَنِّي",
                en: "technician",
                enArabeezy: "fanni",
                hint: "General repair person. Plural: فَنِّيِين.",
                exampleAr: "مُمْكِن تِبْعَت فَنِّي يِشُوف الإِنْتَرْنِت؟",
                exampleArabeezy: "mumkin tib3at fanni yishoof el-internet?",
                exampleEn: "Can you send a technician to check the internet?",
            },
            {
                id: "doshe",
                ar: "دَوْشَة / ضَجَّة",
                en: "noise",
                enArabeezy: "doshe / Dajje",
                hint: "دَوْشَة is very natural. Polite: فِيك تِخَفِّف الصَّوْت شُوَي؟",
                exampleAr: "فِي دَوْشَة مِن الشَّقَّة اللِّي فَوْقِينَا.",
                exampleArabeezy: "fi doshe min esh-sha2qa illi foqena.",
                exampleEn: "There is noise from the apartment above us.",
            },
            {
                id: "rutube",
                ar: "رُطُوبَة",
                en: "humidity / dampness",
                enArabeezy: "ruToobe",
                hint: "Common in Gaza apartments, especially on walls after winter.",
                exampleAr: "فِي رُطُوبَة عَالحِيطَة وَرَا الخِزَانَة.",
                exampleArabeezy: "fi ruToobe 3al-7eeTa wara el-khizane.",
                exampleEn: "There is dampness on the wall behind the closet.",
            },
            {
                id: "mushkile",
                ar: "عِنْدِي مُشْكِلِة / بَدِّي أَحْكِي عَن مُشْكِلِة",
                en: "I have a problem / I want to talk about a problem",
                enArabeezy: "3indi mushkile / baddi a7ki 3an mushkile",
                hint: "Polite repair opening. Add: مَعْلِيش عَالإِزْعَاج، مُمْكِن تِشُوفْهَا؟",
                exampleAr: "لَوْ سَمَحْت، بَدِّي أَحْكِي عَن مُشْكِلِة فِي الشَّقَّة.",
                exampleArabeezy: "law sama7t, baddi a7ki 3an mushkile fi esh-sha2qa.",
                exampleEn: "Excuse me, I want to talk about a problem in the apartment.",
            },
            {
                id: "mumkin_tsa3idni",
                ar: "مُمْكِن تِسَاعِدْنِي؟",
                en: "Can you help me?",
                enArabeezy: "mumkin tsa3idni?",
                hint: "Useful with landlord, neighbour, technician, or guard.",
                exampleAr: "مُمْكِن تِسَاعِدْنِي؟ السَّخَّان مِش شَغَّال.",
                exampleArabeezy: "mumkin tsa3idni? es-sakhkhan mish shaghghal.",
                exampleEn: "Can you help me? The heater is not working.",
            },
        ],
    },

    dialogue: {
    title: "Apartment Hunting - Looking for an Apartment",
    setting: "Rami and Mona meet Abu Ahmad to look at apartments for rent and ask about rooms, rent, internet, neighbors, and building problems.",
    lines: [
        { speaker: "Rami", ar: "السَّلَام عَلَيْكُم، أَبُو أَحْمَد؟", arArabeezy: "es-salam 3aleikom, abu a7mad?", en: "Peace be upon you, Abu Ahmad?" },
        { speaker: "Abu Ahmad", ar: "وَعَلَيْكُم السَّلَام. أَهْلًا وَسَهْلًا، تْفَضَّلُوا.", arArabeezy: "w 3aleikom es-salam. ahlan w sahlan, tfaDDalu.", en: "Peace be upon you too. Welcome, come in." },
        { speaker: "Rami", ar: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة لِلإِيجَار، وَحَكُولْنَا عِنْدَك أَكْتَر مِن شَقَّة فَاضْيَة.", arArabeezy: "i7na bindawwer 3ala sha22a lil-ijar, w 7akoolna 3indak aktar min sha22a faDye.", en: "We’re looking for an apartment to rent, and they told us you have more than one empty apartment." },
        { speaker: "Abu Ahmad", ar: "صَحِيح، عِنْدِي تَلَات شُقَق. وَحْدَة بِالطَّابِق الأَوَّل، وَوَحْدَة بِالتَّالِت، وَوَحْدَة بِالرَّابِع.", arArabeezy: "Sa7ee7, 3indi talat sho2a2. wa7de biT-Tabe2 el-awwal, w wa7de bit-talet, w wa7de bir-rabe3.", en: "That’s right, I have three apartments. One on the first floor, one on the third, and one on the fourth." },
        { speaker: "Mona", ar: "إِحْنَا بَدْنَا إِشِي قَرِيب مِن الجَامْعَة وَالمُوَاصَلَات.", arArabeezy: "i7na baddna ishi 2areeb min el-jam3a w el-mowaSalat.", en: "We want something close to the university and transportation." },
        { speaker: "Abu Ahmad", ar: "المَوْقِع كُلُّه قَرِيب، بَس كُلّ شَقَّة إِلْهَا مِيزَاتْهَا.", arArabeezy: "el-mawqi3 kollo 2areeb, bas kol sha22a ilha meezatha.", en: "The whole location is close, but each apartment has its own advantages." },
        { speaker: "Rami", ar: "طَيِّب، خَلِّينَا نْبَلِّش بِالطَّابِق التَّالِت.", arArabeezy: "Tayyib, khallina nballish biT-Tabe2 et-talet.", en: "Okay, let’s start with the third floor." },
        { speaker: "Abu Ahmad", ar: "اتْفَضَّلُوا، الأَسَنْسِير هُون.", arArabeezy: "itfaDDalu, el-asansir hoon.", en: "Come in, the elevator is here." },
        { speaker: "Mona", ar: "الحَمْدُ لله فِيه أَسَنْسِير، كُنْت مُفَكِّرَة مَا فِيه.", arArabeezy: "el-7amdullah fee asansir, kont mfakkire ma fee.", en: "Thank God there’s an elevator. I thought there wasn’t one." },
        { speaker: "Abu Ahmad", ar: "لَا، مَوْجُود وَبْيِشْتَغِل الحَمْدُ لله.", arArabeezy: "la, mawjood w biyishtighil el-7amdullah.", en: "No, it’s there and it works, thank God." },
        { speaker: "Rami", ar: "وَلَو خَرِب؟", arArabeezy: "w law khirib?", en: "And if it breaks?" },
        { speaker: "Abu Ahmad", ar: "بِتْحْكُوا مَعِي، وَبَبْعَت فَنِّي بِنَفْس اليَوْم إِنْ شَاء الله.", arArabeezy: "bit7ku ma3i, w bab3at fanni binafs el-yom inshallah.", en: "You talk to me, and I’ll send a technician the same day, God willing." },
        { speaker: "Mona", ar: "مْنِيح.", arArabeezy: "mnee7.", en: "Good." },
        { speaker: "Abu Ahmad", ar: "هَاي الشَّقَّة.", arArabeezy: "hay esh-sha22a.", en: "This is the apartment." },
        { speaker: "Rami", ar: "وَاو... وَاسْعَة.", arArabeezy: "wow... was3a.", en: "Wow... it’s spacious." },
        { speaker: "Mona", ar: "قَدِّيش عَدَد الغُرَف؟", arArabeezy: "addeesh 3adad el-ghoraf?", en: "How many rooms are there?" },
        { speaker: "Abu Ahmad", ar: "غُرْفْتِين نَوْم، وَصَالُون، وَمَطْبَخ، وَحَمَّام، وَبَرَنْدَة.", arArabeezy: "ghorftain nom, w Saloon, w maTbakh, w 7ammam, w barande.", en: "Two bedrooms, a living room, a kitchen, a bathroom, and a balcony." },
        { speaker: "Rami", ar: "البَرَنْدَة بْتِطِلّ عَلَى وِين؟", arArabeezy: "el-barande btiTill 3ala wayn?", en: "What does the balcony overlook?" },
        { speaker: "Abu Ahmad", ar: "عَلَى شَارِع هَادِي، وَفِي حَدِيقَة قُدَّام العِمَارَة.", arArabeezy: "3ala share3 hadi, w fi 7adee2a qoddam el-3imara.", en: "It overlooks a quiet street, and there’s a garden in front of the building." },
        { speaker: "Mona", ar: "هَاي عَجَبِتْنِي.", arArabeezy: "hay 3ajabitni.", en: "I like this one." },
        { speaker: "Rami", ar: "قَدِّيش الإِيجَار؟", arArabeezy: "addeesh el-ijar?", en: "How much is the rent?" },
        { speaker: "Abu Ahmad", ar: "أَلْف وَخَمْسْمِيَّة بِالشَّهْر.", arArabeezy: "alf w khamsmiyye bish-shaher.", en: "One thousand five hundred per month." },
        { speaker: "Rami", ar: "وَفِي تَأْمِين؟", arArabeezy: "w fi ta2meen?", en: "And is there a deposit?" },
        { speaker: "Abu Ahmad", ar: "آه، شَهْر وَاحِد.", arArabeezy: "ah, shaher wa7ed.", en: "Yes, one month." },
        { speaker: "Mona", ar: "وَالكَهْرَبَا وَالإِنْتَرْنِت كِيف هُون؟", arArabeezy: "w el-kahraba w el-internet keef hoon?", en: "And how are the electricity and internet here?" },
        { speaker: "Abu Ahmad", ar: "الكَهْرَبَا كُوَيِّسَة، وَالإِنْتَرْنِت فَايْبَر.", arArabeezy: "el-kahraba kwayyise, w el-internet fiber.", en: "The electricity is good, and the internet is fiber." },
        { speaker: "Rami", ar: "مُمْتَاز.", arArabeezy: "momtaz.", en: "Excellent." },
        { speaker: "Mona", ar: "فِيه رُطُوبَة بِالشِّتَا؟", arArabeezy: "fee rToobe bish-sheta?", en: "Is there humidity in winter?" },
        { speaker: "Abu Ahmad", ar: "كَان فِيه مُشْكِلَة بَسِيطَة وَرَا الخِزَانَة، بَس انْحَلَّت.", arArabeezy: "kan fee moshkile baseeTa wara el-khazane, bas in7allat.", en: "There was a small issue behind the closet, but it was fixed." },
        { speaker: "Rami", ar: "أَكِيد انْحَلَّت؟ وَلَا مُمْكِن تِرْجَع؟", arArabeezy: "akeed in7allat? wala mumkin tirja3?", en: "Are you sure it was fixed? Or could it come back?" },
        { speaker: "Abu Ahmad", ar: "لَا إِنْ شَاء الله، تْفَضَّل شُوف الحِيط لَحَالَك.", arArabeezy: "la inshallah, tfaDDal shoof el-7eeT la7alak.", en: "No, God willing. Go ahead and check the wall yourself." },
        { speaker: "Mona", ar: "شَكْلُه تَمَام.", arArabeezy: "shaklo tamam.", en: "It looks fine." },
        { speaker: "Rami", ar: "وَالتَّدْفِئَة؟", arArabeezy: "w et-tadfi2a?", en: "And the heating?" },
        { speaker: "Abu Ahmad", ar: "السَّخَّان جَدِيد، وَالمُكَيِّف بَارِد وَسُخْن.", arArabeezy: "es-sakhkhan jadeed, w el-mkayif bared w sokhen.", en: "The water heater is new, and the AC does both cold and hot." },
        { speaker: "Mona", ar: "وَالجِيرَان كِيف؟", arArabeezy: "w el-jeeran keef?", en: "And how are the neighbors?" },
        { speaker: "Abu Ahmad", ar: "هَادْئِين، بَس فَوْق فِي عِيلَة مَعْهَا وَلَدِين صْغَار.", arArabeezy: "hadi2een, bas fo2 fi 3eile ma3ha waladain Sghar.", en: "They’re quiet, but upstairs there’s a family with two small children." },
        { speaker: "Rami", ar: "بْيِلْعَبُوا كْتِير؟", arArabeezy: "byil3abu kteer?", en: "Do they play a lot?" },
        { speaker: "Abu Ahmad", ar: "بِصَرَاحَة مَرَّات العَصِر، أَمَّا بِاللَّيْل هُدُوء.", arArabeezy: "biSara7a marrat el-3aSr, amma bil-leil hodoo2.", en: "Honestly, sometimes in the afternoon, but at night it’s quiet." },
        { speaker: "Mona", ar: "هَيْك مْنِيح.", arArabeezy: "hek mnee7.", en: "That’s good." },
        { speaker: "Rami", ar: "فِي سَطْح؟", arArabeezy: "fi saT7?", en: "Is there a rooftop?" },
        { speaker: "Abu Ahmad", ar: "آه، فَوْق مُبَاشَرَة.", arArabeezy: "ah, fo2 mobasharatan.", en: "Yes, directly above." },
        { speaker: "Rami", ar: "مَسْمُوح نِطْلَع عَلَيْه؟", arArabeezy: "masmoo7 niTla3 3aleih?", en: "Are we allowed to go up there?" },
        { speaker: "Abu Ahmad", ar: "أَكِيد، بَس بِدُون إِزْعَاج لِلْجِيرَان.", arArabeezy: "akeed, bas bidoon iz3aj lil-jeeran.", en: "Of course, but without disturbing the neighbors." },
        { speaker: "Mona", ar: "طَيِّب وِين الغَسَّالَة بْتِنْحَطّ؟", arArabeezy: "Tayyib wayn el-ghassale btin7aTT?", en: "Okay, where does the washing machine go?" },
        { speaker: "Abu Ahmad", ar: "بَرَّا بِالبَرَنْدَة، وَفِيهَا مَكَان مُخَصَّص.", arArabeezy: "barra bil-barande, w feeha makan mkhaSSaS.", en: "Outside on the balcony, and there’s a designated place for it." },
        { speaker: "Rami", ar: "وَالقُمَامَة؟", arArabeezy: "w el-qomame?", en: "And the trash?" },
        { speaker: "Abu Ahmad", ar: "الحَاوِيَات قُدَّام العِمَارَة.", arArabeezy: "el-7awiyat qoddam el-3imara.", en: "The bins are in front of the building." },
        { speaker: "Mona", ar: "طَيِّب إِذَا صَار عَطَل بِالكَهْرَبَا أَو الإِنْتَرْنِت؟", arArabeezy: "Tayyib iza Sar 3aTal bil-kahraba aw el-internet?", en: "Okay, if there’s a problem with the electricity or internet?" },
        { speaker: "Abu Ahmad", ar: "بِتْتِصْلُوا فِيَّ، وَأَنَا بَتَابَع مَع الفَنِّي.", arArabeezy: "bittSilu fiyya, w ana bataba3 ma3 el-fanni.", en: "You call me, and I’ll follow up with the technician." },
        { speaker: "Rami", ar: "مْنِيح، لِأَنُّه آخِر شَقَّة كُنَّا فِيهَا كُنَّا نِسْتَنَّى بِالأَيَّام.", arArabeezy: "mnee7, la2anno akher sha22a kunna feeha kunna nistanna bil-ayam.", en: "Good, because in the last apartment we used to wait for days." },
        { speaker: "Abu Ahmad", ar: "لَا، هُون إِنْ شَاء الله الأُمُور أَسْرَع.", arArabeezy: "la, hoon inshallah el-omoor asra3.", en: "No, here things should be faster, God willing." },
        { speaker: "Mona", ar: "طَيِّب... مُمْكِن نْشُوف شَقَّة الطَّابِق الرَّابِع كَمَان؟", arArabeezy: "Tayyib... mumkin nshoof sha22et eT-Tabe2 er-rabe3 kaman?", en: "Okay... can we also see the fourth-floor apartment?" },
        { speaker: "Abu Ahmad", ar: "أَكِيد.", arArabeezy: "akeed.", en: "Of course." },
        { speaker: "Rami", ar: "شُو الفَرْق بَيْنْهَا وَبَيْن هَاي؟", arArabeezy: "shoo el-far2 bainha w bain hay?", en: "What’s the difference between it and this one?" },
        { speaker: "Abu Ahmad", ar: "إِيجَارْهَا أَغْلَى بِمِيَّة شِيكل، بَس أَصْغَر شُوَي، وَإِطْلَالْتْهَا أَحْلَى.", arArabeezy: "ijarha aghla b-miyye shekel, bas aSghar shway, w iTlalitha a7la.", en: "Its rent is one hundred shekels more expensive, but it’s a little smaller, and its view is nicer." },
        { speaker: "Mona", ar: "أَمَّا أَنَا بُفَضِّل التَّالْتَة.", arArabeezy: "amma ana bfaDDil et-talte.", en: "As for me, I prefer the third one." },
        { speaker: "Rami", ar: "وَأَنَا كَمَان. أَكْبَر وَأَرْيَح.", arArabeezy: "w ana kaman. akbar w arya7.", en: "Me too. It’s bigger and more comfortable." },
        { speaker: "Abu Ahmad", ar: "خُدُوا رَاحْتْكُم، وَلَا تِسْتَعْجِلُوا بِالقَرَار.", arArabeezy: "khodu ra7etkom, w la tista3jilu bil-qarar.", en: "Take your time, and don’t rush the decision." },
        { speaker: "Rami", ar: "إِنْ شَاء الله. إِذَا قَرَّرْنَا، بِنِتْوَاصَل مَعَك اليَوْمِين الجَايِين.", arArabeezy: "inshallah. iza qarrarna, binitwaSal ma3ak el-yomain el-jayeen.", en: "God willing. If we decide, we’ll contact you in the next couple of days." },
        { speaker: "Abu Ahmad", ar: "أَهْلًا وَسَهْلًا بِأَي وَقْت.", arArabeezy: "ahlan w sahlan bi-ay wa2t.", en: "You’re welcome anytime." },
        { speaker: "Mona", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Abu Ahmad", ar: "الله يْعَافِيكُم.", arArabeezy: "allah y3afeekom.", en: "You’re welcome." }
    ],

    questions: [
        { ar: "كَم شَقَّة كَانِت فَاضْيَة فِي العِمَارَة؟", en: "How many apartments were empty in the building?" },
        { ar: "بِأَي طَابِق بَلَّشُوا الجَوْلَة؟", en: "Which floor did they start the tour with?" },
        { ar: "كَم غُرْفَة فِي شَقَّة الطَّابِق التَّالِت؟", en: "How many rooms are in the third-floor apartment?" },
        { ar: "عَلَى شُو بْتِطِلّ البَرَنْدَة؟", en: "What does the balcony overlook?" },
        { ar: "قَدِّيش كَان إِيجَار الشَّقَّة؟", en: "How much was the apartment rent?" },
        { ar: "هَل كَان فِي تَأْمِين؟", en: "Was there a deposit?" },
        { ar: "كِيف وَصَف أَبُو أَحْمَد الإِنْتَرْنِت؟", en: "How did Abu Ahmad describe the internet?" },
        { ar: "شُو كَانِت مُشْكِلَة الرُّطُوبَة؟", en: "What was the humidity problem?" },
        { ar: "كِيف وَصَف الجِيرَان؟", en: "How did he describe the neighbors?" },
        { ar: "وِين مَكَان الغَسَّالَة؟", en: "Where is the washing machine placed?" },
        { ar: "شُو الفَرْق بَيْن شَقَّة الطَّابِق التَّالِت وَالرَّابِع؟", en: "What is the difference between the third-floor and fourth-floor apartments?" },
        { ar: "أَي شَقَّة عَجَبَت رَامِي وَمُونَا أَكْتَر؟ وَلِيش؟", en: "Which apartment did Rami and Mona like more, and why?" }
    ],
},

    grammar: [
        {
            title: "1. Ownership in housing: عند، إلـ, and تَبَع",
            short: "عِنْدِي شُقَّة — إِلْنَا سَطْح — الشُّقَّة تَبَع مِين؟",
            description: "Housing conversations use several kinds of possession. عِنْد + person says someone has or has access to something. إِلـ + person identifies who something belongs to. تَبَع is a very common spoken ownership word meaning ‘belonging to / the one of’. The structure changes according to whether the focus is possession, ownership, or identifying an owner.",
            table: {
                title: "Three spoken possession frames",
                headers: ["Frame", "Example", "Natural meaning", "Focus"],
                rows: [
                    ["عِنْد + person", "عِنْدِي شُقَّة فَاضْيَة", "I have an available apartment", "having/access"],
                    ["إِلـ + person", "هَاد المِفْتَاح إِلَك", "this key is yours", "belonging"],
                    ["تَبَع + owner", "العَدَّاد تَبَع الشُّقَّة", "the apartment’s meter", "spoken association"],
                    ["تَبَع مِين؟", "الشُّقَّة تَبَع مِين؟", "whose apartment is it?", "asking owner"],
                    ["noun + owner", "بَاب العِمَارَة", "the building door", "tight noun possession"],
                ],
            },
            examples: [
                { ar: "عِنْدْكُم شُقَّة فَاضْيَة بِالطَّابِق التَّانِي؟", arabeezy: "3indkum shuqqa faDyeh biT-Tabiq et-tani?", en: "Do you have an available apartment on the second floor?" },
                { ar: "السَّطْح إِلْنَا وَلَا مُشْتَرَك مَع كُلّ السُّكَّان؟", arabeezy: "es-saT7 ilna wala mushtarak ma3 kul es-sukkan?", en: "Is the rooftop ours, or shared with all residents?" },
                { ar: "هَاد المِفْتَاح تَبَع بَاب العِمَارَة.", arabeezy: "had el-mifta7 taba3 bab el-3imara.", en: "This key is for/belongs to the building entrance." },
            ],
            commonMistakes: [
                "عِنْدِي does not always mean legal ownership. عِنْدِي مِفْتَاح may simply mean the key is with me.",
                "إِلِي, إِلَك, إِلُه, إِلْهَا identify the beneficiary/owner and change with person.",
                "تَبَع is highly conversational. Formal Arabic often uses different constructions, but تَبَع is essential for understanding everyday Palestinian speech.",
            ],
            exercises: [
                { prompt: "Ask: ‘Whose apartment is it?’", options: ["الشُّقَّة تَبَع مِين؟", "مِين عِنْد الشُّقَّة فِي؟", "الشُّقَّة مِن وِين؟"], correct: "الشُّقَّة تَبَع مِين؟", explanation: "تَبَع مِين directly asks who the item belongs to." },
                { prompt: "Choose: ‘This key is yours.’ (to one man)", options: ["هَاد المِفْتَاح إِلَك.", "هَاد المِفْتَاح عِنْدِي.", "هَاد المِفْتَاح تَبَعْنَا."], correct: "هَاد المِفْتَاح إِلَك.", explanation: "إِلَك identifies the listener as the owner/recipient." },
                { prompt: "What does عِنْدِي شُقَّة فَاضْيَة communicate?", options: ["I have an available apartment.", "The apartment belongs to you.", "Where is the apartment?"], correct: "I have an available apartment.", explanation: "عِنْدِي presents something available or possessed by the speaker." },
            ],
        },
        {
            title: "2. Compound location words",
            short: "جُوَّة، بَرَّة، فَوق، تَحْت، جَنْب، قُدَّام، وَرَا، بَيْن",
            description: "Palestinian location words behave like relational nouns. They can be followed by a named place—جَنْب المَدْرَسَة—or attach a person/object ending—جَنْبُه (‘next to it/him’), فَوقْهَا (‘above it/her’). Choosing the ending requires knowing what landmark the speaker refers back to.",
            table: {
                title: "Location with a noun and with an attached reference",
                headers: ["Location", "With a noun", "With ـهَا", "Meaning"],
                rows: [
                    ["جُوَّة", "جُوَّة الشُّقَّة", "جُوَّاتْهَا", "inside the apartment / inside it"],
                    ["بَرَّة", "بَرَّة العِمَارَة", "بَرَّاتْهَا", "outside the building / outside it"],
                    ["فَوق", "فَوق المَطْبَخ", "فَوقْهَا", "above the kitchen / above it"],
                    ["تَحْت", "تَحْت الشُّبَّاك", "تَحْتْهَا", "under the window / under it"],
                    ["جَنْب", "جَنْب المَدْرَسَة", "جَنْبْهَا", "next to the school / next to it"],
                    ["قُدَّام", "قُدَّام البَاب", "قُدَّامْهَا", "in front of the door / it"],
                    ["وَرَا", "وَرَا العِمَارَة", "وَرَاهَا", "behind the building / it"],
                    ["بَيْن", "بَيْن البَيْتَيْن", "بَيْنْهُم", "between the two houses / them"],
                ],
            },
            examples: [
                { ar: "الحَمَّام جَنْب غُرْفَة النَّوم، وَالمَطْبَخ قُدَّامُه.", arabeezy: "el-7ammam jamb ghurfet en-nom, wil-maTbakh quddamo.", en: "The bathroom is next to the bedroom, and the kitchen is in front of it." },
                { ar: "فِي رُطُوبَة تَحْت الشُّبَّاك وَوَرَا الخِزَانَة.", arabeezy: "fi ruTooba ta7t esh-shubbak w wara el-khizaneh.", en: "There is dampness under the window and behind the wardrobe." },
                { ar: "المِصْعَد بَيْن الشُّقَّتَيْن، مِش جَنْب الدَّرَج.", arabeezy: "el-miS3ad bein esh-shuqqatein, mish jamb ed-daraj.", en: "The elevator is between the two apartments, not beside the stairs." },
            ],
            commonMistakes: [
                "Do not translate every location using فِي. Use the precise relationship: جَنْب, وَرَا, تَحْت, or مُقَابِل.",
                "The attached ending refers to the landmark, not automatically to the nearest English noun. Confirm what ـه / ـهَا means from context.",
                "بَيْن normally needs two or more reference points: بَيْن الشُّقَّتَيْن or بَيْنْهُم.",
            ],
            exercises: [
                { prompt: "Choose: ‘behind the building’.", options: ["وَرَا العِمَارَة", "قُدَّام العِمَارَة", "جُوَّة العِمَارَة"], correct: "وَرَا العِمَارَة", explanation: "وَرَا expresses ‘behind’." },
                { prompt: "What does جَنْبْهَا mean when ـهَا refers to المدرسة?", options: ["next to it", "inside it", "above it"], correct: "next to it", explanation: "جَنْب gives the relation and ـهَا refers back to the feminine landmark." },
                { prompt: "Complete: المِصْعَد ___ الشُّقَّتَيْن. (between)", options: ["بَيْن", "فَوق", "بَرَّة"], correct: "بَيْن", explanation: "بَيْن places something between two reference points." },
            ],
        },
        {
            title: "3. There is, it is located, and it is available",
            short: "فِي شُقَّة — الشُّقَّة مَوْجُودَة — الشُّقَّة فَاضْيَة",
            description: "Three similar-looking ideas do different jobs. فِي introduces the existence of something new: ‘there is’. مَوْجُود/مَوْجُودَة confirms that a known thing exists or is present. فَاضِي/فَاضْيَة says a place or item is empty, free, or available. Negation changes accordingly: مَا فِي, مِش مَوْجُود, مِش فَاضْيَة.",
            table: {
                title: "Existence versus state",
                headers: ["Meaning", "Affirmative", "Negative"],
                rows: [
                    ["there is / are", "فِي مِصْعَد", "مَا فِي مِصْعَد"],
                    ["present / exists (m.)", "المِصْعَد مَوْجُود", "المِصْعَد مِش مَوْجُود"],
                    ["present / exists (f.)", "الخِدْمَة مَوْجُودَة", "الخِدْمَة مِش مَوْجُودَة"],
                    ["available (f.)", "الشُّقَّة فَاضْيَة", "الشُّقَّة مِش فَاضْيَة"],
                    ["working", "المِصْعَد شَغَّال", "المِصْعَد مِش شَغَّال"],
                ],
            },
            examples: [
                { ar: "فِي شُقَّة فَاضْيَة بِالطَّابِق الأَوَّل؟", arabeezy: "fi shuqqa faDyeh biT-Tabiq el-awwal?", en: "Is there an available apartment on the first floor?" },
                { ar: "المِصْعَد مَوْجُود، بَس مِش شَغَّال هَلْقِيت.", arabeezy: "el-miS3ad mawjood, bas mish shaghghal hal2eet.", en: "There is an elevator, but it is not working right now." },
                { ar: "مَا فِي مَيّ سَاخْنَة بِالحَمَّام.", arabeezy: "ma fi mayy sakhneh bil-7ammam.", en: "There is no hot water in the bathroom." },
            ],
            commonMistakes: [
                "Use مَا فِي to negate existence, not مِش فِي as the core beginner pattern.",
                "مَوْجُود does not guarantee that a device works. A lift can be مَوْجُود but مِش شَغَّال.",
                "Match state adjectives to the noun: شُقَّة فَاضْيَة, مَحَلّ فَاضِي.",
            ],
            exercises: [
                { prompt: "Choose: ‘There is no elevator.’", options: ["مَا فِي مِصْعَد.", "المِصْعَد مِش شَغَّال.", "المِصْعَد فَاضِي."], correct: "مَا فِي مِصْعَد.", explanation: "مَا فِي negates the existence of the elevator." },
                { prompt: "The elevator exists but does not operate. Choose the precise sentence.", options: ["المِصْعَد مَوْجُود، بَس مِش شَغَّال.", "مَا فِي مِصْعَد.", "المِصْعَد مِش مَوْجُود وَشَغَّال."], correct: "المِصْعَد مَوْجُود، بَس مِش شَغَّال.", explanation: "مَوْجُود confirms existence; مِش شَغَّال describes its faulty state." },
                { prompt: "Complete with feminine agreement: الشُّقَّة ___. (available)", options: ["فَاضْيَة", "فَاضِي", "فَاضْيِين"], correct: "فَاضْيَة", explanation: "شُقَّة is feminine singular." },
            ],
        },
        {
            title: "4. Result states and passive participles",
            short: "مَفْتُوح، مْسَكَّر، مَسْدُود، مَقْطُوع، مَفْصُول",
            description: "Forms such as مَسْدُود describe the state resulting from an action: something has been blocked, cut, disconnected, installed, or rented. Traditional grammar calls these passive participles. In Palestinian speech they behave like adjectives, agree with the noun, and often contrast with an active problem verb.",
            table: {
                title: "Useful apartment result states",
                headers: ["Masculine", "Feminine", "Typical housing meaning"],
                rows: [
                    ["مَفْتُوح", "مَفْتُوحَة", "open"],
                    ["مْسَكَّر", "مْسَكَّرَة", "closed/shut"],
                    ["مَسْدُود", "مَسْدُودَة", "blocked"],
                    ["مَقْطُوع", "مَقْطُوعَة", "cut off"],
                    ["مَفْصُول", "مَفْصُولَة", "disconnected"],
                    ["مُرَكَّب", "مُرَكَّبَة", "installed"],
                    ["مْأَجَّر", "مْأَجَّرَة", "rented out / occupied by tenant"],
                ],
            },
            examples: [
                { ar: "المَغْسَلَة مَسْدُودَة وَالمَيّ مِش نَازْلَة.", arabeezy: "el-maghsaleh masdoodeh wil-mayy mish nazleh.", en: "The sink is blocked and the water is not draining." },
                { ar: "الكَهْرَبَا مَقْطُوعَة مِن الصُّبُح.", arabeezy: "el-kahraba maqToo3a min eS-Subu7.", en: "The electricity has been cut since morning." },
                { ar: "السَّخَّان مُرَكَّب، بَس لِسَّه مِش مَوْصُول.", arabeezy: "es-sakhkhan mrakkab, bas lissa mish mawSool.", en: "The heater is installed, but it is not connected yet." },
            ],
            commonMistakes: [
                "A result state is not always a complete past event. المَغْسَلَة مَسْدُودَة describes its current condition; the full past tense tells who blocked it or when it happened.",
                "Agree with the item: البَاب مَفْتُوح but الشُّبَّاكَة مَفْتُوحَة.",
                "خَرْبَان is a common general adjective for broken; مَسْدُود, مَقْطُوع, and مَفْصُول identify more precise states.",
            ],
            exercises: [
                { prompt: "Choose: ‘The sink is blocked.’", options: ["المَغْسَلَة مَسْدُودَة.", "المَغْسَلَة مَسْدُود.", "المَغْسَلَة بِتْسُدّ هِيَّ."], correct: "المَغْسَلَة مَسْدُودَة.", explanation: "The feminine noun takes the feminine result-state form." },
                { prompt: "What does الكَهْرَبَا مَقْطُوعَة describe?", options: ["The electricity is cut off.", "The electricity is expensive.", "The electricity is being purchased."], correct: "The electricity is cut off.", explanation: "مَقْطُوعَة describes the resulting disconnected state." },
                { prompt: "Complete: السَّخَّان ___، بَس مِش مَوْصُول. (installed)", options: ["مُرَكَّب", "مُرَكَّبَة", "بِرَكِّب"], correct: "مُرَكَّب", explanation: "سَخَّان is masculine, and the sentence describes its installed state." },
            ],
        },
        {
            title: "5. Reporting a problem and requesting repair",
            short: "صَارْلُه، لِسَّه، بَدُّه تَصْلِيح، مُمْكِن تِبْعَت فَنِّي؟",
            description: "A useful complaint gives four pieces of information: the problem, how long it has existed, its current status, and the action requested. صَارْلُه / صَارْلْهَا introduces duration, لِسَّه means the issue continues, بَدُّه تَصْلِيح says it needs repair, and a polite question requests follow-up.",
            table: {
                title: "A complete repair report",
                headers: ["Information", "Palestinian frame", "Example"],
                rows: [
                    ["problem", "في / noun + state", "الحَنَفِيَّة بِتْنَقِّط"],
                    ["duration (m.)", "صَارْلُه + time", "صَارْلُه يَومَيْن"],
                    ["duration (f.)", "صَارْلْهَا + time", "صَارْلْهَا أُسْبُوع"],
                    ["still continuing", "لِسَّه + state/action", "لِسَّه بِتْنَقِّط"],
                    ["need", "بَدُّه/بَدَّهَا + noun", "بَدَّهَا تَصْلِيح"],
                    ["request", "مُمْكِن + action?", "مُمْكِن تِبْعَت فَنِّي؟"],
                ],
            },
            examples: [
                { ar: "الحَنَفِيَّة بِتْنَقِّط، وَصَارْلْهَا تَلَات أَيَّام هَيْك.", arabeezy: "el-7anafiyyeh bitnaqqiT, w Sarilha talat ayyam heik.", en: "The tap is dripping, and it has been like this for three days." },
                { ar: "المِصْعَد لِسَّه خَرْبَان وَبَدُّه تَصْلِيح.", arabeezy: "el-miS3ad lissa kharban w biddo taSlee7.", en: "The elevator is still broken and needs repair." },
                { ar: "مَعَلِّش، مُمْكِن تِبْعَتْلَنَا فَنِّي اليَوم؟", arabeezy: "ma3allish, mumkin tib3atlna fanni el-yom?", en: "Excuse me, could you send us a technician today?" },
            ],
            commonMistakes: [
                "Do not report only مُشْكِلَة. Name what is happening: بِتْنَقِّط, مَقْطُوعَة, مَسْدُودَة, or مِش شَغَّال.",
                "صَارْلُه agrees with a masculine issue/item; صَارْلْهَا refers to a feminine one.",
                "بَدُّه تَصْلِيح describes need. It does not itself promise that anyone has arranged the repair; follow with a clear request and time.",
            ],
            exercises: [
                { prompt: "The feminine الحَنَفِيَّة has leaked for two days. Choose the agreeing duration frame.", options: ["صَارْلْهَا يَومَيْن.", "صَارْلُه يَومَيْن.", "صِرْت يَومَيْن."], correct: "صَارْلْهَا يَومَيْن.", explanation: "ـهَا refers back to the feminine item الحَنَفِيَّة." },
                { prompt: "Which sentence shows that the problem continues?", options: ["لِسَّه المِصْعَد خَرْبَان.", "المِصْعَد كَان جَدِيد.", "فِي مِصْعَد فَوق."], correct: "لِسَّه المِصْعَد خَرْبَان.", explanation: "لِسَّه indicates the state remains true." },
                { prompt: "Choose the polite repair request.", options: ["مُمْكِن تِبْعَتْلَنَا فَنِّي؟", "الفَنِّي هَلْقِيت غَصْب!", "مُشْكِلَة وَخَلَص."], correct: "مُمْكِن تِبْعَتْلَنَا فَنِّي؟", explanation: "The question requests a specific action while remaining polite." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "apt_mc1",
                type: "complete",
                prompt: "You are viewing an apartment. Complete: How much is the rent per month? قَدِّيش ___ بِالشَّهْر؟",
                options: ["الإِيجَار", "شَقَّة", "عِمَارَة", "طَابِق"],
                correct: "الإِيجَار",
            },
            {
                id: "apt_mc2",
                type: "match",
                prompt: "Choose the natural question for: Which floor is the apartment on?",
                options: ["الشَّقَّة عَأَيّ طَابِق؟", "الشَّقَّة شُو مَالِك؟", "الشَّقَّة كِيف الجَوّ؟", "الشَّقَّة قَدِّيش عُمُرَك؟"],
                correct: "الشَّقَّة عَأَيّ طَابِق؟",
            },
            {
                id: "apt_mc3",
                type: "reorder",
                prompt: "Reorder: The balcony looks out onto the street.",
                options: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
                correct: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
            },
            {
                id: "apt_mc4",
                type: "complete",
                prompt: "Complete: المِصْعَد ___ وَلَا خَرْبَان؟",
                options: ["بِشْتَغِل", "دَرَج", "كَهْرَبَا", "مَمَرّ"],
                correct: "بِشْتَغِل",
            },
            {
                id: "apt_mc5",
                type: "complete",
                prompt: "Complete: المَغْسَلَة ___.",
                options: ["مَسْدُودَة", "بْتِنْقُط", "مَاسُورَة", "حَنَفِيَّة"],
                correct: "مَسْدُودَة",
            },
            {
                id: "apt_mc6",
                type: "match",
                prompt: "Choose the Arabic word for: broken",
                options: ["خَرْبَان", "مَسْدُود", "بْتِنْقُط", "بِشْتَغِل"],
                correct: "خَرْبَان",
            },
            {
                id: "apt_mc7",
                type: "complete",
                prompt: "Choose the natural Gaza word for: noise",
                options: ["دَوْشَة", "رُطُوبَة", "مُشْكِلِة", "فَنِّي"],
                correct: "دَوْشَة",
            },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            {
                id: "apt_q1",
                questionAr: "Choose the English meaning of: «بَرَنْدَة»",
                optionsEn: ["balcony", "hallway", "deposit"],
                correctIndex: 0,
            },
            {
                id: "apt_q2",
                questionAr: "Choose how to ask about the rent.",
                optionsEn: ["قَدِّيش الإِيجَار؟", "كِيف الجَوّ؟", "شُو مَالَك؟"],
                correctIndex: 0,
            },
            {
                id: "apt_q3",
                questionAr: "Choose the English meaning of: «المَمَرّ بَيْن الشُّقَق»",
                optionsEn: ["the hallway between the apartments", "the balcony view", "the roof above"],
                correctIndex: 0,
            },
            {
                id: "apt_q4",
                questionAr: "Choose the English meaning of: «فَوْق»",
                optionsEn: ["above / upstairs", "behind", "outside"],
                correctIndex: 0,
            },
            {
                id: "apt_q5",
                questionAr: "Choose the worker you call when a faucet is leaking.",
                optionsEn: ["سَبَّاك", "دُكْتُور", "صَرَّاف"],
                correctIndex: 0,
            },
            {
                id: "apt_q6",
                questionAr: "Choose the English meaning of: «لِسَّا نَفْس المُشْكِلِة»",
                optionsEn: ["It is still the same problem.", "Everything is solved now.", "The view is beautiful."],
                correctIndex: 0,
            },
            {
                id: "apt_q7",
                questionAr: "Choose the natural Palestinian Arabic word for “noise”.",
                optionsEn: ["دَوْشَة", "تَأْمِين", "إِطْلَالَة"],
                correctIndex: 0,
            },
            {
                id: "apt_q8",
                questionAr: "Choose the English meaning of: «قُدَّام العِمَارَة»",
                optionsEn: ["in front of the building", "behind the building", "inside the building"],
                correctIndex: 0,
            },
            {
                id: "apt_q9",
                questionAr: "Choose the polite way to report a housing problem.",
                optionsEn: ["لو سمحت، بدي أبلغ عن مشكلة.", "إنت غلطان.", "ما بدي أحكي."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Apartment role-play: ask about the rent and floor, describe one location, report one broken item, and request a repair politely.",
        ],
        legacySections: [
            {
                matching: [
                    { ar: "سَطْح", en: "rooftop" },
                    { ar: "مَمَرّ", en: "hallway" },
                    { ar: "بَرَنْدَة", en: "balcony" },
                    { ar: "دَوْشَة", en: "noise" },
                    { ar: "رُطُوبَة", en: "dampness" },
                ],
                fillInTheBlank: [
                    { prompt: "قَدِّيش ___ بِالشَّهْر؟", answer: "الإِيجَار" },
                    { prompt: "البَرَنْدَة ___ عَالشَّارِع.", answer: "بِتْطُلّ" },
                    { prompt: "المَاسُورَة ___ المَغْسَلَة.", answer: "تَحْت" },
                    { prompt: "فِي ___ عَالحِيطَة وَرَا الخِزَانَة.", answer: "رُطُوبَة" },
                    { prompt: "مُمْكِن ___ فَنِّي؟", answer: "تِبْعَت" },
                ],
                reorderSentences: [
                    {
                        prompt: "Put the words in order: How many apartments are on the floor?",
                        words: ["كَم", "شَقَّة", "فِي", "الطَّابِق؟"],
                        answer: "كَم شَقَّة فِي الطَّابِق؟",
                    },
                    {
                        prompt: "Put the words in order: The balcony looks out onto the street.",
                        words: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
                        answer: "البَرَنْدَة بِتْطُلّ عَالشَّارِع.",
                    },
                    {
                        prompt: "Put the words in order: There is dampness behind the closet.",
                        words: ["فِي", "رُطُوبَة", "وَرَا", "الخِزَانَة."],
                        answer: "فِي رُطُوبَة وَرَا الخِزَانَة.",
                    },
                ],
                writeYourOwnSentences: [
                    "Write 6 questions you would ask a landlord before renting an apartment.",
                    "Write 5 sentences comparing two apartments: rent, floor, balcony view, neighbours, and problems.",
                    "Change these to feminine: خَرْبَان / مَسْدُود / شَغَّال.",
                    "Use 5 location words in your own sentences: جوا، برا، فوق، تحت، جنب، قدام، ورا، بين.",
                ],
            },
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "شَقَّة", arabeezy: "shaqqa", en: "apartment" },
                    { ar: "إِيجَار", arabeezy: "ijar", en: "rent" },
                    { ar: "بَرَنْدَة", arabeezy: "barandeh", en: "balcony" },
                    { ar: "مَمَرّ", arabeezy: "mamarr", en: "hallway" },
                    { ar: "مَسْدُود", arabeezy: "masdood", en: "blocked" },
                    { ar: "خَرْبَان", arabeezy: "kharban", en: "broken" },
                ],
                multipleChoice: [
                    { prompt: "Choose the passive description for a blocked sink.", options: ["المَغْسَلَة مَسْدُودَة.", "المَغْسَلَة بِتْسُدّ.", "المَغْسَلَة سَدَّت."], correct: "المَغْسَلَة مَسْدُودَة." },
                    { prompt: "Choose the location word for “behind.”", options: ["وَرَا (wara)", "قُدَّام (quddam)", "فَوْق (foo2)"], correct: "وَرَا (wara)" },
                ],
            },
            {
                title: "B - Housing grammar practice",
                fillInTheBlank: [
                    { prompt: "قَدِّيش الإِيجَار ___ الشَّهْر؟", arabeezy: "addeesh el-ijar ___ esh-shaher?", cueEn: "per", answer: "بِـ" },
                    { prompt: "المَاسُورَة ___ المَغْسَلَة.", arabeezy: "el-masoora ___ el-maghSaleh.", cueEn: "under", answer: "تَحْت" },
                    { prompt: "فِي رُطُوبَة ___ الخِزَانَة.", arabeezy: "fi rToobeh ___ el-khizaneh.", cueEn: "behind", answer: "وَرَا" },
                    { prompt: "المَغْسَلَة ___.", arabeezy: "el-maghSaleh ___.", cueEn: "blocked (feminine)", answer: "مَسْدُودَة" },
                    { prompt: "السَّخَّان ___.", arabeezy: "es-sakhkhan ___.", cueEn: "broken (masculine)", answer: "خَرْبَان" },
                    { prompt: "البَرَنْدَة ___ عَالشَّارِع.", arabeezy: "el-barandeh ___ 3ash-share3.", cueEn: "looks out", answer: "بِتْطُلّ" },
                    { prompt: "الشَّقَّة اللِّي ___ فَوْقِينَا فِيهَا دَوْشَة.", arabeezy: "esh-shaqqa illi ___ foo2eina fiha dosheh.", cueEn: "is", answer: "هِيَّ" },
                    { prompt: "مُمْكِن ___ فَنِّي اليَوم؟", arabeezy: "mumkin ___ fanni el-yom?", cueEn: "send", answer: "تِبْعَت" },
                    { prompt: "هَادَا مِفْتَاح الشَّقَّة ___.", arabeezy: "hada mifta7 esh-shaqqa ___.", cueEn: "ours", answer: "تَبَعْنَا" },
                    { prompt: "Review past: السَّبَّاك ___ الحَنَفِيَّة.", arabeezy: "es-sabbak ___ el-7anafiyyeh.", cueEn: "fixed", answer: "صَلَّح" },
                    { prompt: "Review health: بَدِّي أَحْجِز مَوْعِد ___ الدُّكْتُور.", arabeezy: "baddi a7jez maw3ed ___ ed-doctor.", cueEn: "with/at", answer: "عِنْد" },
                    { prompt: "Review future: بُكْرَا الفَنِّي ___ يِيجِي.", arabeezy: "bukra el-fanni ___ yiji.", cueEn: "will", answer: "رَاح" },
                ],
                correctTheMistake: [
                    { prompt: "Correct: المَغْسَلَة مَسْدُود.", arabeezy: "el-maghSaleh masdood.", answer: "المَغْسَلَة مَسْدُودَة." },
                    { prompt: "Correct: السَّخَّان خَرْبَانَة.", arabeezy: "es-sakhkhan kharbaneh.", answer: "السَّخَّان خَرْبَان." },
                    { prompt: "Correct: فِي دَوْشَة مِن الشَّقَّة تَحْتِينَا.", arabeezy: "fi dosheh min esh-shaqqa ta7teina.", answer: "فِي دَوْشَة مِن الشَّقَّة فَوْقِينَا." },
                    { prompt: "Review future: بُكْرَا السَّبَّاك إِجَا.", arabeezy: "bukra es-sabbak ija.", answer: "بُكْرَا السَّبَّاك رَاح يِيجِي." },
                    { prompt: "Correct the location: الخِزَانَة فَوْق الحِيطَة.", arabeezy: "el-khizaneh foo2 el-7eeTa.", answer: "الخِزَانَة جَنْب الحِيطَة." },
                    { prompt: "Correct the ownership: هَادَا مِفْتَاح الشَّقَّة تَبَعْهُم، إِحْنَا سَاكْنِين فِيهَا.", arabeezy: "hada mifta7 esh-shaqqa taba3hum, i7na sakneen fiha.", answer: "هَادَا مِفْتَاح الشَّقَّة تَبَعْنَا، إِحْنَا سَاكْنِين فِيهَا." },
                ],
                reorderSentences: [
                    { prompt: "Build: There is dampness behind the closet.", arabeezy: "fi rToobeh wara el-khizaneh.", words: ["فِي رُطُوبَة", "وَرَا", "الخِزَانَة."], answer: "فِي رُطُوبَة وَرَا الخِزَانَة." },
                    { prompt: "Build: The pipe under the sink is dripping.", arabeezy: "el-masoora ta7t el-maghSaleh btin2oT.", words: ["المَاسُورَة", "تَحْت المَغْسَلَة", "بْتِنْقُط."], answer: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط." },
                    { prompt: "Build: Can you send a technician?", arabeezy: "mumkin tib3at fanni?", words: ["مُمْكِن", "تِبْعَت", "فَنِّي؟"], answer: "مُمْكِن تِبْعَت فَنِّي؟" },
                    { prompt: "Review: Tomorrow the plumber will come.", arabeezy: "bukra es-sabbak ra7 yiji.", words: ["بُكْرَا", "السَّبَّاك", "رَاح يِيجِي."], answer: "بُكْرَا السَّبَّاك رَاح يِيجِي." },
                    { prompt: "Build: This apartment key is ours.", arabeezy: "hada mifta7 esh-shaqqa taba3na.", words: ["هَادَا", "مِفْتَاح الشَّقَّة", "تَبَعْنَا."], answer: "هَادَا مِفْتَاح الشَّقَّة تَبَعْنَا." },
                    { prompt: "Review: I want to book an appointment with the doctor.", arabeezy: "baddi a7jez maw3ed 3ind ed-doctor.", words: ["بَدِّي أَحْجِز", "مَوْعِد", "عِنْد الدُّكْتُور."], answer: "بَدِّي أَحْجِز مَوْعِد عِنْد الدُّكْتُور." },
                ],
            },
        ],
        translation: [
            { id: "apt_t1", type: "enToAr", textEn: "We are looking for an apartment near the university.", textAr: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة قَرِيب مِن الجَامْعَة." },
            { id: "apt_t2", type: "arToEn", textEn: "How many floors is the building?", textAr: "العِمَارَة كَم طَابِق؟" },
            { id: "apt_t3", type: "enToAr", textEn: "How many apartments are on each floor?", textAr: "كَم شَقَّة فِي كُلّ طَابِق؟" },
            { id: "apt_t4", type: "arToEn", textEn: "How much is the rent per month?", textAr: "قَدِّيش الإِيجَار بِالشَّهْر؟" },
            { id: "apt_t5", type: "enToAr", textEn: "The balcony looks out onto a quiet street.", textAr: "البَرَنْدَة بِتْطُلّ عَشَارِع هَادِي." },
            { id: "apt_t6", type: "arToEn", textEn: "There is dampness behind the closet.", textAr: "فِي رُطُوبَة وَرَا الخِزَانَة." },
            { id: "apt_t7", type: "enToAr", textEn: "Is the elevator working or broken?", textAr: "الأَسَنْسِير بِشْتَغِل وَلَا خَرْبَان؟" },
            { id: "apt_t8", type: "arToEn", textEn: "The hallway between the apartments is spacious.", textAr: "المَمَرّ بَيْن الشُّقَق وِاسِع." },
            { id: "apt_t9", type: "enToAr", textEn: "The pipe under the sink is dripping.", textAr: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط." },
            { id: "apt_t10", type: "arToEn", textEn: "Can you send a technician?", textAr: "مُمْكِن تِبْعَت فَنِّي؟" },
            { id: "apt_t11", type: "enToAr", textEn: "There is noise from the apartment above us.", textAr: "فِي دَوْشَة مِن الشَّقَّة اللِّي فَوْقِينَا." },
            { id: "apt_t12", type: "arToEn", textEn: "Can you lower the sound a little?", textAr: "فِيك تِخَفِّف الصَّوْت شُوَي؟" },
            { id: "apt_t13", type: "enToAr", textEn: "I want to talk about a problem in the apartment.", textAr: "بَدِّي أَحْكِي عَن مُشْكِلِة فِي الشَّقَّة." },
            { id: "apt_t14", type: "arToEn", textEn: "It is still the same problem.", textAr: "لِسَّا نَفْس المُشْكِلِة." },
            { id: "apt_t15", type: "enToAr", textEn: "Thank you for the help. Everything is okay now.", textAr: "يِعْطِيك العَافْيِة عَالمُسَاعَدَة. كُلّ إِشِي تَمَام هَلِّق." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-90 second apartment-hunting conversation in Gaza Palestinian Arabic. Pretend you are viewing an apartment with a landlord. Ask about: floor, rent, deposit, number of apartments on the floor, balcony view, neighbours, elevator, internet, and any repair problems. Use at least 10 words from this unit and 5 old words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. We are looking for an apartment near the university.
2. How many floors is the building?
3. How many apartments are on each floor?
4. How much is the rent per month?
5. The balcony looks out onto a quiet street.
6. There is dampness behind the closet.
7. Is the elevator working or broken?
8. The hallway between the apartments is spacious.
9. The pipe under the sink is dripping.
10. Can you send a technician?
11. There is noise from the apartment above us.
12. Can you lower the sound a little?
13. I want to talk about a problem in the apartment.
14. It is still the same problem.
15. Thank you for the help. Everything is okay now.`,
    },

    teacherNotes: {
        warmup: [
            "Start with: وين ساكن هلقيت؟ شقة ولا بيت؟ Then move into apartment-hunting questions.",
            "This unit's hidden focus is location words, numbers/floors, rent questions, polite requests, and repair follow-up.",
            "Keep the lesson as a real viewing appointment, not a vocabulary list.",
        ],
        vocabularySteps: [
            "Teach vocabulary in the same order as the dialogue: building -> available apartments -> rent -> balcony/view -> neighbours -> problems.",
            "Do not teach location words as grammar; use quick physical examples: المفتاح جوا، السطح فوق، السباك برا.",
            "Keep expressions practical: لو سمحت، ممكن تساعدني؟ بدي أبلغ عن مشكلة، لسا نفس المشكلة، هلقيت أحسن.",
        ],
        dialogueSteps: [
            "Act the dialogue as a viewing appointment with movement: entrance, hallway, elevator, apartment, balcony.",
            "Ask the dialogue questions orally and require complete answers.",
            "Have the student choose one of the three apartments and explain why.",
        ],
        practiceTips: [
            "Push real output: the student must ask the landlord questions, not only answer.",
            "Use comparison drills: أرخص / أغلى، أهدى / أزعج، أكبر / أصغر.",
            "Practice polite complaints without sounding aggressive.",
        ],
        wrapup: [
            "Student asks 6 landlord questions without reading.",
            "Student describes one apartment and one problem.",
            "Student says one polite neighbour sentence.",
        ],
        myNotes: "",
    },
};
