import { LESSON_ID_APARTMENT } from '../../core/constants.js';

export const lessonId = LESSON_ID_APARTMENT;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Apartment & Problems",
        lessonTitle: "Unit 10 - Apartment Hunting & Building Problems in Gaza Palestinian Arabic",
        contentVersion: 2026070102,
    },

    overview: {
        title: "Unit 10 - Apartment Hunting & Building Problems",
        description:
            "Students learn how to look for an apartment, ask about rent, floor, rooms, neighbours, balcony view, and common building problems in natural Gaza Palestinian Arabic.",
        goals: [
            "Ask about available apartments, floor, rent, deposit, and number of apartments per floor.",
            "Describe parts of a building: apartment, building, hallway, rooftop, balcony, kitchen, bathroom, and living room.",
            "Ask about neighbours, noise, humidity, electricity, internet, heater, elevator, and repairs.",
            "Use location words naturally: inside, outside, above, below, next to, in front of, behind, between.",
            "Speak politely with a landlord, neighbour, or technician using real Gaza-style expressions.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can view an apartment and ask 8-10 practical questions.",
            "The student can compare two apartments using floor, rent, view, and problems.",
            "The student can report a building problem politely and ask when it can be fixed.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "shaqqa",
                ar: "شَقَّة",
                en: "apartment / flat",
                enArabeezy: "sha2qa",
                hint: "Plural: شُقَق. My apartment = شِقِّتِي. Use it for rented or owned flats.",
                exampleAr: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة قَرِيب مِن الجَامْعَة.",
                exampleArabeezy: "e7na bindawwer 3ala sha2qa qareeb min el-jam3a.",
                exampleEn: "We are looking for an apartment near the university.",
            },
            {
                id: "3imara",
                ar: "عِمَارَة / بِنَايَة",
                en: "building",
                enArabeezy: "3imara / binaye",
                hint: "Both are natural. Plural: عِمَارَات / بِنَايَات.",
                exampleAr: "العِمَارَة هَادِي فِيهَا أَرْبَع طَوَابِق.",
                exampleArabeezy: "el-3imara hadi feeha arba3 Tawabeq.",
                exampleEn: "This building has four floors.",
            },
            {
                id: "tabaq",
                ar: "طَابِق",
                en: "floor",
                enArabeezy: "Tabaq",
                hint: "Examples: أَوَّل طَابِق، تَانِي طَابِق، الطَّابِق التَّالِت. We say التالت because it means the third floor, not the number three alone.",
                exampleAr: "الشَّقَّة عَالطَّابِق التَّالِت.",
                exampleArabeezy: "esh-sha2qa 3aT-Tabaq et-talet.",
                exampleEn: "The apartment is on the third floor.",
            },
            {
                id: "kam_shaqqa",
                ar: "كَم شَقَّة فِي الطَّابِق؟",
                en: "How many apartments are on the floor?",
                enArabeezy: "kam sha2qa fi eT-Tabaq?",
                hint: "Practical question when viewing a building.",
                exampleAr: "لَوْ سَمَحْت، كَم شَقَّة فِي الطَّابِق؟",
                exampleArabeezy: "law sama7t, kam sha2qa fi eT-Tabaq?",
                exampleEn: "Excuse me, how many apartments are on the floor?",
            },
            {
                id: "ijar",
                ar: "إِيجَار",
                en: "rent",
                enArabeezy: "ijar",
                hint: "Monthly rent. Ask: قَدِّيش الإِيجَار بِالشَّهْر؟",
                exampleAr: "قَدِّيش الإِيجَار بِالشَّهْر؟",
                exampleArabeezy: "addeesh el-ijar bish-shahr?",
                exampleEn: "How much is the rent per month?",
            },
            {
                id: "ta2meen",
                ar: "تَأْمِين",
                en: "deposit",
                enArabeezy: "ta2meen",
                hint: "Money paid before renting. Different from health insurance.",
                exampleAr: "الإِيجَار شَهْر، وَالتَّأْمِين شَهْر.",
                exampleArabeezy: "el-ijar shahr, w et-ta2meen shahr.",
                exampleEn: "The rent is one month, and the deposit is one month.",
            },
            {
                id: "aqd_ijar",
                ar: "عَقْد إِيجَار",
                en: "rental contract",
                enArabeezy: "3aqd ijar",
                hint: "Use when asking about rules, deposit, and repairs.",
                exampleAr: "التَّصْلِيح مَكْتُوب فِي عَقْد الإِيجَار.",
                exampleArabeezy: "et-taSli7 maktoob fi 3aqd el-ijar.",
                exampleEn: "The repair is written in the rental contract.",
            },
            {
                id: "sa7eb_el_beit",
                ar: "صَاحِب البَيْت",
                en: "landlord / owner",
                enArabeezy: "sa7eb el-beit",
                hint: "For a woman: صَاحْبِة البَيْت.",
                exampleAr: "صَاحِب البَيْت وَرَّانَا تَلَات شُقَق.",
                exampleArabeezy: "sa7eb el-beit warrana talat shuqaq.",
                exampleEn: "The landlord showed us three apartments.",
            },
            {
                id: "jar",
                ar: "جَار / جَارَة",
                en: "neighbour",
                enArabeezy: "jar / jara",
                hint: "Plural: جِيرَان. Ask: كِيف الجِيرَان؟",
                exampleAr: "كِيف الجِيرَان فِي العِمَارَة؟",
                exampleArabeezy: "keef el-jeeran fi el-3imara?",
                exampleEn: "How are the neighbours in the building?",
            },
            {
                id: "salon",
                ar: "صَالُون",
                en: "living room",
                enArabeezy: "salon",
                hint: "Room for sitting with family or guests.",
                exampleAr: "الصَّالُون وَاسِع وَفِيه ضَوّ حُلْو.",
                exampleArabeezy: "eS-Salon wase3 w feeh Daw 7ilu.",
                exampleEn: "The living room is spacious and has nice light.",
            },
            {
                id: "ghurfet_nom",
                ar: "غُرْفِة نَوم",
                en: "bedroom",
                enArabeezy: "ghurfet nom",
                hint: "Useful when counting rooms: غُرْفِة نَوم وَاحْدَة / غُرْفِتِين نَوم.",
                exampleAr: "الشَّقَّة فِيهَا غُرْفِتِين نَوم وَصَالُون.",
                exampleArabeezy: "esh-sha2qa feeha ghurfitain nom w salon.",
                exampleEn: "The apartment has two bedrooms and a living room.",
            },
            {
                id: "matbakh",
                ar: "مَطْبَخ",
                en: "kitchen",
                enArabeezy: "maTbakh",
                hint: "Plural: مَطَابِخ.",
                exampleAr: "المَطْبَخ جَنْب الصَّالُون.",
                exampleArabeezy: "el-maTbakh jamb eS-Salon.",
                exampleEn: "The kitchen is next to the living room.",
            },
            {
                id: "7ammam",
                ar: "حَمَّام",
                en: "bathroom",
                enArabeezy: "7ammam",
                hint: "Plural: حَمَّامَات.",
                exampleAr: "الحَمَّام جُوَّا الشَّقَّة، قُدَّام المَطْبَخ.",
                exampleArabeezy: "el-7ammam juwwa esh-sha2qa, quddam el-maTbakh.",
                exampleEn: "The bathroom is inside the apartment, in front of the kitchen.",
            },
            {
                id: "balkon_barande",
                ar: "بَلَكُون / بَرَنْدَة",
                en: "balcony",
                enArabeezy: "balkon / barande",
                hint: "Both are used. Ask: البَرَنْدَة وِين بِتْطُلّ؟ = Where does the balcony look out?",
                exampleAr: "البَرَنْدَة بِتْطُلّ عَالشَّارِع.",
                exampleArabeezy: "el-barande bitTull 3ash-share3.",
                exampleEn: "The balcony looks out onto the street.",
            },
            {
                id: "iTlala",
                ar: "إِطْلَالَة",
                en: "view",
                enArabeezy: "iTlala",
                hint: "Common with balcony/roof: إِطْلَالَة عَالبَحْر / عَالشَّارِع.",
                exampleAr: "إِطْلَالَة البَلَكُون حُلْوَة بِالمَسَا.",
                exampleArabeezy: "iTlalet el-balkon 7ilwe bil-masa.",
                exampleEn: "The balcony view is nice in the evening.",
            },
            {
                id: "saTe7",
                ar: "سَطْح",
                en: "rooftop",
                enArabeezy: "saTe7",
                hint: "The roof of the building. Often used for laundry, tanks, or sitting outside.",
                exampleAr: "السَّطْح فَوْق، وَمُمْكِن نِنْشُر غَسِيل هُنَاك.",
                exampleArabeezy: "es-saTe7 foq, w mumkin ninshor ghaseel hunak.",
                exampleEn: "The rooftop is upstairs, and we can hang laundry there.",
            },
            {
                id: "mamarr",
                ar: "مَمَرّ",
                en: "hallway",
                enArabeezy: "mamarr",
                hint: "Inside a building or apartment. Also: المَمَرّ بَيْن الشُّقَق. Use with location words: جُوَّا العِمَارَة، بَيْن الشُّقَق.",
                exampleAr: "المَمَرّ بَيْن الشُّقَق ضَيِّق شُوَيّ.",
                exampleArabeezy: "el-mamarr bain esh-shuqaq Dayyeq shway.",
                exampleEn: "The hallway between the apartments is a little narrow.",
            },
            {
                id: "mis3ad",
                ar: "مِصْعَد / أَسَنْسِير",
                en: "elevator",
                enArabeezy: "miS3ad / asanseer",
                hint: "أَسَنْسِير is very common in speech. Ask if it works before renting.",
                exampleAr: "الأَسَنْسِير شَغَّال وَلَا خَرْبَان؟",
                exampleArabeezy: "el-asanseer shaghghal wala kharban?",
                exampleEn: "Is the elevator working or broken?",
            },
            {
                id: "daraj",
                ar: "دَرَج / سِلِّم",
                en: "stairs / staircase",
                enArabeezy: "daraj / sillem",
                hint: "دَرَج is stairs in general. سِلِّم is the building staircase.",
                exampleAr: "إِذَا الأَسَنْسِير خَرْبَان، بِنِطْلَع عَالدَّرَج.",
                exampleArabeezy: "iza el-asanseer kharban, biniTla3 3ad-daraj.",
                exampleEn: "If the elevator is broken, we go up the stairs.",
            },
            {
                id: "kahraba",
                ar: "كَهْرَبَا",
                en: "electricity",
                enArabeezy: "kahraba",
                hint: "Ask about cuts: الكَهْرَبَا بِتِقْطَع كْتِير؟",
                exampleAr: "الكَهْرَبَا بِتِقْطَع كْتِير فِي المِنْطَقَة؟",
                exampleArabeezy: "el-kahraba biti2Ta3 kteer fi el-minTa2a?",
                exampleEn: "Does the electricity cut off a lot in the area?",
            },
            {
                id: "internet",
                ar: "إِنْتَرْنِت",
                en: "internet",
                enArabeezy: "internet",
                hint: "Common questions: الإِنْتَرْنِت قَوِي؟ فِي أَلْيَاف؟",
                exampleAr: "الإِنْتَرْنِت قَوِي فِي الطَّابِق التَّالِت؟",
                exampleArabeezy: "el-internet qawi fi eT-Tabaq et-talet?",
                exampleEn: "Is the internet strong on the third floor?",
            },
            {
                id: "sakhan",
                ar: "سَخَّان",
                en: "water heater",
                enArabeezy: "sakhkhan",
                hint: "Ask if it works: السَّخَّان شَغَّال؟",
                exampleAr: "السَّخَّان شَغَّال وَلَا بَدُّه تَصْلِيح؟",
                exampleArabeezy: "es-sakhkhan shaghghal wala biddo taSli7?",
                exampleEn: "Is the heater working or does it need repair?",
            },
            {
                id: "7anafiye",
                ar: "حَنَفِيَّة",
                en: "tap / faucet",
                enArabeezy: "7anafiye",
                hint: "Plural: حَنَفِيَّات. It drips = بْتِنْقُط.",
                exampleAr: "حَنَفِيَّة الحَمَّام بْتِنْقُط طُول اللَّيْل.",
                exampleArabeezy: "7anafiyyet el-7ammam bitinqoT Tool el-lel.",
                exampleEn: "The bathroom tap drips all night.",
            },
            {
                id: "masoora",
                ar: "مَاسُورَة",
                en: "pipe",
                enArabeezy: "masoora",
                hint: "Plural: مَوَاسِير. Common with plumbers and leaks. Use location words: تَحْت المَغْسَلَة، وَرَا الحِيطَة.",
                exampleAr: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط.",
                exampleArabeezy: "el-masoora ta7t el-maghsale bitinqoT.",
                exampleEn: "The pipe under the sink is dripping.",
            },
            {
                id: "maghsale",
                ar: "مَغْسَلَة",
                en: "sink",
                enArabeezy: "maghsale",
                hint: "Bathroom or kitchen sink. Plural: مَغَاسِل.",
                exampleAr: "المَغْسَلَة فِي المَطْبَخ مَسْدُودَة.",
                exampleArabeezy: "el-maghsale fi el-maTbakh masdoode.",
                exampleEn: "The kitchen sink is blocked.",
            },
            {
                id: "masdood",
                ar: "مَسْدُود / مَسْدُودَة",
                en: "blocked / clogged",
                enArabeezy: "masdood / masdoode",
                hint: "Male: مَسْدُود. Female: مَسْدُودَة.",
                exampleAr: "المَغْسَلَة مَسْدُودَة وِبِدَّهَا سَبَّاك.",
                exampleArabeezy: "el-maghsale masdoode w biddha sabbak.",
                exampleEn: "The sink is blocked and needs a plumber.",
            },
            {
                id: "binqoT",
                ar: "بْيِنْقُط / بْتِنْقُط",
                en: "it drips / leaks",
                enArabeezy: "binqoT / bitinqoT",
                hint: "For taps, pipes, roofs, or ceilings.",
                exampleAr: "السَّقْف بْيِنْقُط لَمَّا الدُّنْيَا تِشْتِي.",
                exampleArabeezy: "es-saqf binqoT lamma ed-dunya tishti.",
                exampleEn: "The ceiling drips when it rains.",
            },
            {
                id: "kharban",
                ar: "خَرْبَان / خَرْبَانَة",
                en: "broken / not working",
                enArabeezy: "kharban / kharbane",
                hint: "Male: خَرْبَان. Female: خَرْبَانَة. Plural: خَرْبَانِين.",
                exampleAr: "الأَسَنْسِير خَرْبَان مِن اِمْبَارِح.",
                exampleArabeezy: "el-asanseer kharban min embare7.",
                exampleEn: "The elevator has been broken since yesterday.",
            },
            {
                id: "bishtaghel",
                ar: "بِشْتَغِل / مِش شَغَّال",
                en: "it works / it is not working",
                enArabeezy: "bishtaghel / mish shaghghal",
                hint: "For elevator, heater, internet, light, washing machine.",
                exampleAr: "السَّخَّان مِش شَغَّال بَس الأَسَنْسِير بِشْتَغِل.",
                exampleArabeezy: "es-sakhkhan mish shaghghal bas el-asanseer bishtaghel.",
                exampleEn: "The heater is not working, but the elevator works.",
            },
            {
                id: "salle7",
                ar: "صَلَّح / بَدُّه تَصْلِيح",
                en: "fixed / it needs repair",
                enArabeezy: "Salla7 / biddo taSli7",
                hint: "Question: صَلَّحْتُه؟ Answer: لِسَّا نَفْس المُشْكِلَة / هَلِّق أَحْسَن.",
                exampleAr: "السَّخَّان بَدُّه تَصْلِيح قَبْل مَا نِسْكُن.",
                exampleArabeezy: "es-sakhkhan biddo taSli7 qabel ma niskon.",
                exampleEn: "The heater needs repair before we move in.",
            },
            {
                id: "sabbak",
                ar: "سَبَّاك",
                en: "plumber",
                enArabeezy: "sabbak",
                hint: "For sink, tap, pipe, heater, or dripping.",
                exampleAr: "إِمْتَى بِتِقْدَر تِبْعَت سَبَّاك؟",
                exampleArabeezy: "emta btigdar tib3at sabbak?",
                exampleEn: "When can you send a plumber?",
            },
            {
                id: "fanni",
                ar: "فَنِّي",
                en: "technician",
                enArabeezy: "fanni",
                hint: "General repair person. Plural: فَنِّيِين.",
                exampleAr: "مُمْكِن تِبْعَت فَنِّي يِشُوف الإِنْتَرْنِت؟",
                exampleArabeezy: "mumkin tib3at fanni yishoof el-internet?",
                exampleEn: "Can you send a technician to check the internet?",
            },
            {
                id: "doshe",
                ar: "دَوْشَة / ضَجَّة",
                en: "noise",
                enArabeezy: "doshe / Dajje",
                hint: "دَوْشَة is very natural. Polite: فِيك تِخَفِّف الصَّوْت شُوَي؟",
                exampleAr: "فِي دَوْشَة مِن الشَّقَّة اللِّي فَوْقِينَا.",
                exampleArabeezy: "fi doshe min esh-sha2qa illi foqena.",
                exampleEn: "There is noise from the apartment above us.",
            },
            {
                id: "rutube",
                ar: "رُطُوبَة",
                en: "humidity / dampness",
                enArabeezy: "ruToobe",
                hint: "Common in Gaza apartments, especially on walls after winter.",
                exampleAr: "فِي رُطُوبَة عَالحِيطَة وَرَا الخِزَانَة.",
                exampleArabeezy: "fi ruToobe 3al-7eeTa wara el-khizane.",
                exampleEn: "There is dampness on the wall behind the closet.",
            },
            {
                id: "mushkile",
                ar: "عِنْدِي مُشْكِلِة / بَدِّي أَحْكِي عَن مُشْكِلِة",
                en: "I have a problem / I want to talk about a problem",
                enArabeezy: "3indi mushkile / baddi a7ki 3an mushkile",
                hint: "Polite repair opening. Add: مَعْلِيش عَالإِزْعَاج، مُمْكِن تِشُوفْهَا؟",
                exampleAr: "لَوْ سَمَحْت، بَدِّي أَحْكِي عَن مُشْكِلِة فِي الشَّقَّة.",
                exampleArabeezy: "law sama7t, baddi a7ki 3an mushkile fi esh-sha2qa.",
                exampleEn: "Excuse me, I want to talk about a problem in the apartment.",
            },
            {
                id: "mumkin_tsa3idni",
                ar: "مُمْكِن تِسَاعِدْنِي؟",
                en: "Can you help me?",
                enArabeezy: "mumkin tsa3idni?",
                hint: "Useful with landlord, neighbour, technician, or guard.",
                exampleAr: "مُمْكِن تِسَاعِدْنِي؟ السَّخَّان مِش شَغَّال.",
                exampleArabeezy: "mumkin tsa3idni? es-sakhkhan mish shaghghal.",
                exampleEn: "Can you help me? The heater is not working.",
            },
        ],
    },

    dialogue: {
    title: "Apartment Hunting - Looking for an Apartment",
    setting: "Rami and Mona meet Abu Ahmad to look at apartments for rent and ask about rooms, rent, internet, neighbors, and building problems.",
    lines: [
        { speaker: "Rami", ar: "السَّلَام عَلَيْكُم، أَبُو أَحْمَد؟", arArabeezy: "es-salam 3aleikom, abu a7mad?", en: "Peace be upon you, Abu Ahmad?" },
        { speaker: "Abu Ahmad", ar: "وَعَلَيْكُم السَّلَام. أَهْلًا وَسَهْلًا، تْفَضَّلُوا.", arArabeezy: "w 3aleikom es-salam. ahlan w sahlan, tfaDDalu.", en: "Peace be upon you too. Welcome, come in." },
        { speaker: "Rami", ar: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة لِلإِيجَار، وَحَكُولْنَا عِنْدَك أَكْتَر مِن شَقَّة فَاضْيَة.", arArabeezy: "i7na bindawwer 3ala sha22a lil-ijar, w 7akoolna 3indak aktar min sha22a faDye.", en: "We’re looking for an apartment to rent, and they told us you have more than one empty apartment." },
        { speaker: "Abu Ahmad", ar: "صَحِيح، عِنْدِي تَلَات شُقَق. وَحْدَة بِالطَّابِق الأَوَّل، وَوَحْدَة بِالتَّالِت، وَوَحْدَة بِالرَّابِع.", arArabeezy: "Sa7ee7, 3indi talat sho2a2. wa7de biT-Tabe2 el-awwal, w wa7de bit-talet, w wa7de bir-rabe3.", en: "That’s right, I have three apartments. One on the first floor, one on the third, and one on the fourth." },
        { speaker: "Mona", ar: "إِحْنَا بَدْنَا إِشِي قَرِيب مِن الجَامْعَة وَالمُوَاصَلَات.", arArabeezy: "i7na baddna ishi 2areeb min el-jam3a w el-mowaSalat.", en: "We want something close to the university and transportation." },
        { speaker: "Abu Ahmad", ar: "المَوْقِع كُلُّه قَرِيب، بَس كُلّ شَقَّة إِلْهَا مِيزَاتْهَا.", arArabeezy: "el-mawqi3 kollo 2areeb, bas kol sha22a ilha meezatha.", en: "The whole location is close, but each apartment has its own advantages." },
        { speaker: "Rami", ar: "طَيِّب، خَلِّينَا نْبَلِّش بِالطَّابِق التَّالِت.", arArabeezy: "Tayyib, khallina nballish biT-Tabe2 et-talet.", en: "Okay, let’s start with the third floor." },
        { speaker: "Abu Ahmad", ar: "اتْفَضَّلُوا، الأَسَنْسِير هُون.", arArabeezy: "itfaDDalu, el-asansir hoon.", en: "Come in, the elevator is here." },
        { speaker: "Mona", ar: "الحَمْدُ لله فِيه أَسَنْسِير، كُنْت مُفَكِّرَة مَا فِيه.", arArabeezy: "el-7amdullah fee asansir, kont mfakkire ma fee.", en: "Thank God there’s an elevator. I thought there wasn’t one." },
        { speaker: "Abu Ahmad", ar: "لَا، مَوْجُود وَبْيِشْتَغِل الحَمْدُ لله.", arArabeezy: "la, mawjood w biyishtighil el-7amdullah.", en: "No, it’s there and it works, thank God." },
        { speaker: "Rami", ar: "وَلَو خَرِب؟", arArabeezy: "w law khirib?", en: "And if it breaks?" },
        { speaker: "Abu Ahmad", ar: "بِتْحْكُوا مَعِي، وَبَبْعَت فَنِّي بِنَفْس اليَوْم إِنْ شَاء الله.", arArabeezy: "bit7ku ma3i, w bab3at fanni binafs el-yom inshallah.", en: "You talk to me, and I’ll send a technician the same day, God willing." },
        { speaker: "Mona", ar: "مْنِيح.", arArabeezy: "mnee7.", en: "Good." },
        { speaker: "Abu Ahmad", ar: "هَاي الشَّقَّة.", arArabeezy: "hay esh-sha22a.", en: "This is the apartment." },
        { speaker: "Rami", ar: "وَاو... وَاسْعَة.", arArabeezy: "wow... was3a.", en: "Wow... it’s spacious." },
        { speaker: "Mona", ar: "قَدِّيش عَدَد الغُرَف؟", arArabeezy: "addeesh 3adad el-ghoraf?", en: "How many rooms are there?" },
        { speaker: "Abu Ahmad", ar: "غُرْفْتِين نَوْم، وَصَالُون، وَمَطْبَخ، وَحَمَّام، وَبَرَنْدَة.", arArabeezy: "ghorftain nom, w Saloon, w maTbakh, w 7ammam, w barande.", en: "Two bedrooms, a living room, a kitchen, a bathroom, and a balcony." },
        { speaker: "Rami", ar: "البَرَنْدَة بْتِطِلّ عَلَى وِين؟", arArabeezy: "el-barande btiTill 3ala wayn?", en: "What does the balcony overlook?" },
        { speaker: "Abu Ahmad", ar: "عَلَى شَارِع هَادِي، وَفِي حَدِيقَة قُدَّام العِمَارَة.", arArabeezy: "3ala share3 hadi, w fi 7adee2a qoddam el-3imara.", en: "It overlooks a quiet street, and there’s a garden in front of the building." },
        { speaker: "Mona", ar: "هَاي عَجَبِتْنِي.", arArabeezy: "hay 3ajabitni.", en: "I like this one." },
        { speaker: "Rami", ar: "قَدِّيش الإِيجَار؟", arArabeezy: "addeesh el-ijar?", en: "How much is the rent?" },
        { speaker: "Abu Ahmad", ar: "أَلْف وَخَمْسْمِيَّة بِالشَّهْر.", arArabeezy: "alf w khamsmiyye bish-shaher.", en: "One thousand five hundred per month." },
        { speaker: "Rami", ar: "وَفِي تَأْمِين؟", arArabeezy: "w fi ta2meen?", en: "And is there a deposit?" },
        { speaker: "Abu Ahmad", ar: "آه، شَهْر وَاحِد.", arArabeezy: "ah, shaher wa7ed.", en: "Yes, one month." },
        { speaker: "Mona", ar: "وَالكَهْرَبَا وَالإِنْتَرْنِت كِيف هُون؟", arArabeezy: "w el-kahraba w el-internet keef hoon?", en: "And how are the electricity and internet here?" },
        { speaker: "Abu Ahmad", ar: "الكَهْرَبَا كُوَيِّسَة، وَالإِنْتَرْنِت فَايْبَر.", arArabeezy: "el-kahraba kwayyise, w el-internet fiber.", en: "The electricity is good, and the internet is fiber." },
        { speaker: "Rami", ar: "مُمْتَاز.", arArabeezy: "momtaz.", en: "Excellent." },
        { speaker: "Mona", ar: "فِيه رُطُوبَة بِالشِّتَا؟", arArabeezy: "fee rToobe bish-sheta?", en: "Is there humidity in winter?" },
        { speaker: "Abu Ahmad", ar: "كَان فِيه مُشْكِلَة بَسِيطَة وَرَا الخِزَانَة، بَس انْحَلَّت.", arArabeezy: "kan fee moshkile baseeTa wara el-khazane, bas in7allat.", en: "There was a small issue behind the closet, but it was fixed." },
        { speaker: "Rami", ar: "أَكِيد انْحَلَّت؟ وَلَا مُمْكِن تِرْجَع؟", arArabeezy: "akeed in7allat? wala mumkin tirja3?", en: "Are you sure it was fixed? Or could it come back?" },
        { speaker: "Abu Ahmad", ar: "لَا إِنْ شَاء الله، تْفَضَّل شُوف الحِيط لَحَالَك.", arArabeezy: "la inshallah, tfaDDal shoof el-7eeT la7alak.", en: "No, God willing. Go ahead and check the wall yourself." },
        { speaker: "Mona", ar: "شَكْلُه تَمَام.", arArabeezy: "shaklo tamam.", en: "It looks fine." },
        { speaker: "Rami", ar: "وَالتَّدْفِئَة؟", arArabeezy: "w et-tadfi2a?", en: "And the heating?" },
        { speaker: "Abu Ahmad", ar: "السَّخَّان جَدِيد، وَالمُكَيِّف بَارِد وَسُخْن.", arArabeezy: "es-sakhkhan jadeed, w el-mkayif bared w sokhen.", en: "The water heater is new, and the AC does both cold and hot." },
        { speaker: "Mona", ar: "وَالجِيرَان كِيف؟", arArabeezy: "w el-jeeran keef?", en: "And how are the neighbors?" },
        { speaker: "Abu Ahmad", ar: "هَادْئِين، بَس فَوْق فِي عِيلَة مَعْهَا وَلَدِين صْغَار.", arArabeezy: "hadi2een, bas fo2 fi 3eile ma3ha waladain Sghar.", en: "They’re quiet, but upstairs there’s a family with two small children." },
        { speaker: "Rami", ar: "بْيِلْعَبُوا كْتِير؟", arArabeezy: "byil3abu kteer?", en: "Do they play a lot?" },
        { speaker: "Abu Ahmad", ar: "بِصَرَاحَة مَرَّات العَصِر، أَمَّا بِاللَّيْل هُدُوء.", arArabeezy: "biSara7a marrat el-3aSr, amma bil-leil hodoo2.", en: "Honestly, sometimes in the afternoon, but at night it’s quiet." },
        { speaker: "Mona", ar: "هَيْك مْنِيح.", arArabeezy: "hek mnee7.", en: "That’s good." },
        { speaker: "Rami", ar: "فِي سَطْح؟", arArabeezy: "fi saT7?", en: "Is there a rooftop?" },
        { speaker: "Abu Ahmad", ar: "آه، فَوْق مُبَاشَرَة.", arArabeezy: "ah, fo2 mobasharatan.", en: "Yes, directly above." },
        { speaker: "Rami", ar: "مَسْمُوح نِطْلَع عَلَيْه؟", arArabeezy: "masmoo7 niTla3 3aleih?", en: "Are we allowed to go up there?" },
        { speaker: "Abu Ahmad", ar: "أَكِيد، بَس بِدُون إِزْعَاج لِلْجِيرَان.", arArabeezy: "akeed, bas bidoon iz3aj lil-jeeran.", en: "Of course, but without disturbing the neighbors." },
        { speaker: "Mona", ar: "طَيِّب وِين الغَسَّالَة بْتِنْحَطّ؟", arArabeezy: "Tayyib wayn el-ghassale btin7aTT?", en: "Okay, where does the washing machine go?" },
        { speaker: "Abu Ahmad", ar: "بَرَّا بِالبَرَنْدَة، وَفِيهَا مَكَان مُخَصَّص.", arArabeezy: "barra bil-barande, w feeha makan mkhaSSaS.", en: "Outside on the balcony, and there’s a designated place for it." },
        { speaker: "Rami", ar: "وَالقُمَامَة؟", arArabeezy: "w el-qomame?", en: "And the trash?" },
        { speaker: "Abu Ahmad", ar: "الحَاوِيَات قُدَّام العِمَارَة.", arArabeezy: "el-7awiyat qoddam el-3imara.", en: "The bins are in front of the building." },
        { speaker: "Mona", ar: "طَيِّب إِذَا صَار عَطَل بِالكَهْرَبَا أَو الإِنْتَرْنِت؟", arArabeezy: "Tayyib iza Sar 3aTal bil-kahraba aw el-internet?", en: "Okay, if there’s a problem with the electricity or internet?" },
        { speaker: "Abu Ahmad", ar: "بِتْتِصْلُوا فِيَّ، وَأَنَا بَتَابَع مَع الفَنِّي.", arArabeezy: "bittSilu fiyya, w ana bataba3 ma3 el-fanni.", en: "You call me, and I’ll follow up with the technician." },
        { speaker: "Rami", ar: "مْنِيح، لِأَنُّه آخِر شَقَّة كُنَّا فِيهَا كُنَّا نِسْتَنَّى بِالأَيَّام.", arArabeezy: "mnee7, la2anno akher sha22a kunna feeha kunna nistanna bil-ayam.", en: "Good, because in the last apartment we used to wait for days." },
        { speaker: "Abu Ahmad", ar: "لَا، هُون إِنْ شَاء الله الأُمُور أَسْرَع.", arArabeezy: "la, hoon inshallah el-omoor asra3.", en: "No, here things should be faster, God willing." },
        { speaker: "Mona", ar: "طَيِّب... مُمْكِن نْشُوف شَقَّة الطَّابِق الرَّابِع كَمَان؟", arArabeezy: "Tayyib... mumkin nshoof sha22et eT-Tabe2 er-rabe3 kaman?", en: "Okay... can we also see the fourth-floor apartment?" },
        { speaker: "Abu Ahmad", ar: "أَكِيد.", arArabeezy: "akeed.", en: "Of course." },
        { speaker: "Rami", ar: "شُو الفَرْق بَيْنْهَا وَبَيْن هَاي؟", arArabeezy: "shoo el-far2 bainha w bain hay?", en: "What’s the difference between it and this one?" },
        { speaker: "Abu Ahmad", ar: "إِيجَارْهَا أَغْلَى بِمِيَّة شِيكل، بَس أَصْغَر شُوَي، وَإِطْلَالْتْهَا أَحْلَى.", arArabeezy: "ijarha aghla b-miyye shekel, bas aSghar shway, w iTlalitha a7la.", en: "Its rent is one hundred shekels more expensive, but it’s a little smaller, and its view is nicer." },
        { speaker: "Mona", ar: "أَمَّا أَنَا بُفَضِّل التَّالْتَة.", arArabeezy: "amma ana bfaDDil et-talte.", en: "As for me, I prefer the third one." },
        { speaker: "Rami", ar: "وَأَنَا كَمَان. أَكْبَر وَأَرْيَح.", arArabeezy: "w ana kaman. akbar w arya7.", en: "Me too. It’s bigger and more comfortable." },
        { speaker: "Abu Ahmad", ar: "خُدُوا رَاحْتْكُم، وَلَا تِسْتَعْجِلُوا بِالقَرَار.", arArabeezy: "khodu ra7etkom, w la tista3jilu bil-qarar.", en: "Take your time, and don’t rush the decision." },
        { speaker: "Rami", ar: "إِنْ شَاء الله. إِذَا قَرَّرْنَا، بِنِتْوَاصَل مَعَك اليَوْمِين الجَايِين.", arArabeezy: "inshallah. iza qarrarna, binitwaSal ma3ak el-yomain el-jayeen.", en: "God willing. If we decide, we’ll contact you in the next couple of days." },
        { speaker: "Abu Ahmad", ar: "أَهْلًا وَسَهْلًا بِأَي وَقْت.", arArabeezy: "ahlan w sahlan bi-ay wa2t.", en: "You’re welcome anytime." },
        { speaker: "Mona", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Abu Ahmad", ar: "الله يْعَافِيكُم.", arArabeezy: "allah y3afeekom.", en: "You’re welcome." }
    ],

    questions: [
        { ar: "كَم شَقَّة كَانِت فَاضْيَة فِي العِمَارَة؟", en: "How many apartments were empty in the building?" },
        { ar: "بِأَي طَابِق بَلَّشُوا الجَوْلَة؟", en: "Which floor did they start the tour with?" },
        { ar: "كَم غُرْفَة فِي شَقَّة الطَّابِق التَّالِت؟", en: "How many rooms are in the third-floor apartment?" },
        { ar: "عَلَى شُو بْتِطِلّ البَرَنْدَة؟", en: "What does the balcony overlook?" },
        { ar: "قَدِّيش كَان إِيجَار الشَّقَّة؟", en: "How much was the apartment rent?" },
        { ar: "هَل كَان فِي تَأْمِين؟", en: "Was there a deposit?" },
        { ar: "كِيف وَصَف أَبُو أَحْمَد الإِنْتَرْنِت؟", en: "How did Abu Ahmad describe the internet?" },
        { ar: "شُو كَانِت مُشْكِلَة الرُّطُوبَة؟", en: "What was the humidity problem?" },
        { ar: "كِيف وَصَف الجِيرَان؟", en: "How did he describe the neighbors?" },
        { ar: "وِين مَكَان الغَسَّالَة؟", en: "Where is the washing machine placed?" },
        { ar: "شُو الفَرْق بَيْن شَقَّة الطَّابِق التَّالِت وَالرَّابِع؟", en: "What is the difference between the third-floor and fourth-floor apartments?" },
        { ar: "أَي شَقَّة عَجَبَت رَامِي وَمُونَا أَكْتَر؟ وَلِيش؟", en: "Which apartment did Rami and Mona like more, and why?" }
    ],
},

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "apt_mc1",
                type: "complete",
                prompt: "You are viewing an apartment. Complete: How much is the rent per month? قَدِّيش ___ بِالشَّهْر؟",
                options: ["الإِيجَار", "السَّطْح", "الدَّرَج", "الدَّوْشَة"],
                correct: "الإِيجَار",
            },
            {
                id: "apt_mc2",
                type: "match",
                prompt: "Choose the natural question for: Which floor is the apartment on?",
                options: ["الشَّقَّة عَأَيّ طَابِق؟", "الشَّقَّة شُو مَالِك؟", "الشَّقَّة كِيف الجَوّ؟", "الشَّقَّة قَدِّيش عُمُرَك؟"],
                correct: "الشَّقَّة عَأَيّ طَابِق؟",
            },
            {
                id: "apt_mc3",
                type: "reorder",
                prompt: "Reorder: The balcony looks out onto the street.",
                options: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
                correct: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
            },
            {
                id: "apt_mc4",
                type: "complete",
                prompt: "Location check: The pipe is under the sink. المَاسُورَة ___ المَغْسَلَة.",
                options: ["تَحْت", "بِتْطُلّ", "إِيجَار", "دَوْشَة"],
                correct: "تَحْت",
            },
            {
                id: "apt_mc5",
                type: "complete",
                prompt: "Polite problem sentence: لَوْ سَمَحْت، بَدِّي ___ عَن مُشْكِلِة.",
                options: ["أَحْكِي", "أَنَام", "أَشْتَرِي", "أَفْطَر"],
                correct: "أَحْكِي",
            },
            {
                id: "apt_mc6",
                type: "match",
                prompt: "Choose the natural Gaza word for noise.",
                options: ["دَوْشَة", "رُطُوبَة", "تَأْمِين", "بَرَنْدَة"],
                correct: "دَوْشَة",
            },
            {
                id: "apt_mc7",
                type: "complete",
                prompt: "Follow-up after repair: ___ أَحْسَن.",
                options: ["هَلِّق", "قَدِّيش", "وَرَا", "سَبَّاك"],
                correct: "هَلِّق",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "apt_q1",
                questionAr: "«بَرَنْدَة» مَعْنَاهَا:",
                optionsEn: ["balcony", "hallway", "deposit"],
                correctIndex: 0,
            },
            {
                id: "apt_q2",
                questionAr: "إِذَا بَدَّك تِسْأَل عَن rent، بِتِقُول:",
                optionsEn: ["قَدِّيش الإِيجَار؟", "كِيف الجَوّ؟", "شُو مَالَك؟"],
                correctIndex: 0,
            },
            {
                id: "apt_q3",
                questionAr: "«المَمَرّ بَيْن الشُّقَق» مَعْنَاهَا:",
                optionsEn: ["the hallway between the apartments", "the balcony view", "the roof above"],
                correctIndex: 0,
            },
            {
                id: "apt_q4",
                questionAr: "«فَوْق» مَعْنَاهَا:",
                optionsEn: ["above / upstairs", "behind", "outside"],
                correctIndex: 0,
            },
            {
                id: "apt_q5",
                questionAr: "إِذَا الحَنَفِيَّة بْتِنْقُط، بِنْحْكِي مَع:",
                optionsEn: ["سَبَّاك", "دُكْتُور", "صَرَّاف"],
                correctIndex: 0,
            },
            {
                id: "apt_q6",
                questionAr: "«لِسَّا نَفْس المُشْكِلِة» مَعْنَاهَا:",
                optionsEn: ["It is still the same problem.", "Everything is solved now.", "The view is beautiful."],
                correctIndex: 0,
            },
            {
                id: "apt_q7",
                questionAr: "أَيّ كَلِمَة أَكْثَر طَبِيعِيَّة لِلـ noise؟",
                optionsEn: ["دَوْشَة", "تَأْمِين", "إِطْلَالَة"],
                correctIndex: 0,
            },
            {
                id: "apt_q8",
                questionAr: "«قُدَّام العِمَارَة» مَعْنَاهَا:",
                optionsEn: ["in front of the building", "behind the building", "inside the building"],
                correctIndex: 0,
            },
            {
                id: "apt_q9",
                questionAr: "إِذَا بَدَّك تِبَلِّغ عَن مُشْكِلِة بِأَدَب، بِتِقُول:",
                optionsEn: ["لو سمحت، بدي أبلغ عن مشكلة.", "إنت غلطان.", "ما بدي أحكي."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "View an apartment: ask the landlord about floor, rent, deposit, number of apartments per floor, balcony view, and neighbours.",
            "Compare two apartments: one cheaper but noisy, one more expensive but quieter and with a better balcony view.",
            "Report a repair problem: say the tap drips, the sink is blocked, or the heater is not working. Ask when someone can come.",
            "Talk to a neighbour politely: say there is noise and ask them to lower the sound a little.",
            "Mini speaking prompt: describe your ideal apartment in 8-10 sentences using location words.",
        ],
        sections: [
            {
                matching: [
                    { ar: "سَطْح", en: "rooftop" },
                    { ar: "مَمَرّ", en: "hallway" },
                    { ar: "بَرَنْدَة", en: "balcony" },
                    { ar: "دَوْشَة", en: "noise" },
                    { ar: "رُطُوبَة", en: "dampness" },
                ],
                fillInTheBlank: [
                    { prompt: "قَدِّيش ___ بِالشَّهْر؟", answer: "الإِيجَار" },
                    { prompt: "البَرَنْدَة ___ عَالشَّارِع.", answer: "بِتْطُلّ" },
                    { prompt: "المَاسُورَة ___ المَغْسَلَة.", answer: "تَحْت" },
                    { prompt: "فِي ___ عَالحِيطَة وَرَا الخِزَانَة.", answer: "رُطُوبَة" },
                    { prompt: "مُمْكِن ___ فَنِّي؟", answer: "تِبْعَت" },
                ],
                reorderSentences: [
                    {
                        prompt: "Put the words in order: How many apartments are on the floor?",
                        words: ["كَم", "شَقَّة", "فِي", "الطَّابِق؟"],
                        answer: "كَم شَقَّة فِي الطَّابِق؟",
                    },
                    {
                        prompt: "Put the words in order: The balcony looks out onto the street.",
                        words: ["البَرَنْدَة", "بِتْطُلّ", "عَالشَّارِع."],
                        answer: "البَرَنْدَة بِتْطُلّ عَالشَّارِع.",
                    },
                    {
                        prompt: "Put the words in order: There is dampness behind the closet.",
                        words: ["فِي", "رُطُوبَة", "وَرَا", "الخِزَانَة."],
                        answer: "فِي رُطُوبَة وَرَا الخِزَانَة.",
                    },
                ],
                writeYourOwnSentences: [
                    "Write 6 questions you would ask a landlord before renting an apartment.",
                    "Write 5 sentences comparing two apartments: rent, floor, balcony view, neighbours, and problems.",
                    "Change these to feminine: خَرْبَان / مَسْدُود / شَغَّال.",
                    "Use 5 location words in your own sentences: جوا، برا، فوق، تحت، جنب، قدام، ورا، بين.",
                ],
            },
        ],
        translation: [
            { id: "apt_t1", type: "enToAr", textEn: "We are looking for an apartment near the university.", textAr: "إِحْنَا بِنْدَوِّر عَلَى شَقَّة قَرِيب مِن الجَامْعَة." },
            { id: "apt_t2", type: "arToEn", textEn: "How many floors is the building?", textAr: "العِمَارَة كَم طَابِق؟" },
            { id: "apt_t3", type: "enToAr", textEn: "How many apartments are on each floor?", textAr: "كَم شَقَّة فِي كُلّ طَابِق؟" },
            { id: "apt_t4", type: "arToEn", textEn: "How much is the rent per month?", textAr: "قَدِّيش الإِيجَار بِالشَّهْر؟" },
            { id: "apt_t5", type: "enToAr", textEn: "The balcony looks out onto a quiet street.", textAr: "البَرَنْدَة بِتْطُلّ عَشَارِع هَادِي." },
            { id: "apt_t6", type: "arToEn", textEn: "There is dampness behind the closet.", textAr: "فِي رُطُوبَة وَرَا الخِزَانَة." },
            { id: "apt_t7", type: "enToAr", textEn: "Is the elevator working or broken?", textAr: "الأَسَنْسِير بِشْتَغِل وَلَا خَرْبَان؟" },
            { id: "apt_t8", type: "arToEn", textEn: "The hallway between the apartments is spacious.", textAr: "المَمَرّ بَيْن الشُّقَق وِاسِع." },
            { id: "apt_t9", type: "enToAr", textEn: "The pipe under the sink is dripping.", textAr: "المَاسُورَة تَحْت المَغْسَلَة بْتِنْقُط." },
            { id: "apt_t10", type: "arToEn", textEn: "Can you send a technician?", textAr: "مُمْكِن تِبْعَت فَنِّي؟" },
            { id: "apt_t11", type: "enToAr", textEn: "There is noise from the apartment above us.", textAr: "فِي دَوْشَة مِن الشَّقَّة اللِّي فَوْقِينَا." },
            { id: "apt_t12", type: "arToEn", textEn: "Can you lower the sound a little?", textAr: "فِيك تِخَفِّف الصَّوْت شُوَي؟" },
            { id: "apt_t13", type: "enToAr", textEn: "I want to talk about a problem in the apartment.", textAr: "بَدِّي أَحْكِي عَن مُشْكِلِة فِي الشَّقَّة." },
            { id: "apt_t14", type: "arToEn", textEn: "It is still the same problem.", textAr: "لِسَّا نَفْس المُشْكِلِة." },
            { id: "apt_t15", type: "enToAr", textEn: "Thank you for the help. Everything is okay now.", textAr: "يِعْطِيك العَافْيِة عَالمُسَاعَدَة. كُلّ إِشِي تَمَام هَلِّق." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-90 second apartment-hunting conversation in Gaza Palestinian Arabic. Pretend you are viewing an apartment with a landlord. Ask about: floor, rent, deposit, number of apartments on the floor, balcony view, neighbours, elevator, internet, and any repair problems. Use at least 10 words from this unit and 5 old words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. We are looking for an apartment near the university.
2. How many floors is the building?
3. How many apartments are on each floor?
4. How much is the rent per month?
5. The balcony looks out onto a quiet street.
6. There is dampness behind the closet.
7. Is the elevator working or broken?
8. The hallway between the apartments is spacious.
9. The pipe under the sink is dripping.
10. Can you send a technician?
11. There is noise from the apartment above us.
12. Can you lower the sound a little?
13. I want to talk about a problem in the apartment.
14. It is still the same problem.
15. Thank you for the help. Everything is okay now.`,
    },

    teacherNotes: {
        warmup: [
            "Start with: وين ساكن هلقيت؟ شقة ولا بيت؟ Then move into apartment-hunting questions.",
            "This unit's hidden focus is location words, numbers/floors, rent questions, polite requests, and repair follow-up.",
            "Keep the lesson as a real viewing appointment, not a vocabulary list.",
        ],
        vocabularySteps: [
            "Teach vocabulary in the same order as the dialogue: building -> available apartments -> rent -> balcony/view -> neighbours -> problems.",
            "Do not teach location words as grammar; use quick physical examples: المفتاح جوا، السطح فوق، السباك برا.",
            "Keep expressions practical: لو سمحت، ممكن تساعدني؟ بدي أبلغ عن مشكلة، لسا نفس المشكلة، هلقيت أحسن.",
        ],
        dialogueSteps: [
            "Act the dialogue as a viewing appointment with movement: entrance, hallway, elevator, apartment, balcony.",
            "Ask the dialogue questions orally and require complete answers.",
            "Have the student choose one of the three apartments and explain why.",
        ],
        practiceTips: [
            "Push real output: the student must ask the landlord questions, not only answer.",
            "Use comparison drills: أرخص / أغلى، أهدى / أزعج، أكبر / أصغر.",
            "Practice polite complaints without sounding aggressive.",
        ],
        wrapup: [
            "Student asks 6 landlord questions without reading.",
            "Student describes one apartment and one problem.",
            "Student says one polite neighbour sentence.",
        ],
        myNotes: "",
    },
};
