import { LESSON_ID_SHOPPING } from '../../core/constants.js';

export const lessonId = LESSON_ID_SHOPPING;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Shopping & Prices",
        lessonTitle: "Unit 8 - Shopping, Markets & Prices in Gaza Palestinian Arabic",
        contentVersion: 2026063001,
    },

    overview: {
        title: "Unit 8 - Shopping, Markets & Prices",
        description:
            "Students learn how to shop naturally in Gaza Palestinian Arabic: ask prices, compare quality, ask for size/color, bargain politely, buy by kilo or piece, and pay cash or card.",
        goals: [
            "Ask and answer about prices clearly.",
            "Use numbers, quantities, colors, size, and money in real shopping situations.",
            "Bargain politely without sounding rude.",
            "Say if something is expensive, cheap, suitable, or too much.",
            "Recycle previous units: greetings, weather, transport, food, family, work/study, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can buy something from a shop or market.",
            "The student can ask for another size/color and compare prices.",
            "The student can bargain in a simple natural way and complete payment.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "dukkan",
                ar: "دُكَّان",
                en: "corner shop / small shop",
                enArabeezy: "dukkan",
                hint: "Small neighborhood shop. Plural: دَكَاكِين.",
                exampleAr: "رُحْت عَالدُّكَّان أَشْتَرِي خُبِز وَحَلِيب.",
                exampleArabeezy: "ru7t 3ad-dukkan ashtiri khubiz w 7aleeb.",
                exampleEn: "I went to the corner shop to buy bread and milk.",
            },
            {
                id: "ma7al",
                ar: "مَحَلّ",
                en: "shop / store",
                enArabeezy: "ma7all",
                hint: "General word for any shop. Plural: مَحَلَّات.",
                exampleAr: "هَادَا المَحَلّ عِنْدُه أَوَاعِي مْنِيحَة.",
                exampleArabeezy: "hada el-ma7all 3indo awa3i mnee7a.",
                exampleEn: "This shop has good clothes.",
            },
            {
                id: "souk",
                ar: "سُوق",
                en: "market",
                enArabeezy: "souq",
                hint: "Traditional market or shopping street. In Gaza, السوق is used for clothes, vegetables, and daily needs.",
                exampleAr: "يَوم الجُمْعَة بِنِنْزَل عَالسُّوق.",
                exampleArabeezy: "yom el-jum3a bininzel 3as-souq.",
                exampleEn: "On Friday we go to the market.",
            },
            {
                id: "bashtiri",
                ar: "بَشْتِرِي",
                en: "I buy",
                enArabeezy: "bashtiri",
                hint: "From اِشْتَرَى = to buy. You can say: بَدِّي أَشْتِرِي... = I want to buy...",
                exampleAr: "بَشْتِرِي الخُضَار مِن السُّوق.",
                exampleArabeezy: "bashtiri el-khuDar min es-souq.",
                exampleEn: "I buy vegetables from the market.",
            },
            {
                id: "baddi_ashtiri",
                ar: "بَدِّي أَشْتِرِي",
                en: "I want to buy",
                enArabeezy: "baddi ashtiri",
                hint: "Best opener with a seller: بَدِّي أَشْتِرِي قَمِيص / جَزْمَة / هَدِيَّة.",
                exampleAr: "بَدِّي أَشْتِرِي هَدِيَّة لِأُخْتِي.",
                exampleArabeezy: "baddi ashtiri hadiyye la-okhti.",
                exampleEn: "I want to buy a gift for my sister.",
            },
            {
                id: "addeesh_hada",
                ar: "قَدِّيش هَادَا؟",
                en: "How much is this?",
                enArabeezy: "addeesh hada?",
                hint: "To ask price while pointing. For feminine item: قَدِّيش هَادِي؟",
                exampleAr: "لَوْ سَمَحْت، قَدِّيش هَادَا؟",
                exampleArabeezy: "law sama7t, addeesh hada?",
                exampleEn: "Please, how much is this?",
            },
            {
                id: "se3er",
                ar: "سِعِر",
                en: "price",
                enArabeezy: "se3er",
                hint: "Common chunks: السِّعِر غَالِي، السِّعِر مْنِيح، آخِر سِعِر؟",
                exampleAr: "السِّعِر مْنَاسِب، بَس بَدِّي أَشُوف غَيْرُه.",
                exampleArabeezy: "es-se3er mnasib, bas baddi ashoof gheero.",
                exampleEn: "The price is suitable, but I want to see another one.",
            },
            {
                id: "ghali",
                ar: "غَالِي / غَالْيَة",
                en: "expensive",
                enArabeezy: "ghali / ghalye",
                hint: "Male: غَالِي. Female: غَالْيَة. Plural: غَالْيِين.",
                exampleAr: "هَادَا غَالِي شُوَيّ، فِي أَرْخَص؟",
                exampleArabeezy: "hada ghali shway, fi arkhaS?",
                exampleEn: "This is a little expensive; is there a cheaper one?",
            },
            {
                id: "rkhees",
                ar: "رْخِيص / رْخِيصَة",
                en: "cheap / inexpensive",
                enArabeezy: "rkheeS / rkheeSa",
                hint: "Can be good price or low quality depending on context.",
                exampleAr: "هَادِي رْخِيصَة، بَس الجَوْدَة كِيف؟",
                exampleArabeezy: "hadi rkheeSa, bas el-jawde keef?",
                exampleEn: "This is cheap, but how is the quality?",
            },
            {
                id: "mnasib",
                ar: "مْنَاسِب / مْنَاسْبَة",
                en: "suitable / fair",
                enArabeezy: "mnasib / mnasbe",
                hint: "Useful for price, size, color, and timing.",
                exampleAr: "السِّعِر مْنَاسِب لِلْمِيزَانِيَّة.",
                exampleArabeezy: "es-se3er mnasib lil-mizaniyye.",
                exampleEn: "The price is suitable for the budget.",
            },
            {
                id: "tanzeelat",
                ar: "تَنْزِيلَات",
                en: "sales / discounts",
                enArabeezy: "tanzeelat",
                hint: "Common in shops. Also: خَصْم = discount.",
                exampleAr: "فِي تَنْزِيلَات عَالأَوَاعِي هَالأَيَّام.",
                exampleArabeezy: "fi tanzeelat 3al-awa3i hal-ayyam.",
                exampleEn: "There are sales on clothes these days.",
            },
            {
                id: "khasm",
                ar: "خَصْم",
                en: "discount",
                enArabeezy: "khasm",
                hint: "Ask politely: فِي خَصْم؟ / فِي خَصْم لِلْطُلَّاب؟",
                exampleAr: "فِي خَصْم إِذَا دَفَعْت كَاش؟",
                exampleArabeezy: "fi khasm iza dafa3t cash?",
                exampleEn: "Is there a discount if I pay cash?",
            },
            {
                id: "mumkin_tnazzel",
                ar: "مُمْكِن تْنَزِّل شُوَيّ؟",
                en: "Can you lower it a little?",
                enArabeezy: "mumkin tnazzel shway?",
                hint: "Polite bargaining phrase. To a woman seller: مُمْكِن تْنَزِّلِي شُوَيّ؟",
                exampleAr: "السِّعِر عَالِي، مُمْكِن تْنَزِّل شُوَيّ؟",
                exampleArabeezy: "es-se3er 3ali, mumkin tnazzel shway?",
                exampleEn: "The price is high; can you lower it a little?",
            },
            {
                id: "akher_se3er",
                ar: "آخِر سِعِر؟",
                en: "final price?",
                enArabeezy: "akher se3er?",
                hint: "Used after bargaining. Natural in markets, less in fixed-price stores.",
                exampleAr: "طَيِّب، آخِر سِعِر قَدِّيش؟",
                exampleArabeezy: "Tayyib, akher se3er addeesh?",
                exampleEn: "Okay, what's the final price?",
            },
            {
                id: "masari",
                ar: "مَصَارِي",
                en: "money",
                enArabeezy: "maSari",
                hint: "Very common Palestinian word. My money = مَصَارِيّي.",
                exampleAr: "مَعِي مَصَارِي شُوَيّ، بَدِّي شِي مْنَاسِب.",
                exampleArabeezy: "ma3i maSari shway, baddi shi mnasib.",
                exampleEn: "I have a little money; I want something suitable.",
            },
            {
                id: "mizaniyye",
                ar: "مِيزَانِيَّة",
                en: "budget",
                enArabeezy: "mizaniyye",
                hint: "Money you plan to spend.",
                exampleAr: "مِيزَانِيَّتِي اليَوم خَمْسِين شِيكِل.",
                exampleArabeezy: "mizaniyyti el-yom khamseen shekel.",
                exampleEn: "My budget today is fifty shekels.",
            },
            {
                id: "shekel",
                ar: "شِيكِل / شَوَاكِل",
                en: "shekel / shekels",
                enArabeezy: "shekel / shawakel",
                hint: "Common local currency. Singular: شِيكِل. Plural: شَوَاكِل.",
                exampleAr: "الكِيلُو بِعَشَرَة شَوَاكِل.",
                exampleArabeezy: "el-keelo bi-3ashara shawakel.",
                exampleEn: "The kilo is ten shekels.",
            },
            {
                id: "cash",
                ar: "كَاش",
                en: "cash",
                enArabeezy: "cash",
                hint: "Paying with physical money. Often better for small shops.",
                exampleAr: "بَدِّي أَدْفَع كَاش.",
                exampleArabeezy: "baddi adfa3 cash.",
                exampleEn: "I want to pay cash.",
            },
            {
                id: "card",
                ar: "كَارْت",
                en: "card",
                enArabeezy: "kart",
                hint: "Bank card. Ask: بِصِير أَدْفَع بِالكَارْت؟",
                exampleAr: "بِصِير أَدْفَع بِالكَارْت وَلَا بَس كَاش؟",
                exampleArabeezy: "biSeer adfa3 bil-kart wala bas cash?",
                exampleEn: "Can I pay by card, or only cash?",
            },
            {
                id: "wasl",
                ar: "وَصْل",
                en: "receipt",
                enArabeezy: "waSl",
                hint: "Useful for exchange/return. Also people may say: فَاتُورَة.",
                exampleAr: "خُد الوَصْل، مُمْكِن تِحْتَاجُه بَعْدِين.",
                exampleArabeezy: "khod el-waSl, mumkin ti7tajo ba3deen.",
                exampleEn: "Take the receipt; you might need it later.",
            },
            {
                id: "maqas",
                ar: "مَقَاس",
                en: "size",
                enArabeezy: "ma2as",
                hint: "For clothes and shoes. Big = كْبِير. Small = صْغِير.",
                exampleAr: "هَادَا المَقَاس كْبِير عَلَيّ شُوَيّ.",
                exampleArabeezy: "hada el-ma2as kbeer 3alay shway.",
                exampleEn: "This size is a little big on me.",
            },
            {
                id: "lawn",
                ar: "لَوْن / أَلْوَان",
                en: "color / colors",
                enArabeezy: "lawn / alwan",
                hint: "Use for clothes, shoes, bags, and gifts.",
                exampleAr: "عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟",
                exampleArabeezy: "3indak nafs el-ma2as bi-lawn tani?",
                exampleEn: "Do you have the same size in another color?",
            },
            {
                id: "azra2_aswad",
                ar: "أَزْرَق / أَسْوَد",
                en: "blue / black",
                enArabeezy: "azra2 / aswad",
                hint: "Color review. Feminine: زَرْقَا / سَوْدَا.",
                exampleAr: "بَدِّي الجَزْمَة السَّوْدَا، مِش الزَّرْقَا.",
                exampleArabeezy: "baddi el-jazme es-soda, mish ez-zar2a.",
                exampleEn: "I want the black shoes, not the blue ones.",
            },
            {
                id: "no3",
                ar: "نَوْع",
                en: "type / kind",
                enArabeezy: "no3",
                hint: "Use for fabric, food, coffee, clothes, and quality.",
                exampleAr: "شُو نَوْع القُمَاش هَادَا؟",
                exampleArabeezy: "sho no3 el-2umash hada?",
                exampleEn: "What type of fabric is this?",
            },
            {
                id: "jawde",
                ar: "جَوْدَة",
                en: "quality",
                enArabeezy: "jawde",
                hint: "High quality = جَوْدَة عَالْيَة. Low quality = جَوْدَة عَادِيَّة.",
                exampleAr: "السِّعِر رْخِيص، بَس الجَوْدَة عَادِيَّة.",
                exampleArabeezy: "es-se3er rkheeS, bas el-jawde 3adiyye.",
                exampleEn: "The price is cheap, but the quality is average.",
            },
            {
                id: "kilo",
                ar: "كِيلُو",
                en: "kilo",
                enArabeezy: "keelo",
                hint: "Used in food markets: fruits, vegetables, meat, cheese.",
                exampleAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة.",
                exampleArabeezy: "baddi noSS keelo bandora.",
                exampleEn: "I want half a kilo of tomatoes.",
            },
            {
                id: "noSS",
                ar: "نُصّ",
                en: "half",
                enArabeezy: "noSS",
                hint: "Very useful with kilos and prices: نُصّ كِيلُو، نُصّ السِّعِر.",
                exampleAr: "خَلِّيه نُصّ كِيلُو بَس.",
                exampleArabeezy: "khallih noSS keelo bas.",
                exampleEn: "Make it only half a kilo.",
            },
            {
                id: "qiT3a",
                ar: "قِطْعَة",
                en: "piece / item",
                enArabeezy: "2iT3a",
                hint: "Plural: قِطَع. Used for clothes, sweets, cheese, and items.",
                exampleAr: "بَدِّي قِطْعَة تَانْيَة مِن هَادَا النَّوْع.",
                exampleArabeezy: "baddi 2iT3a tanye min hada en-no3.",
                exampleEn: "I want another piece of this kind.",
            },
            {
                id: "kamm",
                ar: "كَمّ؟",
                en: "how many?",
                enArabeezy: "kam?",
                hint: "Use for quantity. Price question uses قَدِّيش؟",
                exampleAr: "كَمّ قِطْعَة بَدَّك؟",
                exampleArabeezy: "kam 2iT3a baddak?",
                exampleEn: "How many pieces do you want?",
            },
            {
                id: "3indak_tani",
                ar: "عِنْدَك إِشِي تَانِي؟",
                en: "Do you have something else?",
                enArabeezy: "3indak ishi tani?",
                hint: "Use for another model, size, color, or option.",
                exampleAr: "عِنْدَك إِشِي تَانِي نَفْس المَقَاس؟",
                exampleArabeezy: "3indak ishi tani nafs el-ma2as?",
                exampleEn: "Do you have something else in the same size?",
            },
            {
                id: "bas_batfarraj",
                ar: "أَنَا بَس بَتْفَرَّج",
                en: "I'm just looking",
                enArabeezy: "ana bas batfarraj",
                hint: "Polite phrase when seller approaches and you are not ready to buy.",
                exampleAr: "شُكْرًا، أَنَا بَس بَتْفَرَّج هَلْقِيت.",
                exampleArabeezy: "shukran, ana bas batfarraj halla2et.",
                exampleEn: "Thanks, I'm just looking for now.",
            },
            {
                id: "khallih",
                ar: "خَلِّيه",
                en: "make it / let it be",
                enArabeezy: "khallih",
                hint: "Useful in bargaining: خَلِّيه بِخَمْسِين = make it fifty.",
                exampleAr: "خَلِّيه بِخَمْسِين وَبَاخُدُه هَلْقِيت.",
                exampleArabeezy: "khallih bi-khamseen w bakhdo halla2et.",
                exampleEn: "Make it fifty and I'll take it now.",
            },
            {
                id: "bakhdo",
                ar: "بَاخُدُه / بَاخُدْهَا",
                en: "I'll take it",
                enArabeezy: "bakhdo / bakhodha",
                hint: "Male item: بَاخُدُه. Female item: بَاخُدْهَا. Plural: بَاخُدْهُم.",
                exampleAr: "تَمَام، بَاخُدْهَا.",
                exampleArabeezy: "tamam, bakhodha.",
                exampleEn: "Okay, I'll take it.",
            },
        ],
    },

    dialogue: {
    title: "Shopping, Markets & Prices - At the Market",
    setting: "Rami and Mona go shopping to buy a gift and then buy vegetables at the local market.",
    lines: [
        { speaker: "Rami", ar: "مُونَا، تَعَالِي هُون شُوَي.", arArabeezy: "mona, ta3ali hoon shway.", en: "Mona, come here for a second." },
        { speaker: "Mona", ar: "شُو لْقِيت؟", arArabeezy: "shoo l2eet?", en: "What did you find?" },
        { speaker: "Rami", ar: "بَدِّي أَجِيب هَدِيَّة لِأَخُوي، بَس مِش عَارِف شُو آخُد.", arArabeezy: "baddi ajeeb hadiyye la-akhuy, bas mish 3aref shoo akhod.", en: "I want to buy a gift for my brother, but I don't know what to get." },
        { speaker: "Mona", ar: "شُو نَاقْصُه؟", arArabeezy: "shoo na2So?", en: "What does he need?" },
        { speaker: "Rami", ar: "بِفَكِّر قَمِيص. بَسِيط وَحِلْو.", arArabeezy: "bfakkir qameeS. baseeT w 7ilw.", en: "I'm thinking of a shirt. Simple and nice." },
        { speaker: "Mona", ar: "طَيِّب خَلِّينَا نْفُوت هُون.", arArabeezy: "Tayyib khallina nfoot hoon.", en: "Okay, let's go in here." },

        { speaker: "Seller", ar: "أَهْلًا، تْفَضَّلُوا.", arArabeezy: "ahlan, tfaDDalu.", en: "Welcome, come in." },
        { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Seller", ar: "الله يْعَافِيك. شُو بَدْكُم؟", arArabeezy: "allah y3afeek. shoo baddkom?", en: "You're welcome. What are you looking for?" },
        { speaker: "Rami", ar: "بَدِّي قَمِيص لِشَبّ عُمْرُه تَقْرِيبًا خَمْسَة وَعِشْرِين.", arArabeezy: "baddi qameeS la-shabb 3omro ta2reeban khamse w 3ishreen.", en: "I need a shirt for a guy who's about twenty-five years old." },
        { speaker: "Seller", ar: "كَاجُوَال وَلَّا رَسْمِي؟", arArabeezy: "casual wala rasmi?", en: "Casual or formal?" },
        { speaker: "Rami", ar: "كَاجُوَال.", arArabeezy: "casual.", en: "Casual." },
        { speaker: "Seller", ar: "شُو رَأْيَك بِهَاد؟", arArabeezy: "shoo ra2yak bihad?", en: "What do you think of this one?" },
        { speaker: "Rami", ar: "حِلْو... بَس عِنْدَك لَوْن تَانِي؟", arArabeezy: "7ilw... bas 3indak lawn tani?", en: "Nice... but do you have another color?" },
        { speaker: "Seller", ar: "آه، فِي كُحْلِي، وَأَسْوَد، وَرَصَاصِي.", arArabeezy: "ah, fi ko7li, w aswad, w raSaSi.", en: "Yes, there's navy, black, and gray." },
        { speaker: "Mona", ar: "أَنَا الكُحْلِي عَاجِبْنِي أَكْتَر.", arArabeezy: "ana el-ko7li 3ajebni aktar.", en: "I like the navy one more." },
        { speaker: "Rami", ar: "بَس أَخُوي بْحِبّ الأَلْوَان الهَادْيَة.", arArabeezy: "bas akhuy bi7ibb el-alwan el-hadye.", en: "But my brother likes calm colors." },
        { speaker: "Mona", ar: "الكُحْلِي هَادِي.", arArabeezy: "el-ko7li hadi.", en: "Navy is a calm color." },
        { speaker: "Rami", ar: "مَعِك حَقّ.", arArabeezy: "ma3ik 7a2.", en: "You're right." },
        { speaker: "Rami", ar: "قَدِّيش سِعْرُه؟", arArabeezy: "addeesh si3ro?", en: "How much is it?" },
        { speaker: "Seller", ar: "خَمْسَة وَسِتِّين.", arArabeezy: "khamse w sitteen.", en: "Sixty-five." },
        { speaker: "Rami", ar: "آخِر سِعْر؟", arArabeezy: "akher si3er?", en: "Final price?" },
        { speaker: "Seller", ar: "هَاي آخِرُه.", arArabeezy: "hay akhro.", en: "That's my final price." },
        { speaker: "Mona", ar: "يَا زَلَمَة... اِعْمِلْنَا سِعْر، إِحْنَا أَوَّل زَبُونَات اليَوْم. 😄", arArabeezy: "ya zalame... i3milna si3er, i7na awwal zaboonat el-yom.", en: "Come on... give us a better price, we're your first customers today." },
        { speaker: "Seller", ar: "ههههه... وَالله أَوَّل مَرَّة بِسْمَعْهَا اليَوْم.", arArabeezy: "hahaha... wallah awwal marra bisma3ha el-yom.", en: "Haha... that's the first time I've heard that today." },
        { speaker: "Rami", ar: "يَعْنِي بِزْبَط بِسِتِّين؟", arArabeezy: "ya3ni bizbaT bisitteen?", en: "So, can you make it sixty?" },
        { speaker: "Seller", ar: "خَلَص، عَشَانْكُم بِسِتِّين.", arArabeezy: "khalaS, 3ashankom bisitteen.", en: "Alright, for you, sixty." },
        { speaker: "Rami", ar: "المِقَاس هَاد وَسَط؟", arArabeezy: "el-me2as had wasaT?", en: "Is this a medium?" },
        { speaker: "Seller", ar: "لَا، هَاد كْبِير.", arArabeezy: "la, had kbeer.", en: "No, this one is large." },
        { speaker: "Rami", ar: "طَيِّب جِيبْلِي وَسَط.", arArabeezy: "Tayyib jeebli wasaT.", en: "Okay, bring me a medium." },
        { speaker: "Seller", ar: "لَحْظَة...", arArabeezy: "la7Za...", en: "One moment..." },
        { speaker: "Mona", ar: "هَيْك أَحْسَن.", arArabeezy: "hek a7san.", en: "That's better." },
        { speaker: "Rami", ar: "إِذَا مَا زَبَط، بَقْدَر أَبَدِّلُه؟", arArabeezy: "iza ma zabaT, ba2dar abaddlo?", en: "If it doesn't fit, can I exchange it?" },
        { speaker: "Seller", ar: "أَكِيد، بَس خَلِّي الوَصْل مَعَك.", arArabeezy: "akeed, bas khalli el-waSel ma3ak.", en: "Of course, just keep the receipt." },
        { speaker: "Rami", ar: "تَمَام.", arArabeezy: "tamam.", en: "Great." },
        { speaker: "Seller", ar: "كَاش وَلَّا بِطَاقَة؟", arArabeezy: "cash wala biTa2a?", en: "Cash or card?" },
        { speaker: "Rami", ar: "كَاش.", arArabeezy: "cash.", en: "Cash." },
        { speaker: "Seller", ar: "تْفَضَّل البَاقِي وَالوَصْل.", arArabeezy: "tfaDDal el-baqi w el-waSel.", en: "Here’s your change and the receipt." },
        { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Seller", ar: "الله يْعَافِيكُم.", arArabeezy: "allah y3afeekom.", en: "You're welcome." },

        { speaker: "Mona", ar: "بِمَا إِنَّا هُون، بَدِّي أَجِيب شُوَيَّة خُضْرَة.", arArabeezy: "bima inna hoon, baddi ajeeb shwayyet khoDra.", en: "Since we're here, I want to buy some vegetables." },
        { speaker: "Rami", ar: "يَلَّا.", arArabeezy: "yalla.", en: "Let's go." },

        { speaker: "Vegetable Seller", ar: "تْفَضَّلُوا يَا جَمَاعَة.", arArabeezy: "tfaDDalu ya jama3a.", en: "Welcome, everyone." },
        { speaker: "Mona", ar: "قَدِّيش البَنْدُورَة اليَوْم؟", arArabeezy: "addeesh el-bandora el-yom?", en: "How much are the tomatoes today?" },
        { speaker: "Vegetable Seller", ar: "الكِيلُو بِعَشَرَة.", arArabeezy: "el-kilo bi3ashara.", en: "Ten per kilo." },
        { speaker: "Mona", ar: "إِمْبَارِح كَانِت بِثْمَانِيَة!", arArabeezy: "embare7 kanit bithmane.", en: "Yesterday they were eight!" },
        { speaker: "Vegetable Seller", ar: "وَالله اليَوْم البِضَاعَة أَقَلّ.", arArabeezy: "wallah el-yom el-biDa3a a2all.", en: "Today there’s less produce." },
        { speaker: "Rami", ar: "وَالخِيَار؟", arArabeezy: "w el-khyar?", en: "What about cucumbers?" },
        { speaker: "Vegetable Seller", ar: "بِسَبْعَة.", arArabeezy: "bisab3a.", en: "Seven." },
        { speaker: "Mona", ar: "طَيِّب... أَعْطِينِي نُصّ كِيلُو بَنْدُورَة، وَنُصّ كِيلُو خِيَار.", arArabeezy: "Tayyib... a3Teeni noSS kilo bandora, w noSS kilo khyar.", en: "Okay... give me half a kilo of tomatoes and half a kilo of cucumbers." },
        { speaker: "Vegetable Seller", ar: "غَيْر إِشِي؟", arArabeezy: "gheir ishi?", en: "Anything else?" },
        { speaker: "Mona", ar: "قَدِّيش البُرْتُقَال؟", arArabeezy: "addeesh el-borto2al?", en: "How much are the oranges?" },
        { speaker: "Vegetable Seller", ar: "بِخَمْسَة.", arArabeezy: "bikhamse.", en: "Five." },
        { speaker: "Mona", ar: "خَلَص، كِيلُو كَمَان.", arArabeezy: "khalaS, kilo kaman.", en: "Okay, one kilo too." },
        { speaker: "Vegetable Seller", ar: "هَيْك صَار سَبْعْتَعْش شِيكِل.", arArabeezy: "hek Sar sab3ta3ash shekel.", en: "That'll be seventeen shekels." },
        { speaker: "Mona", ar: "إِذَا أَخَدْت كِيلُوَيْن بَنْدُورَة، بْتِنْزِل شُوَي؟", arArabeezy: "iza akhadt kilowain bandora, btinzil shway?", en: "If I buy two kilos of tomatoes, can you lower the price a bit?" },
        { speaker: "Vegetable Seller", ar: "ههههه... لَا وَالله، اليَوْم مَا بَقْدَر.", arArabeezy: "hahaha... la wallah, el-yom ma ba2dar.", en: "Haha... honestly, I can't today." },
        { speaker: "Rami", ar: "جَرِّبِي مَعُه شُوَي.", arArabeezy: "jarribi ma3o shway.", en: "Try bargaining a little." },
        { speaker: "Mona", ar: "طَيِّب خَلِّيهُم خَمْسْتَعْش؟", arArabeezy: "Tayyib khallihom khamsta3ash?", en: "Okay, make it fifteen?" },
        { speaker: "Vegetable Seller", ar: "وَلَا يْهِمَّك، خَمْسْتَعْش.", arArabeezy: "wala yhimmak, khamsta3ash.", en: "No problem, fifteen." },
        { speaker: "Mona", ar: "الله يْرْزُقَك.", arArabeezy: "allah yirzo2ak.", en: "May God bless your livelihood." },
        { speaker: "Vegetable Seller", ar: "وَإِيَّاكُم.", arArabeezy: "w iyyakom.", en: "You too." },
        { speaker: "Mona", ar: "تْفَضَّل، هَاي عِشْرِين.", arArabeezy: "tfaDDal, hay 3ishreen.", en: "Here, twenty." },
        { speaker: "Vegetable Seller", ar: "وَهُون خَمْس شِيكِل البَاقِي.", arArabeezy: "w hoon khams shekel el-baqi.", en: "And here are your five shekels change." },
        { speaker: "Mona", ar: "يِسْلَمُوا.", arArabeezy: "yislamu.", en: "Thank you." },

        { speaker: "Rami", ar: "خَلَّصْنَا؟", arArabeezy: "khallaSna?", en: "Are we done?" },
        { speaker: "Mona", ar: "آه، الحَمْدُ لله.", arArabeezy: "ah, el-7amdullah.", en: "Yes, thank God." },
        { speaker: "Rami", ar: "يَلَّا نِطْلَع قَبْل مَا السُّوق يْزِيد زَحْمَة.", arArabeezy: "yalla niTla3 2abl ma es-soo2 yzeed za7me.", en: "Let's leave before the market gets more crowded." },
        { speaker: "Mona", ar: "آه وَالله، وَالدُّنْيَا شُوب كَمَان.", arArabeezy: "ah wallah, w ed-dinya shoob kaman.", en: "Yes, and it's hot too." },
        { speaker: "Rami", ar: "بَعْدِين بِنْمُرّ عَالكَافِيه؟", arArabeezy: "ba3dain binmor 3al-cafe?", en: "Shall we stop by the café afterward?" },
        { speaker: "Mona", ar: "إِذَا لَحِقْنَا... أَنَا جُعْت مِن اللَّفَّة كُلْهَا. 😂", arArabeezy: "iza la7i2na... ana jo3t min el-laffe kolha.", en: "If we have time... I got hungry from all this walking." },
        { speaker: "Rami", ar: "ههههه... وَأَنَا كَمَان.", arArabeezy: "hahaha... w ana kaman.", en: "Haha... me too." }
    ],

    questions: [
        { ar: "شُو كَان بَدُّه يِشْتَرِي رَامِي؟", en: "What did Rami want to buy?" },
        { ar: "لِمِين كَانِت الهَدِيَّة؟", en: "Who was the gift for?" },
        { ar: "أَي لَوْن اخْتَارُوا بِالنِّهَايَة؟", en: "Which color did they choose in the end?" },
        { ar: "قَدِّيش كَان السِّعْر أَوَّل إِشِي؟", en: "What was the original price?" },
        { ar: "قَدِّيش دَفَع بِالنِّهَايَة؟", en: "How much did he pay in the end?" },
        { ar: "شُو سَأَل رَامِي عَن المِقَاس؟", en: "What did Rami ask about the size?" },
        { ar: "شُو لَازِم يِحْتَفِظ فِيه إِذَا بَدُّه يِبَدِّل القَمِيص؟", en: "What does he need to keep if he wants to exchange the shirt?" },
        { ar: "كِيف دَفَع رَامِي؟", en: "How did Rami pay?" },
        { ar: "شُو اشْتَرَت مُونَا مِن بَائِع الخُضَار؟", en: "What did Mona buy from the vegetable seller?" },
        { ar: "لِيش سِعْر البَنْدُورَة ارْتَفَع؟", en: "Why did the tomato price increase?" },
        { ar: "هَل قَدِرِت مُونَا تْفَاصِل؟", en: "Was Mona able to bargain?" },
        { ar: "وِين كَانُوا رَايْحِين بَعْد السُّوق؟", en: "Where were they planning to go after the market?" }
    ],
},

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "shopping_mc1",
                type: "match",
                prompt: "Match the English phrase to Arabic: How much is this?",
                options: ["قَدِّيش هَادَا؟", "كِيف الجَوّ؟", "وِين سَاكِن؟", "قَدِّيش عُمُرَك؟"],
                correct: "قَدِّيش هَادَا؟",
            },
            {
                id: "shopping_mc2",
                type: "complete",
                prompt: "Complete the Arabic for: Can you lower it a little? مُمْكِن ___ شُوَيّ؟",
                options: ["تْنَزِّل", "تْشَتِّي", "تُوصَل", "تْدْرُس"],
                correct: "تْنَزِّل",
            },
            {
                id: "shopping_mc3",
                type: "reorder",
                prompt: "Reorder: I want to buy a gift.",
                options: ["بَدِّي", "أَشْتِرِي", "هَدِيَّة"],
                correct: ["بَدِّي", "أَشْتِرِي", "هَدِيَّة"],
            },
            {
                id: "shopping_mc4",
                type: "complete",
                prompt: "Complete the Arabic for: half a kilo. ___ كِيلُو",
                options: ["نُصّ", "لَوْن", "سِعِر", "وَصْل"],
                correct: "نُصّ",
            },
            {
                id: "shopping_mc5",
                type: "match",
                prompt: "Choose the Arabic for: receipt",
                options: ["وَصْل", "خَصْم", "مَقَاس", "سُوق"],
                correct: "وَصْل",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "shopping_q1",
                questionAr: "«قَدِّيش هَادَا؟» بِنِسْتَخْدِمْهَا عَشَان:",
                optionsEn: ["ask the price", "ask someone's age", "ask about weather"],
                correctIndex: 0,
            },
            {
                id: "shopping_q2",
                questionAr: "إِذَا السِّعِر غَالِي، مُمْكِن تِقُول:",
                optionsEn: ["مُمْكِن تْنَزِّل شُوَيّ؟", "كِيف الجَوّ عِنْدَك؟", "أَنَا بَس بَتْفَرَّج."],
                correctIndex: 0,
            },
            {
                id: "shopping_q3",
                questionAr: "«بَاخُدْهَا» بِنِحْكِيهَا لِـ:",
                optionsEn: ["a feminine item", "a masculine item", "a group of people"],
                correctIndex: 0,
            },
            {
                id: "shopping_q4",
                questionAr: "إِذَا بَدَّك لون تاني، بِتِسْأَل:",
                optionsEn: ["عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟", "قَدِّيش الأُجْرَة؟", "كِيف المُوَاصَلَات؟"],
                correctIndex: 0,
            },
            {
                id: "shopping_q5",
                questionAr: "«نُصّ كِيلُو» مَعْنَاهَا:",
                optionsEn: ["half a kilo", "one kilo", "two kilos"],
                correctIndex: 0,
            },
            {
                id: "shopping_q6",
                questionAr: "«آخِر سِعِر؟» بِنِسْتَخْدِمْهَا فِي:",
                optionsEn: ["bargaining", "greeting", "family description"],
                correctIndex: 0,
            },
            {
                id: "shopping_q7",
                questionAr: "إِذَا بَدَّك تِدْفَع بِالمَصَارِي، بِتِقُول:",
                optionsEn: ["بَدِّي أَدْفَع كَاش.", "بَدِّي أَشُوف المَقَاس.", "بَدِّي أَرْجَع بَدْرِي."],
                correctIndex: 0,
            },
            {
                id: "shopping_q8",
                questionAr: "«مْنَاسِب» مُمْكِن تِحْكِيهَا عَن:",
                optionsEn: ["price, size, color, or time", "only weather", "only family"],
                correctIndex: 0,
            },
            {
                id: "shopping_q9",
                questionAr: "لِيش بِنَاخُد الوَصْل؟",
                optionsEn: ["for exchange or proof of payment", "to ask the weather", "to describe family"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "At a clothes shop: ask for a shirt, price, size, and another color. Bargain once and decide if you will buy it.",
            "At a vegetable stand: buy half a kilo of two things, ask the price, and pay.",
            "You only have 50 shekels. Tell the seller your budget and ask for something suitable.",
            "You bought the wrong size. Go back with the receipt and ask to exchange it.",
            "Mini speaking prompt: describe the last thing you bought. Say where, how much, why, and if the price was good.",
        ],
        translation: [
            { id: "shopping_t1", type: "enToAr", textEn: "Good morning, I want to buy a gift for my brother.", textAr: "صَبَاح الخِير، بَدِّي أَشْتِرِي هَدِيَّة لِأَخُوي." },
            { id: "shopping_t2", type: "arToEn", textEn: "How much is this black shirt?", textAr: "قَدِّيش هَادَا القَمِيص الأَسْوَد؟" },
            { id: "shopping_t3", type: "enToAr", textEn: "This is a little expensive. Can you lower it a little?", textAr: "هَادَا غَالِي شُوَيّ. مُمْكِن تْنَزِّل شُوَيّ؟" },
            { id: "shopping_t4", type: "arToEn", textEn: "Do you have the same size in another color?", textAr: "عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟" },
            { id: "shopping_t5", type: "enToAr", textEn: "My budget today is fifty shekels.", textAr: "مِيزَانِيَّتِي اليَوم خَمْسِين شِيكِل." },
            { id: "shopping_t6", type: "arToEn", textEn: "Make it fifty and I'll take it cash.", textAr: "خَلِّيه خَمْسِين وَبَاخُدُه كَاش." },
            { id: "shopping_t7", type: "enToAr", textEn: "Can I pay by card, or only cash?", textAr: "بِصِير أَدْفَع بِالكَارْت وَلَا بَس كَاش؟" },
            { id: "shopping_t8", type: "arToEn", textEn: "Take the receipt; you might need it later.", textAr: "خُد الوَصْل، مُمْكِن تِحْتَاجُه بَعْدِين." },
            { id: "shopping_t9", type: "enToAr", textEn: "I want half a kilo of tomatoes and half a kilo of cucumbers.", textAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة وَنُصّ كِيلُو خِيَار." },
            { id: "shopping_t10", type: "arToEn", textEn: "A kilo of tomatoes is ten shekels.", textAr: "الكِيلُو بَنْدُورَة بِعَشَرَة شَوَاكِل." },
            { id: "shopping_t11", type: "enToAr", textEn: "Yesterday the price was cheaper.", textAr: "اِمْبَارِح السِّعِر كَان أَرْخَص." },
            { id: "shopping_t12", type: "arToEn", textEn: "The price is suitable, but I want to see another one.", textAr: "السِّعِر مْنَاسِب، بَس بَدِّي أَشُوف غَيْرُه." },
            { id: "shopping_t13", type: "enToAr", textEn: "I'm just looking for now, thank you.", textAr: "أَنَا بَس بَتْفَرَّج هَلْقِيت، شُكْرًا." },
            { id: "shopping_t14", type: "arToEn", textEn: "If the size does not work, can I exchange it?", textAr: "إِذَا المَقَاس مَا زَبَط، بِقْدَر أَبَدِّلُه؟" },
            { id: "shopping_t15", type: "enToAr", textEn: "Let's go home before the crowd increases.", textAr: "يَلَّا نْرَوِّح قَبْل مَا يْزِيد الزَّحْمَة." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-90 second shopping story in Gaza Palestinian Arabic. Include: where you went, what you wanted to buy, the price, color or size, whether it was expensive or suitable, how you bargained, how you paid, and whether you took a receipt. Reuse at least 8 words from this unit and 5 old words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Good morning, I want to buy a gift for my brother.
2. How much is this black shirt?
3. This is a little expensive. Can you lower it a little?
4. Do you have the same size in another color?
5. My budget today is fifty shekels.
6. Make it fifty and I'll take it cash.
7. Can I pay by card, or only cash?
8. Take the receipt; you might need it later.
9. I want half a kilo of tomatoes and half a kilo of cucumbers.
10. A kilo of tomatoes is ten shekels.
11. Yesterday the price was cheaper.
12. The price is suitable, but I want to see another one.
13. I'm just looking for now, thank you.
14. If the size does not work, can I exchange it?
15. Let's go home before the crowd increases.`,
    },

    teacherNotes: {
        warmup: [
            "Start with a real question: شو آخر إشي اشتريته؟ قديش كان؟",
            "Recycle previous units immediately: greetings, weather, family gift, transport, and food market.",
            "This unit's hidden focus is numbers, colors, quantities, comparison, and polite bargaining.",
        ],
        vocabularySteps: [
            "Teach phrases as shopping chunks: قَدِّيش هَادَا؟ / غَالِي شُوَيّ / آخِر سِعِر؟ / بَاخُدُه.",
            "Use masculine/feminine through items: هَادَا القَمِيص / هَادِي الجَزْمَة / بَاخُدُه / بَاخُدْهَا.",
            "Keep numbers practical: 10, 12, 15, 50, 55, 60, 80, and prices by kilo.",
            "Use colors as needed in context, not as a separate color lesson.",
        ],
        dialogueSteps: [
            "Act the dialogue in two scenes: clothes shop, then vegetable stand.",
            "Ask the dialogue questions as speaking practice and require full sentence answers.",
            "Have the student replace the shirt with a real item they want to buy.",
        ],
        practiceTips: [
            "Push output: the student must ask price, bargain once, ask for size/color, and close the purchase.",
            "Use quick transformations: هَادَا غَالِي → هَادِي غَالْيَة; بَاخُدُه → بَاخُدْهَا.",
            "End with a 60-second role-play where the student buys something under a budget.",
        ],
        wrapup: [
            "Student buys one item in a role-play without reading.",
            "Student asks for another size/color.",
            "Student bargains politely and says how they will pay.",
        ],
        myNotes: "",
    },
};
