import { LESSON_ID_SHOPPING } from '../../core/constants.js';

export const lessonId = LESSON_ID_SHOPPING;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Shopping & Prices",
        lessonTitle: "Unit 8 - Shopping, Markets & Prices in Gaza Palestinian Arabic",
        contentVersion: 2026071501,
    },

    overview: {
        title: "Unit 8 - Shopping, Markets & Prices",
        description:
            "Students learn how to shop naturally in Gaza Palestinian Arabic: ask prices, compare quality, ask for size/color, bargain politely, buy by kilo or piece, and pay cash or card.",
        goals: [
            "Ask and answer about prices clearly.",
            "Use numbers, quantities, colors, size, and money in real shopping situations.",
            "Bargain politely without sounding rude.",
            "Say if something is expensive, cheap, suitable, or too much.",
            "Recycle previous units: greetings, weather, transport, food, family, work/study, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can buy something from a shop or market.",
            "The student can ask for another size/color and compare prices.",
            "The student can bargain in a simple natural way and complete payment.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "dukkan",
                ar: "دُكَّان",
                en: "corner shop / small shop",
                enArabeezy: "dukkan",
                hint: "Small neighborhood shop. Plural: دَكَاكِين.",
                exampleAr: "رُحْت عَالدُّكَّان أَشْتَرِي خُبِز وَحَلِيب.",
                exampleArabeezy: "ru7t 3ad-dukkan ashtiri khubiz w 7aleeb.",
                exampleEn: "I went to the corner shop to buy bread and milk.",
            },
            {
                id: "ma7al",
                ar: "مَحَلّ",
                en: "shop / store",
                enArabeezy: "ma7all",
                hint: "General word for any shop. Plural: مَحَلَّات.",
                exampleAr: "هَادَا المَحَلّ عِنْدُه أَوَاعِي مْنِيحَة.",
                exampleArabeezy: "hada el-ma7all 3indo awa3i mnee7a.",
                exampleEn: "This shop has good clothes.",
            },
            {
                id: "souk",
                ar: "سُوق",
                en: "market",
                enArabeezy: "souq",
                hint: "Traditional market or shopping street. In Gaza, السوق is used for clothes, vegetables, and daily needs.",
                exampleAr: "يَوم الجُمْعَة بِنِنْزَل عَالسُّوق.",
                exampleArabeezy: "yom el-jum3a bininzel 3as-souq.",
                exampleEn: "On Friday we go to the market.",
            },
            {
                id: "bashtiri",
                ar: "بَشْتِرِي",
                en: "I buy",
                enArabeezy: "bashtiri",
                hint: "From اِشْتَرَى = to buy. You can say: بَدِّي أَشْتِرِي... = I want to buy...",
                exampleAr: "بَشْتِرِي الخُضَار مِن السُّوق.",
                exampleArabeezy: "bashtiri el-khuDar min es-souq.",
                exampleEn: "I buy vegetables from the market.",
            },
            {
                id: "baddi_ashtiri",
                ar: "بَدِّي أَشْتِرِي",
                en: "I want to buy",
                enArabeezy: "baddi ashtiri",
                hint: "Best opener with a seller: بَدِّي أَشْتِرِي قَمِيص / جَزْمَة / هَدِيَّة.",
                exampleAr: "بَدِّي أَشْتِرِي هَدِيَّة لِأُخْتِي.",
                exampleArabeezy: "baddi ashtiri hadiyye la-okhti.",
                exampleEn: "I want to buy a gift for my sister.",
            },
            {
                id: "addeesh_hada",
                ar: "قَدِّيش هَادَا؟",
                en: "How much is this?",
                enArabeezy: "addeesh hada?",
                hint: "To ask price while pointing. For feminine item: قَدِّيش هَادِي؟",
                exampleAr: "لَوْ سَمَحْت، قَدِّيش هَادَا؟",
                exampleArabeezy: "law sama7t, addeesh hada?",
                exampleEn: "Please, how much is this?",
            },
            {
                id: "se3er",
                ar: "سِعِر",
                en: "price",
                enArabeezy: "se3er",
                hint: "Common chunks: السِّعِر غَالِي، السِّعِر مْنِيح، آخِر سِعِر؟",
                exampleAr: "السِّعِر مْنَاسِب، بَس بَدِّي أَشُوف غَيْرُه.",
                exampleArabeezy: "es-se3er mnasib, bas baddi ashoof gheero.",
                exampleEn: "The price is suitable, but I want to see another one.",
            },
            {
                id: "ghali",
                ar: "غَالِي / غَالْيَة",
                en: "expensive",
                enArabeezy: "ghali / ghalye",
                hint: "Male: غَالِي. Female: غَالْيَة. Plural: غَالْيِين.",
                exampleAr: "هَادَا غَالِي شُوَيّ، فِي أَرْخَص؟",
                exampleArabeezy: "hada ghali shway, fi arkhaS?",
                exampleEn: "This is a little expensive; is there a cheaper one?",
            },
            {
                id: "rkhees",
                ar: "رْخِيص / رْخِيصَة",
                en: "cheap / inexpensive",
                enArabeezy: "rkheeS / rkheeSa",
                hint: "Can be good price or low quality depending on context.",
                exampleAr: "هَادِي رْخِيصَة، بَس الجَوْدَة كِيف؟",
                exampleArabeezy: "hadi rkheeSa, bas el-jawde keef?",
                exampleEn: "This is cheap, but how is the quality?",
            },
            {
                id: "mnasib",
                ar: "مْنَاسِب / مْنَاسْبَة",
                en: "suitable / fair",
                enArabeezy: "mnasib / mnasbe",
                hint: "Useful for price, size, color, and timing.",
                exampleAr: "السِّعِر مْنَاسِب لِلْمِيزَانِيَّة.",
                exampleArabeezy: "es-se3er mnasib lil-mizaniyye.",
                exampleEn: "The price is suitable for the budget.",
            },
            {
                id: "tanzeelat",
                ar: "تَنْزِيلَات",
                en: "sales / discounts",
                enArabeezy: "tanzeelat",
                hint: "Common in shops. Also: خَصْم = discount.",
                exampleAr: "فِي تَنْزِيلَات عَالأَوَاعِي هَالأَيَّام.",
                exampleArabeezy: "fi tanzeelat 3al-awa3i hal-ayyam.",
                exampleEn: "There are sales on clothes these days.",
            },
            {
                id: "khasm",
                ar: "خَصْم",
                en: "discount",
                enArabeezy: "khasm",
                hint: "Ask politely: فِي خَصْم؟ / فِي خَصْم لِلْطُلَّاب؟",
                exampleAr: "فِي خَصْم إِذَا دَفَعْت كَاش؟",
                exampleArabeezy: "fi khasm iza dafa3t cash?",
                exampleEn: "Is there a discount if I pay cash?",
            },
            {
                id: "mumkin_tnazzel",
                ar: "مُمْكِن تْنَزِّل شُوَيّ؟",
                en: "Can you lower it a little?",
                enArabeezy: "mumkin tnazzel shway?",
                hint: "Polite bargaining phrase. To a woman seller: مُمْكِن تْنَزِّلِي شُوَيّ؟",
                exampleAr: "السِّعِر عَالِي، مُمْكِن تْنَزِّل شُوَيّ؟",
                exampleArabeezy: "es-se3er 3ali, mumkin tnazzel shway?",
                exampleEn: "The price is high; can you lower it a little?",
            },
            {
                id: "akher_se3er",
                ar: "آخِر سِعِر؟",
                en: "final price?",
                enArabeezy: "akher se3er?",
                hint: "Used after bargaining. Natural in markets, less in fixed-price stores.",
                exampleAr: "طَيِّب، آخِر سِعِر قَدِّيش؟",
                exampleArabeezy: "Tayyib, akher se3er addeesh?",
                exampleEn: "Okay, what's the final price?",
            },
            {
                id: "masari",
                ar: "مَصَارِي",
                en: "money",
                enArabeezy: "maSari",
                hint: "Very common Palestinian word. My money = مَصَارِيّي.",
                exampleAr: "مَعِي مَصَارِي شُوَيّ، بَدِّي شِي مْنَاسِب.",
                exampleArabeezy: "ma3i maSari shway, baddi shi mnasib.",
                exampleEn: "I have a little money; I want something suitable.",
            },
            {
                id: "mizaniyye",
                ar: "مِيزَانِيَّة",
                en: "budget",
                enArabeezy: "mizaniyye",
                hint: "Money you plan to spend.",
                exampleAr: "مِيزَانِيَّتِي اليَوم خَمْسِين شِيكِل.",
                exampleArabeezy: "mizaniyyti el-yom khamseen shekel.",
                exampleEn: "My budget today is fifty shekels.",
            },
            {
                id: "shekel",
                ar: "شِيكِل / شَوَاكِل",
                en: "shekel / shekels",
                enArabeezy: "shekel / shawakel",
                hint: "Common local currency. Singular: شِيكِل. Plural: شَوَاكِل.",
                exampleAr: "الكِيلُو بِعَشَرَة شَوَاكِل.",
                exampleArabeezy: "el-keelo bi-3ashara shawakel.",
                exampleEn: "The kilo is ten shekels.",
            },
            {
                id: "cash",
                ar: "كَاش",
                en: "cash",
                enArabeezy: "cash",
                hint: "Paying with physical money. Often better for small shops.",
                exampleAr: "بَدِّي أَدْفَع كَاش.",
                exampleArabeezy: "baddi adfa3 cash.",
                exampleEn: "I want to pay cash.",
            },
            {
                id: "card",
                ar: "كَارْت",
                en: "card",
                enArabeezy: "kart",
                hint: "Bank card. Ask: بِصِير أَدْفَع بِالكَارْت؟",
                exampleAr: "بِصِير أَدْفَع بِالكَارْت وَلَا بَس كَاش؟",
                exampleArabeezy: "biSeer adfa3 bil-kart wala bas cash?",
                exampleEn: "Can I pay by card, or only cash?",
            },
            {
                id: "wasl",
                ar: "وَصْل",
                en: "receipt",
                enArabeezy: "waSl",
                hint: "Useful for exchange/return. Also people may say: فَاتُورَة.",
                exampleAr: "خُد الوَصْل، مُمْكِن تِحْتَاجُه بَعْدِين.",
                exampleArabeezy: "khod el-waSl, mumkin ti7tajo ba3deen.",
                exampleEn: "Take the receipt; you might need it later.",
            },
            {
                id: "maqas",
                ar: "مَقَاس",
                en: "size",
                enArabeezy: "ma2as",
                hint: "For clothes and shoes. Big = كْبِير. Small = صْغِير.",
                exampleAr: "هَادَا المَقَاس كْبِير عَلَيّ شُوَيّ.",
                exampleArabeezy: "hada el-ma2as kbeer 3alay shway.",
                exampleEn: "This size is a little big on me.",
            },
            {
                id: "lawn",
                ar: "لَوْن / أَلْوَان",
                en: "color / colors",
                enArabeezy: "lawn / alwan",
                hint: "Use for clothes, shoes, bags, and gifts.",
                exampleAr: "عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟",
                exampleArabeezy: "3indak nafs el-ma2as bi-lawn tani?",
                exampleEn: "Do you have the same size in another color?",
            },
            {
                id: "azra2_aswad",
                ar: "أَزْرَق / أَسْوَد",
                en: "blue / black",
                enArabeezy: "azra2 / aswad",
                hint: "Color review. Feminine: زَرْقَا / سَوْدَا.",
                exampleAr: "بَدِّي الجَزْمَة السَّوْدَا، مِش الزَّرْقَا.",
                exampleArabeezy: "baddi el-jazme es-soda, mish ez-zar2a.",
                exampleEn: "I want the black shoes, not the blue ones.",
            },
            {
                id: "no3",
                ar: "نَوْع",
                en: "type / kind",
                enArabeezy: "no3",
                hint: "Use for fabric, food, coffee, clothes, and quality.",
                exampleAr: "شُو نَوْع القُمَاش هَادَا؟",
                exampleArabeezy: "sho no3 el-2umash hada?",
                exampleEn: "What type of fabric is this?",
            },
            {
                id: "jawde",
                ar: "جَوْدَة",
                en: "quality",
                enArabeezy: "jawde",
                hint: "High quality = جَوْدَة عَالْيَة. Low quality = جَوْدَة عَادِيَّة.",
                exampleAr: "السِّعِر رْخِيص، بَس الجَوْدَة عَادِيَّة.",
                exampleArabeezy: "es-se3er rkheeS, bas el-jawde 3adiyye.",
                exampleEn: "The price is cheap, but the quality is average.",
            },
            {
                id: "kilo",
                ar: "كِيلُو",
                en: "kilo",
                enArabeezy: "keelo",
                hint: "Used in food markets: fruits, vegetables, meat, cheese.",
                exampleAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة.",
                exampleArabeezy: "baddi noSS keelo bandora.",
                exampleEn: "I want half a kilo of tomatoes.",
            },
            {
                id: "noSS",
                ar: "نُصّ",
                en: "half",
                enArabeezy: "noSS",
                hint: "Very useful with kilos and prices: نُصّ كِيلُو، نُصّ السِّعِر.",
                exampleAr: "خَلِّيه نُصّ كِيلُو بَس.",
                exampleArabeezy: "khallih noSS keelo bas.",
                exampleEn: "Make it only half a kilo.",
            },
            {
                id: "qiT3a",
                ar: "قِطْعَة",
                en: "piece / item",
                enArabeezy: "2iT3a",
                hint: "Plural: قِطَع. Used for clothes, sweets, cheese, and items.",
                exampleAr: "بَدِّي قِطْعَة تَانْيَة مِن هَادَا النَّوْع.",
                exampleArabeezy: "baddi 2iT3a tanye min hada en-no3.",
                exampleEn: "I want another piece of this kind.",
            },
            {
                id: "kamm",
                ar: "كَمّ؟",
                en: "how many?",
                enArabeezy: "kam?",
                hint: "Use for quantity. Price question uses قَدِّيش؟",
                exampleAr: "كَمّ قِطْعَة بَدَّك؟",
                exampleArabeezy: "kam 2iT3a baddak?",
                exampleEn: "How many pieces do you want?",
            },
            {
                id: "3indak_tani",
                ar: "عِنْدَك إِشِي تَانِي؟",
                en: "Do you have something else?",
                enArabeezy: "3indak ishi tani?",
                hint: "Use for another model, size, color, or option.",
                exampleAr: "عِنْدَك إِشِي تَانِي نَفْس المَقَاس؟",
                exampleArabeezy: "3indak ishi tani nafs el-ma2as?",
                exampleEn: "Do you have something else in the same size?",
            },
            {
                id: "bas_batfarraj",
                ar: "أَنَا بَس بَتْفَرَّج",
                en: "I'm just looking",
                enArabeezy: "ana bas batfarraj",
                hint: "Polite phrase when seller approaches and you are not ready to buy.",
                exampleAr: "شُكْرًا، أَنَا بَس بَتْفَرَّج هَلْقِيت.",
                exampleArabeezy: "shukran, ana bas batfarraj halla2et.",
                exampleEn: "Thanks, I'm just looking for now.",
            },
            {
                id: "khallih",
                ar: "خَلِّيه",
                en: "make it / let it be",
                enArabeezy: "khallih",
                hint: "Useful in bargaining: خَلِّيه بِخَمْسِين = make it fifty.",
                exampleAr: "خَلِّيه بِخَمْسِين وَبَاخُدُه هَلْقِيت.",
                exampleArabeezy: "khallih bi-khamseen w bakhdo halla2et.",
                exampleEn: "Make it fifty and I'll take it now.",
            },
            {
                id: "bakhdo",
                ar: "بَاخُدُه / بَاخُدْهَا",
                en: "I'll take it",
                enArabeezy: "bakhdo / bakhodha",
                hint: "Male item: بَاخُدُه. Female item: بَاخُدْهَا. Plural: بَاخُدْهُم.",
                exampleAr: "تَمَام، بَاخُدْهَا.",
                exampleArabeezy: "tamam, bakhodha.",
                exampleEn: "Okay, I'll take it.",
            },
        ],
    },

    dialogue: {
    title: "Shopping, Markets & Prices - At the Market",
    setting: "Rami and Mona go shopping to buy a gift and then buy vegetables at the local market.",
    lines: [
        { speaker: "Rami", ar: "مُونَا، تَعَالِي هُون شُوَي.", arArabeezy: "mona, ta3ali hoon shway.", en: "Mona, come here for a second." },
        { speaker: "Mona", ar: "شُو لْقِيت؟", arArabeezy: "shoo l2eet?", en: "What did you find?" },
        { speaker: "Rami", ar: "بَدِّي أَجِيب هَدِيَّة لِأَخُوي، بَس مِش عَارِف شُو آخُد.", arArabeezy: "baddi ajeeb hadiyye la-akhuy, bas mish 3aref shoo akhod.", en: "I want to buy a gift for my brother, but I don't know what to get." },
        { speaker: "Mona", ar: "شُو نَاقْصُه؟", arArabeezy: "shoo na2So?", en: "What does he need?" },
        { speaker: "Rami", ar: "بِفَكِّر قَمِيص. بَسِيط وَحِلْو.", arArabeezy: "bfakkir qameeS. baseeT w 7ilw.", en: "I'm thinking of a shirt. Simple and nice." },
        { speaker: "Mona", ar: "طَيِّب خَلِّينَا نْفُوت هُون.", arArabeezy: "Tayyib khallina nfoot hoon.", en: "Okay, let's go in here." },

        { speaker: "Seller", ar: "أَهْلًا، تْفَضَّلُوا.", arArabeezy: "ahlan, tfaDDalu.", en: "Welcome, come in." },
        { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Seller", ar: "الله يْعَافِيك. شُو بَدْكُم؟", arArabeezy: "allah y3afeek. shoo baddkom?", en: "You're welcome. What are you looking for?" },
        { speaker: "Rami", ar: "بَدِّي قَمِيص لِشَبّ عُمْرُه تَقْرِيبًا خَمْسَة وَعِشْرِين.", arArabeezy: "baddi qameeS la-shabb 3omro ta2reeban khamse w 3ishreen.", en: "I need a shirt for a guy who's about twenty-five years old." },
        { speaker: "Seller", ar: "كَاجُوَال وَلَّا رَسْمِي؟", arArabeezy: "casual wala rasmi?", en: "Casual or formal?" },
        { speaker: "Rami", ar: "كَاجُوَال.", arArabeezy: "casual.", en: "Casual." },
        { speaker: "Seller", ar: "شُو رَأْيَك بِهَاد؟", arArabeezy: "shoo ra2yak bihad?", en: "What do you think of this one?" },
        { speaker: "Rami", ar: "حِلْو... بَس عِنْدَك لَوْن تَانِي؟", arArabeezy: "7ilw... bas 3indak lawn tani?", en: "Nice... but do you have another color?" },
        { speaker: "Seller", ar: "آه، فِي كُحْلِي، وَأَسْوَد، وَرَصَاصِي.", arArabeezy: "ah, fi ko7li, w aswad, w raSaSi.", en: "Yes, there's navy, black, and gray." },
        { speaker: "Mona", ar: "أَنَا الكُحْلِي عَاجِبْنِي أَكْتَر.", arArabeezy: "ana el-ko7li 3ajebni aktar.", en: "I like the navy one more." },
        { speaker: "Rami", ar: "بَس أَخُوي بْحِبّ الأَلْوَان الهَادْيَة.", arArabeezy: "bas akhuy bi7ibb el-alwan el-hadye.", en: "But my brother likes calm colors." },
        { speaker: "Mona", ar: "الكُحْلِي هَادِي.", arArabeezy: "el-ko7li hadi.", en: "Navy is a calm color." },
        { speaker: "Rami", ar: "مَعِك حَقّ.", arArabeezy: "ma3ik 7a2.", en: "You're right." },
        { speaker: "Rami", ar: "قَدِّيش سِعْرُه؟", arArabeezy: "addeesh si3ro?", en: "How much is it?" },
        { speaker: "Seller", ar: "خَمْسَة وَسِتِّين.", arArabeezy: "khamse w sitteen.", en: "Sixty-five." },
        { speaker: "Rami", ar: "آخِر سِعْر؟", arArabeezy: "akher si3er?", en: "Final price?" },
        { speaker: "Seller", ar: "هَاي آخِرُه.", arArabeezy: "hay akhro.", en: "That's my final price." },
        { speaker: "Mona", ar: "يَا زَلَمَة... اِعْمِلْنَا سِعْر، إِحْنَا أَوَّل زَبُونَات اليَوْم. 😄", arArabeezy: "ya zalame... i3milna si3er, i7na awwal zaboonat el-yom.", en: "Come on... give us a better price, we're your first customers today." },
        { speaker: "Seller", ar: "ههههه... وَالله أَوَّل مَرَّة بِسْمَعْهَا اليَوْم.", arArabeezy: "hahaha... wallah awwal marra bisma3ha el-yom.", en: "Haha... that's the first time I've heard that today." },
        { speaker: "Rami", ar: "يَعْنِي بِزْبَط بِسِتِّين؟", arArabeezy: "ya3ni bizbaT bisitteen?", en: "So, can you make it sixty?" },
        { speaker: "Seller", ar: "خَلَص، عَشَانْكُم بِسِتِّين.", arArabeezy: "khalaS, 3ashankom bisitteen.", en: "Alright, for you, sixty." },
        { speaker: "Rami", ar: "المِقَاس هَاد وَسَط؟", arArabeezy: "el-me2as had wasaT?", en: "Is this a medium?" },
        { speaker: "Seller", ar: "لَا، هَاد كْبِير.", arArabeezy: "la, had kbeer.", en: "No, this one is large." },
        { speaker: "Rami", ar: "طَيِّب جِيبْلِي وَسَط.", arArabeezy: "Tayyib jeebli wasaT.", en: "Okay, bring me a medium." },
        { speaker: "Seller", ar: "لَحْظَة...", arArabeezy: "la7Za...", en: "One moment..." },
        { speaker: "Mona", ar: "هَيْك أَحْسَن.", arArabeezy: "hek a7san.", en: "That's better." },
        { speaker: "Rami", ar: "إِذَا مَا زَبَط، بَقْدَر أَبَدِّلُه؟", arArabeezy: "iza ma zabaT, ba2dar abaddlo?", en: "If it doesn't fit, can I exchange it?" },
        { speaker: "Seller", ar: "أَكِيد، بَس خَلِّي الوَصْل مَعَك.", arArabeezy: "akeed, bas khalli el-waSel ma3ak.", en: "Of course, just keep the receipt." },
        { speaker: "Rami", ar: "تَمَام.", arArabeezy: "tamam.", en: "Great." },
        { speaker: "Seller", ar: "كَاش وَلَّا بِطَاقَة؟", arArabeezy: "cash wala biTa2a?", en: "Cash or card?" },
        { speaker: "Rami", ar: "كَاش.", arArabeezy: "cash.", en: "Cash." },
        { speaker: "Seller", ar: "تْفَضَّل البَاقِي وَالوَصْل.", arArabeezy: "tfaDDal el-baqi w el-waSel.", en: "Here’s your change and the receipt." },
        { speaker: "Rami", ar: "يِعْطِيك العَافْيَة.", arArabeezy: "ya3teek el-3afyeh.", en: "Thank you." },
        { speaker: "Seller", ar: "الله يْعَافِيكُم.", arArabeezy: "allah y3afeekom.", en: "You're welcome." },

        { speaker: "Mona", ar: "بِمَا إِنَّا هُون، بَدِّي أَجِيب شُوَيَّة خُضْرَة.", arArabeezy: "bima inna hoon, baddi ajeeb shwayyet khoDra.", en: "Since we're here, I want to buy some vegetables." },
        { speaker: "Rami", ar: "يَلَّا.", arArabeezy: "yalla.", en: "Let's go." },

        { speaker: "Vegetable Seller", ar: "تْفَضَّلُوا يَا جَمَاعَة.", arArabeezy: "tfaDDalu ya jama3a.", en: "Welcome, everyone." },
        { speaker: "Mona", ar: "قَدِّيش البَنْدُورَة اليَوْم؟", arArabeezy: "addeesh el-bandora el-yom?", en: "How much are the tomatoes today?" },
        { speaker: "Vegetable Seller", ar: "الكِيلُو بِعَشَرَة.", arArabeezy: "el-kilo bi3ashara.", en: "Ten per kilo." },
        { speaker: "Mona", ar: "إِمْبَارِح كَانِت بِثْمَانِيَة!", arArabeezy: "embare7 kanit bithmane.", en: "Yesterday they were eight!" },
        { speaker: "Vegetable Seller", ar: "وَالله اليَوْم البِضَاعَة أَقَلّ.", arArabeezy: "wallah el-yom el-biDa3a a2all.", en: "Today there’s less produce." },
        { speaker: "Rami", ar: "وَالخِيَار؟", arArabeezy: "w el-khyar?", en: "What about cucumbers?" },
        { speaker: "Vegetable Seller", ar: "بِسَبْعَة.", arArabeezy: "bisab3a.", en: "Seven." },
        { speaker: "Mona", ar: "طَيِّب... أَعْطِينِي نُصّ كِيلُو بَنْدُورَة، وَنُصّ كِيلُو خِيَار.", arArabeezy: "Tayyib... a3Teeni noSS kilo bandora, w noSS kilo khyar.", en: "Okay... give me half a kilo of tomatoes and half a kilo of cucumbers." },
        { speaker: "Vegetable Seller", ar: "غَيْر إِشِي؟", arArabeezy: "gheir ishi?", en: "Anything else?" },
        { speaker: "Mona", ar: "قَدِّيش البُرْتُقَال؟", arArabeezy: "addeesh el-borto2al?", en: "How much are the oranges?" },
        { speaker: "Vegetable Seller", ar: "بِخَمْسَة.", arArabeezy: "bikhamse.", en: "Five." },
        { speaker: "Mona", ar: "خَلَص، كِيلُو كَمَان.", arArabeezy: "khalaS, kilo kaman.", en: "Okay, one kilo too." },
        { speaker: "Vegetable Seller", ar: "هَيْك صَار سَبْعْتَعْش شِيكِل.", arArabeezy: "hek Sar sab3ta3ash shekel.", en: "That'll be seventeen shekels." },
        { speaker: "Mona", ar: "إِذَا أَخَدْت كِيلُوَيْن بَنْدُورَة، بْتِنْزِل شُوَي؟", arArabeezy: "iza akhadt kilowain bandora, btinzil shway?", en: "If I buy two kilos of tomatoes, can you lower the price a bit?" },
        { speaker: "Vegetable Seller", ar: "ههههه... لَا وَالله، اليَوْم مَا بَقْدَر.", arArabeezy: "hahaha... la wallah, el-yom ma ba2dar.", en: "Haha... honestly, I can't today." },
        { speaker: "Rami", ar: "جَرِّبِي مَعُه شُوَي.", arArabeezy: "jarribi ma3o shway.", en: "Try bargaining a little." },
        { speaker: "Mona", ar: "طَيِّب خَلِّيهُم خَمْسْتَعْش؟", arArabeezy: "Tayyib khallihom khamsta3ash?", en: "Okay, make it fifteen?" },
        { speaker: "Vegetable Seller", ar: "وَلَا يْهِمَّك، خَمْسْتَعْش.", arArabeezy: "wala yhimmak, khamsta3ash.", en: "No problem, fifteen." },
        { speaker: "Mona", ar: "الله يْرْزُقَك.", arArabeezy: "allah yirzo2ak.", en: "May God bless your livelihood." },
        { speaker: "Vegetable Seller", ar: "وَإِيَّاكُم.", arArabeezy: "w iyyakom.", en: "You too." },
        { speaker: "Mona", ar: "تْفَضَّل، هَاي عِشْرِين.", arArabeezy: "tfaDDal, hay 3ishreen.", en: "Here, twenty." },
        { speaker: "Vegetable Seller", ar: "وَهُون خَمْس شِيكِل البَاقِي.", arArabeezy: "w hoon khams shekel el-baqi.", en: "And here are your five shekels change." },
        { speaker: "Mona", ar: "يِسْلَمُوا.", arArabeezy: "yislamu.", en: "Thank you." },

        { speaker: "Rami", ar: "خَلَّصْنَا؟", arArabeezy: "khallaSna?", en: "Are we done?" },
        { speaker: "Mona", ar: "آه، الحَمْدُ لله.", arArabeezy: "ah, el-7amdullah.", en: "Yes, thank God." },
        { speaker: "Rami", ar: "يَلَّا نِطْلَع قَبْل مَا السُّوق يْزِيد زَحْمَة.", arArabeezy: "yalla niTla3 2abl ma es-soo2 yzeed za7me.", en: "Let's leave before the market gets more crowded." },
        { speaker: "Mona", ar: "آه وَالله، وَالدُّنْيَا شُوب كَمَان.", arArabeezy: "ah wallah, w ed-dinya shoob kaman.", en: "Yes, and it's hot too." },
        { speaker: "Rami", ar: "بَعْدِين بِنْمُرّ عَالكَافِيه؟", arArabeezy: "ba3dain binmor 3al-cafe?", en: "Shall we stop by the café afterward?" },
        { speaker: "Mona", ar: "إِذَا لَحِقْنَا... أَنَا جُعْت مِن اللَّفَّة كُلْهَا. 😂", arArabeezy: "iza la7i2na... ana jo3t min el-laffe kolha.", en: "If we have time... I got hungry from all this walking." },
        { speaker: "Rami", ar: "ههههه... وَأَنَا كَمَان.", arArabeezy: "hahaha... w ana kaman.", en: "Haha... me too." }
    ],

    questions: [
        { ar: "شُو كَان بَدُّه يِشْتَرِي رَامِي؟", en: "What did Rami want to buy?" },
        { ar: "لِمِين كَانِت الهَدِيَّة؟", en: "Who was the gift for?" },
        { ar: "أَي لَوْن اخْتَارُوا بِالنِّهَايَة؟", en: "Which color did they choose in the end?" },
        { ar: "قَدِّيش كَان السِّعْر أَوَّل إِشِي؟", en: "What was the original price?" },
        { ar: "قَدِّيش دَفَع بِالنِّهَايَة؟", en: "How much did he pay in the end?" },
        { ar: "شُو سَأَل رَامِي عَن المِقَاس؟", en: "What did Rami ask about the size?" },
        { ar: "شُو لَازِم يِحْتَفِظ فِيه إِذَا بَدُّه يِبَدِّل القَمِيص؟", en: "What does he need to keep if he wants to exchange the shirt?" },
        { ar: "كِيف دَفَع رَامِي؟", en: "How did Rami pay?" },
        { ar: "شُو اشْتَرَت مُونَا مِن بَائِع الخُضَار؟", en: "What did Mona buy from the vegetable seller?" },
        { ar: "لِيش سِعْر البَنْدُورَة ارْتَفَع؟", en: "Why did the tomato price increase?" },
        { ar: "هَل قَدِرِت مُونَا تْفَاصِل؟", en: "Was Mona able to bargain?" },
        { ar: "وِين كَانُوا رَايْحِين بَعْد السُّوق؟", en: "Where were they planning to go after the market?" }
    ],
},

    grammar: [
        {
            title: "1. Prices: numbers with شِيكِل",
            short: "شِيكِل، شِيكِلَيْن، تَلَات شَوَاكِل، عِشْرِين شِيكِل",
            description: "Palestinian prices are learned most effectively as complete money chunks. One and two have special forms; three to ten commonly use the plural شَوَاكِل; from eleven upward, everyday speech normally returns to singular شِيكِل after the number. Prices are said without formal case endings.",
            table: {
                title: "A practical price ladder",
                headers: ["Number", "Price chunk", "Arabizi", "Pattern"],
                rows: [
                    ["1", "شِيكِل وَاحَد", "shekel wa7ad", "singular + one"],
                    ["2", "شِيكِلَيْن", "shekelein", "dual form"],
                    ["3", "تَلَات شَوَاكِل", "talat shawakel", "3–10 + plural"],
                    ["7", "سَبَع شَوَاكِل", "saba3 shawakel", "3–10 + plural"],
                    ["10", "عَشَرَة شَوَاكِل", "3ashra shawakel", "3–10 + plural"],
                    ["11", "حْدَاعَشَر شِيكِل", "7da3ashar shekel", "11+ + singular unit"],
                    ["20", "عِشْرِين شِيكِل", "3ishreen shekel", "tens + singular unit"],
                    ["35", "خَمْسَة وَتَلَاتِين شِيكِل", "khamseh w talateen shekel", "ones + و + tens"],
                    ["100", "مِيَّة شِيكِل", "miyyeh shekel", "hundred + singular unit"],
                ],
            },
            examples: [
                { ar: "هَادَا بِسَبَع شَوَاكِل، وَهَادَاك بِحْدَاعَشَر شِيكِل.", arabeezy: "hada b-saba3 shawakel, w hadak b-7da3ashar shekel.", en: "This one is seven shekels, and that one is eleven shekels." },
                { ar: "الحِسَاب خَمْسَة وَتَلَاتِين شِيكِل.", arabeezy: "el-7sab khamseh w talateen shekel.", en: "The total is thirty-five shekels." },
                { ar: "مَعِي خَمْسِين، مَعَك فَكَّة؟", arabeezy: "ma3i khamseen, ma3ak fakkeh?", en: "I have a fifty; do you have change?" },
            ],
            commonMistakes: [
                "Do not keep شَوَاكِل after every large number. Everyday speech normally says عِشْرِين شِيكِل, not عِشْرِين شَوَاكِل.",
                "The dual شِيكِلَيْن already means two shekels; do not normally add اتْنِين after it.",
                "Compound numbers are spoken ones first, then tens: خَمْسَة وَتَلَاتِين (five and thirty).",
            ],
            exercises: [
                { prompt: "Choose the natural price for 7 NIS.", options: ["سَبَع شَوَاكِل", "سَبَعَة شِيكِل وَاحَد", "سَبَع شِيكِلَيْن"], correct: "سَبَع شَوَاكِل", explanation: "Numbers three to ten commonly take the plural شَوَاكِل." },
                { prompt: "Choose the natural price for 20 NIS.", options: ["عِشْرِين شِيكِل", "عِشْرِين شَوَاكِل", "شِيكِلَيْن عَشَرَة"], correct: "عِشْرِين شِيكِل", explanation: "After the tens, the money unit normally returns to singular in everyday speech." },
                { prompt: "What number is خَمْسَة وَتَلَاتِين?", options: ["35", "53", "25"], correct: "35", explanation: "Palestinian Arabic says the ones first: five and thirty." },
            ],
        },
        {
            title: "2. Counting items: one, two, and small quantities",
            short: "بْلُوزَة وَحْدَة، بْلُوزْتَيْن، تَلَات بْلُوزَات",
            description: "When counting objects, ‘one’ normally follows the noun and agrees with it. Two is commonly built into a dual noun. From three upward, speakers use the number before a plural counted form. Exact number shapes vary by noun gender and local speech, so this unit teaches stable shopping chunks rather than an abstract classical rule alone.",
            table: {
                title: "Counting common shopping items",
                headers: ["Quantity", "Feminine item بْلُوزَة", "Masculine item قَمِيص", "Meaning"],
                rows: [
                    ["one", "بْلُوزَة وَحْدَة", "قَمِيص وَاحَد", "one blouse / shirt"],
                    ["two", "بْلُوزْتَيْن", "قَمِيصَيْن", "two blouses / shirts"],
                    ["three", "تَلَات بْلُوزَات", "تَلَات قُمْصَان", "three blouses / shirts"],
                    ["four", "أَرْبَع بْلُوزَات", "أَرْبَع قُمْصَان", "four blouses / shirts"],
                    ["many", "بْلُوزَات كْتِير", "قُمْصَان كْتِير", "many blouses / shirts"],
                ],
            },
            examples: [
                { ar: "بَدِّي بْلُوزَة وَحْدَة سَوْدَا.", arabeezy: "baddi bloozeh wa7deh soda.", en: "I want one black blouse." },
                { ar: "عِنْدَك قَمِيصَيْن مِن نَفْس المَقَاس؟", arabeezy: "3indak qameeSein min nafs el-maqas?", en: "Do you have two shirts in the same size?" },
                { ar: "أَخَدْت تَلَات بْلُوزَات وَأَرْبَع قُمْصَان.", arabeezy: "akhadt talat bloozat w arba3 qumSan.", en: "I took three blouses and four shirts." },
            ],
            commonMistakes: [
                "One follows the item in these chunks: قَمِيص وَاحَد, not وَاحَد قَمِيص in a neutral count.",
                "The dual noun already contains ‘two’: بْلُوزْتَيْن. Adding تِنْتَيْن is possible for emphasis or clarification, but not required.",
                "Do not expect the singular noun after three: say تَلَات قُمْصَان, not تَلَات قَمِيص.",
            ],
            exercises: [
                { prompt: "Choose: ‘one red blouse’.", options: ["بْلُوزَة وَحْدَة حَمْرَا", "وَاحَد بْلُوزَة أَحْمَر", "بْلُوزْتَيْن حَمْرَا"], correct: "بْلُوزَة وَحْدَة حَمْرَا", explanation: "The noun, number one, and colour all agree as feminine singular." },
                { prompt: "Which form already means ‘two shirts’?", options: ["قَمِيصَيْن", "تَلَات قُمْصَان", "قَمِيص وَاحَد"], correct: "قَمِيصَيْن", explanation: "The dual ending ـين carries the meaning two." },
                { prompt: "Complete: ___ قُمْصَان. (three shirts)", options: ["تَلَات", "وَاحَد", "قَمِيصَيْن"], correct: "تَلَات", explanation: "Three precedes the plural counted noun قُمْصَان." },
            ],
        },
        {
            title: "3. Broken plurals you need in the market",
            short: "سِعِر ← أَسْعَار — لَوْن ← أَلْوَان — قَمِيص ← قُمْصَان",
            description: "A broken plural changes the inside of the noun instead of relying only on a final ending. Shopping language contains many high-frequency broken plurals. They cannot be generated safely from one rule, so store each singular and plural as a pair and revisit them across prices, colours, sizes, and products.",
            table: {
                title: "Shopping singular–plural pairs",
                headers: ["Singular", "Plural", "Arabizi", "Meaning"],
                rows: [
                    ["سِعِر", "أَسْعَار", "as3ar", "price → prices"],
                    ["لَوْن", "أَلْوَان", "alwan", "colour → colours"],
                    ["قَمِيص", "قُمْصَان", "qumSan", "shirt → shirts"],
                    ["فُسْتَان", "فَسَاتِين", "fasateen", "dress → dresses"],
                    ["شِيكِل", "شَوَاكِل", "shawakel", "shekel → shekels"],
                    ["مَحَلّ", "مَحَلَّات", "ma7allat", "shop → shops (sound plural)"],
                    ["مَقَاس", "مَقَاسَات", "maqasat", "size → sizes (sound plural)"],
                ],
            },
            examples: [
                { ar: "الأَسْعَار فِي هَاد المَحَلّ أَرْخَص.", arabeezy: "el-as3ar fi had el-ma7all arkhaS.", en: "The prices in this shop are cheaper." },
                { ar: "عِنْدْكُم أَلْوَان تَانْيَة مِن هَاد القَمِيص؟", arabeezy: "3indkum alwan tanyeh min had el-qameeS?", en: "Do you have other colours of this shirt?" },
                { ar: "الفَسَاتِين الجْدِيدَة وَاصْلَة اليَوم.", arabeezy: "el-fasateen el-jdeedeh waSleh el-yom.", en: "The new dresses arrived today." },
            ],
            commonMistakes: [
                "Do not invent *سِعِرَات for أَسْعَار or *لَوْنَات for أَلْوَان as your default. Learn the established plural.",
                "Not every plural is broken. مَقَاسَات and مَحَلَّات use ـات, so classify by the real word rather than by meaning.",
                "A non-human broken plural often takes feminine-singular agreement: الأَسْعَار غَالْيَة, الأَلْوَان حِلْوَة.",
            ],
            exercises: [
                { prompt: "Choose the plural of سِعِر.", options: ["أَسْعَار", "سِعِرَات", "سُعُورِين"], correct: "أَسْعَار", explanation: "سِعِر → أَسْعَار is a high-frequency broken plural." },
                { prompt: "Which pair uses a sound ـات plural?", options: ["مَقَاس ← مَقَاسَات", "لَوْن ← أَلْوَان", "قَمِيص ← قُمْصَان"], correct: "مَقَاس ← مَقَاسَات", explanation: "مَقَاسَات adds the plural ending without an internal broken-plural pattern." },
                { prompt: "Complete: عِنْدْكُم ___ تَانْيَة؟ (other colours)", options: ["أَلْوَان", "لَوْن", "لَوْنَيْن فقط"], correct: "أَلْوَان", explanation: "أَلْوَان is the plural needed for multiple colours." },
            ],
        },
        {
            title: "4. Demonstratives, colours, and adjective agreement",
            short: "هَادَا القَمِيص الأَزْرَق — هَاي البْلُوزَة الزَّرْقَا — هَدُول القُمْصَان",
            description: "A shopping description must keep track of the item’s gender and number. Use هَادَا with a masculine singular item, هَاي with a feminine singular item, and هَدُول with plural items. Colours and ordinary adjectives normally follow the noun and agree with it. With non-human plurals, feminine-singular description is very common.",
            table: {
                title: "Pointing to and describing items",
                headers: ["Item", "Demonstrative phrase", "Colour phrase", "Meaning"],
                rows: [
                    ["قَمِيص (m.)", "هَادَا القَمِيص", "القَمِيص الأَزْرَق", "this blue shirt"],
                    ["بْلُوزَة (f.)", "هَاي البْلُوزَة", "البْلُوزَة الزَّرْقَا", "this blue blouse"],
                    ["قُمْصَان (pl.)", "هَدُول القُمْصَان", "القُمْصَان الجْدِيدَة", "these new shirts"],
                    ["فَسَاتِين (pl.)", "هَدُول الفَسَاتِين", "الفَسَاتِين غَالْيَة", "these dresses are expensive"],
                ],
            },
            examples: [
                { ar: "هَادَا القَمِيص الأَسْوَد مَقَاسُه أَكْبَر.", arabeezy: "hada el-qameeS el-aswad maqaso akbar.", en: "This black shirt is a larger size." },
                { ar: "هَاي البْلُوزَة الحَمْرَا حِلْوَة، بَس غَالْيَة.", arabeezy: "hay el-bloozeh el-7amra 7ilweh, bas ghalyeh.", en: "This red blouse is nice, but expensive." },
                { ar: "هَدُول الفَسَاتِين الجْدِيدَة عِنْدْكُم خَصْم عَلَيْهَا؟", arabeezy: "hadol el-fasateen el-jdeedeh 3indkum khaSm 3aleiha?", en: "Do you have a discount on these new dresses?" },
            ],
            commonMistakes: [
                "Do not use هَادَا with every item. A feminine singular item such as بْلُوزَة takes هَاي.",
                "The colour follows the noun: بْلُوزَة حَمْرَا, not حَمْرَا بْلُوزَة in a neutral description.",
                "Plural objects often take feminine-singular adjective/pronoun reference: الفَسَاتِين غَالْيَة; خَصْم عَلَيْهَا.",
            ],
            exercises: [
                { prompt: "Point to one feminine item: ‘this blouse’.", options: ["هَاي البْلُوزَة", "هَادَا البْلُوزَة", "هَدُول البْلُوزَة"], correct: "هَاي البْلُوزَة", explanation: "هَاي points to a feminine singular noun." },
                { prompt: "Choose the agreeing phrase: ‘the red shirt’.", options: ["القَمِيص الأَحْمَر", "القَمِيص الحَمْرَا", "البْلُوزَة الأَحْمَر"], correct: "القَمِيص الأَحْمَر", explanation: "قَمِيص is masculine singular, so the colour is أَحْمَر." },
                { prompt: "Complete: الفَسَاتِين ___. (expensive)", options: ["غَالْيَة", "غَالِي", "غَالْيِين للأشخاص"], correct: "غَالْيَة", explanation: "The non-human plural commonly takes feminine-singular agreement." },
            ],
        },
        {
            title: "5. Comparing and bargaining with a condition",
            short: "أَغْلَى مِن، أَرْخَص مِن، آخِر سِعِر؟ إِذَا... بَاخُدْهَا",
            description: "Natural bargaining combines evaluation, comparison, a polite request, and sometimes a condition. The shopper can say an item is expensive for them, ask whether the seller can lower it, and make a clear offer with إِذَا (‘if’). Object endings keep track of the item: بَاخُدُه for a masculine item, بَاخُدْهَا for a feminine item, and بَاخُدْهُم for plural items.",
            table: {
                title: "A respectful bargaining sequence",
                headers: ["Job", "Palestinian phrase", "Natural English"],
                rows: [
                    ["evaluate", "هَاد غَالِي عَلَيّ", "this is expensive for me"],
                    ["compare", "هَادَاك أَرْخَص مِن هَادَا", "that one is cheaper than this"],
                    ["request", "مُمْكِن تْنَزِّل شُوَيّ؟", "can you lower it a little?"],
                    ["ask final price", "آخِر سِعِر؟", "final price?"],
                    ["conditional offer", "إِذَا بِعَشَرِين بَاخُدْهَا", "if it is twenty, I’ll take it"],
                    ["accept", "مَاشِي، بَاخُدْهَا", "okay, I’ll take it (f.)"],
                ],
            },
            examples: [
                { ar: "هَادَا أَغْلَى مِن هَادَاك، بَس جَوْدِتُه أَحْسَن.", arabeezy: "hada aghla min hadak, bas jawdeto a7san.", en: "This one is more expensive than that one, but its quality is better." },
                { ar: "مَعَلِّش، السِّعِر غَالِي عَلَيّ. مُمْكِن تْنَزِّل شُوَيّ؟", arabeezy: "ma3allish, es-si3er ghali 3alay. mumkin tnazzel shway?", en: "Excuse me, the price is high for me. Could you lower it a little?" },
                { ar: "إِذَا بِخَمْسَة وَعِشْرِين بَاخُدْهَا هَلْقِيت.", arabeezy: "iza b-khamseh w 3ishreen bakhodha hal2eet.", en: "If it is twenty-five, I’ll take it now." },
            ],
            commonMistakes: [
                "Bargaining is not appropriate in every shop. It is natural in many markets and flexible-price settings, but not at a fixed supermarket checkout.",
                "Keep the item ending consistent: قَمِيص → بَاخُدُه; بْلُوزَة → بَاخُدْهَا; قُمْصَان → بَاخُدْهُم.",
                "A polite opening and calm tone matter. هَاد غَالِي عَلَيّ comments on your budget more softly than accusing the seller of cheating.",
            ],
            exercises: [
                { prompt: "You are buying a feminine item (بْلُوزَة). Choose: ‘I’ll take it.’", options: ["بَاخُدْهَا.", "بَاخُدُه.", "بَاخُدْهُم."], correct: "بَاخُدْهَا.", explanation: "The object ending ـهَا refers to a feminine singular item." },
                { prompt: "Choose the respectful request for a lower price.", options: ["مُمْكِن تْنَزِّل شُوَيّ؟", "نَزِّل السِّعِر هَلْقِيت!", "إِنْتَ سِعِرَك غَلَط."], correct: "مُمْكِن تْنَزِّل شُوَيّ؟", explanation: "مُمْكِن makes the request negotiable and polite." },
                { prompt: "Complete the offer: إِذَا بِعَشَرِين، ___.", options: ["بَاخُدْهَا", "أَغْلَى مِن", "قَدِّيش هَادَا"], correct: "بَاخُدْهَا", explanation: "The condition gives the acceptable price; the result states the purchase." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "shopping_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: market",
                options: ["سُوق", "دُكَّان", "مَحَلّ", "بَشْتَرِي"],
                correct: "سُوق",
            },
            {
                id: "shopping_mc2",
                type: "complete",
                prompt: "Complete: السِّعِر مِش غَالِي، السِّعِر ___.",
                options: ["رْخِيص", "مْنَاسِب", "غَالِي", "سِعِر"],
                correct: "رْخِيص",
            },
            {
                id: "shopping_mc3",
                type: "reorder",
                prompt: "Reorder: Can you lower the price?",
                options: ["مُمْكِن", "تْنَزِّل", "السِّعِر؟"],
                correct: ["مُمْكِن", "تْنَزِّل", "السِّعِر؟"],
            },
            {
                id: "shopping_mc4",
                type: "complete",
                prompt: "Complete: بِصِير أَدْفَع بِـ___.",
                options: ["الكَارْت", "كَاش", "وَصْل", "شِيكِل"],
                correct: "الكَارْت",
            },
            { id: "shopping_mc6", type: "complete", prompt: "Complete: بَدِّي ___ كِيلُو.", options: ["نُصّ", "كِيلُو", "قِطْعَة", "كَمّ"], correct: "نُصّ" },
            { id: "shopping_mc7", type: "complete", prompt: "Complete: السِّعِر مْنَاسِب، ___.", options: ["بَاخُدُه", "خَلِّيه", "بَس بَتْفَرَّج", "عِنْدَك تَانِي؟"], correct: "بَاخُدُه" },
            {
                id: "shopping_mc5",
                type: "match",
                prompt: "Choose the Arabic for: receipt",
                options: ["وَصْل", "خَصْم", "مَقَاس", "سُوق"],
                correct: "وَصْل",
            },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            {
                id: "shopping_q1",
                questionAr: "Choose when to use: «قَدِّيش هَادَا؟»",
                optionsEn: ["ask the price", "ask someone's age", "ask about weather"],
                correctIndex: 0,
            },
            {
                id: "shopping_q2",
                questionAr: "Choose a natural response when the price is high.",
                optionsEn: ["مُمْكِن تْنَزِّل شُوَيّ؟", "كِيف الجَوّ عِنْدَك؟", "أَنَا بَس بَتْفَرَّج."],
                correctIndex: 0,
            },
            {
                id: "shopping_q3",
                questionAr: "Choose when a shopper says: «بَاخُدْهَا»",
                optionsEn: ["a feminine item", "a masculine item", "a group of people"],
                correctIndex: 0,
            },
            {
                id: "shopping_q4",
                questionAr: "Choose how to ask for another color.",
                optionsEn: ["عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟", "قَدِّيش الأُجْرَة؟", "كِيف المُوَاصَلَات؟"],
                correctIndex: 0,
            },
            {
                id: "shopping_q5",
                questionAr: "Choose the English meaning of: «نُصّ كِيلُو»",
                optionsEn: ["half a kilo", "one kilo", "two kilos"],
                correctIndex: 0,
            },
            {
                id: "shopping_q6",
                questionAr: "Choose the situation where you use: «آخِر سِعِر؟»",
                optionsEn: ["bargaining", "greeting", "family description"],
                correctIndex: 0,
            },
            {
                id: "shopping_q7",
                questionAr: "Choose how to say that you want to pay cash.",
                optionsEn: ["بَدِّي أَدْفَع كَاش.", "بَدِّي أَشُوف المَقَاس.", "بَدِّي أَرْجَع بَدْرِي."],
                correctIndex: 0,
            },
            {
                id: "shopping_q8",
                questionAr: "Choose what the adjective «مْنَاسِب» can describe.",
                optionsEn: ["price, size, color, or time", "only weather", "only family"],
                correctIndex: 0,
            },
            {
                id: "shopping_q9",
                questionAr: "Choose why a shopper keeps the receipt.",
                optionsEn: ["for exchange or proof of payment", "to ask the weather", "to describe family"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Shopping role-play: ask for an item, color, size and price; bargain once, choose a quantity, then decide how to pay.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "سِعِر", arabeezy: "si3er", en: "price" },
                    { ar: "خَصْم", arabeezy: "khaSm", en: "discount" },
                    { ar: "مَقَاس", arabeezy: "ma2as", en: "size" },
                    { ar: "لَوْن", arabeezy: "lawn", en: "color" },
                    { ar: "نُصّ كِيلُو", arabeezy: "noSS kilo", en: "half a kilo" },
                    { ar: "وَصْل", arabeezy: "waSl", en: "receipt" },
                ],
                multipleChoice: [
                    { prompt: "Choose the feminine form of غَالِي (ghali).", options: ["غَالْيَة (ghalyeh)", "غَالِيِين (ghalyeen)", "رْخِيصَة (rkheeSa)"], correct: "غَالْيَة (ghalyeh)" },
                    { prompt: "Choose the phrase used to ask a price.", options: ["قَدِّيش هَادَا؟ (addeesh hada?)", "كِيف الجَوّ؟ (keef el-jaww?)", "مَع مِين؟ (ma3 meen?)"], correct: "قَدِّيش هَادَا؟ (addeesh hada?)" },
                ],
            },
            {
                title: "B - Shopping grammar practice",
                fillInTheBlank: [
                    { prompt: "بَدِّي ___ هَدِيَّة.", arabeezy: "baddi ___ hadiyyeh.", cueEn: "buy", answer: "أَشْتِرِي" },
                    { prompt: "قَدِّيش ___ القَمِيص؟", arabeezy: "addeesh ___ el-qameeS?", cueEn: "price of", answer: "سِعِر" },
                    { prompt: "بَدِّي نُصّ ___ بَنْدُورَة.", arabeezy: "baddi noSS ___ bandora.", cueEn: "kilo", answer: "كِيلُو" },
                    { prompt: "عِنْدَك نَفْس المَقَاس ___ تَانِي؟", arabeezy: "3indak nafs el-ma2as ___ tani?", cueEn: "in another color", answer: "بِلَوْن" },
                    { prompt: "هَادَا غَالِي؛ مُمْكِن ___ شُوَيّ؟", arabeezy: "hada ghali; mumkin ___ shway?", cueEn: "lower the price", answer: "تْنَزِّل" },
                    { prompt: "خَلِّيه خَمْسِين وَ___ كَاش.", arabeezy: "khallih khamseen w ___ cash.", cueEn: "I will take it", answer: "بَاخُدُه" },
                    { prompt: "بِصِير أَدْفَع ___ الكَارْت؟", arabeezy: "biseer adfa3 ___ el-card?", cueEn: "by", answer: "بِـ" },
                    { prompt: "بَدِّي تَلَاتَة ___ مَيّ.", arabeezy: "baddi talateh ___ mayy.", cueEn: "bottles", answer: "قَنَانِي" },
                    { prompt: "هَادِي الشَّنْطَة غَالْيَة، بَدِّي وَحْدَة ___.", arabeezy: "hadi esh-shanTa ghalyeh, baddi wa7deh ___.", cueEn: "cheaper (feminine)", answer: "أَرْخَص" },
                    { prompt: "Review: اِمْبَارِح السِّعِر ___ أَرْخَص.", arabeezy: "imbari7 es-si3er ___ arkhaS.", cueEn: "was", answer: "كَان" },
                    { prompt: "Review: بُكْرَا ___ أَرُوح عَالسُّوق.", arabeezy: "bukra ___ aroo7 3as-soo2.", cueEn: "will", answer: "رَاح" },
                    { prompt: "Review: الجَوّ اليَوم أَحْسَن ___ اِمْبَارِح.", arabeezy: "el-jaww el-yom a7san ___ imbari7.", cueEn: "than", answer: "مِن" },
                ],
                correctTheMistake: [
                    { prompt: "Correct: هَادِي القَمِيص غَالْيَة.", arabeezy: "hadi el-qameeS ghalyeh.", answer: "هَادَا القَمِيص غَالِي." },
                    { prompt: "Correct: هَادَا الشَّنْطَة سُودَا.", arabeezy: "hada esh-shanTa soda.", answer: "هَادِي الشَّنْطَة سُودَا." },
                    { prompt: "Correct: بَدِّي تَلَات كِيلُو بَنْدُورَة.", arabeezy: "baddi talat kilo bandora.", answer: "بَدِّي تَلَاتَة كِيلُو بَنْدُورَة." },
                    { prompt: "Review the future: بُكْرَا رُحْت عَالسُّوق.", arabeezy: "bukra ru7t 3as-soo2.", answer: "بُكْرَا رَاح أَرُوح عَالسُّوق." },
                    { prompt: "Correct the number: بَدِّي تَلَات قَنَانِي مَيّ.", arabeezy: "baddi talat qanani mayy.", answer: "بَدِّي تَلَاتَة قَنَانِي مَيّ." },
                    { prompt: "Correct the adjective: هَادِي الشَّنْطَة أَسْوَد.", arabeezy: "hadi esh-shanTa aswad.", answer: "هَادِي الشَّنْطَة سُودَا." },
                ],
                reorderSentences: [
                    { prompt: "Build: I want half a kilo of tomatoes.", arabeezy: "baddi noSS kilo bandora.", words: ["بَدِّي", "نُصّ كِيلُو", "بَنْدُورَة."], answer: "بَدِّي نُصّ كِيلُو بَنْدُورَة." },
                    { prompt: "Build: Do you have another color?", arabeezy: "3indak lawn tani?", words: ["عِنْدَك", "لَوْن", "تَانِي؟"], answer: "عِنْدَك لَوْن تَانِي؟" },
                    { prompt: "Build: Yesterday the price was cheaper.", arabeezy: "imbari7 es-si3er kan arkhaS.", words: ["اِمْبَارِح", "السِّعِر", "كَان أَرْخَص."], answer: "اِمْبَارِح السِّعِر كَان أَرْخَص." },
                    { prompt: "Review: Tomorrow I will go to the market.", arabeezy: "bukra ra7 aroo7 3as-soo2.", words: ["بُكْرَا", "رَاح أَرُوح", "عَالسُّوق."], answer: "بُكْرَا رَاح أَرُوح عَالسُّوق." },
                    { prompt: "Build: Can I pay by card?", arabeezy: "biseer adfa3 bil-card?", words: ["بِصِير", "أَدْفَع", "بِالكَارْت؟"], answer: "بِصِير أَدْفَع بِالكَارْت؟" },
                    { prompt: "Review: Today's weather is better than yesterday's.", arabeezy: "jaww el-yom a7san min imbari7.", words: ["جَوّ اليَوم", "أَحْسَن", "مِن اِمْبَارِح."], answer: "جَوّ اليَوم أَحْسَن مِن اِمْبَارِح." },
                ],
            },
        ],
        translation: [
            { id: "shopping_t1", type: "enToAr", textEn: "Good morning, I want to buy a gift for my brother.", textAr: "صَبَاح الخِير، بَدِّي أَشْتِرِي هَدِيَّة لِأَخُوي." },
            { id: "shopping_t2", type: "arToEn", textEn: "How much is this black shirt?", textAr: "قَدِّيش هَادَا القَمِيص الأَسْوَد؟" },
            { id: "shopping_t3", type: "enToAr", textEn: "This is a little expensive. Can you lower it a little?", textAr: "هَادَا غَالِي شُوَيّ. مُمْكِن تْنَزِّل شُوَيّ؟" },
            { id: "shopping_t4", type: "arToEn", textEn: "Do you have the same size in another color?", textAr: "عِنْدَك نَفْس المَقَاس بِلَوْن تَانِي؟" },
            { id: "shopping_t5", type: "enToAr", textEn: "My budget today is fifty shekels.", textAr: "مِيزَانِيَّتِي اليَوم خَمْسِين شِيكِل." },
            { id: "shopping_t6", type: "arToEn", textEn: "Make it fifty and I'll take it cash.", textAr: "خَلِّيه خَمْسِين وَبَاخُدُه كَاش." },
            { id: "shopping_t7", type: "enToAr", textEn: "Can I pay by card, or only cash?", textAr: "بِصِير أَدْفَع بِالكَارْت وَلَا بَس كَاش؟" },
            { id: "shopping_t8", type: "arToEn", textEn: "Take the receipt; you might need it later.", textAr: "خُد الوَصْل، مُمْكِن تِحْتَاجُه بَعْدِين." },
            { id: "shopping_t9", type: "enToAr", textEn: "I want half a kilo of tomatoes and half a kilo of cucumbers.", textAr: "بَدِّي نُصّ كِيلُو بَنْدُورَة وَنُصّ كِيلُو خِيَار." },
            { id: "shopping_t10", type: "arToEn", textEn: "A kilo of tomatoes is ten shekels.", textAr: "الكِيلُو بَنْدُورَة بِعَشَرَة شَوَاكِل." },
            { id: "shopping_t11", type: "enToAr", textEn: "Yesterday the price was cheaper.", textAr: "اِمْبَارِح السِّعِر كَان أَرْخَص." },
            { id: "shopping_t12", type: "arToEn", textEn: "The price is suitable, but I want to see another one.", textAr: "السِّعِر مْنَاسِب، بَس بَدِّي أَشُوف غَيْرُه." },
            { id: "shopping_t13", type: "enToAr", textEn: "I'm just looking for now, thank you.", textAr: "أَنَا بَس بَتْفَرَّج هَلْقِيت، شُكْرًا." },
            { id: "shopping_t14", type: "arToEn", textEn: "If the size does not work, can I exchange it?", textAr: "إِذَا المَقَاس مَا زَبَط، بِقْدَر أَبَدِّلُه؟" },
            { id: "shopping_t15", type: "enToAr", textEn: "Let's go home before the crowd increases.", textAr: "يَلَّا نْرَوِّح قَبْل مَا يْزِيد الزَّحْمَة." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-90 second shopping story in Gaza Palestinian Arabic. Include: where you went, what you wanted to buy, the price, color or size, whether it was expensive or suitable, how you bargained, how you paid, and whether you took a receipt. Reuse at least 8 words from this unit and 5 old words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Good morning, I want to buy a gift for my brother.
2. How much is this black shirt?
3. This is a little expensive. Can you lower it a little?
4. Do you have the same size in another color?
5. My budget today is fifty shekels.
6. Make it fifty and I'll take it cash.
7. Can I pay by card, or only cash?
8. Take the receipt; you might need it later.
9. I want half a kilo of tomatoes and half a kilo of cucumbers.
10. A kilo of tomatoes is ten shekels.
11. Yesterday the price was cheaper.
12. The price is suitable, but I want to see another one.
13. I'm just looking for now, thank you.
14. If the size does not work, can I exchange it?
15. Let's go home before the crowd increases.`,
    },

    teacherNotes: {
        warmup: [
            "Start with a real question: شو آخر إشي اشتريته؟ قديش كان؟",
            "Recycle previous units immediately: greetings, weather, family gift, transport, and food market.",
            "This unit's hidden focus is numbers, colors, quantities, comparison, and polite bargaining.",
        ],
        vocabularySteps: [
            "Teach phrases as shopping chunks: قَدِّيش هَادَا؟ / غَالِي شُوَيّ / آخِر سِعِر؟ / بَاخُدُه.",
            "Use masculine/feminine through items: هَادَا القَمِيص / هَادِي الجَزْمَة / بَاخُدُه / بَاخُدْهَا.",
            "Keep numbers practical: 10, 12, 15, 50, 55, 60, 80, and prices by kilo.",
            "Use colors as needed in context, not as a separate color lesson.",
        ],
        dialogueSteps: [
            "Act the dialogue in two scenes: clothes shop, then vegetable stand.",
            "Ask the dialogue questions as speaking practice and require full sentence answers.",
            "Have the student replace the shirt with a real item they want to buy.",
        ],
        practiceTips: [
            "Push output: the student must ask price, bargain once, ask for size/color, and close the purchase.",
            "Use quick transformations: هَادَا غَالِي → هَادِي غَالْيَة; بَاخُدُه → بَاخُدْهَا.",
            "End with a 60-second role-play where the student buys something under a budget.",
        ],
        wrapup: [
            "Student buys one item in a role-play without reading.",
            "Student asks for another size/color.",
            "Student bargains politely and says how they will pay.",
        ],
        myNotes: "",
    },
};
