import { LESSON_ID_WEATHER } from '../../core/constants.js';

export const lessonId = LESSON_ID_WEATHER;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Weather & Small Talk",
        lessonTitle: "Unit 7 - Weather & Small Talk in Gaza Palestinian Arabic",
        contentVersion: 2026071401,
    },

    overview: {
        title: "Unit 7 - Weather & Small Talk",
        description:
            "Students learn how Gazans use weather to start real small talk: at the door, on the phone, before work, while waiting for transport, and when checking on family.",
        goals: [
            "Describe the weather naturally in Gaza Palestinian Arabic.",
            "Start and continue small talk using weather, feelings, and quick follow-up questions.",
            "Give simple advice based on the weather.",
            "Compare weather using today, yesterday, tomorrow, and next week inside examples and conversation.",
            "Recycle previous units: greetings, family, routine, food, transport, work/study, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can give a 60-second weather update.",
            "The student can start a light conversation about weather and keep it going for 8-10 lines.",
            "The student can warn someone politely about rain, wind, heat, humidity, or dust.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "el_jaw",
                ar: "الجَوّ",
                en: "the weather",
                enArabeezy: "el-jaw",
                hint: "Main word for weather. Common chunks: الجَوّ حِلُو، الجَوّ مُتْعِب، كِيف الجَوّ عِنْدَك؟",
                exampleAr: "اليَوم الجَوّ حِلُو، بَس فِي هَوَا شُوَيّ.",
                exampleArabeezy: "el-yom el-jaw 7ilu, bas fi hawa shway.",
                exampleEn: "Today the weather is nice, but there is a little wind.",
            },
            {
                id: "keef_el_jaw",
                ar: "كِيف الجَوّ؟",
                en: "How is the weather?",
                enArabeezy: "keef el-jaw?",
                hint: "Natural small-talk question. Add place/person: كِيف الجَوّ عِنْدَك؟ / كِيف الجَوّ فِي غَزَّة؟",
                exampleAr: "مَرْحَبَا، كِيفَك؟ كِيف الجَوّ عِنْدَك اليَوم؟",
                exampleArabeezy: "marhaba, keefak? keef el-jaw 3indak el-yom?",
                exampleEn: "Hi, how are you? How is the weather where you are today?",
            },
            {
                id: "ed_dunya",
                ar: "الدُّنْيَا",
                en: "the weather / outside conditions",
                enArabeezy: "ed-dunya",
                hint: "Very common in Gaza when talking about weather outside: الدُّنْيَا شُوب، الدُّنْيَا غَايْمَة، الدُّنْيَا بِتْشَتِّي.",
                exampleAr: "الدُّنْيَا شُوب اليَوم، الله يْعِين.",
                exampleArabeezy: "ed-dunya shob el-yom, allah y3een.",
                exampleEn: "It is really hot outside today, may God help.",
            },
            {
                id: "shob",
                ar: "شُوب",
                en: "heat / hot weather",
                enArabeezy: "shoob",
                hint: "Very natural in Gaza for hot weather. Say: فِي شُوب / شُو هَالشُّوب! This is the main Gaza-style word for hot weather.",
                exampleAr: "شُو هَالشُّوب! خُد مَعَك مَيّ بَارْدَة.",
                exampleArabeezy: "sho hal-shoob! khod ma3ak may barde.",
                exampleEn: "What heat! Take cold water with you.",
            },
            {
                id: "bard",
                ar: "بَرْد / سَقْعَة",
                en: "cold weather",
                enArabeezy: "bard",
                hint: "Say: فِي بَرْد / فِي سَقْعَة. For a person: بَرْدَان / بَرْدَانَة.",
                exampleAr: "بِاللَّيْل فِي سَقْعَة، خُد جَاكِيت مَعَك.",
                exampleArabeezy: "bil-lel fi sa2'a, khod jacket ma3ak.",
                exampleEn: "At night it is cold; take a jacket with you.",
            },
            {
                id: "dafi",
                ar: "دِفَا / دَافِي",
                en: "warmth / warm",
                enArabeezy: "difa / daafi",
                hint: "دِفَا = warmth. دَافِي / دَافْيَة = warm. Used for weather, clothes, drinks, and homes.",
                exampleAr: "الصُّبْح فِي دِفَا، بَس بَاللَّيْل بِبْرَد.",
                exampleArabeezy: "eS-Sub7 fi difa, bas bel-lel bibrod.",
                exampleEn: "In the morning there is warmth, but at night it gets cold.",
            },
            {
                id: "rtoobe",
                ar: "رُطُوبَة",
                en: "humidity",
                enArabeezy: "rToobe",
                hint: "Very important for Gaza because it is by the sea. Common chunk: الرُّطُوبَة عَالْيَة.",
                exampleAr: "فِي رُطُوبَة عَالْيَة اليَوم، الجَوّ مُتْعِب.",
                exampleArabeezy: "fi rToobe 3alye el-yom, el-jaw mut3ib.",
                exampleEn: "There is high humidity today; the weather is tiring.",
            },
            {
                id: "hawa",
                ar: "هَوَا",
                en: "wind / air",
                enArabeezy: "hawa",
                hint: "Natural Gaza word. Strong wind = هَوَا قَوِي. A little wind = هَوَا خَفِيف.",
                exampleAr: "الهَوَا قَوِي، سَكِّر الشُّبَّاك.",
                exampleArabeezy: "el-hawa qawi, sakkir esh-shubbak.",
                exampleEn: "The wind is strong; close the window.",
            },
            {
                id: "matar",
                ar: "مَطَر",
                en: "rain",
                enArabeezy: "maTar",
                hint: "Say: فِي مَطَر. You can also say: الدُّنْيَا بِتْشَتِّي.",
                exampleAr: "فِي مَطَر بَرَّا، دِير بَالَك عَالطَّرِيق.",
                exampleArabeezy: "fi maTar barra, deer balak 3aT-Tareeq.",
                exampleEn: "It is raining outside; be careful on the road.",
            },
            {
                id: "btimTor",
                ar: "بِتْشَتِّي",
                en: "it is raining",
                enArabeezy: "bishtetti",
                hint: "Very natural Gaza form. You can also say: فِي مَطَر. Past: شَتَّت / كَان فِي مَطَر.",
                exampleAr: "هَلْقِيت بِتْشَتِّي، خَلِّينَا نِسْتَنَّى خَمْس دَقَايِق.",
                exampleArabeezy: "halla2et bishtetti, khallina nistanna khames da2aye2.",
                exampleEn: "It is raining now; let us wait five minutes.",
            },
            {
                id: "shams",
                ar: "شَمْس",
                en: "sun",
                enArabeezy: "shams",
                hint: "Strong sun = الشَّمْس قَوِيَّة. Sunglasses = نَضَّارَة شَمْس.",
                exampleAr: "الشَّمْس قَوِيَّة، لَا تِنْسَى نَضَّارَة الشَّمْس.",
                exampleArabeezy: "esh-shams qawiyye, la tinsa naDDaret esh-shams.",
                exampleEn: "The sun is strong; do not forget sunglasses.",
            },
            {
                id: "mshammes",
                ar: "مُشْمِس",
                en: "sunny",
                enArabeezy: "mishmis ",
                hint: "For weather/day/sky. ",
                exampleAr: "يَوم الجُمْعَة الجَوّ رَاح يِكُون مُشْمِس.",
                exampleArabeezy: "yom el-jum3a el-jaw ra7 ykoon mishmis.",
                exampleEn: "On Friday the weather will be sunny.",
            },
            {
                id: "saafi",
                ar: "صَافِي",
                en: "clear",
                enArabeezy: "Saafi",
                hint: "Used when the sky/weather is clear. ",
                exampleAr: "الصُّبْح الجَوّ كَان صَافِي، بَس بَعْدِين غَيَّم.",
                exampleArabeezy: "eS-Sub7 el-jaw kan Saafi, bas ba3deen ghayyam.",
                exampleEn: "In the morning the weather was clear, but later it got cloudy.",
            },
            {
                id: "ghayem",
                ar: "غَيْم",
                en: "clouds",
                enArabeezy: "ghayem",
                hint: "Natural chunk: فِي غَيْم كْتِير. ",
                exampleAr: "فِي غَيْم كْتِير، شَكْلُه بُكْرَا فِي مَطَر.",
                exampleArabeezy: "fi ghayem kteer, shaklo bukra fi maTar.",
                exampleEn: "There are many clouds; it looks like there will be rain tomorrow.",
            },
            {
                id: "mghayyam",
                ar: "مْغَيَّم",
                en: " cloudy",
                enArabeezy: " mghayyam",
                hint: "Very natural spoken phrase.",
                exampleAr: "الجو اليَوم مْغَيَّم مِن الصُّبْح.",
                exampleArabeezy: "el-jaw el-yom mghayyam min eS-Sub7.",
                exampleEn: "The weather today has been cloudy since the morning.",
            },
            {
                id: "ghobar",
                ar: "غَبَار",
                en: "dust",
                enArabeezy: "ghabar",
                hint: "Common with wind. Say: فِي غَبَار / الدُّنْيَا غَبَار.",
                exampleAr: "فِي غَبَار عَالطَّرِيق، السَّوَاقَة صَعْبَة.",
                exampleArabeezy: "fi ghabar 3aT-Tareeq, es-sawa2a Sa3be.",
                exampleEn: "There is dust on the road; driving is hard.",
            },
            
            {
                id: "el_sayf",
                ar: "الصَّيْف",
                en: "summer",
                enArabeezy: "eS-Sayf",
                hint: "In Gaza, summer usually means شُوب + رُطُوبَة. Months can appear in examples: شَهْر سَبْعَة / شَهْر تَمَانِيَة.",
                exampleAr: "فِي الصَّيْف الرُّطُوبَة فِي غَزَّة عَالْيَة.",
                exampleArabeezy: "fi eS-Sayf er-rToobe fi ghazza 3alye.",
                exampleEn: "In summer the humidity in Gaza is high.",
            },
            {
                id: "esh_sheta",
                ar: "الشِّتَا",
                en: "winter / rain season",
                enArabeezy: "esh-sheta",
                hint: "In speech, الشِّتَا can mean winter and sometimes rainy weather.",
                exampleAr: "بَحِبّ الشِّتَا عَشَان المَطَر وَالشَّاي السَّاخِن.",
                exampleArabeezy: "ba7ib esh-sheta 3ashan el-maTar w esh-shay es-sakhen.",
                exampleEn: "I like winter because of rain and hot tea.",
            },
            {
                id: "er_rabee3",
                ar: "الرَّبِيع",
                en: "spring",
                enArabeezy: "er-rabee3",
                hint: "Usually good weather for walking and visiting family.",
                exampleAr: "فِي الرَّبِيع الجَوّ أَلْطَف مِن الصَّيْف.",
                exampleArabeezy: "fi er-rabee3 el-jaw alTaf min eS-Sayf.",
                exampleEn: "In spring the weather is nicer than summer.",
            },
            {
                id: "el_khareef",
                ar: "الخَرِيف",
                en: "fall / autumn",
                enArabeezy: "el-khareef",
                hint: "Between summer and winter. Weather starts changing.",
                exampleAr: "فِي الخَرِيف الجَوّ بِصِير أَخَفّ.",
                exampleArabeezy: "fi el-khareef el-jaw biSeer akhaff.",
                exampleEn: "In autumn the weather becomes lighter.",
            },
            {
                id: "a7san_min",
                ar: "أَحْسَن مِن",
                en: "better than",
                enArabeezy: "a7san min",
                hint: "Main comparison chunk. Other weather chunks in examples: أَبْرَد مِن، أَحَرّ مِن، أَلْطَف مِن.",
                exampleAr: "الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح.",
                exampleArabeezy: "el-jaw el-yom a7san min embare7.",
                exampleEn: "The weather today is better than yesterday.",
            },
            {
                id: "darajet_el7arara",
                ar: "دَرَجَة الحَرَارَة",
                en: "temperature",
                enArabeezy: "darajet el-7arara",
                hint: "Useful when asking about numbers and weather. Example: قَدِّيش دَرَجَة الحَرَارَة؟",
                exampleAr: "دَرَجَة الحَرَارَة اليَوم أَعْلَى مِن اِمْبَارِح.",
                exampleArabeezy: "darajet el-7arara el-yom a3la min embare7.",
                exampleEn: "The temperature today is higher than yesterday.",
            },
            {
                id: "ma_basta7mel",
                ar: "مَا بَسْتَحْمِل",
                en: "I cannot stand",
                enArabeezy: "ma basta7mel",
                hint: "Strong opinion. Use with heat, humidity, cold, noise, or waiting.",
                exampleAr: "صَرَاحَةً، مَا بَسْتَحْمِل الشُّوب مَع الرُّطُوبَة.",
                exampleArabeezy: "Sara7atan, ma basta7mel esh-shob ma3 er-rToobe.",
                exampleEn: "Honestly, I cannot stand heat with humidity.",
            },
            {
                id: "ed_dill",
                ar: "الضِّلّ",
                en: "the shade",
                enArabeezy: "eD-Dill",
                hint: "Useful in hot Gaza weather. Common advice: اِقْعَد بِالضِّلّ.",
                exampleAr: "الشَّمْس قَوِيَّة، اِقْعَد بِالضِّلّ.",
                exampleArabeezy: "esh-shams qawiyye, i23od biD-Dill.",
                exampleEn: "The sun is strong; sit in the shade.",
            },
            {
                id: "ra3d_barq",
                ar: "رَعْد وَبَرْق",
                en: "thunder and lightning",
                enArabeezy: "ra3d w barq",
                hint: "Useful recognition weather phrase. Keep it light for this unit; students do not need storm vocabulary yet.",
                exampleAr: "بَاللَّيْل كَان فِي رَعْد وَبَرْق.",
                exampleArabeezy: "bel-lel kan fi ra3d w barq.",
                exampleEn: "At night there was thunder and lightning.",
            },
            {
                id: "talj",
                ar: "تَلْج",
                en: "snow",
                enArabeezy: "talj",
                hint: "Recognition word. Snow is not common in Gaza, but students hear it when talking about other cities/countries.",
                exampleAr: "فِي بَعْض البِلَاد بِالشِّتَا بِنْزَل تَلْج.",
                exampleArabeezy: "fi ba3d el-bilad bish-sheta binzal talj.",
                exampleEn: "In some countries, snow falls in winter.",
            },
            {
                id: "dabab",
                ar: "ضَبَاب",
                en: "fog",
                enArabeezy: "dabab",
                hint: "Use with roads and visibility: فِي ضَبَاب عَالطَّرِيق.",
                exampleAr: "الصُّبْح كَان فِي ضَبَاب عَالطَّرِيق.",
                exampleArabeezy: "eS-Sub7 kan fi dabab 3aT-Tareeq.",
                exampleEn: "In the morning there was fog on the road.",
            },
            {
                id: "asfeh",
                ar: "عَاصْفَة",
                en: "storm",
                enArabeezy: "3aSfeh",
                hint: "Useful but less frequent than rain/wind. Do not overload students with rare storm types in this unit.",
                exampleAr: "إِذَا فِي عَاصْفَة، خَلِّيك جُوَّه البَيْت.",
                exampleArabeezy: "iza fi 3aSfeh, khaleek juwwa el-beit.",
                exampleEn: "If there is a storm, stay inside the house.",
            },
            {
                id: "deer_balak",
                ar: "دِير بَالَك",
                en: "be careful / take care",
                enArabeezy: "deer balak",
                hint: "To a woman: دِيرِي بَالِك. To a group: دِيرُوا بَالْكُم.",
                exampleAr: "دِير بَالَك عَالطَّرِيق، فِي مَطَر وَغَبَار.",
                exampleArabeezy: "deer balak 3aT-Tareeq, fi maTar w ghabar.",
                exampleEn: "Be careful on the road; there is rain and dust.",
            },
            {
                id: "khod_ma3ak",
                ar: "خُد مَعَك",
                en: "take with you",
                enArabeezy: "khod ma3ak",
                hint: "To a woman: خُدِي مَعِك. Useful with شَمْسِيَّة، جَاكِيت، مَيّ.",
                exampleAr: "خُد مَعَك شَمْسِيَّة، شَكْلُهَا بَدْهَا تْشَتِّي.",
                exampleArabeezy: "khod ma3ak shamsiyye, shakilha baddha tshetti.",
                exampleEn: "Take an umbrella with you; it looks like it will rain.",
            },
        ],
    },

  dialogue: {
    title: "Weather & Transportation - Waiting for the Bus",
    setting: "Rami and Noor are waiting for the bus on a windy, cloudy day. They talk about weather, transportation, family advice, and favorite seasons.",
    lines: [
        { speaker: "Rami", ar: "يَا سَاتِر... شُو هَالهَوَا!", arArabeezy: "ya sater... shoo hal-hawa!", en: "Oh wow... what wind!" },
        { speaker: "Noor", ar: "ههههه قُلْتِلَك خُد جَاكِيت.", arArabeezy: "hahaha oltillak khod jacket.", en: "Haha, I told you to take a jacket." },
        { speaker: "Rami", ar: "وَالله الصُّبُح كَان الجَوّ مْنِيح، مَا تَوَقَّعْت يِقْلِب هَيْك.", arArabeezy: "wallah eS-Sobo7 kan el-jaw mnee7, ma tawaqqa3t yi2lib hek.", en: "The weather was good in the morning. I didn’t expect it to change like this." },
        { speaker: "Noor", ar: "هَالأَيَّام مَا بْتِعْرَف عَلَى الجَوّ. الصُّبُح بَرْد، الضُّهُر شُوب، وَبِاللَّيْل بَرْد مِن جَدِيد.", arArabeezy: "hal-ayam ma bti3raf 3ala el-jaw. eS-Sobo7 bard, eD-Duher shoob, w bil-leil bard min jadeed.", en: "These days you can’t understand the weather. Morning is cold, noon is hot, and at night it gets cold again." },
        { speaker: "Rami", ar: "شَكْلْهَا بَدْهَا تِشْتِي.", arArabeezy: "shakilha baddha tishti.", en: "Looks like it’s going to rain." },
        { speaker: "Noor", ar: "مِيَّة بِالمِيَّة. شُوف الغَيْم كِيف صَار.", arArabeezy: "meyye bil-meyye. shoof el-gheim keef Sar.", en: "Definitely. Look at how the clouds are now." },
        { speaker: "Rami", ar: "بَس نَاقِص البَاص يِتْأَخَّر.", arArabeezy: "bas na2iS el-baS yit2akhkhar.", en: "All we need now is for the bus to be late." },
        { speaker: "Noor", ar: "لَا تِحْكِي هَيْك، أَنَا إِذَا اتْأَخَّرْت كَمَان خَمْس دَقَايِق الدُّكْتُور بِسَكِّر البَاب.", arArabeezy: "la ti7ki hek, ana iza it2akhkhart kaman khams da2aye2 ed-doctor bisakkir el-bab.", en: "Don’t say that. If I’m five more minutes late, the doctor will close the door." },
        { speaker: "Rami", ar: "لِسَّه مَا إِجَاش؟", arArabeezy: "lissa ma ijash?", en: "It still hasn’t come?" },
        { speaker: "Noor", ar: "صَارْلِي رُبُع سَاعَة بَسْتَنَّاه.", arArabeezy: "Sarli rob3 sa3a bastannah.", en: "I’ve been waiting for it for fifteen minutes." },
        { speaker: "Rami", ar: "يَا زَلَمَة... لَمَّا الدُّنْيَا تْغَيِّم هَيْك، المُوَاصَلَات بْتِتْأَخَّر.", arArabeezy: "ya zalame... lamma ed-dinya tghayyim hek, el-mowaSalat btit2akhkhar.", en: "Man... when it gets cloudy like this, transportation gets delayed." },
        { speaker: "Noor", ar: "آه، وَالنَّاس كُلْهَا بْتِطْلَع بِنَفْس الوَقْت.", arArabeezy: "ah, w en-nas kolha btiTla3 binafs el-wa2t.", en: "Yes, and everyone goes out at the same time." },
        { speaker: "Rami", ar: "أَنَا إِمْبَارِح رِجِعْت مَشِي نُصّ الطَّرِيق.", arArabeezy: "ana embare7 riji3t mashi noSS eT-Taree2.", en: "Yesterday I walked half the way back." },
        { speaker: "Noor", ar: "لِيش؟", arArabeezy: "leesh?", en: "Why?" },
        { speaker: "Rami", ar: "مَا لْقِيت وَلَا تَاكْسِي فَاضِي.", arArabeezy: "ma l2eet wala taxi faDi.", en: "I couldn’t find a single empty taxi." },
        { speaker: "Noor", ar: "الحَمْدُ لله إِنِّي رِجِعْت بَدْرِي.", arArabeezy: "el-7amdullah inni riji3t badri.", en: "Thank God I came back early." },
        { speaker: "Rami", ar: "أَهْلِك كِيف؟ الجَوّ أَثَّر عَلَيْهِم؟", arArabeezy: "ahlik keef? el-jaw aththar 3aleihom?", en: "How’s your family? Did the weather affect them?" },
        { speaker: "Noor", ar: "إِمِّي مِن الصُّبُح بْتِحْكِيلِي: لَا تِنْسِي الجَاكِيت، وَلَا تِطْلَعِي بَدُون شَمْسِيَّة.", arArabeezy: "immi min eS-Sobo7 bti7keeli: la tinsi el-jacket, w la tiTla3i bidoon shamsiyye.", en: "My mom has been telling me since the morning: don’t forget the jacket, and don’t go out without an umbrella." },
        { speaker: "Rami", ar: "ههههه... الأُمَّهَات كُلْهُم نَفْس الحَكِي.", arArabeezy: "hahaha... el-ommahat kolhom nafs el-7aki.", en: "Haha... all mothers say the same things." },
        { speaker: "Noor", ar: "وَإِنْت؟", arArabeezy: "w inta?", en: "And you?" },
        { speaker: "Rami", ar: "أَبُوي مِن إِمْبَارِح بْيِقُولِّي: الدُّنْيَا بَدْهَا تِشْتِي، لَا تِغْسِل السَّيَّارَة. 😂", arArabeezy: "aboy min embare7 bi2olli: ed-dinya baddha tishti, la tighsil es-sayyara.", en: "My dad has been telling me since yesterday: it’s going to rain, don’t wash the car." },
        { speaker: "Noor", ar: "هههههه... شَكْلُه كَان عِنْدُه حَقّ.", arArabeezy: "hahaha... shaklo kan 3indo 7a2.", en: "Haha... looks like he was right." },
        { speaker: "Rami", ar: "أَكِيد.", arArabeezy: "akeed.", en: "Of course." },
        { speaker: "Noor", ar: "أَنَا أَكْتَر إِشِي بَكْرَهُه بِالرُّطُوبَة.", arArabeezy: "ana aktar ishi bakraho bir-rToobe.", en: "The thing I hate most is humidity." },
        { speaker: "Rami", ar: "آه وَالله... بْتِحِسّ البَيْت مَخْنُوق.", arArabeezy: "ah wallah... bti7iss el-beit makhnoo2.", en: "Yes, really... it makes the house feel stuffy." },
        { speaker: "Noor", ar: "خُصُوصًا بِاللَّيْل.", arArabeezy: "khuSooSan bil-leil.", en: "Especially at night." },
        { speaker: "Rami", ar: "بَس مَع هَيْك، أَنَا بَحِبّ الشِّتَا أَكْتَر مِن الصَّيْف.", arArabeezy: "bas ma3 hek, ana ba7ibb esh-sheta aktar min eS-Seif.", en: "But even so, I like winter more than summer." },
        { speaker: "Noor", ar: "أَنَا العَكْس.", arArabeezy: "ana el-3aks.", en: "I’m the opposite." },
        { speaker: "Rami", ar: "لِيش؟", arArabeezy: "leesh?", en: "Why?" },
        { speaker: "Noor", ar: "الصَّيْف أَسْهَل بِالنِّسْبَة إِلِي. بَتْحَرَّك أَكْتَر، وَبَحِبّ أَقْعُد عَالبَحْر.", arArabeezy: "eS-Seif ashal bin-nisbe ili. bat7arrak aktar, w ba7ibb a2od 3al-ba7er.", en: "Summer is easier for me. I move around more, and I like sitting by the sea." },
        { speaker: "Rami", ar: "أَمَّا أَنَا أَوَّل مَا يِيجِي الصَّيْف بَزْهَق مِن الشُّوب.", arArabeezy: "amma ana awwal ma yeeji eS-Seif bazha2 min esh-shoob.", en: "As for me, as soon as summer comes, I get tired of the heat." },
        { speaker: "Noor", ar: "الرَّبِيع أَحْسَن إِشِي.", arArabeezy: "er-rabee3 a7san ishi.", en: "Spring is the best." },
        { speaker: "Rami", ar: "هَاي أَوَّل مَرَّة نِتَّفِق اليَوْم. 😂", arArabeezy: "hay awwal marra nittafi2 el-yom.", en: "This is the first time we agree today." },
        { speaker: "Noor", ar: "ههههه... عَنْجَد.", arArabeezy: "hahaha... 3anjad.", en: "Haha... seriously." },
        { speaker: "Rami", ar: "شُفْتِي التَّطْبِيق؟", arArabeezy: "shofti et-taTbee2?", en: "Did you check the app?" },
        { speaker: "Noor", ar: "لَا، شُو بِيحْكِي؟", arArabeezy: "la, shoo bi7ki?", en: "No, what does it say?" },
        { speaker: "Rami", ar: "بِيْقُول بُكْرَة الجَوّ أَلْطَف، وَمَا فِي مَطَر.", arArabeezy: "bi2ool bokra el-jaw alTaf, w ma fi maTar.", en: "It says tomorrow the weather will be nicer, and there’s no rain." },
        { speaker: "Noor", ar: "الحَمْدُ لله، بُكْرَة عِنْدِي مِشْوَار طَوِيل.", arArabeezy: "el-7amdullah, bokra 3indi mishwar Taweel.", en: "Thank God. Tomorrow I have a long errand." },
        { speaker: "Rami", ar: "وِين رَايْحَة؟", arArabeezy: "wayn ray7a?", en: "Where are you going?" },
        { speaker: "Noor", ar: "عِنْدِي مَوْعِد وَبَعْدَهَا بَدِّي أَمُرّ عَسِتِّي.", arArabeezy: "3indi maw3id w ba3dha baddi amorr 3a-sitti.", en: "I have an appointment, and after that I want to stop by my grandmother’s." },
        { speaker: "Rami", ar: "الله يْخَلِّيلِك إِيَّاهَا.", arArabeezy: "allah ykhaleelik iyyaha.", en: "May God keep her for you." },
        { speaker: "Noor", ar: "آمِين.", arArabeezy: "ameen.", en: "Amen." },
        { speaker: "Rami", ar: "آه... إِجَا البَاص أَخِيرًا.", arArabeezy: "ah... ija el-baS akheeran.", en: "Ah... the bus finally came." },
        { speaker: "Noor", ar: "يَلَّا الحَمْدُ لله.", arArabeezy: "yalla el-7amdullah.", en: "Finally, thank God." },
        { speaker: "Rami", ar: "دِيرِي بَالِك عَحَالِك.", arArabeezy: "deeri balik 3a7alik.", en: "Take care of yourself." },
        { speaker: "Noor", ar: "وَإِنْت كَمَان.", arArabeezy: "w inta kaman.", en: "You too." }
    ],

    questions: [
        { ar: "وِين كَان رَامِي وَنُور؟", en: "Where were Rami and Noor?" },
        { ar: "لِيش كَانُوا مُسْتَنِّيِين؟", en: "Why were they waiting?" },
        { ar: "كِيف كَان الجَوّ؟", en: "How was the weather?" },
        { ar: "لِيش نُور كَانِت خَايْفَة تِتْأَخَّر؟", en: "Why was Noor afraid of being late?" },
        { ar: "شُو صَار مَع رَامِي إِمْبَارِح؟", en: "What happened with Rami yesterday?" },
        { ar: "شُو كَانِت تِنْصَح أُمّ نُور؟", en: "What did Noor’s mother advise her?" },
        { ar: "شُو قَال أَبُو رَامِي عَن السَّيَّارَة؟", en: "What did Rami’s father say about the car?" },
        { ar: "مِين بْحِبّ الشِّتَا؟", en: "Who likes winter?" },
        { ar: "مِين بْحِبّ الصَّيْف؟", en: "Who likes summer?" },
        { ar: "أَي فَصْل اتَّفَقُوا إِنُّه أَلْطَف؟", en: "Which season did they agree was the nicest?" },
        { ar: "شُو كَان تَوَقُّع الطَّقْس لِبُكْرَة؟", en: "What was the weather forecast for tomorrow?" },
        { ar: "وِين كَانِت رَايْحَة نُور بُكْرَة؟", en: "Where was Noor going tomorrow?" }
    ],
},

    grammar: [
        {
            title: "1. Describing weather now and before with كَان",
            short: "الجَوّ حَارّ — الجَوّ كَان حَارّ — الدُّنْيَا كَانَت شِتَا",
            description: "A present weather description normally has no word for ‘is’: الجَوّ حَارّ. To move that description into the past, Palestinian Arabic uses كَان with a masculine subject and كَانَت with a feminine subject. The choice follows the Arabic weather noun: الجَوّ is masculine, while الدُّنْيَا is grammatically feminine.",
            table: {
                title: "Present and past weather frames",
                headers: ["Time", "Masculine الجَوّ", "Feminine الدُّنْيَا", "Meaning"],
                rows: [
                    ["now", "الجَوّ بَارِد", "الدُّنْيَا بَرْد", "the weather is cold"],
                    ["past", "الجَوّ كَان بَارِد", "الدُّنْيَا كَانَت بَرْد", "the weather was cold"],
                    ["now", "الجَوّ مُغَبِّر", "الدُّنْيَا غَبَرَة", "it is dusty"],
                    ["past", "الجَوّ كَان مُغَبِّر", "الدُّنْيَا كَانَت غَبَرَة", "it was dusty"],
                ],
            },
            examples: [
                { ar: "اليَوم الجَوّ دَافِي، بَس إِمْبَارِح كَان بَارِد.", arabeezy: "el-yom el-jaww dafi, bas imbari7 kan bared.", en: "Today the weather is warm, but yesterday it was cold." },
                { ar: "الصُّبُح الدُّنْيَا كَانَت شِتَا، وَهَلْقِيت صَحْيِت.", arabeezy: "eS-Subu7 ed-dinya kanat shita, w hal2eet Sa7yet.", en: "In the morning it was rainy, and now it has cleared up." },
                { ar: "الأُسْبُوع المَاضِي الجَوّ كَان أَرْطَب مِن هَالأُسْبُوع.", arabeezy: "el-usboo3 el-maDi el-jaww kan arTab min hal-usboo3.", en: "Last week the weather was more humid than this week." },
            ],
            commonMistakes: [
                "Do not add كَان to a present description. الجَوّ حَارّ means ‘the weather is hot’; الجَوّ كَان حَارّ means it was hot.",
                "Use كَانَت with the feminine noun الدُّنْيَا, even though English translates the whole expression as impersonal ‘it’." ,
                "Weather descriptions differ across Palestine. Both الجَوّ and الدُّنْيَا are natural, but their grammatical gender is different.",
            ],
            exercises: [
                { prompt: "Choose: ‘Yesterday the weather was cold.’", options: ["إِمْبَارِح الجَوّ كَان بَارِد.", "إِمْبَارِح الجَوّ بَارِد هَلْقِيت.", "إِمْبَارِح الدُّنْيَا كَان بَارِد."], correct: "إِمْبَارِح الجَوّ كَان بَارِد.", explanation: "الجَوّ is masculine, so its past description uses كَان." },
                { prompt: "Complete with the agreeing past form: الدُّنْيَا ___ غَبَرَة.", options: ["كَانَت", "كَان", "كُنْت"], correct: "كَانَت", explanation: "الدُّنْيَا is grammatically feminine." },
                { prompt: "Which sentence describes the weather now?", options: ["الجَوّ دَافِي.", "الجَوّ كَان دَافِي.", "الجَوّ رَاح يِدْفَى."], correct: "الجَوّ دَافِي.", explanation: "The present nominal sentence needs no ‘is’." },
            ],
        },
        {
            title: "2. Comparing weather with أَفْعَل and أَكْتَر",
            short: "أَحَرّ مِن، أَبْرَد مِن، أَحْسَن مِن، أَكْتَر رُطُوبَة",
            description: "Many common Palestinian comparisons use a compact comparative form followed by مِن: أَحَرّ مِن (‘hotter than’). When no familiar compact form is used, speakers can say أَكْتَر + noun/adjective idea, such as أَكْتَر رُطُوبَة. The object after مِن is the comparison point.",
            table: {
                title: "Weather comparisons",
                headers: ["Base idea", "Comparative", "Arabizi", "Example meaning"],
                rows: [
                    ["حَارّ", "أَحَرّ مِن", "a7arr min", "hotter than"],
                    ["بَارِد", "أَبْرَد مِن", "abrad min", "colder than"],
                    ["مْنِيح", "أَحْسَن مِن", "a7san min", "better than"],
                    ["سَيِّئ", "أَسْوَأ مِن", "aswa2 min", "worse than"],
                    ["رُطُوبَة", "أَكْتَر رُطُوبَة مِن", "aktar ruTooba min", "more humid than"],
                    ["هَوَا", "أَقَلّ هَوَا مِن", "aqall hawa min", "less windy than"],
                ],
            },
            examples: [
                { ar: "اليَوم أَحَرّ مِن إِمْبَارِح.", arabeezy: "el-yom a7arr min imbari7.", en: "Today is hotter than yesterday." },
                { ar: "غَزَّة بِالصَّيْف أَكْتَر رُطُوبَة مِن الخَلِيل.", arabeezy: "Ghazza biS-Seif aktar ruTooba min el-Khaleel.", en: "Gaza is more humid than Hebron in summer." },
                { ar: "الجَوّ بَعْد المَطَر أَحْسَن مِن قَبْل.", arabeezy: "el-jaww ba3d el-maTar a7san min qabel.", en: "The weather after the rain is better than before." },
            ],
            commonMistakes: [
                "Do not use مِن before the comparative word. The order is أَبْرَد مِن: comparative first, comparison point second.",
                "أَكْتَر does not mean ‘very’. أَكْتَر رُطُوبَة مِن compares two things; رُطُوبَة كْتِير simply says it is very humid.",
                "Comparative forms are often fixed and irregular. Learn أَحْسَن and أَسْوَأ as complete words rather than trying to derive them mechanically.",
            ],
            exercises: [
                { prompt: "Choose: ‘Today is colder than yesterday.’", options: ["اليَوم أَبْرَد مِن إِمْبَارِح.", "اليَوم بَارِد مِن إِمْبَارِح.", "مِن إِمْبَارِح اليَوم أَحَرّ."], correct: "اليَوم أَبْرَد مِن إِمْبَارِح.", explanation: "أَبْرَد gives the comparison and مِن introduces yesterday." },
                { prompt: "Complete: غَزَّة ___ رُطُوبَة مِن القُدْس.", options: ["أَكْتَر", "كْتِير", "أَحَرّ"], correct: "أَكْتَر", explanation: "أَكْتَر رُطُوبَة مِن means ‘more humid than’." },
                { prompt: "Which expression means ‘better than’?", options: ["أَحْسَن مِن", "مْنِيح كْتِير", "أَكْتَر مِن أَحْسَن"], correct: "أَحْسَن مِن", explanation: "أَحْسَن is the common comparative of the idea ‘good’." },
            ],
        },
        {
            title: "3. People versus non-human plurals",
            short: "الطُّلَّاب تَعْبَانِين — الشَّوَارِع فَاضْيَة",
            description: "Human plural groups normally take plural descriptions in Palestinian Arabic. Non-human plural nouns—streets, cars, days, clouds—very often take a feminine-singular description, especially as a collective scene. Everyday speech allows some plural agreement too, but the feminine-singular pattern is essential for understanding natural Arabic.",
            table: {
                title: "Agreement by meaning",
                headers: ["Subject type", "Subject", "Description", "Meaning"],
                rows: [
                    ["human plural", "النَّاس", "مِزْعُوجِين", "the people are bothered"],
                    ["human plural", "الطُّلَّاب", "بَرْدَانِين", "the students feel cold"],
                    ["non-human plural", "الشَّوَارِع", "مَبْلُولَة", "the streets are wet"],
                    ["non-human plural", "السَّيَّارَات", "وَاقْفَة", "the cars are stopped"],
                    ["non-human plural", "الغْيُوم", "تْقِيلَة", "the clouds are heavy"],
                ],
            },
            examples: [
                { ar: "النَّاس تَعْبَانِين مِن الحَرّ وَالرُّطُوبَة.", arabeezy: "en-nas ta3baneen min el-7arr wir-ruTooba.", en: "People are tired from the heat and humidity." },
                { ar: "الشَّوَارِع مَبْلُولَة عَشَان المَطَر.", arabeezy: "esh-shaware3 mablooleh 3ashan el-maTar.", en: "The streets are wet because of the rain." },
                { ar: "السَّيَّارَات وَاقْفَة وَالطَّرِيق زَحْمَة.", arabeezy: "es-sayyarat waqfeh wiT-Tareeq za7meh.", en: "The cars are stopped and the road is congested." },
            ],
            commonMistakes: [
                "Do not copy human plural agreement onto every object. الشَّوَارِع مَبْلُولَة is a core natural pattern.",
                "النَّاس is grammatically a collective word but refers to people, so plural human agreement such as تَعْبَانِين is natural.",
                "You may hear non-human plural adjectives in some dialectal contexts. Learn the feminine-singular pattern first, then notice real variation rather than treating it as an error everywhere.",
            ],
            exercises: [
                { prompt: "Choose the natural core agreement: ‘The streets are empty.’", options: ["الشَّوَارِع فَاضْيَة.", "الشَّوَارِع فَاضْيِين.", "الشَّوَارِع فَاضِي."], correct: "الشَّوَارِع فَاضْيَة.", explanation: "A non-human plural commonly takes a feminine-singular description." },
                { prompt: "Complete the human description: الطُّلَّاب ___. (tired)", options: ["تَعْبَانِين", "تَعْبَانَة", "تَعْبَان"], correct: "تَعْبَانِين", explanation: "A human plural group takes plural agreement." },
                { prompt: "Why is وَاقْفَة singular in السَّيَّارَات وَاقْفَة?", options: ["Non-human plurals often take feminine-singular agreement.", "سيارات means one car.", "The sentence is past tense."], correct: "Non-human plurals often take feminine-singular agreement.", explanation: "The cars form a non-human plural scene, triggering common feminine-singular agreement." },
            ],
        },
        {
            title: "4. Predicting weather with رَاح, مُمْكِن, and شَكْلُه",
            short: "رَاح تِشْتِي — مُمْكِن يِنْزَل مَطَر — شَكْلُه الجَوّ بَدُّه يِقْلَب",
            description: "Weather forecasts range from confident to uncertain. رَاح + verb gives a straightforward future prediction. مُمْكِن + verb lowers certainty to ‘might’. شَكْلُه introduces an inference from visible signs—clouds, wind, or colour of the sky. After these future/modal words, the following action does not take the habitual بـ.",
            table: {
                title: "Degrees of certainty",
                headers: ["Frame", "Example", "Natural force"],
                rows: [
                    ["رَاح + verb", "رَاح تِشْتِي", "it will rain"],
                    ["مُمْكِن + verb", "مُمْكِن يِنْزَل مَطَر", "it might rain"],
                    ["شَكْلُه + sentence", "شَكْلُه الجَوّ بَدُّه يِقْلَب", "it looks like the weather will turn"],
                    ["مَا رَاح + verb", "مَا رَاح تِشْتِي", "it will not rain"],
                ],
            },
            examples: [
                { ar: "بُكْرَة رَاح يِكُون الجَوّ أَدْفَى.", arabeezy: "bukra ra7 ykoon el-jaww adfa.", en: "Tomorrow the weather will be warmer." },
                { ar: "مُمْكِن يِنْزَل مَطَر بَعْد الضُّهُر.", arabeezy: "mumkin yinzal maTar ba3d eD-Duhr.", en: "It might rain in the afternoon." },
                { ar: "الغْيُوم سَوْدَا؛ شَكْلُهَا بَدَّهَا تِشْتِي.", arabeezy: "el-ghyoom soda; shaklha baddha tishti.", en: "The clouds are dark; it looks like it is going to rain." },
            ],
            commonMistakes: [
                "After رَاح, do not keep habitual بـ: رَاح يِبْرَد, not رَاح بِبْرَد.",
                "مُمْكِن communicates possibility, not certainty. Use it when the forecast or evidence is unclear.",
                "شَكْلُه literally relates to appearance, but conversationally it means ‘apparently / it looks like’. Its attached ending may agree with what the speaker is referring to.",
            ],
            exercises: [
                { prompt: "Choose: ‘It might rain.’", options: ["مُمْكِن تِشْتِي.", "رَاح بِتِشْتِي.", "مُمْكِن بِتِشْتِي دَايْمًا."], correct: "مُمْكِن تِشْتِي.", explanation: "مُمْكِن expresses possibility, and the following verb appears without habitual بـ." },
                { prompt: "Correct: بُكْرَة رَاح بِبْرَد الجَوّ.", options: ["بُكْرَة رَاح يِبْرَد الجَوّ.", "بُكْرَة بَرْد الجَوّ رَاح.", "بُكْرَة رَاح بَارِد."], correct: "بُكْرَة رَاح يِبْرَد الجَوّ.", explanation: "After رَاح, use the future action without habitual بـ." },
                { prompt: "Which phrase signals an inference from what you see?", options: ["شَكْلُه الجَوّ بَدُّه يِقْلَب.", "كُلّ يَوم الجَوّ حَارّ.", "الجَوّ كَان بَارِد."], correct: "شَكْلُه الجَوّ بَدُّه يِقْلَب.", explanation: "شَكْلُه means ‘it looks like/apparently’." },
            ],
        },
        {
            title: "5. Weather conditions and useful advice",
            short: "إِذَا شِتْيِت... — لَو الجَوّ صَحِي... — دِير بَالَك",
            description: "Small talk becomes useful when weather leads to a condition, plan, warning, or suggestion. إِذَا introduces a realistic condition. The result can be an imperative, a present consequence, or a future with رَاح. لَو is also frequent in spoken hypothetical or tentative plans; this unit focuses on practical chunks rather than formal mood labels.",
            table: {
                title: "Condition → response",
                headers: ["Condition", "Response type", "Complete example"],
                rows: [
                    ["إِذَا شِتْيِت", "command", "إِذَا شِتْيِت، خُد شَمْسِيَّة"],
                    ["إِذَا الجَوّ بَرِد", "future", "إِذَا الجَوّ بَرِد، رَاح نِرْجَع"],
                    ["إِذَا فِي غَبَرَة", "warning", "إِذَا فِي غَبَرَة، دِير بَالَك"],
                    ["لَو الجَوّ صَحِي", "tentative plan", "لَو الجَوّ صَحِي، بِنْرُوح عَالبَحَر"],
                ],
            },
            examples: [
                { ar: "إِذَا شِتْيِت، خُد مَعَك شَمْسِيَّة.", arabeezy: "iza shityit, khod ma3ak shamsiyyeh.", en: "If it rains, take an umbrella with you." },
                { ar: "إِذَا فِي غَبَرَة، دِير بَالَك عَطَرِيقَك.", arabeezy: "iza fi ghabara, deer balak 3a Tareeqak.", en: "If it is dusty, be careful on your way." },
                { ar: "لَو الجَوّ صَحِي يَوم الجُمْعَة، بِنْزُور سِتِّي.", arabeezy: "law el-jaww Sa7i yom el-jum3a, binzoor sitti.", en: "If the weather is clear on Friday, we’ll visit my grandmother." },
            ],
            commonMistakes: [
                "Do not translate every English ‘if’ using one rigid formal rule. Spoken إِذَا and لَو overlap, while certainty and context guide the choice.",
                "A condition needs a meaningful result: advice, warning, decision, or consequence—not two unrelated weather sentences.",
                "دِير بَالَك is addressed to one man. To a woman: دِيرِي بَالِك; to a group: دِيرُوا بَالْكُم.",
            ],
            exercises: [
                { prompt: "Complete the useful response: إِذَا شِتْيِت، ___.", options: ["خُد مَعَك شَمْسِيَّة", "مِن وِين إِنْتَ", "الجَوّ كَان إِمْبَارِح"], correct: "خُد مَعَك شَمْسِيَّة", explanation: "The condition logically leads to advice about an umbrella." },
                { prompt: "Address one woman: ‘Be careful.’", options: ["دِيرِي بَالِك.", "دِير بَالَك.", "دِيرُوا بَالْكُم."], correct: "دِيرِي بَالِك.", explanation: "The feminine command uses ـي and the possessive ending is also feminine." },
                { prompt: "Which sentence gives a tentative weather plan?", options: ["لَو الجَوّ صَحِي، بِنْرُوح عَالبَحَر.", "الجَوّ صَحِي مِن البَحَر.", "بِنْرُوح لَأَنُّه إِذَا."], correct: "لَو الجَوّ صَحِي، بِنْرُوح عَالبَحَر.", explanation: "لَو introduces the condition; the second clause gives the plan." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "weather_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: the weather",
                options: ["الجَوّ", "الشُّغُل", "العِيلَة", "الأُجْرَة"],
                correct: "الجَوّ",
            },
            {
                id: "weather_mc2",
                type: "complete",
                prompt: "Complete the Arabic for: There is a lot of heat today. فِي ___ كْتِير اليَوم.",
                options: ["شُوب", "اِسْمِي", "سَاكِن", "أُخْت"],
                correct: "شُوب",
            },
            {
                id: "weather_mc3",
                type: "reorder",
                prompt: "Reorder: How is the weather where you are?",
                options: ["كِيف", "الجَوّ", "عِنْدَك؟"],
                correct: ["كِيف", "الجَوّ", "عِنْدَك؟"],
            },
            {
                id: "weather_mc4",
                type: "complete",
                prompt: "Choose the Arabic word for: winter",
                options: ["الشِّتَا", "الصَّيْف", "الرَّبِيع", "الخَرِيف"],
                correct: "الشِّتَا",
            },
            {
                id: "weather_mc5",
                type: "match",
                prompt: "Complete: فِي رَعْد وَ___.",
                options: ["بَرْق", "ظِلّ", "غُبَار", "مَطَر"],
                correct: "بَرْق",
            },
            { id: "weather_mc6", type: "match", prompt: "Choose the Arabic phrase for: take with you", options: ["خُد مَعَك", "دِير بَالَك", "مَا بَسْتَحْمِل", "أَحْسَن مِن"], correct: "خُد مَعَك" },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        quiz: [
            {
                id: "weather_q1",
                questionAr: "Choose the English meaning of: «كِيف الجَوّ عِنْدَك؟»",
                optionsEn: ["How is the weather where you are?", "Where do you live?", "What is your name?"],
                correctIndex: 0,
            },
            {
                id: "weather_q2",
                questionAr: "Choose the natural advice when it is raining.",
                optionsEn: ["خُد مَعَك شَمْسِيَّة.", "شُو اِسْمَك؟", "أَنَا عِنْدِي أَخ."],
                correctIndex: 0,
            },
            {
                id: "weather_q3",
                questionAr: "Who does the feminine word «بَرْدَانَة» describe?",
                optionsEn: ["to/about a woman feeling cold", "to/about a man feeling hot", "about rain"],
                correctIndex: 0,
            },
            {
                id: "weather_q4",
                questionAr: "Choose how to say: “I cannot stand the heat.”",
                optionsEn: ["مَا بَسْتَحْمِل الشُّوب.", "بَحِبّ الشِّتَا.", "الدُّنْيَا غَايْمَة."],
                correctIndex: 0,
            },
            {
                id: "weather_q5",
                questionAr: "Choose who the instruction «دِيرِي بَالِك» addresses.",
                optionsEn: ["to a woman", "to a man", "to a group"],
                correctIndex: 0,
            },
            {
                id: "weather_q6",
                questionAr: "Choose the sentence that contains a comparison.",
                optionsEn: ["الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح.", "مَرْحَبَا، كِيفَك؟", "اِسْمِي نُور."],
                correctIndex: 0,
            },
            {
                id: "weather_q7",
                questionAr: "Choose the situation where you often hear: «الرُّطُوبَة عَالْيَة»",
                optionsEn: ["Gaza/coastal weather", "family introductions", "asking for a name"],
                correctIndex: 0,
            },
            {
                id: "weather_q8",
                questionAr: "Choose the phrase that naturally starts weather small talk.",
                optionsEn: ["وَالله الجَوّ اليَوم حِلُو.", "بَدِّي حِسَاب البَنْك.", "عِنْدِي اِمْتِحَان رِيَاضِيَّات."],
                correctIndex: 0,
            },
            {
                id: "weather_q9",
                questionAr: "Choose the English meaning of: «الدُّنْيَا غَايْمَة»",
                optionsEn: ["It is cloudy outside.", "It is very sunny.", "It is my first day."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Give a weather update: describe yesterday, today, and tomorrow; make one comparison and give one piece of advice.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "شُوب", arabeezy: "shoob", en: "hot weather / heat" },
                    { ar: "بَرْد", arabeezy: "bard", en: "cold weather" },
                    { ar: "رُطُوبَة", arabeezy: "rToobeh", en: "humidity" },
                    { ar: "مَطَر", arabeezy: "maTar", en: "rain" },
                    { ar: "غَايِم", arabeezy: "ghayem", en: "cloudy" },
                    { ar: "أَحْسَن مِن", arabeezy: "a7san min", en: "better than" },
                ],
                multipleChoice: [
                    { prompt: "Choose the feminine form of بَرْدَان (bardan).", options: ["بَرْدَانَة (bardaneh)", "بَرْد (bard)", "دَافِيَة (dafiyeh)"], correct: "بَرْدَانَة (bardaneh)" },
                    { prompt: "Choose the sentence that compares two days.", options: ["الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح.", "اليَوم فِي هَوَا.", "خُد مَعَك شَمْسِيَّة."], correct: "الجَوّ اليَوم أَحْسَن مِن اِمْبَارِح." },
                ],
            },
            {
                title: "B - Weather grammar practice",
                fillInTheBlank: [
                    { prompt: "الجَوّ اليَوم أَحْسَن ___ اِمْبَارِح.", arabeezy: "el-jaww el-yom a7san ___ imbari7.", cueEn: "than", answer: "مِن" },
                    { prompt: "اِمْبَارِح ___ الجَوّ حَارّ.", arabeezy: "imbari7 ___ el-jaww 7arr.", cueEn: "was", answer: "كَان" },
                    { prompt: "بُكْرَا الجَوّ ___ يِكُون أَلْطَف.", arabeezy: "bukra el-jaww ___ ykoon alTaf.", cueEn: "will", answer: "رَاح" },
                    { prompt: "الدُّنْيَا غَايْمَة وَ___ هَوَا.", arabeezy: "ed-dinya ghaymeh w ___ hawa.", cueEn: "there is", answer: "فِي" },
                    { prompt: "هِيَّ ___ عَشَان الجَوّ بَارِد.", arabeezy: "hiyyeh ___ 3ashan el-jaww bared.", cueEn: "cold (feminine)", answer: "بَرْدَانَة" },
                    { prompt: "هُوَّ مَا ___ الشُّوب مَع الرُّطُوبَة.", arabeezy: "huwwe ma ___ esh-shoob ma3 er-ruToobeh.", cueEn: "can stand", answer: "بِسْتَحْمِل" },
                    { prompt: "لَمَّا تِشَتِّي، ___ مَعَك شَمْسِيَّة.", arabeezy: "lamma tishti, ___ ma3ak shamsiyyeh.", cueEn: "take (command, masculine)", answer: "خُد" },
                    { prompt: "الهَوَا قَوِي؛ ___ الشُّبَّاك.", arabeezy: "el-hawa qawi; ___ esh-shubbak.", cueEn: "close (command, masculine)", answer: "سَكِّر" },
                    { prompt: "الصَّيف فِي غَزَّة ___ مِن الشِّتَا.", arabeezy: "eS-Seif fi ghazzeh ___ min esh-shita.", cueEn: "hotter", answer: "أَحَرّ" },
                    { prompt: "Review: بَرُوح عَالشُّغُل ___ البَاص.", arabeezy: "baroo7 3ash-shughul ___ el-bas.", cueEn: "by", answer: "بِـ" },
                    { prompt: "Review: هُمَّ ___ فِي المَكْتَب اليَوم.", arabeezy: "humme ___ fil-maktab el-yom.", cueEn: "work (they)", answer: "بِشْتِغْلُوا" },
                    { prompt: "Review: اِتْأَخَّرْت ___ الزَّحْمَة.", arabeezy: "it2akhkhart ___ ez-za7meh.", cueEn: "because of", answer: "عَشَان" },
                ],
                correctTheMistake: [
                    { prompt: "Correct: الدُّنْيَا غَايِم.", arabeezy: "ed-dinya ghayem.", answer: "الدُّنْيَا غَايْمَة." },
                    { prompt: "Correct: هِيَّ بَرْدَان.", arabeezy: "hiyyeh bardan.", answer: "هِيَّ بَرْدَانَة." },
                    { prompt: "Correct the past: اِمْبَارِح الجَوّ يِكُون حَارّ.", arabeezy: "imbari7 el-jaww ykoon 7arr.", answer: "اِمْبَارِح كَان الجَوّ حَارّ." },
                    { prompt: "Correct the future: بُكْرَا الجَوّ كَان أَحْسَن.", arabeezy: "bukra el-jaww kan a7san.", answer: "بُكْرَا الجَوّ رَاح يِكُون أَحْسَن." },
                    { prompt: "Correct the comparison: اليَوم أَحْسَن عَن اِمْبَارِح.", arabeezy: "el-yom a7san 3an imbari7.", answer: "اليَوم أَحْسَن مِن اِمْبَارِح." },
                    { prompt: "Correct the command to a woman: خُد مَعَك شَمْسِيَّة.", arabeezy: "khod ma3ik shamsiyyeh.", answer: "خُدِي مَعِك شَمْسِيَّة." },
                ],
                reorderSentences: [
                    { prompt: "Build: Yesterday was hotter than today.", arabeezy: "imbari7 kan a7arr min el-yom.", words: ["اِمْبَارِح", "كَان أَحَرّ", "مِن اليَوم."], answer: "اِمْبَارِح كَان أَحَرّ مِن اليَوم." },
                    { prompt: "Build: Tomorrow will be better.", arabeezy: "bukra ra7 ykoon a7san.", words: ["بُكْرَا", "رَاح يِكُون", "أَحْسَن."], answer: "بُكْرَا رَاح يِكُون أَحْسَن." },
                    { prompt: "Build: Take an umbrella with you.", arabeezy: "khod ma3ak shamsiyyeh.", words: ["خُد مَعَك", "شَمْسِيَّة."], answer: "خُد مَعَك شَمْسِيَّة." },
                    { prompt: "Review: There is traffic on the road.", arabeezy: "fi za7meh 3aT-Taree2.", words: ["فِي زَحْمَة", "عَالطَّرِيق."], answer: "فِي زَحْمَة عَالطَّرِيق." },
                    { prompt: "Build: Summer in Gaza is hotter than winter.", arabeezy: "eS-Seif fi ghazzeh a7arr min esh-shita.", words: ["الصَّيف فِي غَزَّة", "أَحَرّ", "مِن الشِّتَا."], answer: "الصَّيف فِي غَزَّة أَحَرّ مِن الشِّتَا." },
                    { prompt: "Review: They work in the office today.", arabeezy: "humme bishtighlu fil-maktab el-yom.", words: ["هُمَّ", "بِشْتِغْلُوا", "فِي المَكْتَب", "اليَوم."], answer: "هُمَّ بِشْتِغْلُوا فِي المَكْتَب اليَوم." },
                ],
            },
        ],
        translation: [
            { id: "weather_t1", type: "enToAr", textEn: "Hi, how are you? How is the weather where you are?", textAr: "مَرْحَبَا، كِيفَك؟ كِيف الجَوّ عِنْدَك؟" },
            { id: "weather_t2", type: "arToEn", textEn: "Today the weather is nice, but there is wind.", textAr: "اليَوم الجَوّ حِلُو، بَس فِي هَوَا." },
            { id: "weather_t3", type: "enToAr", textEn: "There is a lot of heat and humidity today.", textAr: "فِي شُوب وَرُطُوبَة كْتِير اليَوم." },
            { id: "weather_t4", type: "arToEn", textEn: "It is raining outside; take an umbrella with you.", textAr: "بَرَّه بِتْشَتِّي، خُد مَعَك شَمْسِيَّة." },
            { id: "weather_t5", type: "enToAr", textEn: "The wind is strong; close the window.", textAr: "الهَوَا قَوِي، سَكِّر الشُّبَّاك." },
            { id: "weather_t6", type: "arToEn", textEn: "Yesterday the weather was hotter than today.", textAr: "اِمْبَارِح كَان الجَوّ أَحَرّ مِن اليَوم." },
            { id: "weather_t7", type: "enToAr", textEn: "Tomorrow the weather will be better than today.", textAr: "بُكْرَا الجَوّ رَاح يِكُون أَحْسَن مِن اليَوم." },
            { id: "weather_t8", type: "arToEn", textEn: "Honestly, I cannot stand heat with humidity.", textAr: "صَرَاحَةً، مَا بَسْتَحْمِل الشُّوب مَع الرُّطُوبَة." },
            { id: "weather_t9", type: "enToAr", textEn: "I like winter because of the rain and hot tea.", textAr: "بَحِبّ الشِّتَا عَشَان المَطَر وَالشَّاي السَّاخِن." },
            { id: "weather_t10", type: "arToEn", textEn: "In summer, Gaza's humidity is high.", textAr: "فِي الصَّيْف رُطُوبَة غَزَّة عَالْيَة." },
            { id: "weather_t11", type: "enToAr", textEn: "There is dust on the road; be careful.", textAr: "فِي غَبَار عَالطَّرِيق، دِير بَالَك." },
            { id: "weather_t12", type: "arToEn", textEn: "If the weather is sunny on Friday, we will visit my grandmother.", textAr: "إِذَا الجَوّ مُشْمِس يَوم الجُمْعَة، رَاح نْرُوح عِنْد سِتِّي." },
            { id: "weather_t13", type: "enToAr", textEn: "I have university today, but it is windy and cloudy outside.", textAr: "عِنْدِي جَامْعَة اليَوم، بَس الدُّنْيَا غَايْمَة وَفِي هَوَا." },
            { id: "weather_t14", type: "arToEn", textEn: "Really? It rained yesterday?", textAr: "عَنْ جَدّ؟ اِمْبَارِح مَطَّرَت؟" },
            { id: "weather_t15", type: "enToAr", textEn: "God be with you, and tell me when you arrive.", textAr: "الله مَعَك، وَطَمِّنِّي بَس تُوصَل." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second weather small-talk story in Gaza Palestinian Arabic. Include: a greeting, how you feel today, the weather where you are, how the weather was yesterday, what you expect tomorrow or Friday, one comparison, one opinion, and one advice sentence. Reuse at least 8 words from this unit and 5 old words from earlier units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you? How is the weather where you are?
2. Today the weather is nice, but there is wind.
3. It is raining outside; take an umbrella with you.
4. There is a lot of heat and humidity today.
5. Yesterday the weather was hotter than today.
6. Tomorrow the weather will be better than today.
7. I like winter because of the rain and hot tea.
8. Honestly, I cannot stand heat with humidity.
9. There is dust on the road, so be careful.
10. If the weather is sunny on Friday, we will visit my grandmother.
11. I have university today, but it is windy and cloudy outside.
12. My mother said the humidity is high inside the house.
13. In spring the weather is nicer than summer.
14. Really? It rained yesterday?
15. God be with you, and tell me when you arrive.`,
    },

    teacherNotes: {
        warmup: [
            "Start with real small talk: مَرْحَبَا، كِيفَك؟ كِيف الجَوّ عِنْدَك؟",
            "This unit's hidden focus is time and comparison: اليَوم، اِمْبَارِح، بُكْرَا، يَوم الجُمْعَة، أَحْسَن مِن، أَحَرّ مِن، أَلْطَف مِن.",
            "Keep the lesson conversational; avoid listing time words as separate vocabulary unless the student needs them.",
        ],
        vocabularySteps: [
            "Teach vocabulary as chunks: فِي شُوب، فِي بَرْد، فِي رُطُوبَة، بِتْشَتِّي، خُد مَعَك...",
            "Use example words like taxi, fare, university, grandmother, water, and tea as recycling, not new vocabulary targets.",
            "Show masculine/feminine through quick substitutions: بَرْدَان / بَرْدَانَة, دِير بَالَك / دِيرِي بَالِك.",
        ],
        dialogueSteps: [
            "Act the dialogue naturally, then have the student change the destination, weather, and advice.",
            "Ask the dialogue questions as spoken output. Push full answers, not one-word answers.",
            "After the dialogue, ask the student to make their own door/building small-talk scene.",
        ],
        practiceTips: [
            "Push student output: one weather sentence, one comparison, one opinion, and one advice sentence.",
            "Recycle transport and time: قَدِّيش الأُجْرَة؟ / عَالوَقْت / قَبْل مَا تْشَتِّي.",
            "Have the student start the next three lessons with a 30-second weather update.",
        ],
        wrapup: [
            "Student gives a 60-second weather update without reading.",
            "Student asks the teacher two weather questions.",
            "Student gives one advice sentence based on the weather.",
        ],
        myNotes: "",
    },
};
