import { LESSON_ID_WORK_STUDY } from '../../core/constants.js';

export const lessonId = LESSON_ID_WORK_STUDY;

export const lesson = {
    meta: {
        level: "Pre-Intermediate",
        unit: "Work & Study",
        lessonTitle: "Unit 6 - Work & Study in Gaza Palestinian Arabic",
        contentVersion: 2026063001,
    },

    overview: {
        title: "Unit 6 - Work & Study",
        description:
            "Students learn how to talk naturally about university, school, work, schedules, exams, projects, deadlines, and being busy in Gaza Palestinian Arabic. The goal is to help students explain their real life, not memorize job and school words.",
        goals: [
            "Talk about studying, working, and daily schedules.",
            "Say what they study, where they work, and what their day looks like.",
            "Use useful chunks like: عِنْدِي دَوَام، عِنْدِي اِمْتِحَان، لَازِم أَدْرُس، بَقْدَر / مَا بَقْدَر.",
            "Ask and answer real questions about work, university, exams, and deadlines.",
            "Recycle earlier units: greetings, family, routine, food, transport, time, and politeness.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can explain their work/study situation in 60-90 seconds.",
            "The student can talk about a busy day with university, work, transport, food, and family.",
            "The student can ask a classmate about their schedule, exams, job, and free time.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "shoghol",
                ar: "شُغُل",
                en: "work / job",
                enArabeezy: "shoghol",
                hint: "Very common. I have work = عِنْدِي شُغُل. My work = شُغْلِي.",
                exampleAr: "عِنْدِي شُغُل بَعْد الجَامْعَة.",
                exampleArabeezy: "3indi shoghol ba3d el-jam3a.",
                exampleEn: "I have work after university.",
            },
            {
                id: "dawam",
                ar: "دَوَام",
                en: "shift / working hours / class schedule",
                enArabeezy: "dawam",
                hint: "Used for work and study schedules: عِنْدِي دَوَام، دَوَامِي مِن 8 لَـ 4.",
                exampleAr: "دَوَامِي مِن السَّاعَة تَمَانْيَة لَلسَّاعَة أَرْبَعَة.",
                exampleArabeezy: "dawami min el-sa3a tamanye lal-sa3a arba3a.",
                exampleEn: "My shift is from eight to four.",
            },
            {
                id: "dawam_kamel",
                ar: "دَوَام كَامِل",
                en: "full-time",
                enArabeezy: "dawam kamel",
                hint: "Full-time work or study schedule.",
                exampleAr: "أَبُوي بِشْتِغِل دَوَام كَامِل.",
                exampleArabeezy: "abuy bishtaghel dawam kamel.",
                exampleEn: "My father works full-time.",
            },
            {
                id: "dawam_joz2i",
                ar: "دَوَام جُزْئِي",
                en: "part-time",
                enArabeezy: "dawam joz2i",
                hint: "Part-time work. Useful for students who work and study.",
                exampleAr: "أَنَا طَالِب وَبَشْتِغِل دَوَام جُزْئِي.",
                exampleArabeezy: "ana Taleb w bashtaghel dawam joz2i.",
                exampleEn: "I am a student and I work part-time.",
            },
            {
                id: "Taleb",
                ar: "طَالِب / طَالْبِة",
                en: "student",
                enArabeezy: "Taleb / Talbeh",
                hint: "Male: طَالِب. Female: طَالْبِة. Plural: طُلَّاب.",
                exampleAr: "أَنَا طَالْبِة وَبَتْعَلَّم عَرَبِي.",
                exampleArabeezy: "ana Talbeh w bat3allam 3arabi.",
                exampleEn: "I am a student and I am learning Arabic.",
            },
            {
                id: "jame3a",
                ar: "جَامْعَة",
                en: "university",
                enArabeezy: "jame3a",
                hint: "Plural: جَامْعَات. My university = جَامْعْتِي.",
                exampleAr: "بَدْرُس فِي جَامْعَة غَزَّة.",
                exampleArabeezy: "badros fi jam3et ghazza.",
                exampleEn: "I study at Gaza University.",
            },
            {
                id: "madraseh",
                ar: "مَدْرَسَة",
                en: "school",
                enArabeezy: "madraseh",
                hint: "Plural: مَدَارِس. My school = مَدْرَسْتِي.",
                exampleAr: "أَخُوي لِسَّه فِي المَدْرَسَة.",
                exampleArabeezy: "akhuy lissa fi el-madraseh.",
                exampleEn: "My brother is still in school.",
            },
            {
                id: "qism",
                ar: "قِسِم",
                en: "department",
                enArabeezy: "qisim",
                hint: "University/work department: قِسِم الحَاسُوب، قِسِم اللُّغَات.",
                exampleAr: "أَنَا فِي قِسِم الحَاسُوب.",
                exampleArabeezy: "ana fi qisim el-7asob.",
                exampleEn: "I am in the computer department.",
            },
            {
                id: "sharikeh",
                ar: "شَرِكَة",
                en: "company",
                enArabeezy: "sharikeh",
                hint: "Plural: شَرِكَات. Work in a company = بَشْتِغِل فِي شَرِكَة.",
                exampleAr: "أَبُوي بِشْتِغِل فِي شَرِكَة صْغِيرَة.",
                exampleArabeezy: "abuy bishtaghel fi sharikeh zghireh.",
                exampleEn: "My father works in a small company.",
            },
            {
                id: "maktab",
                ar: "مَكْتَب",
                en: "office",
                enArabeezy: "maktab",
                hint: "Common workplace. My office = مَكْتَبِي.",
                exampleAr: "بَشْتِغِل فِي مَكْتَب قَرِيب مِن الجَامْعَة.",
                exampleArabeezy: "bashtaghel fi maktab qareeb min el-jam3a.",
                exampleEn: "I work in an office near the university.",
            },
            {
                id: "ostaz",
                ar: "أُسْتَاذ / أُسْتَاذَة",
                en: "teacher / professor",
                enArabeezy: "ustaz / ustazeh",
                hint: "Very common for teachers, tutors, and university instructors.",
                exampleAr: "الأُسْتَاذ شَرَح الدَّرْس مْنِيح.",
                exampleArabeezy: "el-ustaz shara7 el-dars mneeh.",
                exampleEn: "The teacher explained the lesson well.",
            },
            {
                id: "zamil",
                ar: "زْمِيل / زْمِيلَة",
                en: "classmate / colleague",
                enArabeezy: "zmeel / zmeeleh",
                hint: "Used for study or work colleagues. Plural: زْمَلَا.",
                exampleAr: "زْمِيلِي فِي الشُّغُل بِيِسَاعِدْنِي كْتِير.",
                exampleArabeezy: "zmeeli fi el-shoghol byisa3idni kteer.",
                exampleEn: "My colleague at work helps me a lot.",
            },
            {
                id: "mudir",
                ar: "مُدِير / مُدِيرَة",
                en: "manager / director",
                enArabeezy: "mudeer / mudeereh",
                hint: "Used in work or school context. Plural: مُدَرَا.",
                exampleAr: "المُدِير عِنْدُه اِجْتِمَاع اليَوم.",
                exampleArabeezy: "el-mudeer 3indo ijtima3 el-yom.",
                exampleEn: "The manager has a meeting today.",
            },
            {
                id: "muwazzaf",
                ar: "مُوَظَّف / مُوَظَّفَة",
                en: "employee",
                enArabeezy: "muwazzaf / muwazzafeh",
                hint: "Person who works in an office, bank, company, etc.",
                exampleAr: "أَخُوي مُوَظَّف فِي بَنْك.",
                exampleArabeezy: "akhuy muwazzaf fi bank.",
                exampleEn: "My brother is an employee in a bank.",
            },
            {
                id: "ijtima3",
                ar: "اِجْتِمَاع",
                en: "meeting",
                enArabeezy: "ijtima3",
                hint: "Plural: اِجْتِمَاعَات. Work/school meeting.",
                exampleAr: "عِنْدِي اِجْتِمَاع السَّاعَة عَشَرَة.",
                exampleArabeezy: "3indi ijtima3 el-sa3a 3ashara.",
                exampleEn: "I have a meeting at ten.",
            },
            {
                id: "maw3ed",
                ar: "مَوْعِد",
                en: "appointment / deadline",
                enArabeezy: "maw3ed",
                hint: "Use for appointments and project deadlines.",
                exampleAr: "مَوْعِد تَسْلِيم المَشْرُوع بُكْرَا.",
                exampleArabeezy: "maw3ed tasleem el-mashroo3 bukra.",
                exampleEn: "The project deadline is tomorrow.",
            },
            {
                id: "mu7adara",
                ar: "مُحَاضَرَة",
                en: "lecture / class session",
                enArabeezy: "mu7aDara",
                hint: "University/college class session.",
                exampleAr: "عِنْدِي مُحَاضَرَة سَاعْتِين اليَوم.",
                exampleArabeezy: "3indi mu7aDara sa3teen el-yom.",
                exampleEn: "I have a two-hour lecture today.",
            },
            {
                id: "maddeh",
                ar: "مَادَّة",
                en: "subject / course",
                enArabeezy: "maddeh",
                hint: "School/university subject. Plural: مَوَادّ.",
                exampleAr: "عِنْدِي تَلَات مَوَادّ هَاد الفَصِل.",
                exampleArabeezy: "3indi talat mawaad had el-faSil.",
                exampleEn: "I have three subjects this semester.",
            },
            {
                id: "imti7an",
                ar: "اِمْتِحَان",
                en: "exam / test",
                enArabeezy: "imti7an",
                hint: "Plural: اِمْتِحَانَات. Final exam = اِمْتِحَان نِهَائِي.",
                exampleAr: "الأُسْبُوع الجَاي عِنْدِي اِمْتِحَان مُهِمّ.",
                exampleArabeezy: "el-usboo3 el-jay 3indi imti7an muhim.",
                exampleEn: "Next week I have an important exam.",
            },
            {
                id: "wajeb",
                ar: "وَاجِب",
                en: "homework / assignment",
                enArabeezy: "wajeb",
                hint: "Plural: وَاجْبَات. Common school/university word.",
                exampleAr: "الأُسْتَاذ بِيِعْطِينَا وَاجِب بَعْد كُلّ دَرْس.",
                exampleArabeezy: "el-ustaz byi3Teena wajeb ba3d kul dars.",
                exampleEn: "The teacher gives us homework after every lesson.",
            },
            {
                id: "mashroo3",
                ar: "مَشْرُوع",
                en: "project",
                enArabeezy: "mashroo3",
                hint: "Plural: مَشَارِيع. Graduation project = مَشْرُوع تَخَرُّج.",
                exampleAr: "هَاد أَوَّل مَشْرُوع بَسَوِّيه فِي الجَامْعَة.",
                exampleArabeezy: "had awwal mashroo3 basawweeh fi el-jam3a.",
                exampleEn: "This is the first project I do at university.",
            },
            {
                id: "istira7a",
                ar: "اِسْتِرَاحَة",
                en: "break",
                enArabeezy: "istira7a",
                hint: "Pause from work or class.",
                exampleAr: "بِنْخُد اِسْتِرَاحَة صْغِيرَة بَيْن المُحَاضَرَات.",
                exampleArabeezy: "binkhud istira7a zghireh been el-mu7aDarat.",
                exampleEn: "We take a short break between lectures.",
            },
            {
                id: "badros",
                ar: "بَدْرُس",
                en: "I study",
                enArabeezy: "badros",
                hint: "Use with subject/field: بَدْرُس عَرَبِي / حَاسُوب / طِبّ.",
                exampleAr: "بَدْرُس حَاسُوب فِي الجَامْعَة.",
                exampleArabeezy: "badros 7asob fi el-jam3a.",
                exampleEn: "I study computer science at university.",
            },
            {
                id: "bat3allam",
                ar: "بَتْعَلَّم",
                en: "I learn",
                enArabeezy: "bat3allam",
                hint: "More general than study. Use with skills/languages: بَتْعَلَّم عَرَبِي / تَصْمِيم.",
                exampleAr: "بَتْعَلَّم عَرَبِي وَإِنْجْلِيزِي.",
                exampleArabeezy: "bat3allam 3arabi w inglizi.",
                exampleEn: "I am learning Arabic and English.",
            },
            {
                id: "bashteghil",
                ar: "بَشْتِغِل",
                en: "I work",
                enArabeezy: "bashteghil",
                hint: "Add where/how: بَشْتِغِل أُونْلَايْن / فِي مَكْتَب / دَوَام جُزْئِي.",
                exampleAr: "بَشْتِغِل دَوَام جُزْئِي وَبَدْرُس كَمَان.",
                exampleArabeezy: "bashteghil dawam joz2i w badros kaman.",
                exampleEn: "I work part-time and study too.",
            },
            {
                id: "bas2al",
                ar: "بَسْأَل",
                en: "I ask",
                enArabeezy: "bas2al",
                hint: "Classroom survival verb: لَمَّا مَا أَفْهَم بَسْأَل الأُسْتَاذ.",
                exampleAr: "لَمَّا مَا أَفْهَم بَسْأَل الأُسْتَاذ.",
                exampleArabeezy: "lamma ma afham bas2al el-ustaz.",
                exampleEn: "When I don't understand, I ask the teacher.",
            },
            {
                id: "baraji3",
                ar: "بَرَاجِع",
                en: "I review",
                enArabeezy: "baraji3",
                hint: "Use before exams or after class.",
                exampleAr: "بَرَاجِع المَادَّة بَعْد المُحَاضَرَة.",
                exampleArabeezy: "baraji3 el-maddeh ba3d el-mu7aDara.",
                exampleEn: "I review the subject after the lecture.",
            },
            {
                id: "bakammel",
                ar: "بَكَمِّل",
                en: "I continue / finish",
                enArabeezy: "bakammel",
                hint: "Use with homework/project/study: بَكَمِّل الوَاجِب / المَشْرُوع.",
                exampleAr: "بَكَمِّل المَشْرُوع بِاللِّيل.",
                exampleArabeezy: "bakammel el-mashroo3 bel-leel.",
                exampleEn: "I finish the project at night.",
            },
            {
                id: "banja7_barsob",
                ar: "بَنْجَح / بَرْسُب",
                en: "I pass / I fail",
                enArabeezy: "banja7 / barsob",
                hint: "Use with exams/subjects. Sensitive word; use carefully.",
                exampleAr: "بَنْجَح فِي الاِمْتِحَان إِذَا بَدْرُس مْنِيح.",
                exampleArabeezy: "banja7 fi el-imti7an iza badros mneeh.",
                exampleEn: "I pass the exam if I study well.",
            },
            {
                id: "lazem",
                ar: "لَازِم",
                en: "must / have to",
                enArabeezy: "lazem",
                hint: "Very useful for tasks/deadlines: لَازِم أَدْرُس / لَازِم أَخَلِّص.",
                exampleAr: "لَازِم أَخَلِّص الوَاجِب اليَوم.",
                exampleArabeezy: "lazem akhalliS el-wajeb el-yom.",
                exampleEn: "I have to finish the homework today.",
            },
            {
                id: "ba2dar",
                ar: "بَقْدَر / مَا بَقْدَر",
                en: "I can / I can't",
                enArabeezy: "ba2dar / ma ba2dar",
                hint: "Use for ability/time: بَقْدَر أَسَاعْدَك / مَا بَقْدَر اليَوم.",
                exampleAr: "بَقْدَر أَسَاعْدَك بَعْد المُحَاضَرَة.",
                exampleArabeezy: "ba2dar asa3dak ba3d el-mu7aDara.",
                exampleEn: "I can help you after the lecture.",
            },
            {
                id: "mashghool",
                ar: "مَشْغُول / مَشْغُولَة",
                en: "busy",
                enArabeezy: "mashghool / mashghooleh",
                hint: "Male: مَشْغُول. Female: مَشْغُولَة. Plural: مَشْغُولِين.",
                exampleAr: "اليَوم أَنَا مَشْغُول كْتِير.",
                exampleArabeezy: "el-yom ana mashghool kteer.",
                exampleEn: "Today I am very busy.",
            },
            {
                id: "jadwal",
                ar: "جَدْوَل",
                en: "schedule",
                enArabeezy: "jadwal",
                hint: "My schedule = جَدْوَلِي. Full schedule = جَدْوَلِي مَلْيَان.",
                exampleAr: "جَدْوَلِي هَاد الأُسْبُوع مَلْيَان.",
                exampleArabeezy: "jadwali had el-usboo3 malyan.",
                exampleEn: "My schedule is full this week.",
            },
            {
                id: "usboo3",
                ar: "أُسْبُوع",
                en: "week",
                enArabeezy: "usboo3",
                hint: "This week = الأُسْبُوع هَادَا. Next week = الأُسْبُوع الجَاي.",
                exampleAr: "عِنْدِي اِمْتِحَان الأُسْبُوع الجَاي.",
                exampleArabeezy: "3indi imti7an el-usboo3 el-jay.",
                exampleEn: "I have an exam next week.",
            },
            {
                id: "shahar",
                ar: "شَهْر",
                en: "month",
                enArabeezy: "shahar",
                hint: "In speech you can say شهر 6 / شهر ستة, or الشهر الجاي.",
                exampleAr: "فِي شَهْر سِتَّة عِنْدِي اِمْتِحَانَات نِهَائِيَّة.",
                exampleArabeezy: "fi shahar sitteh 3indi imti7anat niha2iyyeh.",
                exampleEn: "In month six / June, I have final exams.",
            },
            {
                id: "ayy_yom",
                ar: "أَيّ يَوم؟",
                en: "which day?",
                enArabeezy: "ayy yom?",
                hint: "Use with days: السَّبِت، الأَحَد، الاِتْنِين، التَّلَات، الأَرْبَعَا، الخَمِيس، الجُمْعَة.",
                exampleAr: "أَيّ يَوم عِنْدَك اِمْتِحَان؟ يَوم الخَمِيس.",
                exampleArabeezy: "ayy yom 3indak imti7an? yom el-khamees.",
                exampleEn: "Which day do you have an exam? Thursday.",
            },
            {
                id: "kam_sa3a",
                ar: "كَم سَاعَة؟",
                en: "how many hours?",
                enArabeezy: "kam sa3a?",
                hint: "Use for work, study, sleep, travel, and meetings.",
                exampleAr: "كَم سَاعَة دَوَامَك اليَوم؟ أَرْبَع سَاعَات.",
                exampleArabeezy: "kam sa3a dawamak el-yom? arba3 sa3at.",
                exampleEn: "How many hours is your shift today? Four hours.",
            },
            {
                id: "sabt_lakhmis",
                ar: "مِن السَّبِت لِلْخَمِيس",
                en: "from Saturday to Thursday",
                enArabeezy: "min el-sabet lil-khamees",
                hint: "Typical study/work week in many Arab countries.",
                exampleAr: "بَدْرُس مِن السَّبِت لِلْخَمِيس وَالجُمْعَة إِجَازَة.",
                exampleArabeezy: "badros min el-sabet lil-khamees w el-jum3a ijazeh.",
                exampleEn: "I study from Saturday to Thursday and Friday is off.",
            },
            {
                id: "mahameh",
                ar: "مَهَمَّة",
                en: "task",
                enArabeezy: "mahammEh",
                hint: "Task at work or for a project. Plural: مَهَمَّات.",
                exampleAr: "المُدِير بِعْطِينِي مَهَمَّات جْدِيدَة كُلّ يَوم.",
                exampleArabeezy: "el-mudeer bi3Teeni mahammat jdeedeh kul yom.",
                exampleEn: "The manager gives me new tasks every day.",
            },
            {
                id: "wa2t_faDi",
                ar: "وَقْت فَاضِي",
                en: "free time",
                enArabeezy: "wa2t faDi",
                hint: "Time without work or study.",
                exampleAr: "مَا عِنْدِي وَقْت فَاضِي اليَوم.",
                exampleArabeezy: "ma 3indi wa2t faDi el-yom.",
                exampleEn: "I have no free time today.",
            },
        ],
    },

    dialogue: {
    title: "Work & Study - A Busy Student Day",
    setting: "Mona and Samer talk before class about transportation, university, work, projects, online learning, and organizing time.",
    lines: [
        { speaker: "Mona", ar: "سَامِر، وِينَك؟ المُحَاضَرَة قَرَّبَت تِبْلَش.", arArabeezy: "samer, waynak? el-mo7aDara qarrabat tiblish.", en: "Samer, where are you? The lecture is about to start." },
        { speaker: "Samer", ar: "وَالله بِالطَّرِيق، بَس الإِشَارَة وَاقْفَة وَالدُّنْيَا زَحْمَة.", arArabeezy: "wallah biT-Taree2, bas el-ishara wa2fe w ed-dinya za7me.", en: "I'm on the way, but the traffic light is stuck and it's crowded." },
        { speaker: "Mona", ar: "رْكِبْت بَاص وَلَّا تَاكْسِي؟", arArabeezy: "rkibt baS wala taxi?", en: "Did you take a bus or a taxi?" },
        { speaker: "Samer", ar: "بَاص طَبْعًا. التَّاكْسِي صَار بَدُّه مِيزَانِيَّة لَحَالُه.", arArabeezy: "baS Tab3an. et-taxi Sar baddo mizaniyye la7alo.", en: "A bus, of course. A taxi needs its own budget now." },
        { speaker: "Mona", ar: "مَعَك حَقّ. بَس الحَق حَالَك، الدُّكْتُور مَا بْحِبّ حَدَا يِدْخُل مُتْأَخِّر.", arArabeezy: "ma3ak 7a2. bas el7a2 7alak, ed-doctor ma bi7ibb 7ada yodkhul mit2akhkher.", en: "You're right. But hurry up, the professor doesn't like anyone coming in late." },
        { speaker: "Samer", ar: "عَارِف، عَارِف. أَصْلًا اليَوْم مِن أَوَّلُه مُلَخْبَط.", arArabeezy: "3aref, 3aref. aSlan el-yom min awwalo mlakhbaT.", en: "I know, I know. This day has been messy from the start." },
        { speaker: "Mona", ar: "لِيش؟ شُو عِنْدَك؟", arArabeezy: "leesh? shoo 3indak?", en: "Why? What do you have?" },
        { speaker: "Samer", ar: "جَامْعَة الصُّبُح، وَبَعْدَهَا دَوَام مِن تَلَاتَة لِسَبْعَة، وَبِاللَّيْل لَازِم أَشْتَغِل عَالمَشْرُوع.", arArabeezy: "jam3a eS-Sobo7, w ba3dha dawam min talate la-sab3a, w bil-leil lazem ashtighil 3al-mashroo3.", en: "University in the morning, then work from three to seven, and at night I have to work on the project." },
        { speaker: "Mona", ar: "يَا سَاتِر، يَوْمَك طَوِيل.", arArabeezy: "ya sater, yomak Taweel.", en: "Wow, your day is long." },
        { speaker: "Samer", ar: "مِش طَوِيل، هَادَا عُقُوبَة. 😂", arArabeezy: "mish Taweel, hada 3oqoobe.", en: "Not long, this is punishment." },
        { speaker: "Mona", ar: "ههههه، شُو بِتِشْتَغِل بَعْد الجَامْعَة؟", arArabeezy: "hahaha, shoo btishtighil ba3d el-jam3a?", en: "Haha, what do you work after university?" },
        { speaker: "Samer", ar: "بِمَكْتَب صْغِير. بَرُدّ عَالتِّلِفُون، بَكْتُب مِلَفَّات، وَبْسَاعِد المُوَظَّفِين.", arArabeezy: "bimaktab Sgheer. barodd 3at-telefon, baktob malafat, w bsa3id el-mwaZZafeen.", en: "At a small office. I answer the phone, write files, and help the employees." },
        { speaker: "Mona", ar: "طَيِّب بْتِقْدَر تْوَازِن بَيْن الشُّغُل وَالدِّرَاسَة؟", arArabeezy: "Tayyib bti2dar twazin bein esh-shoghol w ed-dirase?", en: "Can you balance work and studying?" },
        { speaker: "Samer", ar: "بَقْدَر، بَس بِصُعُوبَة. خُصُوصًا هَالأُسْبُوع، عِنْدِي اِمْتِحَان وَمَشْرُوع بِنَفْس الوَقْت.", arArabeezy: "ba2dar, bas biSo3oobe. khuSooSan hal-osboo3, 3indi imti7an w mashroo3 binafs el-wa2t.", en: "I can, but with difficulty. Especially this week, I have an exam and a project at the same time." },
        { speaker: "Mona", ar: "مَوْعِد تَسْلِيم المَشْرُوع إِمْتَى؟", arArabeezy: "maw3id tasleem el-mashroo3 imta?", en: "When is the project deadline?" },
        { speaker: "Samer", ar: "الخَمِيس، وَلِسَّه ضَايِل نُصُّه تَقْرِيبًا.", arArabeezy: "el-khamees, w lissa Dayel noSSo ta2reeban.", en: "Thursday, and about half of it is still left." },
        { speaker: "Mona", ar: "مَع مِين شَغَّال عَلَيْه؟", arArabeezy: "ma3 meen shaghghal 3aleih?", en: "Who are you working on it with?" },
        { speaker: "Samer", ar: "مَع أَنَس، بَس هُو كَمَان مَشْغُول وَدَوَامُه أَطْوَل مِن دَوَامِي.", arArabeezy: "ma3 anas, bas ho kaman mashghool w dawamo aTwal min dawami.", en: "With Anas, but he's also busy and his shift is longer than mine." },
        { speaker: "Mona", ar: "طَيِّب بَعْد المُحَاضَرَة عِنْدِي سَاعَة فَاضْيَة. إِذَا بَدَّك بِنْرَاجِع مَع بَعْض.", arArabeezy: "Tayyib ba3d el-mo7aDara 3indi sa3a faDye. iza baddak binraji3 ma3 ba3D.", en: "After the lecture, I have a free hour. If you want, we can review together." },
        { speaker: "Samer", ar: "جَد؟ وَالله بِتِنْقِذِينِي.", arArabeezy: "jad? wallah bitinqizeeni.", en: "Really? You'd honestly save me." },
        { speaker: "Mona", ar: "بَس سَاعَة، بَعْدِين عِنْدِي دَرْس أُونْلَايْن.", arArabeezy: "bas sa3a, ba3dain 3indi dars online.", en: "Only one hour, then I have an online lesson." },
        { speaker: "Samer", ar: "كِفَايَة. نْرَاجِع الدَّرْس الأَخِير وَنْرَتِّب أَفْكَار المَشْرُوع.", arArabeezy: "kifaye. nraji3 ed-dars el-akheer w nrattib afkar el-mashroo3.", en: "That's enough. We'll review the last lesson and organize the project ideas." },
        { speaker: "Mona", ar: "إِنْت فَاهِم الدَّرْس الأَخِير؟", arArabeezy: "inta fahem ed-dars el-akheer?", en: "Do you understand the last lesson?" },
        { speaker: "Samer", ar: "نُصّ نُصّ. كُنْت تَعْبَان وَمَا رَكَّزْت مْنِيح.", arArabeezy: "noSS noSS. kont ta3ban w ma rakkazt mnee7.", en: "Half and half. I was tired and didn't focus well." },
        { speaker: "Mona", ar: "وَلَا يْهِمَّك. بِنِسْأَل الدُّكْتُور بَعْد المُحَاضَرَة إِذَا فِي نُقْطَة مِش وَاضْحَة.", arArabeezy: "wala yhimmak. binis2al ed-doctor ba3d el-mo7aDara iza fi no2Ta mish waD7a.", en: "Don't worry. We'll ask the professor after the lecture if there's anything unclear." },
        { speaker: "Samer", ar: "تَمَام. بِالمُنَاسَبَة، إِنْتِ شُو عَامْلَة بِالكُورْس تَبَع التَّصْمِيم؟", arArabeezy: "tamam. bil-munasabe, inti shoo 3amle bil-course taba3 et-taSmeem?", en: "Great. By the way, how's your design course going?" },
        { speaker: "Mona", ar: "مَاشْيَة فِيه شُوَي شُوَي. بَتْعَلَّم أُونْلَايْن بِاللَّيْل لَمَّا أَفْضَى.", arArabeezy: "mashye feeh shway shway. bat3allam online bil-leil lamma afDa.", en: "I'm moving through it slowly. I study online at night when I'm free." },
        { speaker: "Samer", ar: "بَدَّك تِشْتَغْلِي فِيه بَعْدِين؟", arArabeezy: "baddak tishtaghli feeh ba3dain?", en: "Do you want to work in it later?" },
        { speaker: "Mona", ar: "إِنْ شَاء الله. بَدِّي أَتْعَلَّم مْنِيح بِالأَوَّل، وَبَعْدَهَا أَدَوِّر عَلَى شُغُل.", arArabeezy: "inshallah. baddi at3allam mnee7 bil-awwal, w ba3dha adawwer 3ala shoghol.", en: "God willing. I want to learn well first, and then look for work." },
        { speaker: "Samer", ar: "الله يْوَفْقِك. بَس كِيف بْتِلَاقِي وَقْت؟", arArabeezy: "allah ywafqik. bas keef btla2i wa2t?", en: "May God help you. But how do you find time?" },
        { speaker: "Mona", ar: "بِالعَافْيَة. عِنْدِي جَامْعَة، وَاجِب عَرَبِي، وَبْسَاعِد إِمِّي بِالبَيْت بَعْد الغَدَا.", arArabeezy: "bil-3afye. 3indi jam3a, wajib 3arabi, w bsa3id immi bil-beit ba3d el-ghada.", en: "Barely. I have university, Arabic homework, and I help my mom at home after lunch." },
        { speaker: "Samer", ar: "يَعْنِي كُلْنَا غَرْقَانِين.", arArabeezy: "ya3ni kolna ghar2aneen.", en: "So we're all drowning." },
        { speaker: "Mona", ar: "آه، بَس إِذَا نَظَّمْنَا الوَقْت، بِنِلْحَق.", arArabeezy: "ah, bas iza naZZamna el-wa2t, binil7aq.", en: "Yes, but if we organize our time, we can manage." },
        { speaker: "Samer", ar: "أَنَا مُشْكِلْتِي إِنِّي بْحُطّ خُطَّة وَبَكْسِرْهَا بِنَفْس اليَوْم.", arArabeezy: "ana moshkilti inni b7oT khoTTe w baksirha binafs el-yom.", en: "My problem is that I make a plan and break it the same day." },
        { speaker: "Mona", ar: "لَأَنَّك بْتِحُطّ شُغُل يَوْمَيْن فِي يَوْم وَاحِد.", arArabeezy: "la2annak bti7oT shoghol yomain fi yom wa7ed.", en: "Because you put two days' worth of work into one day." },
        { speaker: "Samer", ar: "صَحّ. اليَوْم كُنْت نَاوِي أَدْرُس، أَدَاوِم، أَخَلِّص المَشْرُوع، وَأَرُوح النَّادِي.", arArabeezy: "Sa77. el-yom kont nawi adros, adawim, akhalliS el-mashroo3, w aroo7 en-nadi.", en: "True. Today I was planning to study, work, finish the project, and go to the gym." },
        { speaker: "Mona", ar: "اِنْسَ النَّادِي اليَوْم. خَلِّص المُهِمّ الأَوَّل.", arArabeezy: "insa en-nadi el-yom. khalliS el-mohimm el-awwal.", en: "Forget the gym today. Finish the important things first." },
        { speaker: "Samer", ar: "بَعْرِف، بَس بَحِسّ إِنِّي مُقَصِّر لَمَّا أَأَجِّل.", arArabeezy: "ba3rif, bas ba7iss inni mqaSSir lamma a2ajjil.", en: "I know, but I feel like I'm falling short when I postpone." },
        { speaker: "Mona", ar: "مِش تَقْصِير. الأَوْلَوِيَّات بْتِتْغَيَّر.", arArabeezy: "mish taqSeer. el-awlawiyyat btitghayyar.", en: "It's not falling short. Priorities change." },
        { speaker: "Samer", ar: "مَعِك حَقّ.", arArabeezy: "ma3ik 7a2.", en: "You're right." },
        { speaker: "Mona", ar: "وِين وْصِلْت هَلَّق؟", arArabeezy: "wayn wSilt halla2?", en: "Where have you reached now?" },
        { speaker: "Samer", ar: "عِنْد بَاب الجَامْعَة.", arArabeezy: "3ind bab el-jam3a.", en: "At the university gate." },
        { speaker: "Mona", ar: "اُدْخُل دَغْرِي. القَاعَة عَالشِّمَال، جَنْب المَكْتَبَة.", arArabeezy: "odkhol doghri. el-qa3a 3ash-shmal, janb el-maktabe.", en: "Go straight in. The hall is on the left, next to the library." },
        { speaker: "Samer", ar: "تَمَام، شَايِفْهَا.", arArabeezy: "tamam, shayifha.", en: "Okay, I see it." },
        { speaker: "Mona", ar: "يَلَّا بِسُرْعَة قَبْل مَا الدُّكْتُور يِسَكِّر البَاب.", arArabeezy: "yalla bisor3a 2abl ma ed-doctor ysakkir el-bab.", en: "Come on quickly before the professor closes the door." },
        { speaker: "Samer", ar: "جَاي. وَبَعْد المُحَاضَرَة بِنْرَاجِع عَشَر دَقَايِق وَلَا سَاعَة؟", arArabeezy: "jay. w ba3d el-mo7aDara binraji3 3ashar da2aye2 wala sa3a?", en: "I'm coming. After the lecture, will we review for ten minutes or an hour?" },
        { speaker: "Mona", ar: "حَسَب مَا نِلْحَق. نْبَلِّش بِعَشَر دَقَايِق، وَإِذَا احْتَجْت نْكَمِّل.", arArabeezy: "7asab ma nil7aq. nballish bi3ashar da2aye2, w iza i7tijt nkammil.", en: "Depends on what we manage. We'll start with ten minutes, and if you need, we'll continue." },
        { speaker: "Samer", ar: "اتَّفَقْنَا. يِسْلَمُوا كْتِير.", arArabeezy: "ittafa2na. yislamu kteer.", en: "Deal. Thank you so much." },
        { speaker: "Mona", ar: "وَلَا يْهِمَّك. بَس المَرَّة الجَايَة اِطْلَع أَبْكَر.", arArabeezy: "wala yhimmak. bas el-marra el-jaye iTla3 abkar.", en: "No problem. But next time, leave earlier." },
        { speaker: "Samer", ar: "خَلَص، هَاي نَصِيحَة اليَوْم. 😂", arArabeezy: "khalaS, hay naSee7et el-yom.", en: "Okay, that's today's advice." }
    ],

    questions: [
        { ar: "لِيش سَامِر تَأَخَّر عَن المُحَاضَرَة؟", en: "Why was Samer late for the lecture?" },
        { ar: "لِيش رْكِب بَاص بَدَل تَاكْسِي؟", en: "Why did he take a bus instead of a taxi?" },
        { ar: "شُو جَدْوَل سَامِر اليَوْم؟", en: "What is Samer's schedule today?" },
        { ar: "وِين سَامِر بِيِشْتَغِل؟", en: "Where does Samer work?" },
        { ar: "شُو طَبِيعَة شُغْلُه؟", en: "What is the nature of his work?" },
        { ar: "شُو عِنْد سَامِر هَالأُسْبُوع؟", en: "What does Samer have this week?" },
        { ar: "إِمْتَى مَوْعِد تَسْلِيم المَشْرُوع؟", en: "When is the project deadline?" },
        { ar: "مَع مِين سَامِر شَغَّال عَالمَشْرُوع؟", en: "Who is Samer working on the project with?" },
        { ar: "كِيف مُونَا عَرَضَت تُسَاعْدُه؟", en: "How did Mona offer to help him?" },
        { ar: "شُو بْتِتْعَلَّم مُونَا أُونْلَايْن؟", en: "What is Mona learning online?" },
        { ar: "شُو عِنْد مُونَا غَيْر الجَامْعَة؟", en: "What does Mona have besides university?" },
        { ar: "لِيش قَالَت مُونَا لِسَامِر يِنْسَى النَّادِي اليَوْم؟", en: "Why did Mona tell Samer to forget the gym today?" }
    ],
},

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "work_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: university",
                options: ["جَامْعَة", "شُغُل", "مَوْعِد", "زْمِيل"],
                correct: "جَامْعَة",
            },
            {
                id: "work_mc2",
                type: "complete",
                prompt: "Complete: عِنْدِي ___ مِن تَلَاتَة لَسَبْعَة.",
                options: ["دَوَام", "فَلَافِل", "زَحْمَة", "سَلَطَة"],
                correct: "دَوَام",
            },
            {
                id: "work_mc3",
                type: "reorder",
                prompt: "Reorder: I have an exam this week.",
                options: ["عِنْدِي", "اِمْتِحَان", "الأُسْبُوع", "هَاد"],
                correct: ["عِنْدِي", "اِمْتِحَان", "الأُسْبُوع", "هَاد"],
            },
            {
                id: "work_mc4",
                type: "choose",
                prompt: "Choose the correct phrase for: I can help you.",
                options: ["بَقْدَر أَسَاعْدَك", "مَا عِنْدِي وَقْت", "بَدِّي مَيّ", "بَنْزَل هِنَا"],
                correct: "بَقْدَر أَسَاعْدَك",
            },
            {
                id: "work_mc5",
                type: "complete",
                prompt: "Complete: مَوْعِد تَسْلِيم المَشْرُوع ___.",
                options: ["بُكْرَا", "قَرِيب", "جَعَان", "شَاي"],
                correct: "بُكْرَا",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "work_q1",
                questionAr: "«عِنْدِي دَوَام مِن تَلَاتَة لَسَبْعَة» مَعْنَاهَا:",
                optionsEn: ["I have a shift from three to seven.", "I have lunch from three to seven.", "I have a taxi from three to seven."],
                correctIndex: 0,
            },
            {
                id: "work_q2",
                questionAr: "«أَنَا طَالِب وَبَشْتِغِل دَوَام جُزْئِي» مَعْنَاهَا:",
                optionsEn: ["I am a student and I work part-time.", "I am a manager and I work full-time.", "I am a teacher and I don't study."],
                correctIndex: 0,
            },
            {
                id: "work_q3",
                questionAr: "كِيف بِنْسْأَل عَن يَوم الاِمْتِحَان؟",
                optionsEn: ["أَيّ يَوم عِنْدَك اِمْتِحَان؟", "شُو اِسْمَك؟", "قَدِّيش الأُجْرَة؟"],
                correctIndex: 0,
            },
            {
                id: "work_q4",
                questionAr: "«مَا عِنْدِي وَقْت فَاضِي اليَوم» مَعْنَاهَا:",
                optionsEn: ["I have no free time today.", "I have a lot of food today.", "I have a taxi today."],
                correctIndex: 0,
            },
            {
                id: "work_q5",
                questionAr: "حَوِّل لِلْمُؤَنَّث: أَنَا مَشْغُول.",
                optionsEn: ["أَنَا مَشْغُولَة.", "أَنَا مَشْغُولِين.", "أَنَا مُوَظَّف."],
                correctIndex: 0,
            },
            {
                id: "work_q6",
                questionAr: "كَمِّل: لَازِم ___ الوَاجِب اليَوم.",
                optionsEn: ["أَخَلِّص", "أَرْكَب", "آكُل"],
                correctIndex: 0,
            },
            {
                id: "work_q7",
                questionAr: "«بَقْدَر أَسَاعْدَك بَعْد المُحَاضَرَة» مَعْنَاهَا:",
                optionsEn: ["I can help you after the lecture.", "I can't eat after lunch.", "I get off after the lecture."],
                correctIndex: 0,
            },
            {
                id: "work_q8",
                questionAr: "«مِن السَّبِت لِلْخَمِيس» مَعْنَاهَا:",
                optionsEn: ["from Saturday to Thursday", "from morning to night", "from home to university"],
                correctIndex: 0,
            },
            {
                id: "work_q9",
                questionAr: "إِذَا بَدِّي أَحْكِي عَن deadline، بَسْتَخْدِم:",
                optionsEn: ["مَوْعِد", "مَيّ", "خُبِز"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Busy student role-play: explain that you study, work part-time, have an exam, and have no free time.",
            "Classmate help role-play: ask a classmate if they understand the lesson and offer help after the lecture.",
            "Schedule role-play: ask and answer about work hours using كَم سَاعَة؟ and مِن... لَـ...",
            "Deadline role-play: talk about a project deadline and what you must finish today.",
            "Real-life challenge: explain your real study/work week in 8-10 sentences using old vocabulary from routine, transport, and food.",
        ],
        translation: [
            { id: "work_t1", type: "enToAr", textEn: "I am a student and I work part-time.", textAr: "أَنَا طَالِب/طَالْبِة وَبَشْتِغِل دَوَام جُزْئِي." },
            { id: "work_t2", type: "arToEn", textEn: "My shift is from three to seven.", textAr: "دَوَامِي مِن تَلَاتَة لَسَبْعَة." },
            { id: "work_t3", type: "enToAr", textEn: "This week I have an exam and a project.", textAr: "الأُسْبُوع هَاد عِنْدِي اِمْتِحَان وَمَشْرُوع." },
            { id: "work_t4", type: "arToEn", textEn: "The project deadline is Thursday.", textAr: "مَوْعِد تَسْلِيم المَشْرُوع يَوم الخَمِيس." },
            { id: "work_t5", type: "enToAr", textEn: "I have to finish the homework today.", textAr: "لَازِم أَخَلِّص الوَاجِب اليَوم." },
            { id: "work_t6", type: "arToEn", textEn: "I can help you after the lecture.", textAr: "بَقْدَر أَسَاعْدَك بَعْد المُحَاضَرَة." },
            { id: "work_t7", type: "enToAr", textEn: "I don't have free time today.", textAr: "مَا عِنْدِي وَقْت فَاضِي اليَوم." },
            { id: "work_t8", type: "arToEn", textEn: "I study from Saturday to Thursday.", textAr: "بَدْرُس مِن السَّبِت لِلْخَمِيس." },
            { id: "work_t9", type: "enToAr", textEn: "What time does the lecture start?", textAr: "أَيّ سَاعَة بِتْبَلِّش المُحَاضَرَة؟" },
            { id: "work_t10", type: "arToEn", textEn: "The classroom is on the left.", textAr: "القَاعَة عَالشِّمَال." },
            { id: "work_t11", type: "enToAr", textEn: "I was late because of traffic.", textAr: "اِتْأَخَّرْت عَشَان الزَّحْمَة." },
            { id: "work_t12", type: "arToEn", textEn: "After class I want falafel and hummus.", textAr: "بَعْد الدَّرْس بَدِّي فَلَافِل وَحُمُّص." },
            { id: "work_t13", type: "enToAr", textEn: "My mother is at home and I want to help her.", textAr: "إِمِّي فِي البِيت وَبَدِّي أَسَاعِدْهَا." },
            { id: "work_t14", type: "arToEn", textEn: "If we organize time, we can finish.", textAr: "إِذَا نَظَّمْنَا الوَقْت، بِنَقْدَر نْخَلِّص." },
            { id: "work_t15", type: "enToAr", textEn: "Thanks a lot, see you later.", textAr: "يِسْلَمُوا كْتِير، بِنْشُوفَك بَعْدِين." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 75-120 second story about your work or study life in Palestinian Arabic. Mention: what you study or where you work, your schedule, one busy day, one exam/project/task, how you get there, what you eat or drink during the day, and if you have free time. Try to use at least 10 words from this vocabulary list and at least 5 words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you today?
2. I am a student and I work part-time.
3. My shift is from three to seven.
4. Every morning I go to university by bus.
5. There is traffic near the traffic light.
6. This week I have an exam and a project.
7. The project deadline is Thursday.
8. I have to finish the homework today.
9. I can help you after the lecture.
10. I do not have free time today.
11. After class I want falafel and hummus.
12. My mother is at home and I want to help her.
13. If we organize time, we can finish.
14. What day do you have the exam?
15. Thanks a lot, see you later.`,
    },

    teacherNotes: {
        warmup: [
            "Recycle units 1-5 first: greeting, route to class/work, breakfast/coffee, and family responsibilities.",
            "Ask: بتدرس؟ بتشتغل؟ عندك دوام؟ عندك امتحان؟ Keep answers personal.",
            "Use a weekly mini-schedule to make days, hours, and deadlines concrete.",
        ],
        vocabularySteps: [
            "Teach chunks, not job lists: عندي دوام، عندي امتحان، لازم أخلص، بقدر أساعدك.",
            "Keep time/days as support inside work-study talk, not a separate grammar section.",
            "Recycle transport and routine vocabulary in examples: بروح عالجامعة بالباص، بتأخر عشان الزحمة.",
        ],
        dialogueSteps: [
            "Treat the dialogue as a realistic busy-student story.",
            "Ask the student to retell Samer's day in five sentences.",
            "Then replace Samer's day with the student's real study/work schedule.",
        ],
        practiceTips: [
            "Push complete answers: عندي دوام من... لـ..., not just the hours.",
            "Drill بقدر / ما بقدر with real tasks.",
            "Ask follow-ups after every answer: أي يوم؟ أي ساعة؟ كم ساعة؟ ليش؟",
        ],
        wrapup: [
            "Student explains their schedule in 60 seconds.",
            "Student asks the teacher three work/study questions.",
            "Student records the homework story.",
        ],
        myNotes: "",
    },
};
