import { LESSON_ID_DAILY_ROUTINE } from '../../core/constants.js';

export const lessonId = LESSON_ID_DAILY_ROUTINE;

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Daily Routine",
        lessonTitle: "Unit 3 - Daily Routine & Time",
        contentVersion: 2026063001,
    },

    overview: {
        title: "Unit 3 - Daily Routine & Time",
        description:
            "Students learn to talk about a normal day in natural Gaza Palestinian Arabic: waking up, washing, eating, going out, coming back, resting, studying, cleaning, talking with family, and sleeping.",
        goals: [
            "Describe a simple daily routine from morning to night.",
            "Ask and answer simple time questions: أَيّ سَاعَة؟ / إِمْتَى؟",
            "Use everyday routine verbs in short spoken sentences.",
            "Connect daily routine with family, greetings, and basic time words from previous units.",
            "Give a 60-90 second spoken description of a normal day.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can say 8-10 sentences about their normal day.",
            "The student can ask another person about their routine.",
            "The student can explain being early, late, tired, or busy in simple Gaza Arabic.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "kul_yom",
                ar: "كُلّ يَوم",
                en: "every day",
                enArabeezy: "kul yom",
                hint: "Use with repeated actions: كُلّ يَوم بَصْحَى... / كُلّ يَوم بَرُوح...",
                exampleAr: "كُلّ يَوم بَحْكِي مَع إِمِّي.",
                exampleArabeezy: "kul yom ba7ki ma3 immi.",
                exampleEn: "Every day I talk with my mother.",
            },
            {
                id: "el_soboh",
                ar: "الصُّبُح",
                en: "in the morning",
                enArabeezy: "el-soboh",
                hint: "Morning time. Common chunks: الصُّبُح بَصْحَى / الصُّبُح بَفْطَر.",
                exampleAr: "الصُّبُح بَفْطَر مَع أَهْلِي.",
                exampleArabeezy: "el-soboh bafTar ma3 ahli.",
                exampleEn: "In the morning I have breakfast with my family.",
            },
            {
                id: "ba3d_el_duhur",
                ar: "بَعْد الضُّهُر",
                en: "in the afternoon",
                enArabeezy: "ba3d el-duhur",
                hint: "Literally after noon. Useful for coming back home, lunch, or resting.",
                exampleAr: "بَعْد الضُّهُر بَرْجَع عَالبِيت.",
                exampleArabeezy: "ba3d el-duhur barja3 3al-beet.",
                exampleEn: "In the afternoon I come back home.",
            },
            {
                id: "bel_masa",
                ar: "بِالمَسَا",
                en: "in the evening",
                enArabeezy: "bel-masa",
                hint: "Natural Gaza time word. Use it for studying, watching, visiting, or talking.",
                exampleAr: "بِالمَسَا بَدْرُس عَرَبِي.",
                exampleArabeezy: "bel-masa badros 3arabi.",
                exampleEn: "In the evening I study Arabic.",
            },
            {
                id: "bel_leel",
                ar: "بِاللِّيل",
                en: "at night",
                enArabeezy: "bel-leel",
                hint: "Night time. Common chunks: بِاللِّيل بَنَام / بِاللِّيل بَحْكِي مَع أَخُوي.",
                exampleAr: "بِاللِّيل بَنَام مِتْأَخِّر.",
                exampleArabeezy: "bel-leel banaam mit2akher.",
                exampleEn: "At night I sleep late.",
            },
            {
                id: "ay_sa3a",
                ar: "أَيّ سَاعَة؟",
                en: "what time?",
                enArabeezy: "ay sa3a?",
                hint: "Ask about schedule: أَيّ سَاعَة بِتِصْحَى؟ / أَيّ سَاعَة بِتْرُوح؟",
                exampleAr: "أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟",
                exampleArabeezy: "ay sa3a bitroo7 3al-shoghol?",
                exampleEn: "What time do you go to work?",
            },
            {
                id: "badri",
                ar: "بَدْرِي",
                en: "early",
                enArabeezy: "badri",
                hint: "Natural Gaza word. Opposite: مِتْأَخِّر. Use with waking up, sleeping, arriving.",
                exampleAr: "بَصْحَى بَدْرِي فِي أَيَّام الشُّغُل.",
                exampleArabeezy: "baS7a badri fi ayyam el-shoghol.",
                exampleEn: "I wake up early on work days.",
            },
            {
                id: "mit2akher",
                ar: "مِتْأَخِّر / مِتْأَخِّرَة",
                en: "late",
                enArabeezy: "mit2akher / mit2akhra",
                hint: "Male: مِتْأَخِّر. Female: مِتْأَخِّرَة. Use with waking, sleeping, arriving.",
                exampleAr: "اليَوم صِحِيت مِتْأَخِّر.",
                exampleArabeezy: "el-yom Si7eet mit2akher.",
                exampleEn: "Today I woke up late.",
            },
            {
                id: "baS7a",
                ar: "بَصْحَى",
                en: "I wake up",
                enArabeezy: "baS7a",
                hint: "Routine verb. Ask: أَيّ سَاعَة بِتِصْحَى؟ To a woman: بِتِصْحِي؟",
                exampleAr: "كُلّ يَوم بَصْحَى السَّاعَة سَبْعَة.",
                exampleArabeezy: "kul yom baS7a el-sa3a sab3a.",
                exampleEn: "Every day I wake up at seven.",
            },
            {
                id: "baghassal",
                ar: "بَغَسِّل",
                en: "I wash",
                enArabeezy: "baghassal",
                hint: "Daily action after waking up. Common chunk: بَغَسِّل وِجْهِي.",
                exampleAr: "أَوَّل إِشِي بَغَسِّل وِجْهِي.",
                exampleArabeezy: "awwal ishi baghassal wijhi.",
                exampleEn: "First thing, I wash my face.",
            },
            {
                id: "bat7ammam",
                ar: "بَتْحَمَّم",
                en: "I take a shower",
                enArabeezy: "bat7ammam",
                hint: "Use before going out: بَتْحَمَّم قَبِل مَا أَطْلَع.",
                exampleAr: "بَتْحَمَّم قَبِل مَا أَطْلَع.",
                exampleArabeezy: "bat7ammam qabel ma aTla3.",
                exampleEn: "I shower before I go out.",
            },
            {
                id: "bafTar",
                ar: "بَفْطَر",
                en: "I have breakfast",
                enArabeezy: "bafTar",
                hint: "Breakfast = فُطُور. Useful chunk: بَفْطَر مَع أَهْلِي.",
                exampleAr: "بَفْطَر مَع أُخْتِي الصُّبُح.",
                exampleArabeezy: "bafTar ma3 okhti el-soboh.",
                exampleEn: "I have breakfast with my sister in the morning.",
            },
            {
                id: "bashrab",
                ar: "بَشْرَب",
                en: "I drink",
                enArabeezy: "bashrab",
                hint: "Use with coffee, tea, water: بَشْرَب قَهْوَة / شَاي / مَيّ.",
                exampleAr: "الصُّبُح بَشْرَب قَهْوَة.",
                exampleArabeezy: "el-soboh bashrab ahwe.",
                exampleEn: "In the morning I drink coffee.",
            },
            {
                id: "baakul",
                ar: "بَاكُل",
                en: "I eat",
                enArabeezy: "baakul",
                hint: "General eating verb. Use with meals: بَاكُل الغَدَا / العَشَا.",
                exampleAr: "بَاكُل الغَدَا مَع أَهْلِي.",
                exampleArabeezy: "baakul el-ghada ma3 ahli.",
                exampleEn: "I eat lunch with my family.",
            },
            {
                id: "baroo7",
                ar: "بَرُوح",
                en: "I go",
                enArabeezy: "baroo7",
                hint: "Use with places: بَرُوح عَالشُّغُل / عَالدَّرْس / عَالجَامْعَة.",
                exampleAr: "بَرُوح عَالشُّغُل السَّاعَة تَمَانْيَة.",
                exampleArabeezy: "baroo7 3al-shoghol el-sa3a tamanye.",
                exampleEn: "I go to work at eight.",
            },
            {
                id: "banzel",
                ar: "بَنْزِل",
                en: "I leave / go out",
                enArabeezy: "banzel",
                hint: "Leaving home. In transport it can also mean I get off.",
                exampleAr: "بَنْزِل مِن البِيت السَّاعَة تَمَانْيَة إِلَّا رُبُع.",
                exampleArabeezy: "banzel min el-beet el-sa3a tamanye illa rubu3.",
                exampleEn: "I leave the house at quarter to eight.",
            },
            {
                id: "barja3",
                ar: "بَرْجَع",
                en: "I come back",
                enArabeezy: "barja3",
                hint: "Return home/work/class. Common chunk: بَرْجَع عَالبِيت.",
                exampleAr: "بَرْجَع عَالبِيت بَعْد الضُّهُر.",
                exampleArabeezy: "barja3 3al-beet ba3d el-duhur.",
                exampleEn: "I come back home in the afternoon.",
            },
            {
                id: "barta7",
                ar: "بَرْتَاح",
                en: "I rest",
                enArabeezy: "barta7",
                hint: "Use after work/class/cleaning: بَرْتَاح شُوَيّ.",
                exampleAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ.",
                exampleArabeezy: "ba3d ma barja3 barta7 shway.",
                exampleEn: "After I come back, I rest a little.",
            },
            {
                id: "badros",
                ar: "بَدْرُس",
                en: "I study",
                enArabeezy: "badros",
                hint: "Use with subjects/languages: بَدْرُس عَرَبِي / إِنْجْلِيزِي.",
                exampleAr: "بِالمَسَا بَدْرُس عَرَبِي.",
                exampleArabeezy: "bel-masa badros 3arabi.",
                exampleEn: "In the evening I study Arabic.",
            },
            {
                id: "bashtaghel",
                ar: "بَشْتِغِل",
                en: "I work",
                enArabeezy: "bashtaghel",
                hint: "General work verb. It will return in Unit 6 Work & Study.",
                exampleAr: "بَشْتِغِل فِي مَكْتَب.",
                exampleArabeezy: "bashtaghel fi maktab.",
                exampleEn: "I work in an office.",
            },
            {
                id: "ba7ki",
                ar: "بَحْكِي",
                en: "I talk / speak",
                enArabeezy: "ba7ki",
                hint: "Very useful for speaking goals: بَحْكِي عَرَبِي / بَحْكِي مَع أَخُوي.",
                exampleAr: "بِاللِّيل بَحْكِي مَع أَخُوي.",
                exampleArabeezy: "bel-leel ba7ki ma3 akhuy.",
                exampleEn: "At night I talk with my brother.",
            },
            {
                id: "batfarraj",
                ar: "بَتْفَرَّج",
                en: "I watch",
                enArabeezy: "batfarraj",
                hint: "Use with TV, series, videos: بَتْفَرَّج عَلَى مُسَلْسَل.",
                exampleAr: "بِالمَسَا بَتْفَرَّج عَلَى مُسَلْسَل.",
                exampleArabeezy: "bel-masa batfarraj 3ala musalsal.",
                exampleEn: "In the evening I watch a series.",
            },
            {
                id: "baqra",
                ar: "بَقْرَا",
                en: "I read",
                enArabeezy: "baqra",
                hint: "Books, messages, articles. Useful before sleeping.",
                exampleAr: "أَحْيَانًا بَقْرَا قَبِل مَا أَنَام.",
                exampleArabeezy: "a7yanan baqra qabel ma anam.",
                exampleEn: "Sometimes I read before I sleep.",
            },
            {
                id: "banaddaf",
                ar: "بَنَضَّف",
                en: "I clean",
                enArabeezy: "banaddaf",
                hint: "House/room routine. Common chunk: بَنَضَّف البِيت / غُرْفْتِي.",
                exampleAr: "يَوم الجُمْعَة بَنَضَّف البِيت.",
                exampleArabeezy: "yom el-jum3a banaddaf el-beet.",
                exampleEn: "On Friday I clean the house.",
            },
            {
                id: "bajli",
                ar: "بَجْلِي الصُّحُون",
                en: "I wash the dishes",
                enArabeezy: "bajli el-Su7oon",
                hint: "Home routine after food. In Gaza people commonly say بَجْلِي.",
                exampleAr: "بَعْد الغَدَا بَجْلِي الصُّحُون.",
                exampleArabeezy: "ba3d el-ghada bajli el-Su7oon.",
                exampleEn: "After lunch I wash the dishes.",
            },
            {
                id: "banaam",
                ar: "بَنَام",
                en: "I sleep",
                enArabeezy: "banaam",
                hint: "End of the day. Common chunks: بَنَام بَدْرِي / بَنَام مِتْأَخِّر.",
                exampleAr: "بِاللِّيل بَنَام بَدْرِي.",
                exampleArabeezy: "bel-leel banaam badri.",
                exampleEn: "At night I sleep early.",
            },
            {
                id: "a7yanan",
                ar: "أَحْيَانًا",
                en: "sometimes",
                enArabeezy: "a7yanan",
                hint: "Frequency word. Put it before the action: أَحْيَانًا بَقْرَا.",
                exampleAr: "أَحْيَانًا بَقْرَا قَبِل مَا أَنَام.",
                exampleArabeezy: "a7yanan baqra qabel ma anam.",
                exampleEn: "Sometimes I read before I sleep.",
            },
            {
                id: "3adatan_ghaliban",
                ar: "عَادَةً / غَالِبًا",
                en: "usually / most of the time",
                enArabeezy: "3adatan / ghaliban",
                hint: "عَادَةً = usually as a habit. غَالِبًا = most of the time.",
                exampleAr: "عَادَةً بَرُوح عَالشُّغُل بَدْرِي.",
                exampleArabeezy: "3adatan baroo7 3al-shoghol badri.",
                exampleEn: "I usually go to work early.",
            },
            {
                id: "qabel_ma",
                ar: "قَبِل مَا...",
                en: "before...",
                enArabeezy: "qabel ma...",
                hint: "Use before an action: قَبِل مَا أَنْزِل / قَبِل مَا أَنَام.",
                exampleAr: "قَبِل مَا أَنْزِل بَفْطَر.",
                exampleArabeezy: "qabel ma anzel bafTar.",
                exampleEn: "Before I leave, I have breakfast.",
            },
            {
                id: "ba3d_ma",
                ar: "بَعْد مَا...",
                en: "after...",
                enArabeezy: "ba3d ma...",
                hint: "Use before an action: بَعْد مَا بَرْجَع / بَعْد مَا بَاكُل.",
                exampleAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ.",
                exampleArabeezy: "ba3d ma barja3 barta7 shway.",
                exampleEn: "After I come back, I rest a little.",
            },
            {
                id: "ba3deen",
                ar: "بَعْدِين",
                en: "then / after that",
                enArabeezy: "ba3deen",
                hint: "Use to link actions in a routine story.",
                exampleAr: "بَصْحَى، بَغَسِّل، بَعْدِين بَفْطَر.",
                exampleArabeezy: "baS7a, baghassal, ba3deen bafTar.",
                exampleEn: "I wake up, wash, then have breakfast.",
            },
        ],
    },

    dialogue: {
        title: "Real Situation - Running Late in the Morning",
        setting: "Lina sees Omar rushing before work. They talk naturally about his morning and normal routine.",
        lines: [
            { speaker: "Lina", ar: "مَرْحَبَا عُمَر، لِيش مِسْتَعْجِل هِيك؟", arArabeezy: "marhaba 3omar, leesh mista3jel heek?", en: "Hi Omar, why are you in such a hurry?" },
            { speaker: "Omar", ar: "أَهْلِين لِينَا. وَالله صِحِيت مِتْأَخِّر اليَوم.", arArabeezy: "ahleen lina. wallah Si7eet mit2akher el-yom.", en: "Hi Lina. Honestly, I woke up late today." },
            { speaker: "Lina", ar: "عَنْجَد؟ عَادَةً بِتِصْحَى بَدْرِي.", arArabeezy: "3anjad? 3adatan bitiS7a badri.", en: "Really? You usually wake up early." },
            { speaker: "Omar", ar: "آه، بَس إِمْبَارِح نِمِت مِتْأَخِّر. كُنْت بَتْفَرَّج عَلَى مُسَلْسَل.", arArabeezy: "ah, bas imbare7 nimet mit2akher. kunt batfarraj 3ala musalsal.", en: "Yes, but yesterday I slept late. I was watching a series." },
            { speaker: "Lina", ar: "طَيِّب لَحِقْت تِفْطَر؟", arArabeezy: "tayyib li7e2t tifTar?", en: "Okay, did you manage to have breakfast?" },
            { speaker: "Omar", ar: "لَا، بَس غَسَّلْت وِجْهِي وَشِرِبْت قَهْوَة بِسُرْعَة.", arArabeezy: "la, bas ghassalt wijhi w shribt ahwe bisur3a.", en: "No, I just washed my face and drank coffee quickly." },
            { speaker: "Lina", ar: "إِمِّي دَايْمًا بِتِحْكِيلِي: قَبِل مَا تِنْزَلِي، اِفْطَرِي إِشِي.", arArabeezy: "immi dayman biti7keeli: qabel ma tinzali, ifTari ishi.", en: "My mom always tells me: before you leave, eat something." },
            { speaker: "Omar", ar: "مَعْهَا حَق. أَنَا غَالِبًا بَفْطَر مَع أَهْلِي، بَس اليَوم مَا لَحِقْت.", arArabeezy: "ma3ha 7a2. ana ghaliban bafTar ma3 ahli, bas el-yom ma li7e2t.", en: "She's right. I usually have breakfast with my family, but today I didn't have time." },
            { speaker: "Lina", ar: "أَيّ سَاعَة بِبْلَش شُغْلَك؟", arArabeezy: "ay sa3a biballesh shoghlak?", en: "What time does your work start?" },
            { speaker: "Omar", ar: "السَّاعَة تَمَانْيَة، وَأَنَا هَلْقِيت لَازِم أَنْزِل.", arArabeezy: "el-sa3a tamanye, w ana halla2et lazim anzel.", en: "At eight, and I have to leave now." },
            { speaker: "Lina", ar: "بِتْرُوح عَالشُّغُل مَشِي وَلَا بِتِرْكَب بَاص؟", arArabeezy: "bitroo7 3al-shoghol mashi wala bitirkab bas?", en: "Do you go to work walking or take a bus?" },
            { speaker: "Omar", ar: "غَالِبًا بَاص، بَس اليَوم بَدِّي تَاكْسِي عَشَان مِتْأَخِّر.", arArabeezy: "ghaliban bas, bas el-yom baddi taxi 3ashan mit2akher.", en: "Usually bus, but today I want a taxi because I'm late." },
            { speaker: "Lina", ar: "بَعْد الشُّغُل بِتِرْجَع عَالبِيت دُغْرِي؟", arArabeezy: "ba3d el-shoghol bitirja3 3al-beet dughri?", en: "After work do you go straight home?" },
            { speaker: "Omar", ar: "آه، بَرْجَع بَعْد الضُّهُر وَبَاكُل الغَدَا مَع أَهْلِي.", arArabeezy: "ah, barja3 ba3d el-duhur w baakul el-ghada ma3 ahli.", en: "Yes, I come back in the afternoon and eat lunch with my family." },
            { speaker: "Lina", ar: "وَبَعْدِين؟ بَتْنَام وَلَا بَتْرْتَاح بَس؟", arArabeezy: "w ba3deen? bitnaam wala bitirta7 bas?", en: "And then? Do you sleep or just rest?" },
            { speaker: "Omar", ar: "بَرْتَاح شُوَيّ. أَحْيَانًا بَنَضَّف غُرْفْتِي، وَبَعْدِين بَدْرُس عَرَبِي.", arArabeezy: "barta7 shway. a7yanan banaddaf ghurfti, w ba3deen badros 3arabi.", en: "I rest a little. Sometimes I clean my room, then I study Arabic." },
            { speaker: "Lina", ar: "حِلْو. أَنَا بِالمَسَا بَحْكِي مَع جَارْتِي عَرَبِي شُوَيّ.", arArabeezy: "7ilu. ana bel-masa ba7ki ma3 jarti 3arabi shway.", en: "Nice. In the evening I speak a little Arabic with my neighbor." },
            { speaker: "Omar", ar: "جَارْتِك مِن غَزَّة، صَح؟", arArabeezy: "jartik min ghazza, Sa7?", en: "Your neighbor is from Gaza, right?" },
            { speaker: "Lina", ar: "آه، وَدَايْمًا بِتْصَحِّحْلِي لَمَّا أَغْلَط.", arArabeezy: "ah, w dayman bitsa77i7li lamma aghlaT.", en: "Yes, and she always corrects me when I make mistakes." },
            { speaker: "Omar", ar: "مُمْتَاز. أَنَا بِاللِّيل بَحْكِي مَع أَخُوي، بَس مِش كُلّ يَوم.", arArabeezy: "mumtaz. ana bel-leel ba7ki ma3 akhuy, bas mish kul yom.", en: "Excellent. At night I talk with my brother, but not every day." },
            { speaker: "Lina", ar: "أَخُوك بِنَام مِتْأَخِّر زَيَّك؟", arArabeezy: "akhook binaam mit2akher zayyak?", en: "Does your brother sleep late like you?" },
            { speaker: "Omar", ar: "أَكْتَر مِنِّي! خُصُوصًا يَوم الخَمِيس.", arArabeezy: "aktar minni! khuSoSan yom el-khamees.", en: "More than me! Especially on Thursday." },
            { speaker: "Lina", ar: "أَنَا الخَمِيس بَحِب أَرْتَاح، بَس أَحْيَانًا بَنَضَّف البِيت مَع إِمِّي.", arArabeezy: "ana el-khamees ba7ib arta7, bas a7yanan banaddaf el-beet ma3 immi.", en: "On Thursday I like to rest, but sometimes I clean the house with my mom." },
            { speaker: "Omar", ar: "إِحْنَا فِي رَمَضَان رُوتِينَّا كُلُّه بِتْغَيَّر.", arArabeezy: "e7na fi ramaDan routine-na kullo bitghayyar.", en: "In Ramadan our whole routine changes." },
            { speaker: "Lina", ar: "طَبِيعِي. بِتِصْحُوا مِتْأَخِّر؟", arArabeezy: "Tabi3i. bitiS7u mit2akher?", en: "Naturally. Do you all wake up late?" },
            { speaker: "Omar", ar: "أَحْيَانًا، وَبِنَام مِتْأَخِّر كَمَان.", arArabeezy: "a7yanan, w binaam mit2akher kaman.", en: "Sometimes, and we sleep late too." },
            { speaker: "Lina", ar: "يَلَّا رُوح، شَكْلَك رَح تِتْأَخَّر.", arArabeezy: "yalla roo7, shaklak ra7 tit2akhar.", en: "Go on, looks like you're going to be late." },
            { speaker: "Omar", ar: "آه وَالله. بِنْشُوفِك بَعْدِين.", arArabeezy: "ah wallah. binshoofik ba3deen.", en: "Yes, honestly. See you later." },
            { speaker: "Lina", ar: "مَع السَّلَامَة، دِير بَالَك عَلَى حَالَك.", arArabeezy: "ma3 salameh, deer balak 3ala 7alak.", en: "Goodbye, take care." },
        ],
        questions: [
            { ar: "لِيش عُمَر كَان مِسْتَعْجِل؟", en: "Why was Omar in a hurry?" },
            { ar: "عُمَر عَادَةً بِصْحَى كِيف؟", en: "How does Omar usually wake up?" },
            { ar: "لِيش عُمَر نَام مِتْأَخِّر إِمْبَارِح؟", en: "Why did Omar sleep late yesterday?" },
            { ar: "عُمَر لَحِق يِفْطَر؟", en: "Did Omar manage to have breakfast?" },
            { ar: "إِمّ لِينَا دَايْمًا بِتِحْكِيلْهَا شُو؟", en: "What does Lina's mother always tell her?" },
            { ar: "شُغْل عُمَر بِبْلَش أَيّ سَاعَة؟", en: "What time does Omar's work start?" },
            { ar: "عُمَر اليَوم بَدُّه بَاص وَلَا تَاكْسِي؟ لِيش؟", en: "Does Omar want a bus or taxi today? Why?" },
            { ar: "عُمَر بِيِرْجَع عَالبِيت إِمْتَى؟", en: "When does Omar come back home?" },
            { ar: "بَعْد مَا بِرْجَع، عُمَر بِيِعْمَل شُو؟", en: "After he comes back, what does Omar do?" },
            { ar: "لِينَا بِتْحْكِي عَرَبِي مَع مِين بِالمَسَا؟", en: "Who does Lina speak Arabic with in the evening?" },
            { ar: "أَخُو عُمَر بِنَام بَدْرِي وَلَا مِتْأَخِّر؟", en: "Does Omar's brother sleep early or late?" },
            { ar: "لِينَا بِتِعْمَل شُو يَوم الخَمِيس؟", en: "What does Lina do on Thursday?" },
            { ar: "فِي رَمَضَان رُوتِين عُمَر بِتْغَيَّر كِيف؟", en: "How does Omar's routine change in Ramadan?" },
            { ar: "اِحْكِي رُوتِين عُمَر بِخَمْس جُمَل.", en: "Tell Omar's routine in five sentences." },
            { ar: "اِحْكِي عَن رُوتِينَك إِنْت مِن الصُّبُح لِلِّيل.", en: "Talk about your routine from morning to night." },
        ],
    },

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "daily_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: I wake up",
                options: ["بَصْحَى", "بَغَسِّل", "بَفْطَر", "بَنَام"],
                correct: "بَصْحَى",
            },
            {
                id: "daily_mc2",
                type: "complete",
                prompt: "Complete: الصُّبُح ___ قَهْوَة.",
                options: ["بَشْرَب", "بَرْجَع", "بَنَام", "بَنَضَّف"],
                correct: "بَشْرَب",
            },
            {
                id: "daily_mc3",
                type: "reorder",
                prompt: "Reorder: I come back home in the afternoon.",
                options: ["بَرْجَع", "عَالبِيت", "بَعْد", "الضُّهُر"],
                correct: ["بَرْجَع", "عَالبِيت", "بَعْد", "الضُّهُر"],
            },
            {
                id: "daily_mc4",
                type: "choose",
                prompt: "Choose the natural Gaza word for early:",
                options: ["بَدْرِي", "بِاللِّيل", "بَعْدِين", "قَبِل مَا"],
                correct: "بَدْرِي",
            },
            {
                id: "daily_mc5",
                type: "complete",
                prompt: "Complete: بَصْحَى، بَغَسِّل، ___ بَفْطَر.",
                options: ["بَعْدِين", "أَحْيَانًا", "مِتْأَخِّر", "أَيّ سَاعَة"],
                correct: "بَعْدِين",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "daily_q1",
                questionAr: "«كُلّ يَوم بَصْحَى السَّاعَة سَبْعَة» مَعْنَاهَا:",
                optionsEn: ["I wake up at seven every day.", "I sleep at seven every day.", "I eat at seven every day."],
                correctIndex: 0,
            },
            {
                id: "daily_q2",
                questionAr: "«بِالمَسَا بَتْفَرَّج عَلَى مُسَلْسَل» مَعْنَاهَا:",
                optionsEn: ["In the evening I watch a series.", "In the morning I watch a series.", "At night I read a book."],
                correctIndex: 0,
            },
            {
                id: "daily_q3",
                questionAr: "كِيف بِنْسْأَل عَن الوَقْت؟",
                optionsEn: ["أَيّ سَاعَة؟", "شُو اِسْمَك؟", "مِن وِين؟"],
                correctIndex: 0,
            },
            {
                id: "daily_q4",
                questionAr: "«قَبِل مَا أَنْزِل بَفْطَر» مَعْنَاهَا:",
                optionsEn: ["Before I leave, I have breakfast.", "After I leave, I sleep.", "Before I sleep, I clean."],
                correctIndex: 0,
            },
            {
                id: "daily_q5",
                questionAr: "«بَنَام مِتْأَخِّر بِاللِّيل» مَعْنَاهَا:",
                optionsEn: ["I sleep early at night.", "I sleep late at night.", "I wake up at night."],
                correctIndex: 1,
            },
            {
                id: "daily_q6",
                questionAr: "كَمِّل: بَعْد مَا بَرْجَع، ___ شُوَيّ.",
                optionsEn: ["بَرْتَاح", "بَنْزِل", "بَصْحَى"],
                correctIndex: 0,
            },
            {
                id: "daily_q7",
                questionAr: "حَوِّل لِسُؤَال: إِنْتَ بَتْصْحَى بَدْرِي؟",
                optionsEn: ["إِنْتِ بَتْصْحِي بَدْرِي؟", "إِنْتِ بَصْحَى بَدْرِي؟", "إِنْتِ بَنَام بَدْرِي؟"],
                correctIndex: 0,
            },
            {
                id: "daily_q8",
                questionAr: "«عَادَةً» أَقْرَب مَعْنَى إِلَهَا:",
                optionsEn: ["usually", "never", "where"],
                correctIndex: 0,
            },
            {
                id: "daily_q9",
                questionAr: "إِذَا بَدِّي أَرْبُط أَفْعَال بِسِلْسِلَة، بَسْتَخْدِم:",
                optionsEn: ["بَعْدِين", "سِتِّي", "أُجْرَة"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Morning rush role-play: explain why you woke up late and what you did quickly before leaving.",
            "Ask your classmate five routine questions using أَيّ سَاعَة؟ / إِمْتَى؟ / كُلّ يَوم؟",
            "Describe your normal day in 8 sentences using الصُّبُح، بَعْد الضُّهُر، بِالمَسَا، بِاللِّيل.",
            "Family routine role-play: say what your mother/father/brother/sister does in the morning or evening.",
            "Weekend contrast: say what you usually do on Thursday or Friday and what changes.",
        ],
        translation: [
            { id: "daily_t1", type: "enToAr", textEn: "Every day I wake up early.", textAr: "كُلّ يَوم بَصْحَى بَدْرِي." },
            { id: "daily_t2", type: "arToEn", textEn: "In the morning I have breakfast with my family.", textAr: "الصُّبُح بَفْطَر مَع أَهْلِي." },
            { id: "daily_t3", type: "enToAr", textEn: "What time do you go to work?", textAr: "أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟" },
            { id: "daily_t4", type: "arToEn", textEn: "Before I leave, I drink coffee.", textAr: "قَبِل مَا أَنْزِل بَشْرَب قَهْوَة." },
            { id: "daily_t5", type: "enToAr", textEn: "I leave the house at quarter to eight.", textAr: "بَنْزِل مِن البِيت السَّاعَة تَمَانْيَة إِلَّا رُبُع." },
            { id: "daily_t6", type: "arToEn", textEn: "I come back home in the afternoon.", textAr: "بَرْجَع عَالبِيت بَعْد الضُّهُر." },
            { id: "daily_t7", type: "enToAr", textEn: "After I come back, I rest a little.", textAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ." },
            { id: "daily_t8", type: "arToEn", textEn: "Sometimes I clean my room.", textAr: "أَحْيَانًا بَنَضَّف غُرْفْتِي." },
            { id: "daily_t9", type: "enToAr", textEn: "In the evening I study Arabic.", textAr: "بِالمَسَا بَدْرُس عَرَبِي." },
            { id: "daily_t10", type: "arToEn", textEn: "At night I talk with my brother.", textAr: "بِاللِّيل بَحْكِي مَع أَخُوي." },
            { id: "daily_t11", type: "enToAr", textEn: "My brother sleeps late on Thursday.", textAr: "أَخُوي بَنَام مِتْأَخِّر يَوم الخَمِيس." },
            { id: "daily_t12", type: "arToEn", textEn: "On Friday I clean the house.", textAr: "يَوم الجُمْعَة بَنَضَّف البِيت." },
            { id: "daily_t13", type: "enToAr", textEn: "I wake up, wash, then have breakfast.", textAr: "بَصْحَى، بَغَسِّل، بَعْدِين بَفْطَر." },
            { id: "daily_t14", type: "arToEn", textEn: "Usually I go to work early.", textAr: "عَادَةً بَرُوح عَالشُّغُل بَدْرِي." },
            { id: "daily_t15", type: "enToAr", textEn: "Goodbye, see you later, take care.", textAr: "مَع السَّلَامَة، بِنْشُوفَك بَعْدِين، دِير بَالَك." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second description of your daily routine in Palestinian Arabic. Start from waking up in the morning and finish with sleeping at night. Mention: what time you wake up, what you eat or drink, where you go, when you come back, what you do in the evening, and what time you sleep. Try to use at least 8 words from the vocabulary list and at least 3 words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you today?
2. My name is Lina, and I live with my family.
3. Every day I wake up early.
4. In the morning I have breakfast with my mother.
5. My father goes to work at eight.
6. What time do you go to class?
7. Before I leave, I drink coffee.
8. I leave the house at quarter to eight.
9. In the afternoon I come back home.
10. I eat lunch with my family.
11. After I come back, I rest a little.
12. In the evening I study Arabic.
13. My sister talks with her friend at night.
14. My brother sleeps late on Thursday.
15. Goodbye, see you later, take care.`,
    },

    teacherNotes: {
        warmup: [
            "Start with Unit 1 and 2 recycling: مَرْحَبَا، كِيفَك؟ وِين سَاكِن؟ مِين سَاكِن مَعَك؟ Then ask about today.",
            "Ask whether the student is a morning person or a night person, then model: أَنَا بَصْحَى بَدْرِي / أَنَا بَنَام مِتْأَخِّر.",
            "Keep the routine as a timeline: الصُّبُح، بَعْد الضُّهُر، بِالمَسَا، بِاللِّيل.",
        ],
        vocabularySteps: [
            "Teach verbs as sentence chunks, not isolated words: بَصْحَى السَّاعَة سَبْعَة، بَفْطَر مَع أَهْلِي، بَرْجَع عَالبِيت.",
            "Teach the spoken b- pattern through repetition only; do not turn it into a grammar lecture.",
            "Recycle family words inside routine sentences so Unit 2 stays alive.",
        ],
        dialogueSteps: [
            "Read the dialogue as a real morning-rush story.",
            "Ask the student to retell Omar's routine in 4-6 sentences.",
            "Then replace Omar's routine with the student's real routine.",
        ],
        practiceTips: [
            "Require full answers: not السَّاعَة سَبْعَة only, but بَصْحَى السَّاعَة سَبْعَة.",
            "Drill masculine/feminine questions naturally: بِتِصْحَى؟ / بِتِصْحِي؟ بِتْنَام؟ / بِتْنَامِي؟",
            "If the student struggles, reduce to five core verbs: بَصْحَى، بَفْطَر، بَرُوح، بَرْجَع، بَنَام.",
        ],
        wrapup: [
            "Student says a 6-sentence routine without looking.",
            "Student asks the teacher 4 routine questions.",
            "End by connecting routine back to real life: record a voice note about tomorrow's normal day.",
        ],
        myNotes: "",
    },
};
