import { LESSON_ID_DAILY_ROUTINE } from '../../core/constants.js';

export const lessonId = LESSON_ID_DAILY_ROUTINE;

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Daily Routine",
        lessonTitle: "Unit 3 - Daily Routine & Time",
        contentVersion: 2026071401,
    },

    overview: {
        title: "Unit 3 - Daily Routine & Time",
        description:
            "Students learn to talk about a normal day in natural Gaza Palestinian Arabic: waking up, washing, eating, going out, coming back, resting, studying, cleaning, talking with family, and sleeping.",
        goals: [
            "Describe a simple daily routine from morning to night.",
            "Ask and answer simple time questions: أَيّ سَاعَة؟ / إِمْتَى؟",
            "Use everyday routine verbs in short spoken sentences.",
            "Connect daily routine with family, greetings, and basic time words from previous units.",
            "Give a 60-90 second spoken description of a normal day.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can say 8-10 sentences about their normal day.",
            "The student can ask another person about their routine.",
            "The student can explain being early, late, tired, or busy in simple Gaza Arabic.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "kul_yom",
                ar: "كُلّ يَوم",
                en: "every day",
                enArabeezy: "kul yom",
                hint: "Use with repeated actions: كُلّ يَوم بَصْحَى... / كُلّ يَوم بَرُوح...",
                exampleAr: "كُلّ يَوم بَحْكِي مَع إِمِّي.",
                exampleArabeezy: "kul yom ba7ki ma3 immi.",
                exampleEn: "Every day I talk with my mother.",
            },
            {
                id: "el_soboh",
                ar: "الصُّبُح",
                en: "in the morning",
                enArabeezy: "el-soboh",
                hint: "Morning time. Common chunks: الصُّبُح بَصْحَى / الصُّبُح بَفْطَر.",
                exampleAr: "الصُّبُح بَفْطَر مَع أَهْلِي.",
                exampleArabeezy: "el-soboh bafTar ma3 ahli.",
                exampleEn: "In the morning I have breakfast with my family.",
            },
            {
                id: "ba3d_el_duhur",
                ar: "بَعْد الضُّهُر",
                en: "in the afternoon",
                enArabeezy: "ba3d el-duhur",
                hint: "Literally after noon. Useful for coming back home, lunch, or resting.",
                exampleAr: "بَعْد الضُّهُر بَرْجَع عَالبِيت.",
                exampleArabeezy: "ba3d el-duhur barja3 3al-beet.",
                exampleEn: "In the afternoon I come back home.",
            },
            {
                id: "bel_masa",
                ar: "بِالمَسَا",
                en: "in the evening",
                enArabeezy: "bel-masa",
                hint: "Natural Gaza time word. Use it for studying, watching, visiting, or talking.",
                exampleAr: "بِالمَسَا بَدْرُس عَرَبِي.",
                exampleArabeezy: "bel-masa badros 3arabi.",
                exampleEn: "In the evening I study Arabic.",
            },
            {
                id: "bel_leel",
                ar: "بِاللِّيل",
                en: "at night",
                enArabeezy: "bel-leel",
                hint: "Night time. Common chunks: بِاللِّيل بَنَام / بِاللِّيل بَحْكِي مَع أَخُوي.",
                exampleAr: "بِاللِّيل بَنَام مِتْأَخِّر.",
                exampleArabeezy: "bel-leel banaam mit2akher.",
                exampleEn: "At night I sleep late.",
            },
            {
                id: "ay_sa3a",
                ar: "أَيّ سَاعَة؟",
                en: "what time?",
                enArabeezy: "ay sa3a?",
                hint: "Ask about schedule: أَيّ سَاعَة بِتِصْحَى؟ / أَيّ سَاعَة بِتْرُوح؟",
                exampleAr: "أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟",
                exampleArabeezy: "ay sa3a bitroo7 3al-shoghol?",
                exampleEn: "What time do you go to work?",
            },
            {
                id: "badri",
                ar: "بَدْرِي",
                en: "early",
                enArabeezy: "badri",
                hint: "Natural Gaza word. Opposite: مِتْأَخِّر. Use with waking up, sleeping, arriving.",
                exampleAr: "بَصْحَى بَدْرِي فِي أَيَّام الشُّغُل.",
                exampleArabeezy: "baS7a badri fi ayyam el-shoghol.",
                exampleEn: "I wake up early on work days.",
            },
            {
                id: "mit2akher",
                ar: "مِتْأَخِّر / مِتْأَخِّرَة",
                en: "late",
                enArabeezy: "mit2akher / mit2akhra",
                hint: "Male: مِتْأَخِّر. Female: مِتْأَخِّرَة. Use with waking, sleeping, arriving.",
                exampleAr: "اليَوم صِحِيت مِتْأَخِّر.",
                exampleArabeezy: "el-yom Si7eet mit2akher.",
                exampleEn: "Today I woke up late.",
            },
            {
                id: "baS7a",
                ar: "بَصْحَى",
                en: "I wake up",
                enArabeezy: "baS7a",
                hint: "Routine verb. Ask: أَيّ سَاعَة بِتِصْحَى؟ To a woman: بِتِصْحِي؟",
                exampleAr: "كُلّ يَوم بَصْحَى السَّاعَة سَبْعَة.",
                exampleArabeezy: "kul yom baS7a el-sa3a sab3a.",
                exampleEn: "Every day I wake up at seven.",
            },
            {
                id: "baghassal",
                ar: "بَغَسِّل",
                en: "I wash",
                enArabeezy: "baghassal",
                hint: "Daily action after waking up. Common chunk: بَغَسِّل وِجْهِي.",
                exampleAr: "أَوَّل إِشِي بَغَسِّل وِجْهِي.",
                exampleArabeezy: "awwal ishi baghassal wijhi.",
                exampleEn: "First thing, I wash my face.",
            },
            {
                id: "bat7ammam",
                ar: "بَتْحَمَّم",
                en: "I take a shower",
                enArabeezy: "bat7ammam",
                hint: "Use before going out: بَتْحَمَّم قَبِل مَا أَطْلَع.",
                exampleAr: "بَتْحَمَّم قَبِل مَا أَطْلَع.",
                exampleArabeezy: "bat7ammam qabel ma aTla3.",
                exampleEn: "I shower before I go out.",
            },
            {
                id: "bafTar",
                ar: "بَفْطَر",
                en: "I have breakfast",
                enArabeezy: "bafTar",
                hint: "Breakfast = فُطُور. Useful chunk: بَفْطَر مَع أَهْلِي.",
                exampleAr: "بَفْطَر مَع أُخْتِي الصُّبُح.",
                exampleArabeezy: "bafTar ma3 okhti el-soboh.",
                exampleEn: "I have breakfast with my sister in the morning.",
            },
            {
                id: "bashrab",
                ar: "بَشْرَب",
                en: "I drink",
                enArabeezy: "bashrab",
                hint: "Use with coffee, tea, water: بَشْرَب قَهْوَة / شَاي / مَيّ.",
                exampleAr: "الصُّبُح بَشْرَب قَهْوَة.",
                exampleArabeezy: "el-soboh bashrab ahwe.",
                exampleEn: "In the morning I drink coffee.",
            },
            {
                id: "baakul",
                ar: "بَاكُل",
                en: "I eat",
                enArabeezy: "baakul",
                hint: "General eating verb. Use with meals: بَاكُل الغَدَا / العَشَا.",
                exampleAr: "بَاكُل الغَدَا مَع أَهْلِي.",
                exampleArabeezy: "baakul el-ghada ma3 ahli.",
                exampleEn: "I eat lunch with my family.",
            },
            {
                id: "baroo7",
                ar: "بَرُوح",
                en: "I go",
                enArabeezy: "baroo7",
                hint: "Use with places: بَرُوح عَالشُّغُل / عَالدَّرْس / عَالجَامْعَة.",
                exampleAr: "بَرُوح عَالشُّغُل السَّاعَة تَمَانْيَة.",
                exampleArabeezy: "baroo7 3al-shoghol el-sa3a tamanye.",
                exampleEn: "I go to work at eight.",
            },
            {
                id: "banzel",
                ar: "بَنْزِل",
                en: "I leave / go out",
                enArabeezy: "banzel",
                hint: "Leaving home. In transport it can also mean I get off.",
                exampleAr: "بَنْزِل مِن البِيت السَّاعَة تَمَانْيَة إِلَّا رُبُع.",
                exampleArabeezy: "banzel min el-beet el-sa3a tamanye illa rubu3.",
                exampleEn: "I leave the house at quarter to eight.",
            },
            {
                id: "barja3",
                ar: "بَرْجَع",
                en: "I come back",
                enArabeezy: "barja3",
                hint: "Return home/work/class. Common chunk: بَرْجَع عَالبِيت.",
                exampleAr: "بَرْجَع عَالبِيت بَعْد الضُّهُر.",
                exampleArabeezy: "barja3 3al-beet ba3d el-duhur.",
                exampleEn: "I come back home in the afternoon.",
            },
            {
                id: "barta7",
                ar: "بَرْتَاح",
                en: "I rest",
                enArabeezy: "barta7",
                hint: "Use after work/class/cleaning: بَرْتَاح شُوَيّ.",
                exampleAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ.",
                exampleArabeezy: "ba3d ma barja3 barta7 shway.",
                exampleEn: "After I come back, I rest a little.",
            },
            {
                id: "badros",
                ar: "بَدْرُس",
                en: "I study",
                enArabeezy: "badros",
                hint: "Use with subjects/languages: بَدْرُس عَرَبِي / إِنْجْلِيزِي.",
                exampleAr: "بِالمَسَا بَدْرُس عَرَبِي.",
                exampleArabeezy: "bel-masa badros 3arabi.",
                exampleEn: "In the evening I study Arabic.",
            },
            {
                id: "bashtaghel",
                ar: "بَشْتِغِل",
                en: "I work",
                enArabeezy: "bashtaghel",
                hint: "General work verb. It will return in Unit 6 Work & Study.",
                exampleAr: "بَشْتِغِل فِي مَكْتَب.",
                exampleArabeezy: "bashtaghel fi maktab.",
                exampleEn: "I work in an office.",
            },
            {
                id: "ba7ki",
                ar: "بَحْكِي",
                en: "I talk / speak",
                enArabeezy: "ba7ki",
                hint: "Very useful for speaking goals: بَحْكِي عَرَبِي / بَحْكِي مَع أَخُوي.",
                exampleAr: "بِاللِّيل بَحْكِي مَع أَخُوي.",
                exampleArabeezy: "bel-leel ba7ki ma3 akhuy.",
                exampleEn: "At night I talk with my brother.",
            },
            {
                id: "batfarraj",
                ar: "بَتْفَرَّج",
                en: "I watch",
                enArabeezy: "batfarraj",
                hint: "Use with TV, series, videos: بَتْفَرَّج عَلَى مُسَلْسَل.",
                exampleAr: "بِالمَسَا بَتْفَرَّج عَلَى مُسَلْسَل.",
                exampleArabeezy: "bel-masa batfarraj 3ala musalsal.",
                exampleEn: "In the evening I watch a series.",
            },
            {
                id: "baqra",
                ar: "بَقْرَا",
                en: "I read",
                enArabeezy: "baqra",
                hint: "Books, messages, articles. Useful before sleeping.",
                exampleAr: "أَحْيَانًا بَقْرَا قَبِل مَا أَنَام.",
                exampleArabeezy: "a7yanan baqra qabel ma anam.",
                exampleEn: "Sometimes I read before I sleep.",
            },
            {
                id: "banaddaf",
                ar: "بَنَضَّف",
                en: "I clean",
                enArabeezy: "banaddaf",
                hint: "House/room routine. Common chunk: بَنَضَّف البِيت / غُرْفْتِي.",
                exampleAr: "يَوم الجُمْعَة بَنَضَّف البِيت.",
                exampleArabeezy: "yom el-jum3a banaddaf el-beet.",
                exampleEn: "On Friday I clean the house.",
            },
            {
                id: "bajli",
                ar: "بَجْلِي الصُّحُون",
                en: "I wash the dishes",
                enArabeezy: "bajli el-Su7oon",
                hint: "Home routine after food. In Gaza people commonly say بَجْلِي.",
                exampleAr: "بَعْد الغَدَا بَجْلِي الصُّحُون.",
                exampleArabeezy: "ba3d el-ghada bajli el-Su7oon.",
                exampleEn: "After lunch I wash the dishes.",
            },
            {
                id: "banaam",
                ar: "بَنَام",
                en: "I sleep",
                enArabeezy: "banaam",
                hint: "End of the day. Common chunks: بَنَام بَدْرِي / بَنَام مِتْأَخِّر.",
                exampleAr: "بِاللِّيل بَنَام بَدْرِي.",
                exampleArabeezy: "bel-leel banaam badri.",
                exampleEn: "At night I sleep early.",
            },
            {
                id: "a7yanan",
                ar: "أَحْيَانًا",
                en: "sometimes",
                enArabeezy: "a7yanan",
                hint: "Frequency word. Put it before the action: أَحْيَانًا بَقْرَا.",
                exampleAr: "أَحْيَانًا بَقْرَا قَبِل مَا أَنَام.",
                exampleArabeezy: "a7yanan baqra qabel ma anam.",
                exampleEn: "Sometimes I read before I sleep.",
            },
            {
                id: "3adatan_ghaliban",
                ar: "عَادَةً / غَالِبًا",
                en: "usually / most of the time",
                enArabeezy: "3adatan / ghaliban",
                hint: "عَادَةً = usually as a habit. غَالِبًا = most of the time.",
                exampleAr: "عَادَةً بَرُوح عَالشُّغُل بَدْرِي.",
                exampleArabeezy: "3adatan baroo7 3al-shoghol badri.",
                exampleEn: "I usually go to work early.",
            },
            {
                id: "qabel_ma",
                ar: "قَبِل مَا...",
                en: "before...",
                enArabeezy: "qabel ma...",
                hint: "Use before an action: قَبِل مَا أَنْزِل / قَبِل مَا أَنَام.",
                exampleAr: "قَبِل مَا أَنْزِل بَفْطَر.",
                exampleArabeezy: "qabel ma anzel bafTar.",
                exampleEn: "Before I leave, I have breakfast.",
            },
            {
                id: "ba3d_ma",
                ar: "بَعْد مَا...",
                en: "after...",
                enArabeezy: "ba3d ma...",
                hint: "Use before an action: بَعْد مَا بَرْجَع / بَعْد مَا بَاكُل.",
                exampleAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ.",
                exampleArabeezy: "ba3d ma barja3 barta7 shway.",
                exampleEn: "After I come back, I rest a little.",
            },
            {
                id: "ba3deen",
                ar: "بَعْدِين",
                en: "then / after that",
                enArabeezy: "ba3deen",
                hint: "Use to link actions in a routine story.",
                exampleAr: "بَصْحَى، بَغَسِّل، بَعْدِين بَفْطَر.",
                exampleArabeezy: "baS7a, baghassal, ba3deen bafTar.",
                exampleEn: "I wake up, wash, then have breakfast.",
            },
        ],
    },

    dialogue: {
        title: "Real Situation - Running Late in the Morning",
        setting: "Lina sees Omar rushing before work. They talk naturally about his morning and normal routine.",
        lines: [
            { speaker: "Lina", ar: "مَرْحَبَا عُمَر، لِيش مِسْتَعْجِل هِيك؟", arArabeezy: "marhaba 3omar, leesh mista3jel heek?", en: "Hi Omar, why are you in such a hurry?" },
            { speaker: "Omar", ar: "أَهْلِين لِينَا. وَالله صِحِيت مِتْأَخِّر اليَوم.", arArabeezy: "ahleen lina. wallah Si7eet mit2akher el-yom.", en: "Hi Lina. Honestly, I woke up late today." },
            { speaker: "Lina", ar: "عَنْجَد؟ عَادَةً بِتِصْحَى بَدْرِي.", arArabeezy: "3anjad? 3adatan bitiS7a badri.", en: "Really? You usually wake up early." },
            { speaker: "Omar", ar: "آه، بَس إِمْبَارِح نِمِت مِتْأَخِّر. كُنْت بَتْفَرَّج عَلَى مُسَلْسَل.", arArabeezy: "ah, bas imbare7 nimet mit2akher. kunt batfarraj 3ala musalsal.", en: "Yes, but yesterday I slept late. I was watching a series." },
            { speaker: "Lina", ar: "طَيِّب لَحِقْت تِفْطَر؟", arArabeezy: "tayyib li7e2t tifTar?", en: "Okay, did you manage to have breakfast?" },
            { speaker: "Omar", ar: "لَا، بَس غَسَّلْت وِجْهِي وَشِرِبْت قَهْوَة بِسُرْعَة.", arArabeezy: "la, bas ghassalt wijhi w shribt ahwe bisur3a.", en: "No, I just washed my face and drank coffee quickly." },
            { speaker: "Lina", ar: "إِمِّي دَايْمًا بِتِحْكِيلِي: قَبِل مَا تِنْزَلِي، اِفْطَرِي إِشِي.", arArabeezy: "immi dayman biti7keeli: qabel ma tinzali, ifTari ishi.", en: "My mom always tells me: before you leave, eat something." },
            { speaker: "Omar", ar: "مَعْهَا حَق. أَنَا غَالِبًا بَفْطَر مَع أَهْلِي، بَس اليَوم مَا لَحِقْت.", arArabeezy: "ma3ha 7a2. ana ghaliban bafTar ma3 ahli, bas el-yom ma li7e2t.", en: "She's right. I usually have breakfast with my family, but today I didn't have time." },
            { speaker: "Lina", ar: "أَيّ سَاعَة بِبْلَش شُغْلَك؟", arArabeezy: "ay sa3a biballesh shoghlak?", en: "What time does your work start?" },
            { speaker: "Omar", ar: "السَّاعَة تَمَانْيَة، وَأَنَا هَلْقِيت لَازِم أَنْزِل.", arArabeezy: "el-sa3a tamanye, w ana halla2et lazim anzel.", en: "At eight, and I have to leave now." },
            { speaker: "Lina", ar: "بِتْرُوح عَالشُّغُل مَشِي وَلَا بِتِرْكَب بَاص؟", arArabeezy: "bitroo7 3al-shoghol mashi wala bitirkab bas?", en: "Do you go to work walking or take a bus?" },
            { speaker: "Omar", ar: "غَالِبًا بَاص، بَس اليَوم بَدِّي تَاكْسِي عَشَان مِتْأَخِّر.", arArabeezy: "ghaliban bas, bas el-yom baddi taxi 3ashan mit2akher.", en: "Usually bus, but today I want a taxi because I'm late." },
            { speaker: "Lina", ar: "بَعْد الشُّغُل بِتِرْجَع عَالبِيت دُغْرِي؟", arArabeezy: "ba3d el-shoghol bitirja3 3al-beet dughri?", en: "After work do you go straight home?" },
            { speaker: "Omar", ar: "آه، بَرْجَع بَعْد الضُّهُر وَبَاكُل الغَدَا مَع أَهْلِي.", arArabeezy: "ah, barja3 ba3d el-duhur w baakul el-ghada ma3 ahli.", en: "Yes, I come back in the afternoon and eat lunch with my family." },
            { speaker: "Lina", ar: "وَبَعْدِين؟ بَتْنَام وَلَا بَتْرْتَاح بَس؟", arArabeezy: "w ba3deen? bitnaam wala bitirta7 bas?", en: "And then? Do you sleep or just rest?" },
            { speaker: "Omar", ar: "بَرْتَاح شُوَيّ. أَحْيَانًا بَنَضَّف غُرْفْتِي، وَبَعْدِين بَدْرُس عَرَبِي.", arArabeezy: "barta7 shway. a7yanan banaddaf ghurfti, w ba3deen badros 3arabi.", en: "I rest a little. Sometimes I clean my room, then I study Arabic." },
            { speaker: "Lina", ar: "حِلْو. أَنَا بِالمَسَا بَحْكِي مَع جَارْتِي عَرَبِي شُوَيّ.", arArabeezy: "7ilu. ana bel-masa ba7ki ma3 jarti 3arabi shway.", en: "Nice. In the evening I speak a little Arabic with my neighbor." },
            { speaker: "Omar", ar: "جَارْتِك مِن غَزَّة، صَح؟", arArabeezy: "jartik min ghazza, Sa7?", en: "Your neighbor is from Gaza, right?" },
            { speaker: "Lina", ar: "آه، وَدَايْمًا بِتْصَحِّحْلِي لَمَّا أَغْلَط.", arArabeezy: "ah, w dayman bitsa77i7li lamma aghlaT.", en: "Yes, and she always corrects me when I make mistakes." },
            { speaker: "Omar", ar: "مُمْتَاز. أَنَا بِاللِّيل بَحْكِي مَع أَخُوي، بَس مِش كُلّ يَوم.", arArabeezy: "mumtaz. ana bel-leel ba7ki ma3 akhuy, bas mish kul yom.", en: "Excellent. At night I talk with my brother, but not every day." },
            { speaker: "Lina", ar: "أَخُوك بِنَام مِتْأَخِّر زَيَّك؟", arArabeezy: "akhook binaam mit2akher zayyak?", en: "Does your brother sleep late like you?" },
            { speaker: "Omar", ar: "أَكْتَر مِنِّي! خُصُوصًا يَوم الخَمِيس.", arArabeezy: "aktar minni! khuSoSan yom el-khamees.", en: "More than me! Especially on Thursday." },
            { speaker: "Lina", ar: "أَنَا الخَمِيس بَحِب أَرْتَاح، بَس أَحْيَانًا بَنَضَّف البِيت مَع إِمِّي.", arArabeezy: "ana el-khamees ba7ib arta7, bas a7yanan banaddaf el-beet ma3 immi.", en: "On Thursday I like to rest, but sometimes I clean the house with my mom." },
            { speaker: "Omar", ar: "إِحْنَا فِي رَمَضَان رُوتِينَّا كُلُّه بِتْغَيَّر.", arArabeezy: "e7na fi ramaDan routine-na kullo bitghayyar.", en: "In Ramadan our whole routine changes." },
            { speaker: "Lina", ar: "طَبِيعِي. بِتِصْحُوا مِتْأَخِّر؟", arArabeezy: "Tabi3i. bitiS7u mit2akher?", en: "Naturally. Do you all wake up late?" },
            { speaker: "Omar", ar: "أَحْيَانًا، وَبِنَام مِتْأَخِّر كَمَان.", arArabeezy: "a7yanan, w binaam mit2akher kaman.", en: "Sometimes, and we sleep late too." },
            { speaker: "Lina", ar: "يَلَّا رُوح، شَكْلَك رَح تِتْأَخَّر.", arArabeezy: "yalla roo7, shaklak ra7 tit2akhar.", en: "Go on, looks like you're going to be late." },
            { speaker: "Omar", ar: "آه وَالله. بِنْشُوفِك بَعْدِين.", arArabeezy: "ah wallah. binshoofik ba3deen.", en: "Yes, honestly. See you later." },
            { speaker: "Lina", ar: "مَع السَّلَامَة، دِير بَالَك عَلَى حَالَك.", arArabeezy: "ma3 salameh, deer balak 3ala 7alak.", en: "Goodbye, take care." },
        ],
        questions: [
            { ar: "لِيش عُمَر كَان مِسْتَعْجِل؟", en: "Why was Omar in a hurry?" },
            { ar: "عُمَر عَادَةً بِصْحَى كِيف؟", en: "How does Omar usually wake up?" },
            { ar: "لِيش عُمَر نَام مِتْأَخِّر إِمْبَارِح؟", en: "Why did Omar sleep late yesterday?" },
            { ar: "عُمَر لَحِق يِفْطَر؟", en: "Did Omar manage to have breakfast?" },
            { ar: "إِمّ لِينَا دَايْمًا بِتِحْكِيلْهَا شُو؟", en: "What does Lina's mother always tell her?" },
            { ar: "شُغْل عُمَر بِبْلَش أَيّ سَاعَة؟", en: "What time does Omar's work start?" },
            { ar: "عُمَر اليَوم بَدُّه بَاص وَلَا تَاكْسِي؟ لِيش؟", en: "Does Omar want a bus or taxi today? Why?" },
            { ar: "عُمَر بِيِرْجَع عَالبِيت إِمْتَى؟", en: "When does Omar come back home?" },
            { ar: "بَعْد مَا بِرْجَع، عُمَر بِيِعْمَل شُو؟", en: "After he comes back, what does Omar do?" },
            { ar: "لِينَا بِتْحْكِي عَرَبِي مَع مِين بِالمَسَا؟", en: "Who does Lina speak Arabic with in the evening?" },
            { ar: "أَخُو عُمَر بِنَام بَدْرِي وَلَا مِتْأَخِّر؟", en: "Does Omar's brother sleep early or late?" },
            { ar: "لِينَا بِتِعْمَل شُو يَوم الخَمِيس؟", en: "What does Lina do on Thursday?" },
            { ar: "فِي رَمَضَان رُوتِين عُمَر بِتْغَيَّر كِيف؟", en: "How does Omar's routine change in Ramadan?" },
            { ar: "اِحْكِي رُوتِين عُمَر بِخَمْس جُمَل.", en: "Tell Omar's routine in five sentences." },
            { ar: "اِحْكِي عَن رُوتِينَك إِنْت مِن الصُّبُح لِلِّيل.", en: "Talk about your routine from morning to night." },
        ],
    },

    grammar: [
        {
            title: "1. The everyday present with بـ",
            short: "بَصْحَى، بَرُوح، بَدْرُس، بَنَام",
            description: "For habits, routines, and things that normally happen, Gaza Palestinian Arabic usually places بَـ / بِـ at the beginning of the present verb. This is not a separate word meaning ‘am’. It is part of the spoken present form. The same verb changes at the beginning—and sometimes at the end—according to the person.",
            table: {
                title: "Present routine: رَاح / يْرُوح → to go",
                headers: ["Person", "Palestinian form", "Arabizi", "Example meaning"],
                rows: [
                    ["أَنَا", "بَرُوح", "baroo7", "I go / I usually go"],
                    ["إِنْتَ", "بِتْرُوح", "bitroo7", "you go (man)"],
                    ["إِنْتِ", "بِتْرُوحِي", "bitroo7i", "you go (woman)"],
                    ["هُوَّ", "بِرُوح", "biroo7", "he goes"],
                    ["هِيَّ", "بِتْرُوح", "bitroo7", "she goes"],
                    ["إِحْنَا", "بِنْرُوح", "binroo7", "we go"],
                    ["إِنْتُو", "بِتْرُوحُوا", "bitroo7u", "you all go"],
                    ["هُمَّ", "بِرُوحُوا", "biroo7u", "they go"],
                ],
            },
            examples: [
                { ar: "أَنَا كُلّ يَوم بَرُوح عَالشُّغُل.", arabeezy: "ana kul yom baroo7 3ash-shughul.", en: "I go to work every day." },
                { ar: "إِنْتِ أَيّ سَاعَة بِتْرُوحِي عَالجَامْعَة؟", arabeezy: "inti ay sa3a bitroo7i 3al-jam3a?", en: "What time do you go to university? (to a woman)" },
                { ar: "هُمَّ بِرُوحُوا مَع بَعْض وَبِرْجَعُوا بَكِّير.", arabeezy: "humme biro7u ma3 ba3D w birja3u bakkeer.", en: "They go together and come back early." },
            ],
            commonMistakes: [
                "Do not use one unchanged verb after every pronoun. Compare أَنَا بَرُوح, إِحْنَا بِنْرُوح, and هُمَّ بِرُوحُوا.",
                "The forms إِنْتَ بِتْرُوح and هِيَّ بِتْرُوح sound identical; the pronoun or context tells us who is meant.",
                "The vowel inside the verb is not always predictable. Learn a verb with useful forms and audio, not only as an abstract root.",
            ],
            exercises: [
                { prompt: "Complete: إِحْنَا كُلّ يَوم ___ عَالجَامْعَة. (we go)", options: ["بِنْرُوح", "بَرُوح", "بِرُوحُوا"], correct: "بِنْرُوح", explanation: "The first-person plural present commonly begins with بِنـ: إِحْنَا بِنْرُوح." },
                { prompt: "Choose: ‘She goes to work early.’", options: ["هِيَّ بِتْرُوح عَالشُّغُل بَكِّير.", "هِيَّ بَرُوح عَالشُّغُل بَكِّير.", "هِيَّ بِتْرُوحِي عَالشُّغُل بَكِّير."], correct: "هِيَّ بِتْرُوح عَالشُّغُل بَكِّير.", explanation: "Third-person feminine singular uses بِتْـ without the final ـي." },
                { prompt: "Which form addresses a group: ‘you all go’?", options: ["بِتْرُوحُوا", "بِرُوحُوا", "بِنْرُوح"], correct: "بِتْرُوحُوا", explanation: "إِنْتُو takes بِتْـ and the plural ending ـُوا." },
            ],
        },
        {
            title: "2. Negating a routine with مَا",
            short: "مَا بَفْطَر — مَا بِتْأَخَّرُوا — مَا بَنَام بَكِّير",
            description: "To negate an action in the everyday present, put مَا directly before the conjugated verb. Keep the person marking on the verb. مِش is normally used to negate descriptions, identities, and some planned or participle-like expressions; this unit’s routine actions use مَا as the safe core pattern.",
            table: {
                title: "Affirmative and negative routine",
                headers: ["Affirmative", "Negative", "Meaning"],
                rows: [
                    ["بَفْطَر", "مَا بَفْطَر", "I eat / do not eat breakfast"],
                    ["بِتْشْرَبِي قَهْوَة", "مَا بِتْشْرَبِي قَهْوَة", "you (f.) drink / do not drink coffee"],
                    ["بِنَام بَكِّير", "مَا بَنَام بَكِّير", "he sleeps / does not sleep early"],
                    ["بِتْأَخَّرُوا", "مَا بِتْأَخَّرُوا", "they are / are not late"],
                ],
            },
            examples: [
                { ar: "أَنَا مَا بَشْرَب قَهْوَة بِاللِّيل.", arabeezy: "ana ma bashrab qahweh bil-leil.", en: "I don’t drink coffee at night." },
                { ar: "هِيَّ مَا بِتْرُوح عَالشُّغُل يَوم الجُمْعَة.", arabeezy: "hiyyeh ma bitroo7 3ash-shughul yom el-jum3a.", en: "She doesn’t go to work on Friday." },
                { ar: "إِحْنَا مَا بِنْتْأَخَّر عَن الدَّرْس.", arabeezy: "i7na ma bnit2akhkhar 3an ed-dars.", en: "We aren’t late for class." },
            ],
            commonMistakes: [
                "Do not remove بـ after مَا: say مَا بَرُوح, not مَا رُوح for a habitual present statement.",
                "Do not use لَا as the default spoken negator for a personal routine. لَا appears in commands and fixed expressions; مَا is the core here.",
                "Some Palestinian speakers add final ـش for emphasis or regional style. This course first stabilises the widely understood مَا + present verb pattern.",
            ],
            exercises: [
                { prompt: "Make بَنَام بَكِّير negative.", options: ["مَا بَنَام بَكِّير.", "لَا بَنَام بَكِّير.", "مَا نَام بَكِّير."], correct: "مَا بَنَام بَكِّير.", explanation: "Place مَا before the complete present form بَنَام." },
                { prompt: "Choose: ‘They do not study at night.’", options: ["هُمَّ مَا بِدْرُسُوا بِاللِّيل.", "هُمَّ مِش بِدْرُس بِاللِّيل.", "هُمَّ لَا دَرَسُوا بِاللِّيل."], correct: "هُمَّ مَا بِدْرُسُوا بِاللِّيل.", explanation: "The plural present remains بِدْرُسُوا after مَا." },
                { prompt: "What is wrong with مَا رُوح عَالشُّغُل كُلّ يَوم?", options: ["The present verb is missing its بـ/person form.", "مَا can never negate a verb.", "عَ means the past."], correct: "The present verb is missing its بـ/person form.", explanation: "For ‘I don’t go’, use مَا بَرُوح." },
            ],
        },
        {
            title: "3. Asking and telling the time naturally",
            short: "أَيّ سَاعَة؟ — السَّاعَة سَبْعَة — عَالسَّبْعَة",
            description: "Palestinian Arabic commonly asks أَيّ سَاعَة؟ for a clock time and إِمْتَى؟ for a broader ‘when?’. Exact clock answers often use السَّاعَة + number. عَالسَّبْعَة means ‘around/at seven’ inside a plan or routine and can feel less like reading a clock.",
            table: {
                title: "Useful clock-time chunks",
                headers: ["Arabic", "Arabizi", "Natural meaning", "Usage"],
                rows: [
                    ["أَيّ سَاعَة؟", "ay sa3a?", "what time?", "asks for clock time"],
                    ["إِمْتَى؟", "eimta?", "when?", "asks for a day, period, or time"],
                    ["السَّاعَة سَبْعَة", "es-sa3a sab3a", "at seven / it is seven", "exact answer"],
                    ["عَالسَّبْعَة", "3as-sab3a", "at/around seven", "inside a routine or arrangement"],
                    ["سَبْعَة وَنُصّ", "sab3a w noSS", "seven thirty", "half past seven"],
                    ["سَبْعَة وَرُبُع", "sab3a w rubu3", "seven fifteen", "quarter past seven"],
                    ["تَمَانْيَة إِلَّا رُبُع", "tamanye illa rubu3", "quarter to eight", "7:45"],
                ],
            },
            examples: [
                { ar: "أَيّ سَاعَة بِتْصْحَى؟ — السَّاعَة سِتَّة وَنُصّ.", arabeezy: "ay sa3a bitS7a? — es-sa3a sitteh w noSS.", en: "What time do you wake up? — At six thirty." },
                { ar: "إِمْتَى بِتْرُوح عَالجَامْعَة؟ — بَعْد الفَطُور.", arabeezy: "eimta bitroo7 3al-jam3a? — ba3d el-faToor.", en: "When do you go to university? — After breakfast." },
                { ar: "عَادَةً بَرْجَع عَالبِيت عَالخَمْسَة.", arabeezy: "3adatan barja3 3al-beit 3al-khamseh.", en: "I usually return home at five." },
            ],
            commonMistakes: [
                "Do not translate English ‘at’ mechanically in every answer. السَّاعَة سَبْعَة is already a complete natural time answer.",
                "أَيّ سَاعَة requests a clock time; إِمْتَى allows answers like بُكْرَة, بَعْد الفَطُور, or يَوم الجُمْعَة.",
                "For 7:30, Palestinian speech says سَبْعَة وَنُصّ, not a literal ‘seven and thirty’." ,
            ],
            exercises: [
                { prompt: "You need an exact clock time. Which question is most precise?", options: ["أَيّ سَاعَة؟", "مِن وِين؟", "قَدِّيش مَرَّة؟"], correct: "أَيّ سَاعَة؟", explanation: "أَيّ سَاعَة asks specifically for the time on the clock." },
                { prompt: "Choose 7:30.", options: ["سَبْعَة وَنُصّ", "سَبْعَة إِلَّا نُصّ", "تَمَانْيَة وَرُبُع"], correct: "سَبْعَة وَنُصّ", explanation: "وَنُصّ means ‘and a half’: half past seven." },
                { prompt: "Which is a natural answer to إِمْتَى بِتْدْرُس؟", options: ["بَعْد العَشَا.", "السَّاعَة قَدِّيش؟", "مِن غَزَّة."], correct: "بَعْد العَشَا.", explanation: "إِمْتَى can be answered with a broad time phrase such as ‘after dinner’." },
            ],
        },
        {
            title: "4. Frequency words: how often a routine happens",
            short: "دَايْمًا، عَادَةً، غَالِبًا، أَحْيَانًا، نَادِرًا",
            description: "Frequency words let the student describe a real routine rather than a rigid list. They can appear before the verb or at the start of the sentence. Palestinian speakers also use chunks such as كُلّ يَوم, مَرَّتَيْن بِالأُسْبُوع, and مِن وَقْت لِوَقْت.",
            table: {
                title: "A practical frequency scale",
                headers: ["Expression", "Arabizi", "Approximate meaning", "Example chunk"],
                rows: [
                    ["دَايْمًا", "dayman", "always", "دَايْمًا بَفْطَر"],
                    ["عَادَةً", "3adatan", "usually", "عَادَةً بَصْحَى بَكِّير"],
                    ["غَالِبًا", "ghaliban", "most of the time", "غَالِبًا بَرُوح مَاشِي"],
                    ["أَحْيَانًا", "a7yanan", "sometimes", "أَحْيَانًا بَتْأَخَّر"],
                    ["نَادِرًا", "nadiran", "rarely", "نَادِرًا بَشْرَب قَهْوَة"],
                    ["وَلَا مَرَّة", "wala marra", "never / not once", "وَلَا مَرَّة بِتْأَخَّر"],
                ],
            },
            examples: [
                { ar: "عَادَةً بَفْطَر مَع أَهْلِي، بَس أَحْيَانًا مَا بَلْحَق.", arabeezy: "3adatan bafTar ma3 ahli, bas a7yanan ma bal7aq.", en: "I usually eat breakfast with my family, but sometimes I don’t have time." },
                { ar: "هِيَّ غَالِبًا بِتْدْرُس بِالمَسَا.", arabeezy: "hiyyeh ghaliban bitdros bil-masa.", en: "She studies in the evening most of the time." },
                { ar: "مَرَّتَيْن بِالأُسْبُوع بَنَضِّف البِيت.", arabeezy: "marratein bil-usboo3 banaDDif el-beit.", en: "I clean the house twice a week." },
            ],
            commonMistakes: [
                "دَايْمًا is a strong claim. If the routine has exceptions, عَادَةً or غَالِبًا is often more accurate.",
                "A frequency word does not replace person conjugation: هِيَّ أَحْيَانًا بِتْدْرُس, not هِيَّ أَحْيَانًا دَرَس.",
                "وَلَا مَرَّة is already negative in meaning, but spoken sentence patterns vary. Learn complete chunks from real examples.",
            ],
            exercises: [
                { prompt: "Choose the best word for a habit that happens on most days but not every day.", options: ["عَادَةً", "وَلَا مَرَّة", "دَايْمًا"], correct: "عَادَةً", explanation: "عَادَةً means ‘usually’ and allows exceptions." },
                { prompt: "Complete: ___ بَقْرَا قَبْل مَا أَنَام، مِش كُلّ يَوم. (sometimes)", options: ["أَحْيَانًا", "دَايْمًا", "وَلَا مَرَّة"], correct: "أَحْيَانًا", explanation: "أَحْيَانًا matches an action that happens sometimes, not daily." },
                { prompt: "Which phrase means ‘twice a week’?", options: ["مَرَّتَيْن بِالأُسْبُوع", "مَرَّة كُلّ يَوم", "أُسْبُوعَيْن"], correct: "مَرَّتَيْن بِالأُسْبُوع", explanation: "مَرَّتَيْن means twice; بِالأُسْبُوع means per week." },
            ],
        },
        {
            title: "5. Connecting the day with قَبْل مَا and بَعْد مَا",
            short: "قَبْل مَا أَطْلَع — بَعْد مَا أَرْجَع",
            description: "A natural routine is connected, not a list of isolated sentences. Use قَبْل مَا + verb for ‘before doing’ and بَعْد مَا + verb for ‘after doing’. The verb after مَا still agrees with the person. When the following item is a noun, مَا is not needed: بَعْد الفَطُور.",
            table: {
                title: "Verb connection versus noun time phrase",
                headers: ["Structure", "Example", "Meaning"],
                rows: [
                    ["قَبْل مَا + verb", "قَبْل مَا أَطْلَع", "before I leave"],
                    ["بَعْد مَا + verb", "بَعْد مَا أَرْجَع", "after I return"],
                    ["قَبْل + noun", "قَبْل الشُّغُل", "before work"],
                    ["بَعْد + noun", "بَعْد الفَطُور", "after breakfast"],
                ],
            },
            examples: [
                { ar: "قَبْل مَا أَطْلَع مِن البِيت، بَشْرَب قَهْوَة.", arabeezy: "qabel ma aTla3 min el-beit, bashrab qahweh.", en: "Before I leave home, I drink coffee." },
                { ar: "بَعْد مَا بِرْجَع مِن الشُّغُل، بِرْتَاح شُوَيّ.", arabeezy: "ba3d ma birja3 min esh-shughul, birta7 shway.", en: "After he returns from work, he rests a little." },
                { ar: "بَعْد العَشَا بَحْكِي مَع عِيلْتِي.", arabeezy: "ba3d el-3asha ba7ki ma3 3eelti.", en: "After dinner, I talk with my family." },
            ],
            commonMistakes: [
                "Use مَا before a following verb: بَعْد مَا أَرْجَع. Do not insert it before a noun: بَعْد الفَطُور.",
                "Conjugate the connected verb for its real subject: بَعْد مَا بِرْجَع (he), بَعْد مَا بِرْجَعُوا (they).",
                "Do not copy English word order mechanically. Learn قَبْل مَا and بَعْد مَا as spoken connectors.",
            ],
            exercises: [
                { prompt: "Choose: ‘after I return’.", options: ["بَعْد مَا أَرْجَع", "بَعْد أَنَا رَجَع", "بَعْد مِن أَرْجَع"], correct: "بَعْد مَا أَرْجَع", explanation: "The natural connector before a verb is بَعْد مَا." },
                { prompt: "Complete: ___ الفَطُور بَرُوح عَالشُّغُل. (after breakfast)", options: ["بَعْد", "بَعْد مَا", "قَبْل مَا"], correct: "بَعْد", explanation: "الفَطُور is a noun, so use بَعْد without مَا." },
                { prompt: "Choose the correct form for ‘before they sleep’.", options: ["قَبْل مَا يِنَامُوا", "قَبْل مَا يِنَام", "قَبْل هُمَّ نَام"], correct: "قَبْل مَا يِنَامُوا", explanation: "The verb after قَبْل مَا agrees with the plural subject through ـُوا." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "daily_mc1",
                type: "match",
                prompt: "Match the English phrase to Arabic: every day",
                options: ["كُلّ يَوم", "الصُّبُح", "بِالمَسَا", "بِاللِّيل"],
                correct: "كُلّ يَوم",
            },
            {
                id: "daily_mc2",
                type: "complete",
                prompt: "Complete: الصُّبُح ___ بَدْرِي.",
                options: ["بَصْحَى", "بَغَسِّل", "بَدْرِي", "مِتْأَخِّر"],
                correct: "بَصْحَى",
            },
            {
                id: "daily_mc3",
                type: "reorder",
                prompt: "Reorder: I go to work.",
                options: ["بَرُوح", "عَالشُّغُل"],
                correct: ["بَرُوح", "عَالشُّغُل"],
            },
            {
                id: "daily_mc4",
                type: "choose",
                prompt: "Choose the natural Gaza word for early:",
                options: ["بَدْرِي", "بِاللِّيل", "بَعْدِين", "قَبِل مَا"],
                correct: "بَدْرِي",
            },
            {
                id: "daily_mc5",
                type: "complete",
                prompt: "Complete: بِاللِّيل ___ كِتَاب.",
                options: ["بَقْرَا", "بَجْلِي", "بَنَضَّف", "بَتْفَرَّج"],
                correct: "بَقْرَا",
            },
            {
                id: "daily_mc6",
                type: "complete",
                prompt: "Complete: ___ بَرُوح عَالشُّغُل بَدْرِي.",
                options: ["عَادَةً", "قَبِل مَا", "بَعْد مَا", "بِاللِّيل"],
                correct: "عَادَةً",
            },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        showCompleteDialogue: false,
        quiz: [
            {
                id: "daily_q1",
                questionAr: "Choose the English meaning of كُلّ يَوم بَصْحَى السَّاعَة سَبْعَة.",
                optionsEn: ["I wake up at seven every day.", "I sleep at seven every day.", "I eat at seven every day."],
                correctIndex: 0,
            },
            {
                id: "daily_q2",
                questionAr: "Choose the English meaning of بِالمَسَا بَتْفَرَّج عَلَى مُسَلْسَل.",
                optionsEn: ["In the evening I watch a series.", "In the morning I watch a series.", "At night I read a book."],
                correctIndex: 0,
            },
            {
                id: "daily_q3",
                questionAr: "Choose the Palestinian Arabic question for: What time?",
                optionsEn: ["أَيّ سَاعَة؟", "شُو اِسْمَك؟", "مِن وِين؟"],
                correctIndex: 0,
            },
            {
                id: "daily_q4",
                questionAr: "Choose the English meaning of قَبِل مَا أَنْزِل بَفْطَر.",
                optionsEn: ["Before I leave, I have breakfast.", "After I leave, I sleep.", "Before I sleep, I clean."],
                correctIndex: 0,
            },
            {
                id: "daily_q5",
                questionAr: "Choose the English meaning of بَنَام مِتْأَخِّر بِاللِّيل.",
                optionsEn: ["I sleep early at night.", "I sleep late at night.", "I wake up at night."],
                correctIndex: 1,
            },
            {
                id: "daily_q6",
                questionAr: "كَمِّل: بَعْد مَا بَرْجَع، ___ شُوَيّ.",
                optionsEn: ["بَرْتَاح", "بَنْزِل", "بَصْحَى"],
                correctIndex: 0,
            },
            {
                id: "daily_q7",
                questionAr: "حَوِّل لِسُؤَال: إِنْتَ بَتْصْحَى بَدْرِي؟",
                optionsEn: ["إِنْتِ بَتْصْحِي بَدْرِي؟", "إِنْتِ بَصْحَى بَدْرِي؟", "إِنْتِ بَنَام بَدْرِي؟"],
                correctIndex: 0,
            },
            {
                id: "daily_q8",
                questionAr: "«عَادَةً» أَقْرَب مَعْنَى إِلَهَا:",
                optionsEn: ["usually", "never", "where"],
                correctIndex: 0,
            },
            {
                id: "daily_q9",
                questionAr: "إِذَا بَدِّي أَرْبُط أَفْعَال بِسِلْسِلَة، بَسْتَخْدِم:",
                optionsEn: ["بَعْدِين", "سِتِّي", "أُجْرَة"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Ask your classmate about a normal day. Use أَيّ سَاعَة؟ (ay sa3a?), إِمْتَى؟ (eemta?), and بَعْدِين؟ (ba3deen?). Then switch roles.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "بَصْحَى", arabeezy: "baS7a", en: "I wake up" },
                    { ar: "بَفْطَر", arabeezy: "baftar", en: "I have breakfast" },
                    { ar: "بَرُوح", arabeezy: "baroo7", en: "I go" },
                    { ar: "بَرْجَع", arabeezy: "barja3", en: "I return" },
                    { ar: "بَنَام", arabeezy: "banam", en: "I sleep" },
                    { ar: "بَعْدِين", arabeezy: "ba3deen", en: "then / after that" },
                ],
                multipleChoice: [
                    { prompt: "Unit 2 review: Choose the meaning of عِنْدِي أَخ (3indi akh).", options: ["I have a brother.", "I visit my brother.", "I am a brother."], correct: "I have a brother." },
                    { prompt: "Choose the meaning of كُلّ يَوم بَصْحَى بَدْرِي (kul yom baS7a badri).", options: ["Every day I wake up early.", "Yesterday I woke up late.", "Every day I sleep early."], correct: "Every day I wake up early." },
                ],
            },
            {
                title: "B - Guided practice",
                fillInTheBlank: [
                    { prompt: "Write the correct form of (wake up): أَنَا ___ بَدْرِي.", arabeezy: "ana ___ badri.", answer: "بَصْحَى" },
                    { prompt: "Write the correct form of (have breakfast): الصُّبُح ___ مَع أَهْلِي.", arabeezy: "eS-Subu7 ___ ma3 ahli.", answer: "بَفْطَر" },
                    { prompt: "Write the correct form of (go): كُلّ يَوم ___ عَالشُّغُل.", arabeezy: "kul yom ___ 3ash-shughul.", answer: "بَرُوح" },
                    { prompt: "Write the correct form of (return): بَعْد الشُّغُل ___ عَالبِيت.", arabeezy: "ba3d esh-shughul ___ 3al-beit.", answer: "بَرْجَع" },
                    { prompt: "Write the correct form of (sleep): بِاللِّيل ___ مِتْأَخِّر.", arabeezy: "bil-leil ___ mit2akhkher.", answer: "بَنَام" },
                    { prompt: "Write the Palestinian Arabic for (what time): ___ سَاعَة بِتْرُوح؟", arabeezy: "___ sa3a btirroo7?", answer: "أَيّ" },
                    { prompt: "Write the Palestinian Arabic for (then): بَصْحَى، ___ بَفْطَر.", arabeezy: "baS7a, ___ baftar.", answer: "بَعْدِين" },
                    { prompt: "Write the Palestinian Arabic for (usually): ___ بَرُوح بَدْرِي.", arabeezy: "___ baroo7 badri.", answer: "عَادَةً" },
                    { prompt: "Write the Palestinian Arabic for (in the evening): ___ بَدْرُس عَرَبِي.", arabeezy: "___ badrus 3arabi.", answer: "بِالمَسَا" },
                    { prompt: "Write the Palestinian Arabic for (at night): ___ بَقْرَا كِتَاب.", arabeezy: "___ baqra kitab.", answer: "بِاللِّيل" },
                    { prompt: "Unit 2 review — write (with): بَفْطَر ___ إِمِّي.", arabeezy: "baftar ___ immi.", answer: "مَع" },
                    { prompt: "Unit 1 review — write (where): ___ بِتْرُوح الصُّبُح؟", arabeezy: "___ btirroo7 eS-Subu7?", answer: "وِين" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the sentence: أَنَا بِتْصْحَى بَدْرِي.", arabeezy: "ana btiS7a badri.", answer: "أَنَا بَصْحَى بَدْرِي." },
                    { prompt: "Correct the sentence: إِنْتِ بِتْصْحَى السَّاعَة سَبْعَة.", arabeezy: "inti btiS7a es-sa3a sab3a.", answer: "إِنْتِ بِتْصْحِي السَّاعَة سَبْعَة." },
                    { prompt: "Correct the sentence: بَعْد مَا بَرْجَع، بَنَام الصُّبُح.", arabeezy: "ba3d ma barja3, banam eS-Subu7.", answer: "بَعْد مَا بَرْجَع، بَرْتَاح شُوَيّ." },
                    { prompt: "Unit 2 review — correct it: هِيَّ سَاكِن مَع أَهْلْهَا.", arabeezy: "hiyyeh saken ma3 ahlha.", answer: "هِيَّ سَاكْنَة مَع أَهْلْهَا." },
                    { prompt: "Use the feminine verb form. Correct: إِنْتِ بِتْرُوح عَالجَامْعَة.", arabeezy: "inti btirroo7 3al-jam3a.", answer: "إِنْتِ بِتْرُوحِي عَالجَامْعَة." },
                    { prompt: "Use the correct time expression. Correct: بِاللِّيل بَصْحَى مِن النَّوم.", arabeezy: "bil-leil baS7a min en-nom.", answer: "الصُّبُح بَصْحَى مِن النَّوم." },
                ],
                reorderSentences: [
                    { prompt: "Build: Every day I wake up early.", arabeezy: "kul yom baS7a badri.", words: ["كُلّ يَوم", "بَصْحَى", "بَدْرِي."], answer: "كُلّ يَوم بَصْحَى بَدْرِي." },
                    { prompt: "Build: After I return, I rest a little.", arabeezy: "ba3d ma barja3, barta7 shway.", words: ["بَعْد مَا بَرْجَع", "بَرْتَاح", "شُوَيّ."], answer: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ." },
                    { prompt: "Build the question: What time do you sleep?", arabeezy: "ay sa3a btnam?", words: ["أَيّ سَاعَة", "بِتْنَام؟"], answer: "أَيّ سَاعَة بِتْنَام؟" },
                    { prompt: "Review loop — build: I have a brother and a sister.", arabeezy: "3indi akh w ukht.", words: ["عِنْدِي", "أَخ", "وَأُخْت."], answer: "عِنْدِي أَخ وَأُخْت." },
                    { prompt: "Put the words in order: In the evening I study Arabic.", arabeezy: "bil-masa badrus 3arabi.", words: ["عَرَبِي.", "بِالمَسَا", "بَدْرُس"], answer: "بِالمَسَا بَدْرُس عَرَبِي." },
                    { prompt: "Put the words in order: Usually I go to work early.", arabeezy: "3adatan baroo7 3ash-shughul badri.", words: ["بَدْرِي.", "عَالشُّغُل", "عَادَةً", "بَرُوح"], answer: "عَادَةً بَرُوح عَالشُّغُل بَدْرِي." },
                ],
            },
        ],
        translation: [
            { id: "daily_t1", type: "enToAr", textEn: "Every day I wake up early.", textAr: "كُلّ يَوم بَصْحَى بَدْرِي." },
            { id: "daily_t2", type: "arToEn", textEn: "In the morning I have breakfast with my family.", textAr: "الصُّبُح بَفْطَر مَع أَهْلِي." },
            { id: "daily_t3", type: "enToAr", textEn: "What time do you go to work?", textAr: "أَيّ سَاعَة بِتْرُوح عَالشُّغُل؟" },
            { id: "daily_t4", type: "arToEn", textEn: "Before I leave, I drink coffee.", textAr: "قَبِل مَا أَنْزِل بَشْرَب قَهْوَة." },
            { id: "daily_t5", type: "enToAr", textEn: "I leave the house at quarter to eight.", textAr: "بَنْزِل مِن البِيت السَّاعَة تَمَانْيَة إِلَّا رُبُع." },
            { id: "daily_t6", type: "arToEn", textEn: "I come back home in the afternoon.", textAr: "بَرْجَع عَالبِيت بَعْد الضُّهُر." },
            { id: "daily_t7", type: "enToAr", textEn: "After I come back, I rest a little.", textAr: "بَعْد مَا بَرْجَع بَرْتَاح شُوَيّ." },
            { id: "daily_t8", type: "arToEn", textEn: "Sometimes I clean my room.", textAr: "أَحْيَانًا بَنَضَّف غُرْفْتِي." },
            { id: "daily_t9", type: "enToAr", textEn: "In the evening I study Arabic.", textAr: "بِالمَسَا بَدْرُس عَرَبِي." },
            { id: "daily_t10", type: "arToEn", textEn: "At night I talk with my brother.", textAr: "بِاللِّيل بَحْكِي مَع أَخُوي." },
            { id: "daily_t11", type: "enToAr", textEn: "My brother sleeps late on Thursday.", textAr: "أَخُوي بَنَام مِتْأَخِّر يَوم الخَمِيس." },
            { id: "daily_t12", type: "arToEn", textEn: "On Friday I clean the house.", textAr: "يَوم الجُمْعَة بَنَضَّف البِيت." },
            { id: "daily_t13", type: "enToAr", textEn: "I wake up, wash, then have breakfast.", textAr: "بَصْحَى، بَغَسِّل، بَعْدِين بَفْطَر." },
            { id: "daily_t14", type: "arToEn", textEn: "Usually I go to work early.", textAr: "عَادَةً بَرُوح عَالشُّغُل بَدْرِي." },
            { id: "daily_t15", type: "enToAr", textEn: "Goodbye, see you later, take care.", textAr: "مَع السَّلَامَة، بِنْشُوفَك بَعْدِين، دِير بَالَك." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second description of your daily routine in Palestinian Arabic. Start from waking up in the morning and finish with sleeping at night. Mention: what time you wake up, what you eat or drink, where you go, when you come back, what you do in the evening, and what time you sleep. Try to use at least 8 words from the vocabulary list and at least 3 words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you today?
2. My name is Lina, and I live with my family.
3. Every day I wake up early.
4. In the morning I have breakfast with my mother.
5. My father goes to work at eight.
6. What time do you go to class?
7. Before I leave, I drink coffee.
8. I leave the house at quarter to eight.
9. In the afternoon I come back home.
10. I eat lunch with my family.
11. After I come back, I rest a little.
12. In the evening I study Arabic.
13. My sister talks with her friend at night.
14. My brother sleeps late on Thursday.
15. Goodbye, see you later, take care.`,
    },

    teacherNotes: {
        warmup: [
            "Start with Unit 1 and 2 recycling: مَرْحَبَا، كِيفَك؟ وِين سَاكِن؟ مِين سَاكِن مَعَك؟ Then ask about today.",
            "Ask whether the student is a morning person or a night person, then model: أَنَا بَصْحَى بَدْرِي / أَنَا بَنَام مِتْأَخِّر.",
            "Keep the routine as a timeline: الصُّبُح، بَعْد الضُّهُر، بِالمَسَا، بِاللِّيل.",
        ],
        vocabularySteps: [
            "Teach verbs as sentence chunks, not isolated words: بَصْحَى السَّاعَة سَبْعَة، بَفْطَر مَع أَهْلِي، بَرْجَع عَالبِيت.",
            "Teach the spoken b- pattern through repetition only; do not turn it into a grammar lecture.",
            "Recycle family words inside routine sentences so Unit 2 stays alive.",
        ],
        dialogueSteps: [
            "Read the dialogue as a real morning-rush story.",
            "Ask the student to retell Omar's routine in 4-6 sentences.",
            "Then replace Omar's routine with the student's real routine.",
        ],
        practiceTips: [
            "Require full answers: not السَّاعَة سَبْعَة only, but بَصْحَى السَّاعَة سَبْعَة.",
            "Drill masculine/feminine questions naturally: بِتِصْحَى؟ / بِتِصْحِي؟ بِتْنَام؟ / بِتْنَامِي؟",
            "If the student struggles, reduce to five core verbs: بَصْحَى، بَفْطَر، بَرُوح، بَرْجَع، بَنَام.",
        ],
        wrapup: [
            "Student says a 6-sentence routine without looking.",
            "Student asks the teacher 4 routine questions.",
            "End by connecting routine back to real life: record a voice note about tomorrow's normal day.",
        ],
        myNotes: "",
    },
};
