import { LESSON_ID_FAMILY } from '../../core/constants.js';

export const lessonId = LESSON_ID_FAMILY;

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Family",
        lessonTitle: "Unit 2 - Family & People (Gaza Palestinian Arabic)",
        contentVersion: 2026062802,
    },

    overview: {
        title: "Unit 2 - Family & People",
        description:
            "Students learn to talk about family in natural Gaza Palestinian Arabic: who is in the family, who lives at home, brothers and sisters, older/younger relatives, marital status, and close relatives.",
        goals: [
            "Talk about close family members using natural Gaza words.",
            "Use عِنْدِي / مَا عِنْدِي to say who they have in their family.",
            "Ask and answer about brothers, sisters, relatives, and who lives at home.",
            "Use older/younger/same-age comparisons in simple sentences.",
            "Recycle greetings from Unit 1 inside a family conversation.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can describe their family in 60 seconds.",
            "The student can ask someone how many brothers and sisters they have.",
            "The student can say who is older, younger, married, single, or engaged.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "3eileh",
                ar: "عِيلَة",
                en: "family",
                enArabeezy: "3eileh",
                hint: "My family = عِيلْتِي. Also common: أَهْلِي = my family / my parents.",
                exampleAr: "عِيلْتِي صْغِيرَة، بَس قَرِيبِين مِن بَعْض.",
                exampleArabeezy: "3eelti zghireh, bas qareebeen min ba3d.",
                exampleEn: "My family is small, but we are close to each other.",
            },
            {
                id: "ahli",
                ar: "أَهْلِي",
                en: "my family / my parents",
                enArabeezy: "ahli",
                hint: "Usually means my parents/family. With you: أَهْلَك / أَهْلِك. With her: أَهْلْهَا.",
                exampleAr: "أَنَا سَاكْنَة مَع أَهْلِي.",
                exampleArabeezy: "ana sakneh ma3 ahli.",
                exampleEn: "I live with my family.",
            },
            {
                id: "abuy",
                ar: "أَبُوي",
                en: "my father",
                enArabeezy: "abuy",
                hint: "His father = أَبُوه. Her father = أَبُوهَا. Parents = أَبُوي وَإِمِّي / أَهْلِي.",
                exampleAr: "أَبُوي بِيِشْتِغِل الصُّبُح.",
                exampleArabeezy: "abuy biyishtighel el-soboh.",
                exampleEn: "My father works in the morning.",
            },
            {
                id: "immi",
                ar: "إِمِّي",
                en: "my mother",
                enArabeezy: "immi",
                hint: "His mother = إِمُّه. Her mother = إِمَّهَا. Calling mom: يَمَّا.",
                exampleAr: "إِمِّي فِي البِيت اليَوم.",
                exampleArabeezy: "immi fi el-beet el-yom.",
                exampleEn: "My mother is at home today.",
            },
           {
                id: "akhuy",
                ar: "أَخُوي",
                en: "my brother",
                enArabeezy: "akhuy",
                hint: "Brother = أخ (akh). My brother = أَخُوي (akhuy). Two brothers = أَخَوَيْن (akhween). Brothers/siblings = إِخْوَة / إِخْوَان. (ikhwan).",
                exampleAr: "أَخُوي أَكْبَر مِنِّي بِتَلَات سِنِين.",
                exampleArabeezy: "akhuy akbar minni bi-talat sineen.",
                exampleEn: "My brother is three years older than me.",
            },
           {
                id: "okhti",
                ar: "أُخْتِي",
                en: "my sister",
                enArabeezy: "okhti",
                hint: "Sister = أخت. My sister = أختي. Two sisters = أختين. Natural Gaza plural: خَوَات.",
                exampleAr: "أُخْتِي أَصْغَر مِنِّي.",
                exampleArabeezy: "okhti asghar minni.",
                exampleEn: "My sister is younger than me.",
            },
            {
                id: "ikhwan",
                ar: "إِخْوَان / إِخْوَة",
                en: "siblings / brothers",
                enArabeezy: "ikhwan",
                hint: "In daily speech it can mean brothers, or siblings in general. Use context.",
                exampleAr: "كم أخ وإخت عندك؟ عندي تلات إخوان.",
                exampleArabeezy: "kam akh w okht 3indak? 3indi talat ikhwan.",
                exampleEn: "How many brothers and sisters do you have? I have three siblings.",
            },
            {
                id: "tawam",
                ar: "تَوْأَم",
                en: "twin",
                enArabeezy: "taw2am",
                hint: "My twin = تَوْأَمِي. Twins = تَوْأَمِين. Useful when talking about siblings or cousins.",
                exampleAr: "أَنَا وَتَوْأَمِي بِنَفْس العُمُر.",
                exampleArabeezy: "ana w taw2ami bnafs el-3omor.",
                exampleEn: "My twin and I are the same age.",
            },
           
            
            {
                id: "sidi",
                ar: "سِيدِي",
                en: "my grandfather",
                enArabeezy: "sidi",
                hint: "Very common affectionate word. Grandparents = سِيدِي وَسِتِّي. His grandfather = سِيدُه. Her grandfather = سِيدْهَا.",
                 exampleAr: "سيدي ساكن قريب منا.",
                exampleArabeezy: "sidi saken qareeb minna.",
                exampleEn: "My grandfather lives near us.",
            },
            {
                id: "sitti",
                ar: "سِتِّي",
                en: "my grandmother",
                enArabeezy: "sitti",
                hint: "Very common affectionate word. Grandparents = سِيدِي وَسِتِّي. Her grandmother = سِتَّهَا.",
               exampleAr: "بروح عند ستي كل يوم جمعة.",
                exampleArabeezy: "Baru7 3ind sitti kil yōm jom3a.",
                exampleEn: "I go to my grandmother's every Friday..",
            },
            {
                id: "3amm",
                ar: "عَمّ",
                en: "paternal uncle",
                enArabeezy: "3amm",
                hint: "Father's brother. My uncle = عَمِّي. Dual: عَمَّيْن. Plural: عْمَام.",
                exampleAr: "عَمِّي سَاكِن بَرَّا البَلَد.",
                exampleArabeezy: "3ammi saken barra el-balad.",
                exampleEn: "My paternal uncle lives abroad.",
            },
            {
                id: "3ammeh",
                ar: "عَمَّة",
                en: "paternal aunt",
                enArabeezy: "3ammeh",
                hint: "Father's sister. My aunt = عَمْتِي. Dual: عَمْتِين. Plural: عَمَّات.",
                exampleAr: "عَمْتِي بِتِيجِي عِنْد سِتِّي كُلّ جُمْعَة.",
                exampleArabeezy: "3amti biteeji 3ind sitti kul jum3a.",
                exampleEn: "My aunt comes to my grandmother's every Friday.",
            },
            {
                id: "khal",
                ar: "خَال",
                en: "maternal uncle",
                enArabeezy: "khal",
                hint: "Mother's brother. My uncle = خَالِي. Dual: خَالَيْن. Plural: أَخْوَال.",
                exampleAr: "خَالِي عِنْدُه اِبِن قَدِّي.",
                exampleArabeezy: "khali 3indo ibin qaddi.",
                exampleEn: "My maternal uncle has a son my age.",
            },
            {
                id: "khaleh",
                ar: "خَالَة",
                en: "maternal aunt",
                enArabeezy: "khaleh",
                hint: "Mother's sister. My aunt = خَالْتِي. Dual: خَالْتِين. Plural: خَالَات.",
                exampleAr: "خَالْتِي زَيّ إِمِّي تَقْرِيبًا.",
                exampleArabeezy: "khalti zay immi taqreeban.",
                exampleEn: "My aunt is almost like my mother.",
            },
             {
                id: "ibin",
                ar: "اِبِن",
                en: "son",
                enArabeezy: "ibin",
                hint: "Dual: وَلَدِين / اِبْنِين. Plural: وِلَاد. His son = اِبْنُه. Her son = اِبْنْهَا.",
                exampleAr: "خالتي عندها ابن بالجامعة.",
                exampleArabeezy: "khalti 3indha ibin bil jam3a.",
                exampleEn: "My aunt has a son at university.",
            },
            {
                id: "bint",
                ar: "بِنْت",
                en: "daughter / girl",
                enArabeezy: "bint",
                hint: "Dual: بِنْتِين. Plural: بَنَات. His daughter = بِنْتُه. Her daughter = بِنْتْهَا. Also used for girl.",
                exampleAr: "خَالْتِي عِنْدْهَا بِنْت صْغِيرَة.",
                exampleArabeezy: "khalti 3indha bint zghireh.",
                exampleEn: "My aunt has a young daughter.",
            },
             {
                id: "wlad",
                ar: "ولاد",
                en: "children / kids",
                enArabeezy: "wlad",
                hint: "Very common spoken word for children or kids. More natural than أطفال in daily speech.",
                exampleAr: "الولاد بيلعبوا برا.",
                exampleArabeezy: "el-wlad biyil3abu barra.",
                exampleEn: "The kids are playing outside.",
            },
            {
                id: "qarayeb",
                ar: "قَرَايِب",
                en: "relatives",
                enArabeezy: "qarayeb",
                hint: "General word for relatives. Singular: قَرِيب / قَرِيبَة.",
                exampleAr: "عِنْدِنَا قَرَايِب فِي غَزَّة وَبَرَّا البَلَد.",
                exampleArabeezy: "3indina qarayeb fi ghazza w barra el-balad.",
                exampleEn: "We have relatives in Gaza and abroad.",
            },
            {
                id: "sho_bi2rablek",
                ar: "شُو بِيِقْرَبْلَك؟",
                en: "How is he related to you?",
                enArabeezy: "sho biy2rablek?",
                hint: "To a woman: شُو بِيِقْرَبْلِك؟ Answer: بِيِقْرَبْلِي خَال / عَمّ / اِبِن خَالِي.",
                exampleAr: "هَاد شُو بِيِقْرَبْلَك؟ - هَاد اِبِن خَالِي.",
                exampleArabeezy: "had sho biy2rablek? - had ibin khali.",
                exampleEn: "How is he related to you? - He is my cousin.",
            },
            {
                id: "akbar",
                ar: "أَكْبَر",
                en: "older",
                enArabeezy: "akbar",
                hint: "Use with مِن: أَكْبَر مِنِّي = older than me.",
                exampleAr: "أَخُوي أَكْبَر مِنِّي.",
                exampleArabeezy: "akhuy akbar minni.",
                exampleEn: "My brother is older than me.",
            },
            {
                id: "asghar",
                ar: "أَصْغَر",
                en: "younger",
                enArabeezy: "asghar",
                hint: "Use with مِن: أَصْغَر مِنِّي = younger than me.",
                exampleAr: "أُخْتِي أَصْغَر مِنِّي.",
                exampleArabeezy: "okhti asghar minni.",
                exampleEn: "My sister is younger than me.",
            },
            {
                id: "qaddi",
                ar: "قَدِّي",
                en: "same age as me",
                enArabeezy: "qaddi",
                hint: "Same age as him = قَدُّه. Same age as her = قَدَّهَا.",
                exampleAr: "اِبِن خَالِي قَدِّي.",
                exampleArabeezy: "ibin khali qaddi.",
                exampleEn: "My cousin is the same age as me.",
            },
            {
                id: "mitjawwez",
                ar: "مِتْجَوِّز / مِتْجَوِّزَة",
                en: "married",
                enArabeezy: "mitjawwez / mitjawwzeh",
                hint: "Male: مِتْجَوِّز. Female: مِتْجَوِّزَة. Plural: مِتْجَوِّزِين.",
               exampleAr: "أخوي متجوز وعنده ولد.",
                exampleArabeezy: "akhuy mitjawwez w 3indo walad.",
                exampleEn: "My brother is married and has a son.",
            },
            {
                id: "a3zabi",
                ar: "عزابي / عزابية",
                en: "single / not married",
                enArabeezy: "3azabi / 3azabeyeh",
                hint: "Spoken way to say not married. Male: عزابي. Female: عزابية.",
                exampleAr: "أختي عزابية ولسه بتدرس.",
                exampleArabeezy: "okhti 3azabeyeh w lissa bitidros.",
                exampleEn: "My sister is single and still studies.",
            },
                {
                id: "joz_mara",
                ar: "جوز / مرة",
                en: "husband / wife",
                enArabeezy: "joz / mara",
                hint: "Natural spoken words. جوزي = my husband. مرتي = my wife.",
                exampleAr: "مرتي من غزة.",
                exampleArabeezy: "marti min ghazzeh.",
                exampleEn: "My wife is from Gaza.",
            },
            {id: "7amay_7amati",
                ar: "حماي / حماتي",
                en: "father-in-law / mother-in-law",
                enArabeezy: "7amay / 7amati",
                hint: "Spouse's parents. حماي (7amay) = my father-in-law. حماتي (7amati) = my mother-in-law. In-laws = حمايل / أهل الجوز أو أهل المرة depending on context.",
                exampleAr: "حماتي ساكنة قريب منا.",
                exampleArabeezy: "7amati sakneh qareeb minna.",
                exampleEn: "My mother-in-law lives near us.",},
            {
                id: "3indi",
                ar: "عِنْدِي...",
                en: "I have...",
                enArabeezy: "3indi...",
                hint: "Main structure: عِنْدِي أَخ، عِنْدِي أُخْتِين، عِنْدِي خَوَات.",
                exampleAr: "عِنْدِي أَخ وَخَوَات.",
                exampleArabeezy: "3indi akh w khawat.",
                exampleEn: "I have a brother and sisters.",
            },
            {
                id: "ma_3indi",
                ar: "مَا عِنْدِي",
                en: "I do not have",
                enArabeezy: "ma 3indi",
                hint: "Negative form of عِنْدِي.",
                exampleAr: "مَا عِنْدِي خَوَات، بَس عِنْدِي أَخ.",
                exampleArabeezy: "ma 3indi khawat, bas 3indi akh.",
                exampleEn: "I do not have sisters, but I have a brother.",
            },
            {
                id: "saken_ma3",
                ar: "سَاكِن مَع...",
                en: "living with...",
                enArabeezy: "saken ma3...",
                hint: "Male: سَاكِن. Female: سَاكْنَة. Plural: سَاكْنِين.",
                exampleAr: "أَنَا سَاكْنَة مَع أَهْلِي.",
                exampleArabeezy: "ana sakneh ma3 ahli.",
                exampleEn: "I live with my family.",
            },
            {
                id: "masha_allah",
                ar: "مَا شَاء الله",
                en: "God has willed / used to show admiration",
                enArabeezy: "masha allah",
                hint: "Very natural reaction when someone talks about family, children, or good news. Use it lightly: مَا شَاء الله، عِيلْتَك حِلْوَة.",
                exampleAr: "مَا شَاء الله، عِنْدَك خَوَات كْتِير.",
                exampleArabeezy: "masha allah, 3indak khawat kteer.",
                exampleEn: "Mashallah, you have many sisters.",
            },
            {
                id: "allah_ykhaleelak",
                ar: "الله يْخَلِّيلَك",
                en: "May God keep them for you",
                enArabeezy: "allah ykhaleelak",
                hint: "Warm Gaza family expression. To a woman: الله يْخَلِّيلِك. For mother: الله يْخَلِّيلِك إِيَّاهَا. Reply: آمِين.",
                exampleAr: "إِمِّي كْتِير طَيِّبَة. ـ الله يْخَلِّيلِك إِيَّاهَا.",
                exampleArabeezy: "immi kteer Tayyibeh. - allah ykhaleelik iyyaha.",
                exampleEn: "My mother is very kind. - May God keep her for you.",
            },
        ],
    },

    dialogue: {
        title: "Real Situation - Talking About Family After Class",
        setting: "Two classmates talk after Arabic class. They already know each other from Unit 1 and now talk naturally about family.",
        lines: [
           { speaker: "Samer", ar: "مرحبا ليلى، كيفك؟ شو هالصورة الحلوة؟", arArabeezy: "mar7aba layla, keefik? shoo hal-soora el-7ilweh?", en: "Hi Layla, how are you? What's this nice picture?" },
            { speaker: "Layla", ar: "أهلين سامر. هاي صورة من يوم الجمعة عند ستي.", arArabeezy: "ahleen samer. hay soora min yom el-jom3a 3ind sitti.", en: "Hi Samer. This is a picture from Friday at my grandmother's place." },
            { speaker: "Samer", ar: "ما شاء الله، مبين العيلة كلها كانت هناك.", arArabeezy: "ma sha allah, mbayyen el-3eileh kullha kanat hnak.", en: "Wow, it looks like the whole family was there." },
            { speaker: "Layla", ar: "تقريبًا آه. إمي، أبوي، إخوتي، وخالتي كمان.", arArabeezy: "taqreeban ah. immi, abuy, ikhwt-i, w khalti kaman.", en: "Almost, yes. My mother, my father, my siblings, and my aunt too." },
            { speaker: "Samer", ar: "هاد اللي جنب أبوك بقربلك؟", arArabeezy: "had elli janb abook biqarrablak?", en: "Is the one next to your father related to you?" },
            { speaker: "Layla", ar: "آه، هاد عمي. ساكن قريب منا وبزورنا كتير.", arArabeezy: "ah, had 3ammi. saken qareeb minna w bizoorna kteer.", en: "Yes, that's my uncle. He lives near us and visits us a lot." },
            { speaker: "Samer", ar: "حلو. وإنتِ ساكنة مع أهلك لسه؟", arArabeezy: "7ilu. w inti sakneh ma3 ahlik lissa?", en: "Nice. And do you still live with your family?" },
            { speaker: "Layla", ar: "آه، أنا ساكنة مع أهلي: إمي، أبوي، أختي الصغيرة، وأخوي.", arArabeezy: "ah, ana sakneh ma3 ahli: immi, abuy, okhti el-zgheereh, w akhuy.", en: "Yes, I live with my family: my mother, father, younger sister, and brother." },
            { speaker: "Samer", ar: "أختك هاي اللي لابسة أزرق؟", arArabeezy: "okhtik hay elli labseh azra2?", en: "Is your sister the one wearing blue?" },
            { speaker: "Layla", ar: "آه، هاي أختي. هي أصغر مني وبتدرس بالجامعة.", arArabeezy: "ah, hay okhti. hiyye asghar minni w bitidros bil jam3a.", en: "Yes, that's my sister. She's younger than me and studies at university." },
            { speaker: "Samer", ar: "وأخوك وين بالصورة؟", arArabeezy: "w akhook ween bil-soora?", en: "And where is your brother in the picture?" },
            { speaker: "Layla", ar: "شايف اللي ماسك البنت الصغيرة؟ هاد أخوي الكبير.", arArabeezy: "shayef elli masik el-bint el-zgheereh? had akhuy el-kbeer.", en: "See the one holding the little girl? That's my older brother." },
            { speaker: "Samer", ar: "آه شفته. هو متجوز؟", arArabeezy: "ah shufto. howwa mitjawwez?", en: "Yes, I see him. Is he married?" },
            { speaker: "Layla", ar: "آه، متجوز وعنده بنت وحدة. بنته دايمًا بتضحك.", arArabeezy: "ah, mitjawwez w 3indo bint wa7deh. binto dayman bitid7ak.", en: "Yes, he's married and has one daughter. His daughter always laughs." },
            { speaker: "Samer", ar: "الله يخليها. عيلتك شكلها قريبة من بعض.", arArabeezy: "allah ykhalliha. 3eiltik shakilha qareebeh min ba3d.", en: "May God protect her. Your family seems close to each other." },
            { speaker: "Layla", ar: "آه الحمد لله. كل جمعة تقريبًا بنجتمع عند ستي.", arArabeezy: "ah el-7amdullah. kul jom3a taqreeban bnjitmi3 3ind sitti.", en: "Yes, thankfully. Almost every Friday we gather at my grandmother's place." },
            { speaker: "Samer", ar: "وسيدك موجود بالصورة؟", arArabeezy: "w sidik mawjood bil-soora?", en: "And is your grandfather in the picture?" },
            { speaker: "Layla", ar: "لا، سيدي ساكن مع خالتي وما قدر ييجي هالمرة.", arArabeezy: "la, sidi saken ma3 khalti w ma qider yeeji hal-marra.", en: "No, my grandfather lives with my aunt and couldn't come this time." },
            { speaker: "Samer", ar: "الله يعطيه الصحة. أنا كمان ستي ساكنة قريب منا.", arArabeezy: "allah yi3Teeh el-Se77a. ana kaman sitti sakneh qareeb minna.", en: "May God give him health. My grandmother also lives near us." },
            { speaker: "Layla", ar: "عنجد؟ بتزوروها كتير؟", arArabeezy: "3anjad? bitzooroha kteer?", en: "Really? Do you visit her often?" },
            { speaker: "Samer", ar: "آه، غالبًا يوم الجمعة. بروح أنا وأخوي.", arArabeezy: "ah, ghaliban yom el-jom3a. baroo7 ana w akhuy.", en: "Yes, usually on Friday. My brother and I go." },
            { speaker: "Layla", ar: "ما عندك خوات، صح؟", arArabeezy: "ma 3indak khawat, sa7?", en: "You don't have sisters, right?" },
            { speaker: "Samer", ar: "صح، ما عندي خوات. عندي أخ واحد بس، أصغر مني.", arArabeezy: "sa7, ma 3indi khawat. 3indi akh wa7ad bas, asghar minni.", en: "Right, I don't have sisters. I only have one brother, younger than me." },
            { speaker: "Layla", ar: "بس أكيد البيت أهدى من بيتنا.", arArabeezy: "bas akeed el-beet ahda min beetna.", en: "But your house is surely quieter than ours." },
            { speaker: "Samer", ar: "مش دايمًا. أخوي بعمل صوت لحاله.", arArabeezy: "mish dayman. akhuy bi3mil Soot la7alo.", en: "Not always. My brother makes noise by himself." },
            { speaker: "Layla", ar: "هههه، نفس أختي الصغيرة.", arArabeezy: "haha, nafs okhti el-zgheereh.", en: "Haha, same as my younger sister." },
                    { speaker: "Samer", ar: "الجيران عندكم كمان بيجوا عند ستك؟", arArabeezy: "el-jeeran 3indkom kaman biyiju 3ind sittik?", en: "Do your neighbors also come to your grandmother's home?" },
            { speaker: "Layla", ar: "آه، جيران ستي زي العيلة. دايمًا بيسألوا عنها.", arArabeezy: "ah, jeeran sitti zay el-3eileh. dayman bis2alu 3anha.", en: "Yes, my grandmother's neighbors are like family. They always ask about her." },
            { speaker: "Samer", ar: "حلو كتير. هيك الواحد بحس حاله مش لحاله.", arArabeezy: "7ilu kteer. heek el-wa7ad bi7is 7alo mish la7alo.", en: "That's really nice. This way a person feels they are not alone." },
            { speaker: "Layla", ar: "صح. يلا المرة الجاية بفرجيك صورة أوضح.", arArabeezy: "sa7. yalla el-marra el-jayeh bafarjeek soora awDa7.", en: "True. Next time I'll show you a clearer picture." },
            { speaker: "Samer", ar: "تمام، يسلمو. ديري بالك على حالك.", arArabeezy: "tamam, yeslamo. deeri balik 3ala 7alik.", en: "Great, thanks. Take care." },
             { speaker: "Layla", ar: "مع السلامة، بنشوفك بعدين.", arArabeezy: "ma3 el-salameh, binshoofak ba3dain.", en: "Goodbye, see you later." },
        ],
        questions: [
              { ar: "شو كان سامر وليلى بيشوفوا؟", en: "What were Samer and Layla looking at?" },
            { ar: "الصورة كانت من أي يوم؟", en: "Which day was the picture from?" },
            { ar: "مين كان موجود بالصورة من عيلة ليلى؟", en: "Who from Layla's family was in the picture?" },
            { ar: "مين الشخص اللي جنب أبو ليلى؟", en: "Who is the person next to Layla's father?" },
            { ar: "ليلى ساكنة مع مين؟", en: "Who does Layla live with?" },
            { ar: "مين أخت ليلى في الصورة؟", en: "Which one is Layla's sister in the picture?" },
            { ar: "أخ ليلى متجوز ولا أعزب؟", en: "Is Layla's brother married or single?" },
            { ar: "كل جمعة وين بتجتمع عيلة ليلى؟", en: "Where does Layla's family gather every Friday?" },
            { ar: "ليش سيد ليلى مش موجود بالصورة؟", en: "Why isn't Layla's grandfather in the picture?" },
            { ar: "سامر عنده خوات؟", en: "Does Samer have sisters?" },
            { ar: "أخ سامر أكبر ولا أصغر منه؟", en: "Is Samer's brother older or younger than him?" },
            { ar: "شو قالت ليلى عن جيران ستي؟", en: "What did Layla say about her grandmother's neighbors?" },
            { ar: "احكي عن عيلة ليلى بخمس جمل.", en: "Talk about Layla's family in five sentences." },
            { ar: "احكي عن عيلتك إنت: مين ساكن معك؟ عندك إخوة؟", en: "Talk about your family: who lives with you? Do you have siblings?" },  ],
    },

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "family_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: family",
                options: ["عِيلَة", "أَبُوي", "خَال", "قَدِّي"],
                correct: "عِيلَة",
            },
            {
                id: "family_mc2",
                type: "complete",
                prompt: "Complete: عِنْدِي أَخ وَ___.",
                options: ["خَوَات", "سَاكِن", "قَدِّي", "مَع"],
                correct: "خَوَات",
            },
            {
                id: "family_mc3",
                type: "choose",
                prompt: "Choose the Gaza-style plural for sisters:",
                options: ["خَوَات", "إِخْوَة", "أَخُوي", "وِلَاد"],
                correct: "خَوَات",
            },
            {
                id: "family_mc4",
                type: "reorder",
                prompt: "Reorder: My brother is older than me.",
                options: ["أَخُوي", "أَكْبَر", "مِنِّي"],
                correct: ["أَخُوي", "أَكْبَر", "مِنِّي"],
            },
            {
                id: "family_mc5",
                type: "complete",
                prompt: "Complete: أَنَا سَاكْنَة ___ أَهْلِي.",
                options: ["مَع", "مِن", "وِين", "قَدِّي"],
                correct: "مَع",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "family_q1",
                questionAr: "«عِنْدِي أَخ وَخَوَات» مَعْنَاهَا:",
                optionsEn: ["I have a brother and sisters.", "I have a father and mother.", "I live with my family."],
                correctIndex: 0,
            },
            {
                id: "family_q2",
                questionAr: "«أَخُوي أَكْبَر مِنِّي» مَعْنَاهَا:",
                optionsEn: ["My brother is older than me.", "My brother is younger than me.", "My brother is my age."],
                correctIndex: 0,
            },
            {
                id: "family_q3",
                questionAr: "«اِبِن خَالِي قَدِّي» مَعْنَاهَا:",
                optionsEn: ["My cousin is my age.", "My uncle is old.", "My son is young."],
                correctIndex: 0,
            },
            {
                id: "family_q4",
                questionAr: "كِيف بِنْقُول: I do not have sisters؟",
                optionsEn: ["مَا عِنْدِي خَوَات.", "أَنَا سَاكِن مَع أَهْلِي.", "أُخْتِي أَصْغَر مِنِّي."],
                correctIndex: 0,
            },
            {
                id: "family_q5",
                questionAr: "«هَاد شُو بِيِقْرَبْلَك؟» مَعْنَاهَا:",
                optionsEn: ["How is he related to you?", "Where does he live?", "Is he older than you?"],
                correctIndex: 0,
            },
            {
                id: "family_q6",
                questionAr: "كَمِّل: أَنَا سَاكْنَة ___ أَهْلِي.",
                optionsEn: ["مَع", "مِن", "قَدِّي"],
                correctIndex: 0,
            },
            {
                id: "family_q7",
                questionAr: "حَوِّل لِلْمُؤَنَّث: أَخُوي مِتْجَوِّز.",
                optionsEn: ["أُخْتِي مِتْجَوِّزَة.", "أُخْتِي أَعْزَب.", "أَخُوي مَخْطُوبَة."],
                correctIndex: 0,
            },
            {
                id: "family_q8",
                questionAr: "جمع أُخْت باللهجة الطبيعية في غزة:",
                optionsEn: ["خَوَات", "أَخَوَيْن", "قَرَايِب"],
                correctIndex: 0,
            },
            {
                id: "family_q9",
                questionAr: "رَدّ طبيعي لما حدا يحكي عن إِمُّه أو أَبُوه:",
                optionsEn: ["الله يْخَلِّيلَك", "شُو اِسْمَك؟", "مَع السَّلَامَة"],
                correctIndex: 0,
            },
            {
                id: "family_q10",
                questionAr: "«سِيدِي وَسِتِّي» مَعْنَاهَا:",
                optionsEn: ["My grandfather and grandmother", "My brother and sister", "My uncle and aunt"],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Introduce your family in 60 seconds. Say who lives with you and how many brothers/sisters you have.",
            "Ask your classmate about their family: عِيلْتَك كْبِيرَة؟ عِنْدَك إِخْوَة؟ مِين أَكْبَر؟",
            "Talk about one relative you are close to and why.",
            "Use the structure عِنْدِي / مَا عِنْدِي in five different sentences.",
            "Picture role-play: show an imaginary family photo and ask/answer هَاد شُو بِيِقْرَبْلَك؟",
        ],
        translation: [
            { id: "family_t1", type: "enToAr", textEn: "I have one brother and sisters.", textAr: "عِنْدِي أَخ وَخَوَات." },
            { id: "family_t2", type: "arToEn", textEn: "My mother is at home today.", textAr: "إِمِّي فِي البِيت اليَوم." },
            { id: "family_t3", type: "enToAr", textEn: "My brother is three years older than me.", textAr: "أَخُوي أَكْبَر مِنِّي بِتَلَات سِنِين." },
            { id: "family_t4", type: "arToEn", textEn: "My sister is younger than me.", textAr: "أُخْتِي أَصْغَر مِنِّي." },
            { id: "family_t5", type: "enToAr", textEn: "My uncle has a son my age.", textAr: "خَالِي عِنْدُه اِبِن قَدِّي." },
            { id: "family_t6", type: "arToEn", textEn: "I live with my family.", textAr: "أَنَا سَاكِن/سَاكْنَة مَع أَهْلِي." },
            { id: "family_t7", type: "enToAr", textEn: "My brother is married.", textAr: "أَخُوي مِتْجَوِّز." },
            { id: "family_t8", type: "arToEn", textEn: "My sister is single.", textAr: "أُخْتِي عَزْبَا." },
            { id: "family_t9", type: "enToAr", textEn: "My sister is engaged.", textAr: "أُخْتِي مَخْطُوبَة." },
            { id: "family_t10", type: "arToEn", textEn: "Our neighbors are like family.", textAr: "جِيرَانَّا زَيّ العِيلَة." },
            { id: "family_t11", type: "enToAr", textEn: "My family lives here in Gaza.", textAr: "أَهْلِي سَاكْنِين هِنَا فِي غَزَّة." },
            { id: "family_t12", type: "arToEn", textEn: "My maternal uncle has a son my age.", textAr: "خَالِي عِنْدُه اِبِن قَدِّي." },
            { id: "family_t13", type: "enToAr", textEn: "How is he related to you?", textAr: "هَاد شُو بِيِقْرَبْلَك؟" },
            { id: "family_t14", type: "arToEn", textEn: "My grandfather lives with my grandmother.", textAr: "سِيدِي سَاكِن مَع سِتِّي." },
            { id: "family_t15", type: "enToAr", textEn: "My aunt has a daughter and a twin.", textAr: "خَالْتِي عِنْدْهَا بِنْت وَتَوْأَم." },
            { id: "family_t16", type: "arToEn", textEn: "Mashallah, your family is nice.", textAr: "مَا شَاء الله، عِيلْتَك حِلْوَة." },
            { id: "family_t17", type: "enToAr", textEn: "May God keep your mother for you.", textAr: "الله يْخَلِّيلِك إِمِّك." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second story about your family in Palestinian Arabic. Mention: who lives in your house, how many brothers and sisters you have, who is older/younger than you, and if any of them are married, single, or engaged. Try to use at least 8 words from the vocabulary list, the structure «عِنْدِي...», and at least 2 words from Unit 1.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you?
2. What's new? Reassure me about you.
3. My name is Omar, and I am from Gaza.
4. I live with my family.
5. My mother is at home today.
6. My father works in the morning.
7. I have one brother and one sister.
8. I do not have sisters, but I have many relatives.
9. Her father lives in Gaza.
10. Her sister is younger than her.
11. His brother is married and has a daughter.
12. My maternal uncle has a son my age.
13. Her paternal aunt visits them on Friday.
14. My mother-in-law is very kind.
15. Goodbye, see you later, take care.`,
    },

    teacherNotes: {
        warmup: [
            "Start by recycling Unit 1: مَرْحَبَا، كِيفَك؟ شُو أَخْبَارَك؟",
            "Ask the student in English who lives in their house, then map only needed words into Arabic.",
            "Keep the first speaking goal simple: عِنْدِي... / مَا عِنْدِي...",
        ],
        vocabularySteps: [
            "Teach family words as chunks with possessive forms: أَبُوي، إِمِّي، أَخُوي، أُخْتِي.",
            "Put related words in hints, not as separate heavy vocabulary.",
            "Use comparisons through examples: أَكْبَر مِنِّي، أَصْغَر مِنِّي، قَدِّي.",
        ],
        dialogueSteps: [
            "Read the dialogue as a real after-class conversation.",
            "Ask the student to answer the dialogue questions in full sentences.",
            "Then replace Layla's family with the student's real or imaginary family.",
        ],
        practiceTips: [
            "Push output: every answer should start with عِنْدِي, مَا عِنْدِي, or أَنَا سَاكِن/سَاكْنَة.",
            "Drill masculine/feminine naturally: مِتْجَوِّز / مِتْجَوِّزَة, سَاكِن / سَاكْنَة.",
            "Recycle Unit 1 closings at the end of every role-play.",
        ],
        wrapup: [
            "Student gives a 5-sentence family summary.",
            "Student asks the teacher 3 family questions.",
            "Student records the homework story.",
        ],
        myNotes: "",
    },
};
