import { LESSON_ID_FOOD_DRINK } from '../../core/constants.js';

export const lessonId = LESSON_ID_FOOD_DRINK;

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Food & Drink",
        lessonTitle: "Unit 4 - Food & Drink in Gaza Palestinian Arabic",
        contentVersion: 2026063001,
    },

    overview: {
        title: "Unit 4 - Food & Drink",
        description:
            "Students learn how to talk about food and drinks in natural Gaza Palestinian Arabic: what they eat, what they drink, what they like, what they want, and how to respond politely when someone offers food.",
        goals: [
            "Name common foods and drinks used in daily Gaza Arabic.",
            "Say what they eat and drink at home or outside.",
            "Use useful food patterns: بَحِبّ، مَا بَحِبّ، بَدِّي، زَاكِي، جَعَان، عَطْشَان.",
            "Accept or refuse food politely in a natural way.",
            "Reuse greetings, family, and daily routine words inside a food conversation.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can talk about what they eat in a normal day.",
            "The student can say what they want to eat or drink.",
            "The student can handle a short home visit where someone offers food, tea, or coffee.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "akl",
                ar: "أَكْل",
                en: "food",
                enArabeezy: "akl",
                hint: "General word for food. My food = أَكْلِي. Home food = أَكْل البِيت.",
                exampleAr: "أَكْل البِيت أَزْكَى مِن المَطْعَم.",
                exampleArabeezy: "akl el-beet azka min el-maT3am.",
                exampleEn: "Home food is tastier than restaurant food.",
            },
            {
                id: "fuToor",
                ar: "فُطُور",
                en: "breakfast",
                enArabeezy: "fuToor",
                hint: "Morning meal. Verb: بَفْطَر = I have breakfast.",
                exampleAr: "الصُّبُح بَفْطَر خُبِز وَجُبْنَة.",
                exampleArabeezy: "el-soboh bafTar khobez w jibneh.",
                exampleEn: "In the morning I have bread and cheese for breakfast.",
            },
            {
                id: "ghada",
                ar: "غَدَا",
                en: "lunch",
                enArabeezy: "ghada",
                hint: "Main family meal in many homes. Verb: بِتْغَدَّى = I have lunch.",
                exampleAr: "بَعْد الضُّهُر بَاكُل الغَدَا مَع أَهْلِي.",
                exampleArabeezy: "ba3d el-duhur baakul el-ghada ma3 ahli.",
                exampleEn: "In the afternoon I eat lunch with my family.",
            },
            {
                id: "3asha",
                ar: "عَشَا",
                en: "dinner / evening meal",
                enArabeezy: "3asha",
                hint: "Evening meal. Verb: بِتْعَشَّى. Often lighter than lunch.",
                exampleAr: "بِالمَسَا بِنِتْعَشَّى إِشِي خَفِيف.",
                exampleArabeezy: "bel-masa bnit3asha ishi khafeef.",
                exampleEn: "In the evening we have a light dinner.",
            },
            {
                id: "khobez",
                ar: "خُبِز",
                en: "bread",
                enArabeezy: "khobez",
                hint: "Very common with almost every meal. A loaf = رَغِيف خُبِز.",
                exampleAr: "خُبِز وَزَيْت زَيْتُون فُطُور بَسِيط وَزَاكِي.",
                exampleArabeezy: "khobez w zeit zaytoon fuToor baseeT w zaki.",
                exampleEn: "Bread and olive oil is a simple and tasty breakfast.",
            },
            {
                id: "jibneh",
                ar: "جُبْنَة",
                en: "cheese",
                enArabeezy: "jibneh",
                hint: "Common breakfast food. White cheese = جُبْنَة بَيْضَا.",
                exampleAr: "بَحِبّ جُبْنَة مَع خُبِز سُخْن.",
                exampleArabeezy: "ba7ibb jibneh ma3 khobez sokhon.",
                exampleEn: "I like cheese with warm bread.",
            },
            {
                id: "zeit_zaytoon",
                ar: "زَيْت زَيْتُون",
                en: "olive oil",
                enArabeezy: "zeit zaytoon",
                hint: "Basic Palestinian ingredient. Often eaten with bread and zaatar.",
                exampleAr: "سِتِّي بِحِبّ خُبِز مَع زَيْت زَيْتُون.",
                exampleArabeezy: "sitti bit7ibb khobez ma3 zeit zaytoon.",
                exampleEn: "My grandmother likes bread with olive oil.",
            },
            {
                id: "za3tar",
                ar: "زَعْتَر",
                en: "zaatar",
                enArabeezy: "za3tar",
                hint: "Thyme mix with sesame and spices. Common with bread and olive oil.",
                exampleAr: "زَعْتَر مَع شَاي إِشِي زَاكِي الصُّبُح.",
                exampleArabeezy: "za3tar ma3 shay ishi zaki el-soboh.",
                exampleEn: "Zaatar with tea is tasty in the morning.",
            },
            {
                id: "hummus",
                ar: "حُمُّص",
                en: "hummus",
                enArabeezy: "hummus",
                hint: "Very common with breakfast, dinner, or falafel.",
                exampleAr: "بِالمَسَا بَدِّي حُمُّص وَفَلَافِل.",
                exampleArabeezy: "bel-masa baddi hummus w falafel.",
                exampleEn: "In the evening I want hummus and falafel.",
            },
            {
                id: "falafel",
                ar: "فَلَافِل",
                en: "falafel",
                enArabeezy: "falafel",
                hint: "Very common in a sandwich. Often breakfast or dinner.",
                exampleAr: "كَتِير نَاس بِفْطَرُوا سَنْدَوِيش فَلَافِل.",
                exampleArabeezy: "kteer nas bifTaru sandawish falafel.",
                exampleEn: "Many people have a falafel sandwich for breakfast.",
            },
            {
                id: "ruz",
                ar: "رُزّ",
                en: "rice",
                enArabeezy: "rozz",
                hint: "Common with chicken, meat, vegetables, and home cooking.",
                exampleAr: "سِتِّي عَامْلَة رُزّ وَجَاج.",
                exampleArabeezy: "sitti 3amleh rozz w jaj.",
                exampleEn: "My grandmother made rice and chicken.",
            },
            {
                id: "jaj",
                ar: "جَاج",
                en: "chicken",
                enArabeezy: "jaj",
                hint: "Spoken word for chicken. More natural in daily speech than دَجَاج.",
                exampleAr: "أَخُوي بِحِبّ الجَاج أَكْتَر مِن اللَّحْمَة.",
                exampleArabeezy: "akhuy bi7ibb el-jaj aktar min el-la7meh.",
                exampleEn: "My brother likes chicken more than meat.",
            },
            {
                id: "la7meh",
                ar: "لَحْمَة",
                en: "meat",
                enArabeezy: "la7meh",
                hint: "General meat. You may hear لَحِم too.",
                exampleAr: "مِش جَاي عَلَى بَالِي لَحْمَة اليَوم.",
                exampleArabeezy: "mish jay 3ala bali la7meh el-yom.",
                exampleEn: "I don't feel like meat today.",
            },
            {
                id: "samak",
                ar: "سَمَك",
                en: "fish",
                enArabeezy: "samak",
                hint: "Important in Gaza because the sea is part of daily food culture.",
                exampleAr: "فِي غَزَّة السَّمَك طَازَة وَزَاكِي.",
                exampleArabeezy: "fi ghazza el-samak Tazeh w zaki.",
                exampleEn: "In Gaza, fish is fresh and tasty.",
            },
            {
                id: "maqlubeh",
                ar: "مَقْلُوبِة",
                en: "maqlubeh",
                enArabeezy: "maqlubeh",
                hint: "Famous Palestinian rice dish with chicken/meat and vegetables.",
                exampleAr: "مَقْلُوبِة جَاج مِن أَشْهَر أَكَلَات فِلَسْطِين.",
                exampleArabeezy: "maqlubeh jaj min ashhar aklat falasteen.",
                exampleEn: "Chicken maqlubeh is one of the most famous Palestinian dishes.",
            },
            {
                id: "salata",
                ar: "سَلَطَة",
                en: "salad",
                enArabeezy: "salaTa",
                hint: "Usually with lunch. Plural/types: سَلَطَات.",
                exampleAr: "دَايْمًا فِي سَلَطَة مَع الغَدَا.",
                exampleArabeezy: "dayman fi salaTa ma3 el-ghada.",
                exampleEn: "There is always salad with lunch.",
            },
            {
                id: "khodar",
                ar: "خُضَار",
                en: "vegetables",
                enArabeezy: "khodar",
                hint: "Examples: بَنْدُورَة، خِيَار، بَطَاطَا، بَصَل.",
                exampleAr: "إِمِّي بِتِسَوِّي سَلَطَة خُضَار طَازَة.",
                exampleArabeezy: "immi bitisawwi salaTat khodar Tazeh.",
                exampleEn: "My mother makes a fresh vegetable salad.",
            },
            {
                id: "fawakeh",
                ar: "فَوَاكِه",
                en: "fruits",
                enArabeezy: "fawakeh",
                hint: "Examples: تُفَّاح، مَوْز، بُرْتُقَال، عِنَب.",
                exampleAr: "بَعْد الغَدَا بَاكُل فَوَاكِه.",
                exampleArabeezy: "ba3d el-ghada baakul fawakeh.",
                exampleEn: "After lunch I eat fruit.",
            },
            {
                id: "tuffa7_moz",
                ar: "تُفَّاح / مَوْز",
                en: "apples / bananas",
                enArabeezy: "tuffa7 / moz",
                hint: "One apple = تُفَّاحَة. One banana = مَوْزَة.",
                exampleAr: "أَخُوي بِحِبّ تُفَّاح، وَأُخْتِي بِتِحِبّ مَوْز.",
                exampleArabeezy: "akhuy bi7ibb tuffa7, w okhti bit7ibb moz.",
                exampleEn: "My brother likes apples, and my sister likes bananas.",
            },
            {
                id: "baharat",
                ar: "بَهَارَات",
                en: "spices",
                enArabeezy: "baharat",
                hint: "Useful for taste talk. Too much spice = بَهَارَات كْتِير.",
                exampleAr: "البَهَارَات فِي الجَاج حِلْوَة.",
                exampleArabeezy: "el-baharat fi el-jaj 7ilweh.",
                exampleEn: "The spices in the chicken are nice.",
            },
            {
                id: "mayy",
                ar: "مَيّ",
                en: "water",
                enArabeezy: "mayy",
                hint: "Very frequent. I want water = بَدِّي مَيّ.",
                exampleAr: "أَنَا عَطْشَان، بَدِّي مَيّ.",
                exampleArabeezy: "ana 3aTshan, baddi mayy.",
                exampleEn: "I'm thirsty, I want water.",
            },
            {
                id: "ahweh",
                ar: "قَهْوَة",
                en: "coffee",
                enArabeezy: "ahweh",
                hint: "In spoken Gaza pronunciation often sounds like أَهْوَة.",
                exampleAr: "الصُّبُح بَشْرَب قَهْوَة.",
                exampleArabeezy: "el-soboh bashrab ahweh.",
                exampleEn: "In the morning I drink coffee.",
            },
            {
                id: "shay",
                ar: "شَاي",
                en: "tea",
                enArabeezy: "shay",
                hint: "Very common after food or with guests. Tea with mint = شَاي مَع نَعْنَاع.",
                exampleAr: "سِتِّي بِتِحِبّ شَاي مَع نَعْنَاع.",
                exampleArabeezy: "sitti bit7ibb shay ma3 na3na3.",
                exampleEn: "My grandmother loves tea with mint.",
            },
            {
                id: "3aseer",
                ar: "عَصِير",
                en: "juice",
                enArabeezy: "3aseer",
                hint: "Plural/types: عَصَايِر. Orange juice = عَصِير بُرْتُقَال.",
                exampleAr: "بَدِّي عَصِير بُرْتُقَال.",
                exampleArabeezy: "baddi 3aseer bortuqal.",
                exampleEn: "I want orange juice.",
            },
            {
                id: "ja3an",
                ar: "جَعَان / جَعَانَة",
                en: "hungry",
                enArabeezy: "ja3an / ja3aneh",
                hint: "Male: جَعَان. Female: جَعَانَة. Plural: جَعَانِين.",
                exampleAr: "أَنَا جَعَانَة، بَدِّي آكُل.",
                exampleArabeezy: "ana ja3aneh, baddi aakul.",
                exampleEn: "I'm hungry, I want to eat.",
            },
            {
                id: "3atshan",
                ar: "عَطْشَان / عَطْشَانَة",
                en: "thirsty",
                enArabeezy: "3atshan / 3atshaneh",
                hint: "Male: عَطْشَان. Female: عَطْشَانَة. Plural: عَطْشَانِين.",
                exampleAr: "أَنَا عَطْشَان، بَدِّي مَيّ.",
                exampleArabeezy: "ana 3atshan, baddi mayy.",
                exampleEn: "I'm thirsty, I want water.",
            },
            {
                id: "zaki",
                ar: "زَاكِي / زَاكِيَة",
                en: "tasty / delicious",
                enArabeezy: "zaki / zakiyeh",
                hint: "Male: زَاكِي. Female: زَاكِيَة. Plural: زَاكْيِين.",
                exampleAr: "الجَاج زَاكِي كْتِير.",
                exampleArabeezy: "el-jaj zaki kteer.",
                exampleEn: "The chicken is very tasty.",
            },
            {
                id: "mish_zaki",
                ar: "مِش زَاكِي",
                en: "not tasty",
                enArabeezy: "mish zaki",
                hint: "Simple taste opinion. Softer: مِش كْتِير زَاكِي = not very tasty.",
                exampleAr: "بِصَرَاحَة الأَكْل اليَوم مِش زَاكِي.",
                exampleArabeezy: "biSara7a el-akl el-yom mish zaki.",
                exampleEn: "Honestly, today's food is not tasty.",
            },
            {
                id: "mish_jay_3ala_bali",
                ar: "مِش جَاي عَلَى بَالِي",
                en: "I don't feel like / nothing sounds good",
                enArabeezy: "mish jay 3ala bali",
                hint: "Natural answer when someone asks what you want to eat and you are unsure.",
                exampleAr: "مِش جَاي عَلَى بَالِي أَكْل كْتِير.",
                exampleArabeezy: "mish jay 3ala bali akl kteer.",
                exampleEn: "I don't feel like eating a lot.",
            },
            {
                id: "ba7ibb",
                ar: "بَحِبّ",
                en: "I like / I love",
                enArabeezy: "ba7ibb",
                hint: "Use with food, drinks, people, activities. He likes = بِحِبّ. She likes = بِتِحِبّ.",
                exampleAr: "بَحِبّ الأَكْل الفِلَسْطِينِي كْتِير.",
                exampleArabeezy: "ba7ibb el-akl el-falasteeni kteer.",
                exampleEn: "I really like Palestinian food.",
            },
            {
                id: "ma_ba7ibb",
                ar: "مَا بَحِبّ",
                en: "I don't like",
                enArabeezy: "ma ba7ibb",
                hint: "Simple negation for preferences. Softer: مَا بَحِبّ كْتِير.",
                exampleAr: "مَا بَحِبّ الأَكْل الحَارّ.",
                exampleArabeezy: "ma ba7ibb el-akl el-7arr.",
                exampleEn: "I don't like spicy food.",
            },
            {
                id: "baddi",
                ar: "بَدِّي",
                en: "I want",
                enArabeezy: "baddi",
                hint: "Use to ask/order: بَدِّي مَيّ / بَدِّي فَلَافِل. To ask: بَدَّك؟ / بَدِّك؟",
                exampleAr: "بَدِّي مَيّ أَوَّل إِشِي.",
                exampleArabeezy: "baddi mayy awwal ishi.",
                exampleEn: "I want water first.",
            },
            {
                id: "shbi3t",
                ar: "شْبِعِت",
                en: "I'm full",
                enArabeezy: "shbi3t",
                hint: "Very useful when refusing more food politely: لَا يِسْلَمُوا، شْبِعِت.",
                exampleAr: "يِسْلَمُوا، شْبِعِت، الأَكْل زَاكِي.",
                exampleArabeezy: "yislamu, shbi3t, el-akl zaki.",
                exampleEn: "Thanks, I'm full, the food is tasty.",
            },
            {
                id: "sa77a_w_3afyeh",
                ar: "صَحَّة وَعَافْيَة",
                en: "enjoy / bon appetit",
                enArabeezy: "sa77a w 3afyeh",
                hint: "Said when serving food or when someone is eating. Reply: الله يْعَافِيك.",
                exampleAr: "تْفَضَّلُوا، صَحَّة وَعَافْيَة.",
                exampleArabeezy: "tfaddalu, sa77a w 3afyeh.",
                exampleEn: "Here you go, enjoy.",
            },
        ],
    },

    dialogue: {
        title: "Real Situation - Lunch at Grandma's House",
        setting: "Rami is going to eat lunch at his grandmother's house. His aunt calls him before he arrives, then they sit together for lunch.",
        lines: [
            { speaker: "Khala", ar: "مَرْحَبَا رَامِي، وِين وَصَلْت؟", arArabeezy: "marhaba rami, wen wSilt?", en: "Hi Rami, where have you reached?" },
            { speaker: "Rami", ar: "أَهْلِين خَالْتِي، أَنَا قَرِيب مِن بِيت سِتِّي.", arArabeezy: "ahleen khalti, ana qareeb min beet sitti.", en: "Hi auntie, I'm close to my grandmother's house." },
            { speaker: "Khala", ar: "تَمَام، سِتَّك مِسْتَنْيَاك عَالغَدَا.", arArabeezy: "tamam, sittak mistannyak 3al-ghada.", en: "Great, your grandmother is waiting for you for lunch." },
            { speaker: "Rami", ar: "شُو عَامْلَة اليَوم؟ أَنَا جَعَان شُوَيّ.", arArabeezy: "sho 3amleh el-yom? ana ja3an shway.", en: "What did she make today? I'm a little hungry." },
            { speaker: "Khala", ar: "عَامْلَة رُزّ وَجَاج وَسَلَطَة.", arArabeezy: "3amleh rozz w jaj w salaTa.", en: "She made rice, chicken, and salad." },
            { speaker: "Rami", ar: "مُمْتَاز. بَس مِش جَاي عَلَى بَالِي أَكْل كْتِير.", arArabeezy: "mumtaz. bas mish jay 3ala bali akl kteer.", en: "Excellent. But I don't feel like eating a lot." },
            { speaker: "Khala", ar: "وَلَا يِهِمَّك، كُل شُوَيّ جَاج وَسَلَطَة.", arArabeezy: "wala yhemmak, kol shway jaj w salaTa.", en: "No problem, eat a little chicken and salad." },
            { speaker: "Rami", ar: "فِي مَيّ؟ أَنَا عَطْشَان.", arArabeezy: "fi mayy? ana 3atshan.", en: "Is there water? I'm thirsty." },
            { speaker: "Khala", ar: "آه، فِي مَيّ وَعَصِير. بَدَّك مَيّ؟", arArabeezy: "ah, fi mayy w 3aseer. baddak mayy?", en: "Yes, there is water and juice. Do you want water?" },
            { speaker: "Rami", ar: "آه، مَيّ أَوَّل إِشِي.", arArabeezy: "ah, mayy awwal ishi.", en: "Yes, water first." },
            { speaker: "Khala", ar: "طَيِّب تَعَال بِسُرْعَة قَبِل مَا يِبْرَد الرُّزّ.", arArabeezy: "tayyib ta3al bisur3a qabel ma yibrad el-rozz.", en: "Okay, come quickly before the rice gets cold." },
            { speaker: "Rami", ar: "دَقِيقْتِين وَبَوْصَل.", arArabeezy: "da2ee2teen w bawSal.", en: "Two minutes and I'll arrive." },
            { speaker: "Rami", ar: "آه وَصِلْت. السَّلَام عَلِيكُم.", arArabeezy: "ah wSilt. el-salam 3aleekom.", en: "I arrived. Peace be upon you." },
            { speaker: "Sitti", ar: "وَعَلِيكُم السَّلَام يَا حَبِيبِي، تْفَضَّل.", arArabeezy: "w 3aleekom el-salam ya 7abeebi, tfaddal.", en: "Peace be upon you too, dear, come in." },
            { speaker: "Khala", ar: "اُقْعُد هِنَا جَنْب سِتَّك.", arArabeezy: "u23od hena jamb sittak.", en: "Sit here next to your grandmother." },
            { speaker: "Rami", ar: "يِسْلَمُوا إِيدِيكِي يَا سِتِّي، رِيحِة الأَكْل بِتْفَتِّح النَّفْس.", arArabeezy: "yislamu eedeki ya sitti, ree7et el-akl bitfatti7 el-nafs.", en: "Bless your hands, grandma, the smell of the food makes me hungry." },
            { speaker: "Sitti", ar: "تْفَضَّل كُل، صَحَّة وَعَافْيَة.", arArabeezy: "tfaddal kol, sa77a w 3afyeh.", en: "Go ahead and eat, enjoy." },
            { speaker: "Khala", ar: "حَطِّيتْلَك رُزّ وَجَاج وَسَلَطَة.", arArabeezy: "7aTTeetlak rozz w jaj w salaTa.", en: "I put rice, chicken, and salad for you." },
            { speaker: "Rami", ar: "الله يْعَافِيكِي. الجَاج زَاكِي، وَالبَهَارَات حِلْوَة.", arArabeezy: "allah y3afeeki. el-jaj zaki, w el-baharat 7ilweh.", en: "Thank you. The chicken is tasty, and the spices are nice." },
            { speaker: "Sitti", ar: "إِمَّك بِتِحِبّ البَهَارَات هِيك كَمَان.", arArabeezy: "immak bit7ibb el-baharat heek kaman.", en: "Your mother likes spices like this too." },
            { speaker: "Rami", ar: "آه، بَس السَّلَطَة بَدْهَا شُوَيِّة مِلِح.", arArabeezy: "ah, bas el-salaTa badha shwayyet mili7.", en: "Yes, but the salad needs a little salt." },
            { speaker: "Khala", ar: "بَحُطِّلَك مِلِح شُوَيّ. هِيك أَحْسَن؟", arArabeezy: "ba7uTTilak mili7 shway. heek a7san?", en: "I'll put a little salt for you. Is this better?" },
            { speaker: "Rami", ar: "آه، هَلْقِيت زَاكِيَة.", arArabeezy: "ah, halla2et zakiyeh.", en: "Yes, now it's tasty." },
            { speaker: "Sitti", ar: "بَدَّك كَمَان جَاج؟", arArabeezy: "baddak kaman jaj?", en: "Do you want more chicken?" },
            { speaker: "Rami", ar: "لَا يِسْلَمُوا، شْبِعِت.", arArabeezy: "la yislamu, shbi3t.", en: "No thanks, I'm full." },
            { speaker: "Khala", ar: "بَعْد الغَدَا فِي شَاي وَفَوَاكِه.", arArabeezy: "ba3d el-ghada fi shay w fawakeh.", en: "After lunch there is tea and fruit." },
            { speaker: "Rami", ar: "شَاي مُمْتَاز، وَالفَوَاكِه بَعْدِين.", arArabeezy: "shay mumtaz, w el-fawakeh ba3deen.", en: "Tea is excellent, and fruit later." },
            { speaker: "Sitti", ar: "اِشْرَب شَاي قَبِل مَا تْرُوح.", arArabeezy: "ishrab shay qabel ma troo7.", en: "Drink tea before you go." },
            { speaker: "Rami", ar: "أَكِيد. شَاي سِتِّي مَا بِنْرَفَض.", arArabeezy: "akeed. shay sitti ma binrafad.", en: "Of course. Grandma's tea can't be refused." },
            { speaker: "Khala", ar: "وَبِالمَسَا إِذَا ضَلِّيت، بِنْجِيب حُمُّص وَفَلَافِل.", arArabeezy: "w bel-masa iza Dalleet, binjeeb hummus w falafel.", en: "And in the evening, if you stay, we'll bring hummus and falafel." },
            { speaker: "Rami", ar: "لَا هِيك يَوم كَامِل أَكْل عِنْدْكُم!", arArabeezy: "la heek yom kamel akl 3indkum!", en: "No, then it's a whole day of food at your place!" },
            { speaker: "Sitti", ar: "البِيت بِيتَك يَا حَبِيبِي.", arArabeezy: "el-beet beetak ya 7abeebi.", en: "Make yourself at home, dear." },
        ],
        questions: [
            { ar: "رَامِي كَان قَرِيب مِن بِيت مِين؟", en: "Whose house was Rami close to?" },
            { ar: "سِتّ رَامِي كَانَت مِسْتَنْيَاه عَلَى شُو؟", en: "What was Rami's grandmother waiting for him for?" },
            { ar: "سِتُّه عَامْلَة شُو عَلَى الغَدَا؟", en: "What did his grandmother make for lunch?" },
            { ar: "رَامِي قَال مِش جَاي عَلَى بَالُه شُو؟", en: "What did Rami say he did not feel like doing?" },
            { ar: "رَامِي كَان عَطْشَان وطلب شُو؟", en: "Rami was thirsty and asked for what?" },
            { ar: "رَامِي قَال لِسِتُّه شُو عَن رِيحِة الأَكْل؟", en: "What did Rami say to his grandmother about the smell of the food?" },
            { ar: "الخَالَة حَطِّت لِرَامِي شُو؟", en: "What did the aunt put for Rami?" },
            { ar: "رَامِي قَال الجَاج كِيف؟", en: "What did Rami say about the chicken?" },
            { ar: "السَّلَطَة كَان بَدْهَا شُو؟", en: "What did the salad need?" },
            { ar: "لَمَّا سِتُّه سَأَلَتُه بَدَّك كَمَان جَاج، رَدّ شُو؟", en: "When his grandmother asked if he wanted more chicken, what did he reply?" },
            { ar: "بَعْد الغَدَا كَان فِي شُو؟", en: "What was there after lunch?" },
            { ar: "بِالمَسَا الخَالَة قَالَت مُمْكِن يِجِيبُوا شُو؟", en: "In the evening, what did the aunt say they might bring?" },
            { ar: "اِحْكِي قِصِّة رَامِي عِنْد سِتُّه بِخَمْس جُمَل.", en: "Tell Rami's story at his grandmother's in five sentences." },
            { ar: "اِحْكِي عَن أَكْلَة بِتِحِبَّهَا: مِين بِيِعْمَلْهَا؟ وَإِمْتَى بْتَاكُلْهَا؟", en: "Talk about a food you like: who makes it and when do you eat it?" },
        ],
    },

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "food_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: lunch",
                options: ["غَدَا", "فُطُور", "عَشَا", "مَيّ"],
                correct: "غَدَا",
            },
            {
                id: "food_mc2",
                type: "complete",
                prompt: "Complete: أَنَا عَطْشَان، بَدِّي ___.",
                options: ["مَيّ", "خُبِز", "زَعْتَر", "فَوَاكِه"],
                correct: "مَيّ",
            },
            {
                id: "food_mc3",
                type: "reorder",
                prompt: "Reorder: The chicken is tasty.",
                options: ["الجَاج", "زَاكِي"],
                correct: ["الجَاج", "زَاكِي"],
            },
            {
                id: "food_mc4",
                type: "choose",
                prompt: "Choose a polite way to refuse more food:",
                options: ["لَا يِسْلَمُوا، شْبِعِت.", "شُو اِسْمَك؟", "أَنَا مِن غَزَّة."],
                correct: "لَا يِسْلَمُوا، شْبِعِت.",
            },
            {
                id: "food_mc5",
                type: "complete",
                prompt: "Complete: تْفَضَّلُوا، ___.",
                options: ["صَحَّة وَعَافْيَة", "مِش زَاكِي", "أَيّ سَاعَة"],
                correct: "صَحَّة وَعَافْيَة",
            },
        ],
    },

    practice: {
        quiz: [
            {
                id: "food_q1",
                questionAr: "«أَنَا جَعَان، بَدِّي آكُل» مَعْنَاهَا:",
                optionsEn: ["I'm hungry, I want to eat.", "I'm thirsty, I want water.", "I'm full, thanks."],
                correctIndex: 0,
            },
            {
                id: "food_q2",
                questionAr: "«الجَاج زَاكِي» مَعْنَاهَا:",
                optionsEn: ["The chicken is tasty.", "The chicken is salty.", "The chicken is cold."],
                correctIndex: 0,
            },
            {
                id: "food_q3",
                questionAr: "إِذَا بَدِّي أَرْفُض أَكْل بِلُطْف، بَقُول:",
                optionsEn: ["لَا يِسْلَمُوا، شْبِعِت.", "بَدِّي مَيّ.", "أَيّ سَاعَة؟"],
                correctIndex: 0,
            },
            {
                id: "food_q4",
                questionAr: "«مِش جَاي عَلَى بَالِي أَكْل كْتِير» مَعْنَاهَا:",
                optionsEn: ["I don't feel like eating a lot.", "I want a lot of food.", "I don't like my family."],
                correctIndex: 0,
            },
            {
                id: "food_q5",
                questionAr: "كَمِّل: بَعْد الغَدَا فِي شَاي وَ___.",
                optionsEn: ["فَوَاكِه", "أُجْرَة", "صَف"],
                correctIndex: 0,
            },
            {
                id: "food_q6",
                questionAr: "حَوِّل لِلْمُؤَنَّث: أَنَا جَعَان.",
                optionsEn: ["أَنَا جَعَانَة.", "أَنَا عَطْشَان.", "أَنَا زَاكِي."],
                correctIndex: 0,
            },
            {
                id: "food_q7",
                questionAr: "الرَّد عَلَى «صَحَّة وَعَافْيَة» مُمْكِن يِكُون:",
                optionsEn: ["الله يْعَافِيك", "شُو أَخْبَارَك؟", "مِن وِين؟"],
                correctIndex: 0,
            },
            {
                id: "food_q8",
                questionAr: "«مَا بَحِبّ الأَكْل الحَارّ» مَعْنَاهَا:",
                optionsEn: ["I don't like spicy food.", "I like spicy food.", "I want spicy food."],
                correctIndex: 0,
            },
            {
                id: "food_q9",
                questionAr: "«بَدِّي مَيّ أَوَّل إِشِي» مَعْنَاهَا:",
                optionsEn: ["I want water first.", "I want tea later.", "I want fruit after lunch."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "Home visit role-play: your grandmother/aunt offers lunch. Accept food, ask for water, and say if the food is tasty.",
            "Polite refusal role-play: someone offers more chicken or rice. Refuse politely using شْبِعِت and thank them.",
            "Food preference role-play: ask your classmate what they like and do not like using بَحِبّ / مَا بَحِبّ.",
            "Daily food routine: describe what you eat for breakfast, lunch, and dinner using Unit 3 time words.",
            "Order role-play: ask for hummus, falafel, water, tea, or juice using بَدِّي.",
        ],
        translation: [
            { id: "food_t1", type: "enToAr", textEn: "I'm hungry, I want to eat.", textAr: "أَنَا جَعَان/جَعَانَة، بَدِّي آكُل." },
            { id: "food_t2", type: "arToEn", textEn: "I'm thirsty, I want water.", textAr: "أَنَا عَطْشَان/عَطْشَانَة، بَدِّي مَيّ." },
            { id: "food_t3", type: "enToAr", textEn: "My grandmother made rice and chicken.", textAr: "سِتِّي عَامْلَة رُزّ وَجَاج." },
            { id: "food_t4", type: "arToEn", textEn: "The chicken is tasty, and the spices are nice.", textAr: "الجَاج زَاكِي، وَالبَهَارَات حِلْوَة." },
            { id: "food_t5", type: "enToAr", textEn: "I don't feel like eating a lot.", textAr: "مِش جَاي عَلَى بَالِي أَكْل كْتِير." },
            { id: "food_t6", type: "arToEn", textEn: "No thanks, I'm full.", textAr: "لَا يِسْلَمُوا، شْبِعِت." },
            { id: "food_t7", type: "enToAr", textEn: "After lunch there is tea and fruit.", textAr: "بَعْد الغَدَا فِي شَاي وَفَوَاكِه." },
            { id: "food_t8", type: "arToEn", textEn: "I like bread and cheese in the morning.", textAr: "بَحِبّ خُبِز وَجُبْنَة الصُّبُح." },
            { id: "food_t9", type: "enToAr", textEn: "I don't like spicy food.", textAr: "مَا بَحِبّ الأَكْل الحَارّ." },
            { id: "food_t10", type: "arToEn", textEn: "I want hummus and falafel, please.", textAr: "بَدِّي حُمُّص وَفَلَافِل، لَوْ سَمَحْت." },
            { id: "food_t11", type: "enToAr", textEn: "My sister likes apples and bananas.", textAr: "أُخْتِي بِتِحِبّ تُفَّاح وَمَوْز." },
            { id: "food_t12", type: "arToEn", textEn: "In Gaza, fish is fresh and tasty.", textAr: "فِي غَزَّة السَّمَك طَازَة وَزَاكِي." },
            { id: "food_t13", type: "enToAr", textEn: "Here you go, enjoy.", textAr: "تْفَضَّل، صَحَّة وَعَافْيَة." },
            { id: "food_t14", type: "arToEn", textEn: "Grandma's tea can't be refused.", textAr: "شَاي سِتِّي مَا بِنْرَفَض." },
            { id: "food_t15", type: "enToAr", textEn: "Goodbye, see you later, take care.", textAr: "مَع السَّلَامَة، بِنْشُوفَك بَعْدِين، دِير بَالَك." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second story about food in your life in Palestinian Arabic. Mention: what you eat in the morning, what you drink, one food you like, one food you do not like, and what your family usually eats at home. Try to use at least 8 words from the vocabulary list and at least 3 words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you today?
2. I live with my family.
3. Every morning I drink coffee.
4. My grandmother makes tea with mint.
5. I am hungry, I want to eat.
6. I am thirsty, I want water.
7. I like bread and cheese.
8. I do not like spicy food.
9. My mother makes rice and chicken.
10. The food at home is very tasty.
11. I want hummus and falafel, please.
12. After lunch, I eat fruit.
13. My brother likes apples and bananas.
14. No thanks, I'm full.
15. Goodbye, see you later, take care.`,
    },

    teacherNotes: {
        warmup: [
            "Start with real life: شُو أَكَلْت اليَوم؟ شُو شِرِبْت الصُّبُح؟",
            "Recycle previous units through food: إِمِّي بِتِعْمَل، سِتِّي بِتِعْمَل، بَعْد الغَدَا، قَبِل مَا أَرُوح.",
            "Keep cultural expressions natural: صَحَّة وَعَافْيَة، يِسْلَمُوا إِيدِيكِي، البِيت بِيْتَك.",
        ],
        vocabularySteps: [
            "Teach food as chunks: بَدِّي مَيّ، بَحِبّ الجَاج، الأَكْل زَاكِي، أَنَا جَعَان.",
            "Keep dish names usable; special dishes like مَقْلُوبِة should appear in examples, not dominate the lesson.",
            "Ask the student to personalize every word immediately.",
        ],
        dialogueSteps: [
            "Treat the dialogue as a visit to grandmother's house, not a restaurant script.",
            "After reading, ask the student to retell: Rami is hungry, Sitti made food, he wants water, then tea.",
            "Have the student replace the foods with their own real foods.",
        ],
        practiceTips: [
            "Push complete answers: بَحِبّ القَهْوَة، مَا بَحِبّ اللَّحْمَة، بَدِّي مَيّ.",
            "Drill polite acceptance/refusal: يِسْلَمُوا، شْبِعِت، صَحَّة وَعَافْيَة.",
            "Use masculine/feminine hunger/thirst forms every lesson.",
        ],
        wrapup: [
            "Student says 5 foods/drinks they like.",
            "Student offers food and refuses more food politely.",
            "Student records a voice note about what they ate today.",
        ],
        myNotes: "",
    },
};
