import { LESSON_ID_FOOD_DRINK } from '../../core/constants.js';

export const lessonId = LESSON_ID_FOOD_DRINK;

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Food & Drink",
        lessonTitle: "Unit 4 - Food & Drink in Gaza Palestinian Arabic",
        contentVersion: 2026071401,
    },

    overview: {
        title: "Unit 4 - Food & Drink",
        description:
            "Students learn how to talk about food and drinks in natural Gaza Palestinian Arabic: what they eat, what they drink, what they like, what they want, and how to respond politely when someone offers food.",
        goals: [
            "Name common foods and drinks used in daily Gaza Arabic.",
            "Say what they eat and drink at home or outside.",
            "Use useful food patterns: بَحِبّ، مَا بَحِبّ، بَدِّي، زَاكِي، جَعَان، عَطْشَان.",
            "Accept or refuse food politely in a natural way.",
            "Reuse greetings, family, and daily routine words inside a food conversation.",
        ],
        speakingOutcomes: [
            "By the end of this unit, the student can talk about what they eat in a normal day.",
            "The student can say what they want to eat or drink.",
            "The student can handle a short home visit where someone offers food, tea, or coffee.",
        ],
    },

    vocabulary: {
        core: [
            {
                id: "akl",
                ar: "أَكْل",
                en: "food",
                enArabeezy: "akl",
                hint: "General word for food. My food = أَكْلِي. Home food = أَكْل البِيت.",
                exampleAr: "أَكْل البِيت أَزْكَى مِن المَطْعَم.",
                exampleArabeezy: "akl el-beet azka min el-maT3am.",
                exampleEn: "Home food is tastier than restaurant food.",
            },
            {
                id: "fuToor",
                ar: "فُطُور",
                en: "breakfast",
                enArabeezy: "fuToor",
                hint: "Morning meal. Verb: بَفْطَر = I have breakfast.",
                exampleAr: "الصُّبُح بَفْطَر خُبِز وَجُبْنَة.",
                exampleArabeezy: "el-soboh bafTar khobez w jibneh.",
                exampleEn: "In the morning I have bread and cheese for breakfast.",
            },
            {
                id: "ghada",
                ar: "غَدَا",
                en: "lunch",
                enArabeezy: "ghada",
                hint: "Main family meal in many homes. Verb: بِتْغَدَّى = I have lunch.",
                exampleAr: "بَعْد الضُّهُر بَاكُل الغَدَا مَع أَهْلِي.",
                exampleArabeezy: "ba3d el-duhur baakul el-ghada ma3 ahli.",
                exampleEn: "In the afternoon I eat lunch with my family.",
            },
            {
                id: "3asha",
                ar: "عَشَا",
                en: "dinner / evening meal",
                enArabeezy: "3asha",
                hint: "Evening meal. Verb: بِتْعَشَّى. Often lighter than lunch.",
                exampleAr: "بِالمَسَا بِنِتْعَشَّى إِشِي خَفِيف.",
                exampleArabeezy: "bel-masa bnit3asha ishi khafeef.",
                exampleEn: "In the evening we have a light dinner.",
            },
            {
                id: "khobez",
                ar: "خُبِز",
                en: "bread",
                enArabeezy: "khobez",
                hint: "Very common with almost every meal. A loaf = رَغِيف خُبِز.",
                exampleAr: "خُبِز وَزَيْت زَيْتُون فُطُور بَسِيط وَزَاكِي.",
                exampleArabeezy: "khobez w zeit zaytoon fuToor baseeT w zaki.",
                exampleEn: "Bread and olive oil is a simple and tasty breakfast.",
            },
            {
                id: "jibneh",
                ar: "جُبْنَة",
                en: "cheese",
                enArabeezy: "jibneh",
                hint: "Common breakfast food. White cheese = جُبْنَة بَيْضَا.",
                exampleAr: "بَحِبّ جُبْنَة مَع خُبِز سُخْن.",
                exampleArabeezy: "ba7ibb jibneh ma3 khobez sokhon.",
                exampleEn: "I like cheese with warm bread.",
            },
            {
                id: "zeit_zaytoon",
                ar: "زَيْت زَيْتُون",
                en: "olive oil",
                enArabeezy: "zeit zaytoon",
                hint: "Basic Palestinian ingredient. Often eaten with bread and zaatar.",
                exampleAr: "سِتِّي بِحِبّ خُبِز مَع زَيْت زَيْتُون.",
                exampleArabeezy: "sitti bit7ibb khobez ma3 zeit zaytoon.",
                exampleEn: "My grandmother likes bread with olive oil.",
            },
            {
                id: "za3tar",
                ar: "زَعْتَر",
                en: "zaatar",
                enArabeezy: "za3tar",
                hint: "Thyme mix with sesame and spices. Common with bread and olive oil.",
                exampleAr: "زَعْتَر مَع شَاي إِشِي زَاكِي الصُّبُح.",
                exampleArabeezy: "za3tar ma3 shay ishi zaki el-soboh.",
                exampleEn: "Zaatar with tea is tasty in the morning.",
            },
            {
                id: "hummus",
                ar: "حُمُّص",
                en: "hummus",
                enArabeezy: "hummus",
                hint: "Very common with breakfast, dinner, or falafel.",
                exampleAr: "بِالمَسَا بَدِّي حُمُّص وَفَلَافِل.",
                exampleArabeezy: "bel-masa baddi hummus w falafel.",
                exampleEn: "In the evening I want hummus and falafel.",
            },
            {
                id: "falafel",
                ar: "فَلَافِل",
                en: "falafel",
                enArabeezy: "falafel",
                hint: "Very common in a sandwich. Often breakfast or dinner.",
                exampleAr: "كَتِير نَاس بِفْطَرُوا سَنْدَوِيش فَلَافِل.",
                exampleArabeezy: "kteer nas bifTaru sandawish falafel.",
                exampleEn: "Many people have a falafel sandwich for breakfast.",
            },
            {
                id: "ruz",
                ar: "رُزّ",
                en: "rice",
                enArabeezy: "rozz",
                hint: "Common with chicken, meat, vegetables, and home cooking.",
                exampleAr: "سِتِّي عَامْلَة رُزّ وَجَاج.",
                exampleArabeezy: "sitti 3amleh rozz w jaj.",
                exampleEn: "My grandmother made rice and chicken.",
            },
            {
                id: "jaj",
                ar: "جَاج",
                en: "chicken",
                enArabeezy: "jaj",
                hint: "Spoken word for chicken. More natural in daily speech than دَجَاج.",
                exampleAr: "أَخُوي بِحِبّ الجَاج أَكْتَر مِن اللَّحْمَة.",
                exampleArabeezy: "akhuy bi7ibb el-jaj aktar min el-la7meh.",
                exampleEn: "My brother likes chicken more than meat.",
            },
            {
                id: "la7meh",
                ar: "لَحْمَة",
                en: "meat",
                enArabeezy: "la7meh",
                hint: "General meat. You may hear لَحِم too.",
                exampleAr: "مِش جَاي عَلَى بَالِي لَحْمَة اليَوم.",
                exampleArabeezy: "mish jay 3ala bali la7meh el-yom.",
                exampleEn: "I don't feel like meat today.",
            },
            {
                id: "samak",
                ar: "سَمَك",
                en: "fish",
                enArabeezy: "samak",
                hint: "Important in Gaza because the sea is part of daily food culture.",
                exampleAr: "فِي غَزَّة السَّمَك طَازَة وَزَاكِي.",
                exampleArabeezy: "fi ghazza el-samak Tazeh w zaki.",
                exampleEn: "In Gaza, fish is fresh and tasty.",
            },
            {
                id: "maqlubeh",
                ar: "مَقْلُوبِة",
                en: "maqlubeh",
                enArabeezy: "maqlubeh",
                hint: "Famous Palestinian rice dish with chicken/meat and vegetables.",
                exampleAr: "مَقْلُوبِة جَاج مِن أَشْهَر أَكَلَات فِلَسْطِين.",
                exampleArabeezy: "maqlubeh jaj min ashhar aklat falasteen.",
                exampleEn: "Chicken maqlubeh is one of the most famous Palestinian dishes.",
            },
            {
                id: "salata",
                ar: "سَلَطَة",
                en: "salad",
                enArabeezy: "salaTa",
                hint: "Usually with lunch. Plural/types: سَلَطَات.",
                exampleAr: "دَايْمًا فِي سَلَطَة مَع الغَدَا.",
                exampleArabeezy: "dayman fi salaTa ma3 el-ghada.",
                exampleEn: "There is always salad with lunch.",
            },
            {
                id: "khodar",
                ar: "خُضَار",
                en: "vegetables",
                enArabeezy: "khodar",
                hint: "Examples: بَنْدُورَة، خِيَار، بَطَاطَا، بَصَل.",
                exampleAr: "إِمِّي بِتِسَوِّي سَلَطَة خُضَار طَازَة.",
                exampleArabeezy: "immi bitisawwi salaTat khodar Tazeh.",
                exampleEn: "My mother makes a fresh vegetable salad.",
            },
            {
                id: "fawakeh",
                ar: "فَوَاكِه",
                en: "fruits",
                enArabeezy: "fawakeh",
                hint: "Examples: تُفَّاح، مَوْز، بُرْتُقَال، عِنَب.",
                exampleAr: "بَعْد الغَدَا بَاكُل فَوَاكِه.",
                exampleArabeezy: "ba3d el-ghada baakul fawakeh.",
                exampleEn: "After lunch I eat fruit.",
            },
            {
                id: "tuffa7_moz",
                ar: "تُفَّاح / مَوْز",
                en: "apples / bananas",
                enArabeezy: "tuffa7 / moz",
                hint: "One apple = تُفَّاحَة. One banana = مَوْزَة.",
                exampleAr: "أَخُوي بِحِبّ تُفَّاح، وَأُخْتِي بِتِحِبّ مَوْز.",
                exampleArabeezy: "akhuy bi7ibb tuffa7, w okhti bit7ibb moz.",
                exampleEn: "My brother likes apples, and my sister likes bananas.",
            },
            {
                id: "baharat",
                ar: "بَهَارَات",
                en: "spices",
                enArabeezy: "baharat",
                hint: "Useful for taste talk. Too much spice = بَهَارَات كْتِير.",
                exampleAr: "البَهَارَات فِي الجَاج حِلْوَة.",
                exampleArabeezy: "el-baharat fi el-jaj 7ilweh.",
                exampleEn: "The spices in the chicken are nice.",
            },
            {
                id: "mayy",
                ar: "مَيّ",
                en: "water",
                enArabeezy: "mayy",
                hint: "Very frequent. I want water = بَدِّي مَيّ.",
                exampleAr: "أَنَا عَطْشَان، بَدِّي مَيّ.",
                exampleArabeezy: "ana 3aTshan, baddi mayy.",
                exampleEn: "I'm thirsty, I want water.",
            },
            {
                id: "ahweh",
                ar: "قَهْوَة",
                en: "coffee",
                enArabeezy: "ahweh",
                hint: "In spoken Gaza pronunciation often sounds like أَهْوَة.",
                exampleAr: "الصُّبُح بَشْرَب قَهْوَة.",
                exampleArabeezy: "el-soboh bashrab ahweh.",
                exampleEn: "In the morning I drink coffee.",
            },
            {
                id: "shay",
                ar: "شَاي",
                en: "tea",
                enArabeezy: "shay",
                hint: "Very common after food or with guests. Tea with mint = شَاي مَع نَعْنَاع.",
                exampleAr: "سِتِّي بِتِحِبّ شَاي مَع نَعْنَاع.",
                exampleArabeezy: "sitti bit7ibb shay ma3 na3na3.",
                exampleEn: "My grandmother loves tea with mint.",
            },
            {
                id: "3aseer",
                ar: "عَصِير",
                en: "juice",
                enArabeezy: "3aseer",
                hint: "Plural/types: عَصَايِر. Orange juice = عَصِير بُرْتُقَال.",
                exampleAr: "بَدِّي عَصِير بُرْتُقَال.",
                exampleArabeezy: "baddi 3aseer bortuqal.",
                exampleEn: "I want orange juice.",
            },
            {
                id: "ja3an",
                ar: "جَعَان / جَعَانَة",
                en: "hungry",
                enArabeezy: "ja3an / ja3aneh",
                hint: "Male: جَعَان. Female: جَعَانَة. Plural: جَعَانِين.",
                exampleAr: "أَنَا جَعَانَة، بَدِّي آكُل.",
                exampleArabeezy: "ana ja3aneh, baddi aakul.",
                exampleEn: "I'm hungry, I want to eat.",
            },
            {
                id: "3atshan",
                ar: "عَطْشَان / عَطْشَانَة",
                en: "thirsty",
                enArabeezy: "3atshan / 3atshaneh",
                hint: "Male: عَطْشَان. Female: عَطْشَانَة. Plural: عَطْشَانِين.",
                exampleAr: "أَنَا عَطْشَان، بَدِّي مَيّ.",
                exampleArabeezy: "ana 3atshan, baddi mayy.",
                exampleEn: "I'm thirsty, I want water.",
            },
            {
                id: "zaki",
                ar: "زَاكِي / زَاكِيَة",
                en: "tasty / delicious",
                enArabeezy: "zaki / zakiyeh",
                hint: "Male: زَاكِي. Female: زَاكِيَة. Plural: زَاكْيِين.",
                exampleAr: "الجَاج زَاكِي كْتِير.",
                exampleArabeezy: "el-jaj zaki kteer.",
                exampleEn: "The chicken is very tasty.",
            },
            {
                id: "mish_zaki",
                ar: "مِش زَاكِي",
                en: "not tasty",
                enArabeezy: "mish zaki",
                hint: "Simple taste opinion. Softer: مِش كْتِير زَاكِي = not very tasty.",
                exampleAr: "بِصَرَاحَة الأَكْل اليَوم مِش زَاكِي.",
                exampleArabeezy: "biSara7a el-akl el-yom mish zaki.",
                exampleEn: "Honestly, today's food is not tasty.",
            },
            {
                id: "mish_jay_3ala_bali",
                ar: "مِش جَاي عَلَى بَالِي",
                en: "I don't feel like / nothing sounds good",
                enArabeezy: "mish jay 3ala bali",
                hint: "Natural answer when someone asks what you want to eat and you are unsure.",
                exampleAr: "مِش جَاي عَلَى بَالِي أَكْل كْتِير.",
                exampleArabeezy: "mish jay 3ala bali akl kteer.",
                exampleEn: "I don't feel like eating a lot.",
            },
            {
                id: "ba7ibb",
                ar: "بَحِبّ",
                en: "I like / I love",
                enArabeezy: "ba7ibb",
                hint: "Use with food, drinks, people, activities. He likes = بِحِبّ. She likes = بِتِحِبّ.",
                exampleAr: "بَحِبّ الأَكْل الفِلَسْطِينِي كْتِير.",
                exampleArabeezy: "ba7ibb el-akl el-falasteeni kteer.",
                exampleEn: "I really like Palestinian food.",
            },
            {
                id: "ma_ba7ibb",
                ar: "مَا بَحِبّ",
                en: "I don't like",
                enArabeezy: "ma ba7ibb",
                hint: "Simple negation for preferences. Softer: مَا بَحِبّ كْتِير.",
                exampleAr: "مَا بَحِبّ الأَكْل الحَارّ.",
                exampleArabeezy: "ma ba7ibb el-akl el-7arr.",
                exampleEn: "I don't like spicy food.",
            },
            {
                id: "baddi",
                ar: "بَدِّي",
                en: "I want",
                enArabeezy: "baddi",
                hint: "Use to ask/order: بَدِّي مَيّ / بَدِّي فَلَافِل. To ask: بَدَّك؟ / بَدِّك؟",
                exampleAr: "بَدِّي مَيّ أَوَّل إِشِي.",
                exampleArabeezy: "baddi mayy awwal ishi.",
                exampleEn: "I want water first.",
            },
            {
                id: "shbi3t",
                ar: "شْبِعِت",
                en: "I'm full",
                enArabeezy: "shbi3t",
                hint: "Very useful when refusing more food politely: لَا يِسْلَمُوا، شْبِعِت.",
                exampleAr: "يِسْلَمُوا، شْبِعِت، الأَكْل زَاكِي.",
                exampleArabeezy: "yislamu, shbi3t, el-akl zaki.",
                exampleEn: "Thanks, I'm full, the food is tasty.",
            },
            {
                id: "sa77a_w_3afyeh",
                ar: "صَحَّة وَعَافْيَة",
                en: "enjoy / bon appetit",
                enArabeezy: "sa77a w 3afyeh",
                hint: "Said when serving food or when someone is eating. Reply: الله يْعَافِيك.",
                exampleAr: "تْفَضَّلُوا، صَحَّة وَعَافْيَة.",
                exampleArabeezy: "tfaddalu, sa77a w 3afyeh.",
                exampleEn: "Here you go, enjoy.",
            },
        ],
    },

    dialogue: {
        title: "Real Situation - Lunch at Grandma's House",
        setting: "Rami is going to eat lunch at his grandmother's house. His aunt calls him before he arrives, then they sit together for lunch.",
        lines: [
            { speaker: "Khala", ar: "مَرْحَبَا رَامِي، وِين وَصَلْت؟", arArabeezy: "marhaba rami, wen wSilt?", en: "Hi Rami, where have you reached?" },
            { speaker: "Rami", ar: "أَهْلِين خَالْتِي، أَنَا قَرِيب مِن بِيت سِتِّي.", arArabeezy: "ahleen khalti, ana qareeb min beet sitti.", en: "Hi auntie, I'm close to my grandmother's house." },
            { speaker: "Khala", ar: "تَمَام، سِتَّك مِسْتَنْيَاك عَالغَدَا.", arArabeezy: "tamam, sittak mistannyak 3al-ghada.", en: "Great, your grandmother is waiting for you for lunch." },
            { speaker: "Rami", ar: "شُو عَامْلَة اليَوم؟ أَنَا جَعَان شُوَيّ.", arArabeezy: "sho 3amleh el-yom? ana ja3an shway.", en: "What did she make today? I'm a little hungry." },
            { speaker: "Khala", ar: "عَامْلَة رُزّ وَجَاج وَسَلَطَة.", arArabeezy: "3amleh rozz w jaj w salaTa.", en: "She made rice, chicken, and salad." },
            { speaker: "Rami", ar: "مُمْتَاز. بَس مِش جَاي عَلَى بَالِي أَكْل كْتِير.", arArabeezy: "mumtaz. bas mish jay 3ala bali akl kteer.", en: "Excellent. But I don't feel like eating a lot." },
            { speaker: "Khala", ar: "وَلَا يِهِمَّك، كُل شُوَيّ جَاج وَسَلَطَة.", arArabeezy: "wala yhemmak, kol shway jaj w salaTa.", en: "No problem, eat a little chicken and salad." },
            { speaker: "Rami", ar: "فِي مَيّ؟ أَنَا عَطْشَان.", arArabeezy: "fi mayy? ana 3atshan.", en: "Is there water? I'm thirsty." },
            { speaker: "Khala", ar: "آه، فِي مَيّ وَعَصِير. بَدَّك مَيّ؟", arArabeezy: "ah, fi mayy w 3aseer. baddak mayy?", en: "Yes, there is water and juice. Do you want water?" },
            { speaker: "Rami", ar: "آه، مَيّ أَوَّل إِشِي.", arArabeezy: "ah, mayy awwal ishi.", en: "Yes, water first." },
            { speaker: "Khala", ar: "طَيِّب تَعَال بِسُرْعَة قَبِل مَا يِبْرَد الرُّزّ.", arArabeezy: "tayyib ta3al bisur3a qabel ma yibrad el-rozz.", en: "Okay, come quickly before the rice gets cold." },
            { speaker: "Rami", ar: "دَقِيقْتِين وَبَوْصَل.", arArabeezy: "da2ee2teen w bawSal.", en: "Two minutes and I'll arrive." },
            { speaker: "Rami", ar: "آه وَصِلْت. السَّلَام عَلِيكُم.", arArabeezy: "ah wSilt. el-salam 3aleekom.", en: "I arrived. Peace be upon you." },
            { speaker: "Sitti", ar: "وَعَلِيكُم السَّلَام يَا حَبِيبِي، تْفَضَّل.", arArabeezy: "w 3aleekom el-salam ya 7abeebi, tfaddal.", en: "Peace be upon you too, dear, come in." },
            { speaker: "Khala", ar: "اُقْعُد هِنَا جَنْب سِتَّك.", arArabeezy: "u23od hena jamb sittak.", en: "Sit here next to your grandmother." },
            { speaker: "Rami", ar: "يِسْلَمُوا إِيدِيكِي يَا سِتِّي، رِيحِة الأَكْل بِتْفَتِّح النَّفْس.", arArabeezy: "yislamu eedeki ya sitti, ree7et el-akl bitfatti7 el-nafs.", en: "Bless your hands, grandma, the smell of the food makes me hungry." },
            { speaker: "Sitti", ar: "تْفَضَّل كُل، صَحَّة وَعَافْيَة.", arArabeezy: "tfaddal kol, sa77a w 3afyeh.", en: "Go ahead and eat, enjoy." },
            { speaker: "Khala", ar: "حَطِّيتْلَك رُزّ وَجَاج وَسَلَطَة.", arArabeezy: "7aTTeetlak rozz w jaj w salaTa.", en: "I put rice, chicken, and salad for you." },
            { speaker: "Rami", ar: "الله يْعَافِيكِي. الجَاج زَاكِي، وَالبَهَارَات حِلْوَة.", arArabeezy: "allah y3afeeki. el-jaj zaki, w el-baharat 7ilweh.", en: "Thank you. The chicken is tasty, and the spices are nice." },
            { speaker: "Sitti", ar: "إِمَّك بِتِحِبّ البَهَارَات هِيك كَمَان.", arArabeezy: "immak bit7ibb el-baharat heek kaman.", en: "Your mother likes spices like this too." },
            { speaker: "Rami", ar: "آه، بَس السَّلَطَة بَدْهَا شُوَيِّة مِلِح.", arArabeezy: "ah, bas el-salaTa badha shwayyet mili7.", en: "Yes, but the salad needs a little salt." },
            { speaker: "Khala", ar: "بَحُطِّلَك مِلِح شُوَيّ. هِيك أَحْسَن؟", arArabeezy: "ba7uTTilak mili7 shway. heek a7san?", en: "I'll put a little salt for you. Is this better?" },
            { speaker: "Rami", ar: "آه، هَلْقِيت زَاكِيَة.", arArabeezy: "ah, halla2et zakiyeh.", en: "Yes, now it's tasty." },
            { speaker: "Sitti", ar: "بَدَّك كَمَان جَاج؟", arArabeezy: "baddak kaman jaj?", en: "Do you want more chicken?" },
            { speaker: "Rami", ar: "لَا يِسْلَمُوا، شْبِعِت.", arArabeezy: "la yislamu, shbi3t.", en: "No thanks, I'm full." },
            { speaker: "Khala", ar: "بَعْد الغَدَا فِي شَاي وَفَوَاكِه.", arArabeezy: "ba3d el-ghada fi shay w fawakeh.", en: "After lunch there is tea and fruit." },
            { speaker: "Rami", ar: "شَاي مُمْتَاز، وَالفَوَاكِه بَعْدِين.", arArabeezy: "shay mumtaz, w el-fawakeh ba3deen.", en: "Tea is excellent, and fruit later." },
            { speaker: "Sitti", ar: "اِشْرَب شَاي قَبِل مَا تْرُوح.", arArabeezy: "ishrab shay qabel ma troo7.", en: "Drink tea before you go." },
            { speaker: "Rami", ar: "أَكِيد. شَاي سِتِّي مَا بِنْرَفَض.", arArabeezy: "akeed. shay sitti ma binrafad.", en: "Of course. Grandma's tea can't be refused." },
            { speaker: "Khala", ar: "وَبِالمَسَا إِذَا ضَلِّيت، بِنْجِيب حُمُّص وَفَلَافِل.", arArabeezy: "w bel-masa iza Dalleet, binjeeb hummus w falafel.", en: "And in the evening, if you stay, we'll bring hummus and falafel." },
            { speaker: "Rami", ar: "لَا هِيك يَوم كَامِل أَكْل عِنْدْكُم!", arArabeezy: "la heek yom kamel akl 3indkum!", en: "No, then it's a whole day of food at your place!" },
            { speaker: "Sitti", ar: "البِيت بِيتَك يَا حَبِيبِي.", arArabeezy: "el-beet beetak ya 7abeebi.", en: "Make yourself at home, dear." },
        ],
        questions: [
            { ar: "رَامِي كَان قَرِيب مِن بِيت مِين؟", en: "Whose house was Rami close to?" },
            { ar: "سِتّ رَامِي كَانَت مِسْتَنْيَاه عَلَى شُو؟", en: "What was Rami's grandmother waiting for him for?" },
            { ar: "سِتُّه عَامْلَة شُو عَلَى الغَدَا؟", en: "What did his grandmother make for lunch?" },
            { ar: "رَامِي قَال مِش جَاي عَلَى بَالُه شُو؟", en: "What did Rami say he did not feel like doing?" },
            { ar: "رَامِي كَان عَطْشَان وطلب شُو؟", en: "Rami was thirsty and asked for what?" },
            { ar: "رَامِي قَال لِسِتُّه شُو عَن رِيحِة الأَكْل؟", en: "What did Rami say to his grandmother about the smell of the food?" },
            { ar: "الخَالَة حَطِّت لِرَامِي شُو؟", en: "What did the aunt put for Rami?" },
            { ar: "رَامِي قَال الجَاج كِيف؟", en: "What did Rami say about the chicken?" },
            { ar: "السَّلَطَة كَان بَدْهَا شُو؟", en: "What did the salad need?" },
            { ar: "لَمَّا سِتُّه سَأَلَتُه بَدَّك كَمَان جَاج، رَدّ شُو؟", en: "When his grandmother asked if he wanted more chicken, what did he reply?" },
            { ar: "بَعْد الغَدَا كَان فِي شُو؟", en: "What was there after lunch?" },
            { ar: "بِالمَسَا الخَالَة قَالَت مُمْكِن يِجِيبُوا شُو؟", en: "In the evening, what did the aunt say they might bring?" },
            { ar: "اِحْكِي قِصِّة رَامِي عِنْد سِتُّه بِخَمْس جُمَل.", en: "Tell Rami's story at his grandmother's in five sentences." },
            { ar: "اِحْكِي عَن أَكْلَة بِتِحِبَّهَا: مِين بِيِعْمَلْهَا؟ وَإِمْتَى بْتَاكُلْهَا؟", en: "Talk about a food you like: who makes it and when do you eat it?" },
        ],
    },

    grammar: [
        {
            title: "1. The Palestinian imperative: inviting and directing",
            short: "كُل / كُلِي / كُلُوا — اِشْرَب / اِشْرَبِي / اِشْرَبُوا",
            description: "The imperative addresses the listener directly, so Palestinian Arabic changes it for one man, one woman, and a group. Around food, an imperative is not automatically rude: تْفَضَّل كُل can be warm hospitality. Tone, relationship, and words such as تْفَضَّل and لَو سَمَحْت determine politeness.",
            table: {
                title: "High-frequency food commands",
                headers: ["Meaning", "To one man", "To one woman", "To a group"],
                rows: [
                    ["eat", "كُل (kol)", "كُلِي (koli)", "كُلُوا (kolu)"],
                    ["drink", "اِشْرَب (ishrab)", "اِشْرَبِي (ishrabi)", "اِشْرَبُوا (ishrabu)"],
                    ["take", "خُد (khod)", "خُدِي (khodi)", "خُدُوا (khodu)"],
                    ["bring", "جِيب (jeeb)", "جِيبِي (jeebi)", "جِيبُوا (jeebu)"],
                    ["put", "حُطّ (7uTT)", "حُطِّي (7uTTi)", "حُطُّوا (7uTTu)"],
                    ["taste / try", "دُوق (doo2)", "دُوقِي (doo2i)", "دُوقُوا (doo2u)"],
                ],
            },
            examples: [
                { ar: "تْفَضَّل كُل، الأَكْل لِسَّه سَاخِن.", arabeezy: "tfaddal kol, el-akel lissa sakhin.", en: "Go ahead and eat; the food is still hot. (to a man)" },
                { ar: "دُوقِي السَّلَطَة وَاحْكِيلِي رَأْيِك.", arabeezy: "doo2i es-salaTa w i7keeli ra2yik.", en: "Taste the salad and tell me what you think. (to a woman)" },
                { ar: "خُدُوا رَاحِتْكُم وَكُلُوا.", arabeezy: "khodu ra7etkum w kolu.", en: "Make yourselves comfortable and eat. (to a group)" },
            ],
            commonMistakes: [
                "Do not use the masculine singular command for everyone. To one woman, the common ending is ـي; to a group, it is ـوا.",
                "The command is not formed by keeping the present بـ: اِشْرَب, not بِتْشْرَب when telling someone to drink.",
                "A bare command can sound sharp with a stranger. Add لَو سَمَحْت, مُمْكِن, or use a request with بَدِّي in service situations.",
            ],
            exercises: [
                { prompt: "You are offering food to one woman. Choose ‘Eat.’", options: ["كُلِي", "كُل", "كُلُوا"], correct: "كُلِي", explanation: "The feminine singular command ends in ـي: كُلِي." },
                { prompt: "Choose the group command: ‘Drink the tea.’", options: ["اِشْرَبُوا الشَّاي.", "اِشْرَبِي الشَّاي.", "بِتْشْرَبُوا الشَّاي."], correct: "اِشْرَبُوا الشَّاي.", explanation: "The group imperative uses ـوا and does not keep the present-tense بـ." },
                { prompt: "Which is the warmest invitation to one male guest?", options: ["تْفَضَّل كُل.", "كُل هَلْقِيت!", "إِنْتَ بِتَاكُل."], correct: "تْفَضَّل كُل.", explanation: "تْفَضَّل frames the command as hospitality and invitation." },
            ],
        },
        {
            title: "2. Wanting, offering, and requesting politely",
            short: "بَدِّي — بَدَّك؟ — مُمْكِن؟ — لَو سَمَحْت",
            description: "In restaurants and homes, Palestinian speakers often avoid direct commands by using بَدِّي (‘I want / I’d like’), questions with بَدَّك؟ (‘do you want?’), and مُمْكِن؟ (‘is it possible / could I?’). These are complete spoken patterns, and بَدّ changes with the person who wants something.",
            table: {
                title: "The spoken pattern بَدّ + person ending",
                headers: ["Person", "Form", "Arabizi", "Food example"],
                rows: [
                    ["I", "بَدِّي", "baddi", "بَدِّي قَهْوَة"],
                    ["you, man", "بَدَّك", "baddak", "بَدَّك شَاي؟"],
                    ["you, woman", "بَدِّك", "baddik", "بَدِّك تَاكْلِي؟"],
                    ["he", "بَدُّه", "biddo", "بَدُّه مَيّ"],
                    ["she", "بَدَّهَا", "baddha", "بَدَّهَا سَلَطَة"],
                    ["we", "بَدِّنَا", "baddna", "بَدِّنَا نُطْلُب"],
                    ["you all", "بَدْكُم", "baddkum", "شُو بَدْكُم؟"],
                    ["they", "بَدْهُم", "baddhum", "بَدْهُم يَاكْلُوا"],
                ],
            },
            examples: [
                { ar: "لَو سَمَحْت، بَدِّي شَاي بِمَرَمِيَّة.", arabeezy: "law sama7t, baddi shay b-maramiyyeh.", en: "Please, I’d like tea with sage." },
                { ar: "بَدِّك كَمَان رُزّ؟ — لَا يِسْلَمُوا، شْبِعِت.", arabeezy: "baddik kaman ruzz? — la yislamu, shbi3t.", en: "Would you like more rice? — No, thank you; I’m full. (to a woman)" },
                { ar: "مُمْكِن تْجِيبْلَنَا الحِسَاب؟", arabeezy: "mumkin tjeeblna el-7sab?", en: "Could you bring us the bill?" },
            ],
            commonMistakes: [
                "بَدِّي is not a verb conjugated like بَرُوح. Treat the forms بَدِّي، بَدَّك، بَدُّه as a high-frequency family of chunks.",
                "بَدِّي can sound direct if tone is demanding. In service encounters, لَو سَمَحْت or مُمْكِن makes the request softer.",
                "When refusing hospitality, a plain لَا may feel abrupt. Add يِسْلَمُوا, شُكْرًا, شْبِعِت, or خَلَاص كَفَايَة.",
            ],
            exercises: [
                { prompt: "Choose: ‘She wants a salad.’", options: ["هِيَّ بَدَّهَا سَلَطَة.", "هِيَّ بَدِّي سَلَطَة.", "هِيَّ بَدَّك سَلَطَة."], correct: "هِيَّ بَدَّهَا سَلَطَة.", explanation: "The feminine third-person form is بَدَّهَا: she wants." },
                { prompt: "Which is the most suitable restaurant request?", options: ["مُمْكِن تْجِيبْلَنَا مَيّ؟", "جِيب مَيّ!", "إِنْتَ مَيّ."], correct: "مُمْكِن تْجِيبْلَنَا مَيّ؟", explanation: "مُمْكِن turns the action into a polite request." },
                { prompt: "Complete: إِحْنَا ___ نُطْلُب صَيَّادِيَّة. (we want)", options: ["بَدِّنَا", "بَدْهُم", "بَدُّه"], correct: "بَدِّنَا", explanation: "The ending ـنَا gives the meaning ‘we want’." },
            ],
        },
        {
            title: "3. Food quantities and basic counting chunks",
            short: "حَبَّة، كَاسَة، صَحْن، كِيلُو، نُصّ، شُوَيِّة",
            description: "Food is rarely counted as isolated dictionary nouns. Palestinian speakers use containers and measure words: a cup of tea, a plate of hummus, half a kilo of tomatoes, or a little salt. Learn the whole quantity+noun chunk. Everyday number forms are simpler than full formal-Arabic case rules, but the counted expression still needs to sound natural.",
            table: {
                title: "Useful quantity patterns",
                headers: ["Quantity", "Palestinian chunk", "Arabizi", "Meaning"],
                rows: [
                    ["one item", "حَبَّة تُفَّاح", "7abbet tuffa7", "one apple / piece of apple"],
                    ["two cups", "كَاسْتَيْن شَاي", "kastein shay", "two cups of tea"],
                    ["three plates", "تَلَات صْحُون", "talat S7oon", "three plates"],
                    ["one kilo", "كِيلُو بَنْدُورَة", "kilo bandora", "a kilo of tomatoes"],
                    ["half a kilo", "نُصّ كِيلُو خِيَار", "noSS kilo khyar", "half a kilo of cucumbers"],
                    ["a little", "شُوَيِّة مِلِح", "shwayyet mili7", "a little salt"],
                    ["a bottle", "قَنِّينَة مَيّ", "qanneenet mayy", "a bottle of water"],
                ],
            },
            examples: [
                { ar: "بَدِّي نُصّ كِيلُو بَنْدُورَة وَكِيلُو خِيَار.", arabeezy: "baddi noSS kilo bandora w kilo khyar.", en: "I’d like half a kilo of tomatoes and a kilo of cucumbers." },
                { ar: "جِيبْلَنَا تَلَات كَاسَات شَاي وَقَنِّينَة مَيّ.", arabeezy: "jeeblna talat kasat shay w qanneenet mayy.", en: "Bring us three glasses of tea and a bottle of water." },
                { ar: "حُطّ شُوَيِّة سُكَّر، بَس مِش كْتِير.", arabeezy: "7uTT shwayyet sukkar, bas mish kteer.", en: "Put a little sugar, but not too much." },
            ],
            commonMistakes: [
                "Do not force English ‘of’ into Arabic with مِن: say كَاسَة شَاي, not كَاسَة مِن شَاي.",
                "حَبَّة is a flexible counter for individual fruit, vegetables, pills, and small items; its exact English translation depends on context.",
                "With three and above, spoken number shapes vary across Palestine. This course uses stable Gaza-friendly chunks such as تَلَات كَاسَات and تَلَات صْحُون before expanding the system in Shopping.",
            ],
            exercises: [
                { prompt: "Choose the natural phrase for ‘half a kilo of tomatoes’.", options: ["نُصّ كِيلُو بَنْدُورَة", "نُصّ مِن كِيلُو البَنْدُورَة", "بَنْدُورَة نُصّ"], correct: "نُصّ كِيلُو بَنْدُورَة", explanation: "The measure and food noun are placed directly together without مِن." },
                { prompt: "Which phrase means ‘a little salt’?", options: ["شُوَيِّة مِلِح", "مِلِح كِيلُو", "حَبَّة مِلِحَة"], correct: "شُوَيِّة مِلِح", explanation: "شُوَيِّة is the everyday quantity word for ‘a little/some’." },
                { prompt: "Complete: ___ شَاي means ‘two cups of tea’.", options: ["كَاسْتَيْن", "كَاسَة", "تَلَات كَاسَات"], correct: "كَاسْتَيْن", explanation: "كَاسْتَيْن is the common dual form: two cups/glasses." },
            ],
        },
        {
            title: "4. Feminine sound plurals in food and daily speech",
            short: "سَلَطَة ← سَلَطَات — كَاسَة ← كَاسَات",
            description: "Many feminine nouns ending in ـة form a spoken plural with ـات. Before adding ـات, the final ـة is heard as t: سَلَطَة → سَلَطَات. This is a useful pattern, not a promise: Arabic also has many broken plurals, so each new noun should still be learned with its real plural.",
            table: {
                title: "Common ـات plurals in this unit",
                headers: ["Singular", "Plural", "Arabizi plural", "Meaning"],
                rows: [
                    ["سَلَطَة", "سَلَطَات", "salaTat", "salads"],
                    ["كَاسَة", "كَاسَات", "kasat", "cups / glasses"],
                    ["وَجْبَة", "وَجْبَات", "wajbat", "meals"],
                    ["طَلْبِيَّة", "طَلْبِيَّات", "Talabiyyat", "orders"],
                    ["قَنِّينَة", "قَنَانِي / قَنِّينَات", "qanani / qanneenat", "bottles (two heard options)"],
                ],
            },
            examples: [
                { ar: "عِنْدْهُم سَلَطَات زَاكْيَات كْتِير.", arabeezy: "3indhum salaTat zakyat kteer.", en: "They have many tasty salads." },
                { ar: "بَدِّنَا تَلَات كَاسَات وَقَنِّينَتَيْن مَيّ.", arabeezy: "baddna talat kasat w qanneentein mayy.", en: "We want three glasses and two bottles of water." },
                { ar: "وَجْبَات المَطْعَم كْبِيرَة وَمْشَبِّعَة.", arabeezy: "wajbat el-maT3am kbeereh w mshabbi3a.", en: "The restaurant’s meals are large and filling." },
            ],
            commonMistakes: [
                "Do not add ـات to every feminine noun. مَدِينَة → مُدُن and فَاكْهَة → فَوَاكِه show that broken plurals remain common.",
                "Adjective agreement with non-human plurals varies in speech. You may hear plural agreement (سَلَطَات زَاكْيَات) and feminine-singular agreement in some contexts. Learn what speakers use with each chunk.",
                "The written ـة is pronounced as t when an ending follows or inside many connected forms: سَلَطَة → سَلَطَات.",
            ],
            exercises: [
                { prompt: "Choose the plural of سَلَطَة.", options: ["سَلَطَات", "سَلَطُون", "سُلُوط"], correct: "سَلَطَات", explanation: "Replace the feminine ending ـة with the plural ending ـات." },
                { prompt: "Which singular/plural pair is correct?", options: ["وَجْبَة ← وَجْبَات", "كَاسَة ← كَاسُون", "فَاكْهَة ← فَاكْهَات دائمًا"], correct: "وَجْبَة ← وَجْبَات", explanation: "وَجْبَات is a regular, common feminine sound plural." },
                { prompt: "What happens to the sound of ـة in سَلَطَات?", options: ["It becomes a clear t sound before ـات.", "It becomes w.", "It disappears with no plural ending."], correct: "It becomes a clear t sound before ـات.", explanation: "The connected stem exposes t: salaTa → salaTat." },
            ],
        },
    ],

    microChecks: {
        enabled: true,
        every: 5,
        items: [
            {
                id: "food_mc1",
                type: "match",
                prompt: "Match the English word to Arabic: lunch",
                options: ["غَدَا", "فُطُور", "عَشَا", "مَيّ"],
                correct: "غَدَا",
            },
            {
                id: "food_mc2",
                type: "complete",
                prompt: "Complete: بَدِّي حُمُّص وَ___.",
                options: ["فَلَافِل", "خُبِز", "زَعْتَر", "فُطُور"],
                correct: "فَلَافِل",
            },
            {
                id: "food_mc3",
                type: "reorder",
                prompt: "Reorder: The chicken is tasty.",
                options: ["الجَاج", "زَاكِي"],
                correct: ["الجَاج", "زَاكِي"],
            },
            {
                id: "food_mc4",
                type: "choose",
                prompt: "Choose the Arabic word for fruit:",
                options: ["فَوَاكِه", "خُضَار", "سَلَطَة", "بَهَارَات"],
                correct: "فَوَاكِه",
            },
            {
                id: "food_mc5",
                type: "complete",
                prompt: "Complete: الصُّبُح بَشْرَب ___.",
                options: ["قَهْوَة", "مَيّ", "شَاي", "عَصِير"],
                correct: "قَهْوَة",
            },
            { id: "food_mc6", type: "complete", prompt: "Complete: أَنَا جَعَان، بَدِّي ___.", options: ["آكُل", "أَشْرَب", "أَنَام", "أَرْجَع"], correct: "آكُل" },
            { id: "food_mc7", type: "choose", prompt: "Choose a polite way to refuse more food:", options: ["لَا يِسْلَمُوا، شْبِعِت.", "شُو اِسْمَك؟", "أَنَا مِن غَزَّة."], correct: "لَا يِسْلَمُوا، شْبِعِت." },
        ],
    },

    practice: {
        showRealUse: false,
        showWriting: false,
        separateExerciseTypes: true,
        showCompleteDialogue: false,
        quiz: [
            {
                id: "food_q1",
                questionAr: "Choose the English meaning of أَنَا جَعَان، بَدِّي آكُل.",
                optionsEn: ["I'm hungry, I want to eat.", "I'm thirsty, I want water.", "I'm full, thanks."],
                correctIndex: 0,
            },
            {
                id: "food_q2",
                questionAr: "Choose the English meaning of الجَاج زَاكِي.",
                optionsEn: ["The chicken is tasty.", "The chicken is salty.", "The chicken is cold."],
                correctIndex: 0,
            },
            {
                id: "food_q3",
                questionAr: "Choose a polite Palestinian Arabic phrase to refuse more food.",
                optionsEn: ["لَا يِسْلَمُوا، شْبِعِت.", "بَدِّي مَيّ.", "أَيّ سَاعَة؟"],
                correctIndex: 0,
            },
            {
                id: "food_q4",
                questionAr: "Choose the English meaning of مِش جَاي عَلَى بَالِي أَكْل كْتِير.",
                optionsEn: ["I don't feel like eating a lot.", "I want a lot of food.", "I don't like my family."],
                correctIndex: 0,
            },
            {
                id: "food_q5",
                questionAr: "Complete the sentence: بَعْد الغَدَا فِي شَاي وَ___.",
                optionsEn: ["فَوَاكِه", "أُجْرَة", "صَف"],
                correctIndex: 0,
            },
            {
                id: "food_q6",
                questionAr: "حَوِّل لِلْمُؤَنَّث: أَنَا جَعَان.",
                optionsEn: ["أَنَا جَعَانَة.", "أَنَا عَطْشَان.", "أَنَا زَاكِي."],
                correctIndex: 0,
            },
            {
                id: "food_q7",
                questionAr: "الرَّد عَلَى «صَحَّة وَعَافْيَة» مُمْكِن يِكُون:",
                optionsEn: ["الله يْعَافِيك", "شُو أَخْبَارَك؟", "مِن وِين؟"],
                correctIndex: 0,
            },
            {
                id: "food_q8",
                questionAr: "«مَا بَحِبّ الأَكْل الحَارّ» مَعْنَاهَا:",
                optionsEn: ["I don't like spicy food.", "I like spicy food.", "I want spicy food."],
                correctIndex: 0,
            },
            {
                id: "food_q9",
                questionAr: "«بَدِّي مَيّ أَوَّل إِشِي» مَعْنَاهَا:",
                optionsEn: ["I want water first.", "I want tea later.", "I want fruit after lunch."],
                correctIndex: 0,
            },
        ],
        rolePlays: [
            "You are visiting a Palestinian family. Accept one dish, ask for water, say what you like, and politely refuse more food when you are full.",
        ],
        sections: [
            {
                title: "A - Recognition",
                matching: [
                    { ar: "فُطُور", arabeezy: "fuToor", en: "breakfast" },
                    { ar: "غَدَا", arabeezy: "ghada", en: "lunch" },
                    { ar: "عَشَا", arabeezy: "3asha", en: "dinner" },
                    { ar: "مَيّ", arabeezy: "mayy", en: "water" },
                    { ar: "جَعَان", arabeezy: "ja3an", en: "hungry (male)" },
                    { ar: "شِبْعِت", arabeezy: "shbi3t", en: "I am full" },
                ],
                multipleChoice: [
                    { prompt: "Unit 3 review: Choose the meaning of الصُّبُح بَفْطَر (eS-Subu7 baftar).", options: ["I have breakfast in the morning.", "I sleep in the morning.", "I return in the morning."], correct: "I have breakfast in the morning." },
                    { prompt: "Choose the natural phrase for “I want water.”", options: ["بَدِّي مَيّ (baddi mayy).", "مَا بَحِبّ مَيّ (ma ba7ibb mayy).", "شِبْعِت (shbi3t)."], correct: "بَدِّي مَيّ (baddi mayy)." },
                ],
            },
            {
                title: "B - Guided practice",
                fillInTheBlank: [
                    { prompt: "Write the Palestinian Arabic for (water): أَنَا عَطْشَان، بَدِّي ___.", arabeezy: "ana 3atshan, baddi ___.", answer: "مَيّ" },
                    { prompt: "Write (tasty — masculine): الجَاج ___.", arabeezy: "el-jaj ___.", answer: "زَاكِي" },
                    { prompt: "Write (tasty — feminine): السَّلَطَة ___.", arabeezy: "es-salaTa ___.", answer: "زَاكِيَة" },
                    { prompt: "Write the correct form of (like): مَا ___ الأَكْل الحَارّ.", arabeezy: "ma ___ el-akl el-7arr.", answer: "بَحِبّ" },
                    { prompt: "Write the Palestinian Arabic for (tea): بَعْد الغَدَا بَشْرَب ___.", arabeezy: "ba3d el-ghada bashrab ___.", answer: "شَاي" },
                    { prompt: "Write the Palestinian Arabic for (hungry — masculine): هُوَّ ___.", arabeezy: "huwwe ___.", answer: "جَعَان" },
                    { prompt: "Write the Palestinian Arabic for (hungry — feminine): هِيَّ ___.", arabeezy: "hiyyeh ___.", answer: "جَعَانَة" },
                    { prompt: "Write the Palestinian Arabic for (I am full): لَا يِسْلَمُوا، ___.", arabeezy: "la yislamu, ___.", answer: "شِبْعِت" },
                    { prompt: "Write the Palestinian Arabic for (I want): ___ قَهْوَة مَع حَلِيب.", arabeezy: "___ ahweh ma3 7aleeb.", answer: "بَدِّي" },
                    { prompt: "Write the correct form of (drink): الصُّبُح ___ قَهْوَة.", arabeezy: "eS-Subu7 ___ ahweh.", answer: "بَشْرَب" },
                    { prompt: "Unit 3 review — write (have breakfast): الصُّبُح ___ مَع أَهْلِي.", arabeezy: "eS-Subu7 ___ ma3 ahli.", answer: "بَفْطَر" },
                    { prompt: "Unit 2 review — write (my grandmother): ___ بِتِعْمَل شَاي.", arabeezy: "___ bti3mal shay.", answer: "سِتِّي" },
                ],
                correctTheMistake: [
                    { prompt: "Correct the sentence: هِيَّ جَعَان.", arabeezy: "hiyyeh ja3an.", answer: "هِيَّ جَعَانَة." },
                    { prompt: "Correct the sentence: أَنَا مِش بَحِبّ السَّمَك.", arabeezy: "ana mish ba7ibb es-samak.", answer: "أَنَا مَا بَحِبّ السَّمَك." },
                    { prompt: "Correct the sentence: السَّلَطَة زَاكِي.", arabeezy: "es-salaTa zaki.", answer: "السَّلَطَة زَاكِيَة." },
                    { prompt: "Review loop — correct it: إِنْتِ بِتْفَطَّر الصُّبُح.", arabeezy: "inti btifaTTar eS-Subu7.", answer: "إِنْتِ بِتْفَطْرِي الصُّبُح." },
                    { prompt: "Use the feminine form. Correct: هِيَّ عَطْشَان.", arabeezy: "hiyyeh 3atshan.", answer: "هِيَّ عَطْشَانَة." },
                    { prompt: "Use ما with the present verb. Correct: أَنَا مِش بَحِبّ القَهْوَة.", arabeezy: "ana mish ba7ibb el-ahweh.", answer: "أَنَا مَا بَحِبّ القَهْوَة." },
                ],
                reorderSentences: [
                    { prompt: "Build: I want hummus and falafel.", arabeezy: "baddi hummus w falafel.", words: ["بَدِّي", "حُمُّص", "وَفَلَافِل."], answer: "بَدِّي حُمُّص وَفَلَافِل." },
                    { prompt: "Build: I do not like spicy food.", arabeezy: "ma ba7ibb el-akl el-7arr.", words: ["مَا بَحِبّ", "الأَكْل", "الحَارّ."], answer: "مَا بَحِبّ الأَكْل الحَارّ." },
                    { prompt: "Build: After lunch I drink tea.", arabeezy: "ba3d el-ghada bashrab shay.", words: ["بَعْد الغَدَا", "بَشْرَب", "شَاي."], answer: "بَعْد الغَدَا بَشْرَب شَاي." },
                    { prompt: "Review loop — build: I have breakfast with my family.", arabeezy: "baftar ma3 ahli.", words: ["بَفْطَر", "مَع", "أَهْلِي."], answer: "بَفْطَر مَع أَهْلِي." },
                    { prompt: "Put the words in order: I am thirsty and I want water.", arabeezy: "ana 3atshan w baddi mayy.", words: ["مَيّ.", "وَبَدِّي", "أَنَا", "عَطْشَان"], answer: "أَنَا عَطْشَان وَبَدِّي مَيّ." },
                    { prompt: "Put the words in order: No thanks, I am full.", arabeezy: "la yislamu, shbi3t.", words: ["شِبْعِت.", "لَا", "يِسْلَمُوا،"], answer: "لَا يِسْلَمُوا، شِبْعِت." },
                ],
            },
        ],
        translation: [
            { id: "food_t1", type: "enToAr", textEn: "I'm hungry, I want to eat.", textAr: "أَنَا جَعَان/جَعَانَة، بَدِّي آكُل." },
            { id: "food_t2", type: "arToEn", textEn: "I'm thirsty, I want water.", textAr: "أَنَا عَطْشَان/عَطْشَانَة، بَدِّي مَيّ." },
            { id: "food_t3", type: "enToAr", textEn: "My grandmother made rice and chicken.", textAr: "سِتِّي عَامْلَة رُزّ وَجَاج." },
            { id: "food_t4", type: "arToEn", textEn: "The chicken is tasty, and the spices are nice.", textAr: "الجَاج زَاكِي، وَالبَهَارَات حِلْوَة." },
            { id: "food_t5", type: "enToAr", textEn: "I don't feel like eating a lot.", textAr: "مِش جَاي عَلَى بَالِي أَكْل كْتِير." },
            { id: "food_t6", type: "arToEn", textEn: "No thanks, I'm full.", textAr: "لَا يِسْلَمُوا، شْبِعِت." },
            { id: "food_t7", type: "enToAr", textEn: "After lunch there is tea and fruit.", textAr: "بَعْد الغَدَا فِي شَاي وَفَوَاكِه." },
            { id: "food_t8", type: "arToEn", textEn: "I like bread and cheese in the morning.", textAr: "بَحِبّ خُبِز وَجُبْنَة الصُّبُح." },
            { id: "food_t9", type: "enToAr", textEn: "I don't like spicy food.", textAr: "مَا بَحِبّ الأَكْل الحَارّ." },
            { id: "food_t10", type: "arToEn", textEn: "I want hummus and falafel, please.", textAr: "بَدِّي حُمُّص وَفَلَافِل، لَوْ سَمَحْت." },
            { id: "food_t11", type: "enToAr", textEn: "My sister likes apples and bananas.", textAr: "أُخْتِي بِتِحِبّ تُفَّاح وَمَوْز." },
            { id: "food_t12", type: "arToEn", textEn: "In Gaza, fish is fresh and tasty.", textAr: "فِي غَزَّة السَّمَك طَازَة وَزَاكِي." },
            { id: "food_t13", type: "enToAr", textEn: "Here you go, enjoy.", textAr: "تْفَضَّل، صَحَّة وَعَافْيَة." },
            { id: "food_t14", type: "arToEn", textEn: "Grandma's tea can't be refused.", textAr: "شَاي سِتِّي مَا بِنْرَفَض." },
            { id: "food_t15", type: "enToAr", textEn: "Goodbye, see you later, take care.", textAr: "مَع السَّلَامَة، بِنْشُوفَك بَعْدِين، دِير بَالَك." },
        ],
    },

    homework: {
        instructions:
            `Write and record a 60-90 second story about food in your life in Palestinian Arabic. Mention: what you eat in the morning, what you drink, one food you like, one food you do not like, and what your family usually eats at home. Try to use at least 8 words from the vocabulary list and at least 3 words from previous units.

Translate these sentences into Gaza Palestinian Arabic:
1. Hi, how are you today?
2. I live with my family.
3. Every morning I drink coffee.
4. My grandmother makes tea with mint.
5. I am hungry, I want to eat.
6. I am thirsty, I want water.
7. I like bread and cheese.
8. I do not like spicy food.
9. My mother makes rice and chicken.
10. The food at home is very tasty.
11. I want hummus and falafel, please.
12. After lunch, I eat fruit.
13. My brother likes apples and bananas.
14. No thanks, I'm full.
15. Goodbye, see you later, take care.`,
    },

    teacherNotes: {
        warmup: [
            "Start with real life: شُو أَكَلْت اليَوم؟ شُو شِرِبْت الصُّبُح؟",
            "Recycle previous units through food: إِمِّي بِتِعْمَل، سِتِّي بِتِعْمَل، بَعْد الغَدَا، قَبِل مَا أَرُوح.",
            "Keep cultural expressions natural: صَحَّة وَعَافْيَة، يِسْلَمُوا إِيدِيكِي، البِيت بِيْتَك.",
        ],
        vocabularySteps: [
            "Teach food as chunks: بَدِّي مَيّ، بَحِبّ الجَاج، الأَكْل زَاكِي، أَنَا جَعَان.",
            "Keep dish names usable; special dishes like مَقْلُوبِة should appear in examples, not dominate the lesson.",
            "Ask the student to personalize every word immediately.",
        ],
        dialogueSteps: [
            "Treat the dialogue as a visit to grandmother's house, not a restaurant script.",
            "After reading, ask the student to retell: Rami is hungry, Sitti made food, he wants water, then tea.",
            "Have the student replace the foods with their own real foods.",
        ],
        practiceTips: [
            "Push complete answers: بَحِبّ القَهْوَة، مَا بَحِبّ اللَّحْمَة، بَدِّي مَيّ.",
            "Drill polite acceptance/refusal: يِسْلَمُوا، شْبِعِت، صَحَّة وَعَافْيَة.",
            "Use masculine/feminine hunger/thirst forms every lesson.",
        ],
        wrapup: [
            "Student says 5 foods/drinks they like.",
            "Student offers food and refuses more food politely.",
            "Student records a voice note about what they ate today.",
        ],
        myNotes: "",
    },
};
