export const lessonId = "Assessment-Beginner-Final";

export const lesson = {
    meta: {
        level: "Beginner",
        unit: "Beginner Final",
        lessonTitle: "Beginner Final Assessment",
        contentVersion: 2026071501,
        availableTabs: ["overview", "practice"],
    },
    overview: {
        title: "Beginner Final Assessment",
        description: "A scored end-of-level check for Units 1-5. Answers are submitted together, so the learner does not receive immediate correctness feedback.",
        goals: ["Measure recognition and sentence control.", "Identify topics that need review.", "Complete one teacher-scored speaking task."],
        speakingOutcomes: ["The learner can complete a connected beginner speaking situation with limited support."],
    },
    vocabulary: { core: [], extra: [] },
    dialogue: { title: "Assessment", setting: "Complete the Practice tab.", lines: [] },
    microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        assessmentMode: true,
        assessmentTitle: "Beginner Final",
        questions: [
            { prompt: "Choose the natural reply to: كِيفَك؟ (keefak?)", options: ["مْنِيح، الحَمْدُ لله.", "مِن وِين؟", "مَع السَّلَامَة."], correctIndex: 0, skill: "Greetings" },
            { prompt: "Choose the feminine form of سَاكِن (saken).", options: ["سَاكْنَة", "سَاكْنِين", "سَكَن"], correctIndex: 0, skill: "Gender" },
            { prompt: "Choose the meaning of عِنْدِي أُخْتِين.", options: ["I have two sisters.", "I have one sister.", "My sisters live here."], correctIndex: 0, skill: "Family" },
            { prompt: "Complete: أَنَا ___ أَهْلِي. (I live with my family.)", options: ["سَاكِن مَع", "مِن", "بَرُوح"], correctIndex: 0, skill: "Possession" },
            { prompt: "Choose the correct sentence for a woman: You wake up early.", options: ["إِنْتِ بِتْصْحِي بَدْرِي.", "إِنْتِ بِتْصْحَى بَدْرِي.", "إِنْتِ بَصْحَى بَدْرِي."], correctIndex: 0, skill: "Present tense" },
            { prompt: "Choose the verbal negative sentence.", options: ["اليَوم مَا بَرُوح عَالشُّغُل.", "اليَوم مِش بَرُوح عَالشُّغُل.", "اليَوم لَا بَرُوح عَالشُّغُل."], correctIndex: 0, skill: "Negation" },
            { prompt: "Choose the meaning of بَعْد مَا بَرْجَع، بَرْتَاح.", options: ["After I return, I rest.", "Before I return, I eat.", "I return after resting."], correctIndex: 0, skill: "Sequence" },
            { prompt: "Choose the feminine adjective: السَّلَطَة ___.", options: ["زَاكِيَة", "زَاكِي", "زَاكِيِين"], correctIndex: 0, skill: "Agreement" },
            { prompt: "Choose a polite refusal of more food.", options: ["لَا يِسْلَمُوا، شِبْعِت.", "مَا بَحِبّ المَيّ.", "قَدِّيش الأُجْرَة؟"], correctIndex: 0, skill: "Food" },
            { prompt: "Choose the natural phrase for half a kilo.", options: ["نُصّ كِيلُو", "تْنِين كِيلُو", "نُصّ قِطْعَة"], correctIndex: 0, skill: "Quantity" },
            { prompt: "Choose the transport sentence: I take the bus every day.", options: ["بَرْكَب البَاص كُلّ يَوم.", "بَنْزَل البَاص كُلّ يَوم.", "بَمْشِي البَاص كُلّ يَوم."], correctIndex: 0, skill: "Transportation" },
            { prompt: "Choose the correct direction: Go straight, then turn right.", options: ["رُوح دُغْرِي، بَعْدِين لِف يَمِين.", "رُوح شِمَال، بَعْدِين اِنْزَل.", "بَنْزَل هِنَا، لَوْ سَمَحْت."], correctIndex: 0, skill: "Directions" },
            { prompt: "Choose the question used to ask the time.", options: ["أَيّ سَاعَة؟", "قَدِّيش الأُجْرَة؟", "شُو مَالَك؟"], correctIndex: 0, skill: "Questions" },
            { prompt: "Choose the correct preposition: بَرُوح ___ الجَامْعَة بِالبَاص.", options: ["عَـ", "مِن", "مَع"], correctIndex: 0, skill: "Prepositions" },
            { prompt: "Choose the polite driver phrase.", options: ["بَنْزَل هِنَا، لَوْ سَمَحْت.", "إِنْتَ غَلَط.", "مَا بَدِّي أَسْمَع."], correctIndex: 0, skill: "Pragmatics" },
            { prompt: "A woman named Lina introduces herself. Choose her natural sentence.", options: ["أنا اسمي لينا وأنا ساكنة بخان يونس.", "أنا اسمك لينا وهو ساكنة بخان يونس.", "أنا اسمي لينا وأنا ساكن بخان يونس."], correctIndex: 0, skill: "Integrated introduction" },
            { prompt: "Someone asks: مين هادا؟ Choose the answer that fits the question.", options: ["هاد أخوي.", "أنا من رفح.", "عالساعة تمانية."], correctIndex: 0, skill: "Question comprehension" },
            { prompt: "Choose: My mother does not drink coffee at night.", options: ["إمّي ما بتشرب قهوة بالليل.", "إمّي مش شربت قهوة بكرة.", "إمّي ما بشرب قهوة بالليل."], correctIndex: 0, skill: "Gender and negation" },
            { prompt: "You asked for two sandwiches but received one. Choose the clearest sentence.", options: ["أنا طلبت سندويشتين، مش سندويشة وحدة.", "بدّي وين الباص؟", "هي ساكنة مع أهلي."], correctIndex: 0, skill: "Quantity in context" },
            { prompt: "A driver asks وين بدّك تنزل؟ Choose the relevant response.", options: ["قبال الجامعة، لو سمحت.", "عندي أختين.", "كل يوم بصحى بكّير."], correctIndex: 0, skill: "Transport response" },
        ],
        speaking: {
            prompt: "Meet a new classmate. Introduce yourself and your family, describe your morning, say what food you like, and explain how you travel to class.",
            criteria: ["Task completion", "Understandable pronunciation", "Present-tense control", "Question formation", "Natural polite phrases"],
            maxScore: 10,
        },
        quiz: [], rolePlays: [], translation: [], sections: [],
    },
    homework: { instructions: "No homework. Use the result to choose the next review step." },
    teacherNotes: { myNotes: "" },
};
