export const lessonId = "Assessment-Intermediate-Final";
export const lesson = {
    meta: { level: "Intermediate", unit: "Intermediate Final", lessonTitle: "Intermediate Final Assessment", contentVersion: 2026071501, availableTabs: ["overview", "practice"] },
    overview: { title: "Intermediate Final", description: "A scored assessment of Units 11-15 with connected grammar, narration, and teacher-scored speaking.", goals: ["Measure past and future control.", "Measure object pronouns and connected sentences.", "Measure narration, opinions, and pragmatic language."], speakingOutcomes: ["The learner can narrate, explain, compare, and plan in connected Palestinian Arabic."] },
    vocabulary: { core: [], extra: [] }, dialogue: { title: "Assessment", setting: "Complete Practice.", lines: [] }, microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        assessmentMode: true, assessmentTitle: "Intermediate Final",
        questions: [
            { prompt: "Choose the polite disagreement.", options: ["فَاهِم عَلَيْك، بَس رَأْيِي مُخْتَلِف.", "إِنْتَ غَلَط.", "مَا بَدِّي أَسْمَع."], correctIndex: 0, skill: "Opinion" },
            { prompt: "Choose the advanced comparison.", options: ["هَادَا أَرْخَص مِن الأَوَّل.", "هَادَا أَرْخَص عَلَى الأَوَّل.", "هَادَا رْخِيص مِن."], correctIndex: 0, skill: "Comparison" },
            { prompt: "Choose the past form: She spoke.", options: ["هِيَّ حَكَت.", "هِيَّ حَكَى.", "هِيَّ بِتْحْكِي."], correctIndex: 0, skill: "Past tense" },
            { prompt: "Choose the past form: They went.", options: ["هُمَّ رَاحُوا.", "هُمَّ رُحْنَا.", "هُمَّ بِرُوحُوا."], correctIndex: 0, skill: "Past plural" },
            { prompt: "Choose: They promised me.", options: ["وَعَدُونِي", "وَعَدُوه", "وَعَدْتُه"], correctIndex: 0, skill: "Indirect object" },
            { prompt: "Choose: I told her.", options: ["حَكَيْتْلَهَا.", "حَكَيْتْلُه.", "حَكَتْلِي."], correctIndex: 0, skill: "Indirect object" },
            { prompt: "Choose the future sentence.", options: ["بُكْرَا رَاح نِلْتَقِي.", "اِمْبَارِح اِلْتَقَيْنَا.", "كُلّ يَوم بِنِلْتَقِي."], correctIndex: 0, skill: "Future" },
            { prompt: "Choose the negative future.", options: ["مِش رَاح أَتْأَخَّر.", "مَا تْأَخَّرْت.", "مِش مُتْأَخِّر."], correctIndex: 0, skill: "Future negation" },
            { prompt: "Choose the conditional sentence.", options: ["إِذَا مَا زَبَطَت، بِنْأَجِّلْهَا.", "بِنْأَجِّلْهَا اِمْبَارِح.", "مَا زَبَطَت لَأَنّ بُكْرَا."], correctIndex: 0, skill: "Condition" },
            { prompt: "Choose the frequency phrase.", options: ["تَلَات مَرَّات بِالأُسْبُوع", "تَلَات مَرَّة بِالأُسْبُوع", "تَلَات بِأُسْبُوع"], correctIndex: 0, skill: "Frequency" },
            { prompt: "Choose: They keep exercising.", options: ["هُمَّ بِضَلُّوا يِتْمَرَّنُوا.", "هُمَّ ضَلّ يِتْمَرَّن.", "هُمَّ رَاحُوا تَمْرِين."], correctIndex: 0, skill: "Continuity" },
            { prompt: "Choose the correct كان form: We were tired.", options: ["إِحْنَا كُنَّا تَعْبَانِين.", "إِحْنَا كَان تَعْبَان.", "إِحْنَا كُنْت تَعْبَان."], correctIndex: 0, skill: "كان" },
            { prompt: "Choose the cause connector.", options: ["لَأَنِّي", "بَعْدِين", "عَلَى حَسَب"], correctIndex: 0, skill: "Cause" },
            { prompt: "Choose the result connector.", options: ["عَشَان هِيك", "مَع إِنُّه", "قَبْل مَا"], correctIndex: 0, skill: "Result" },
            { prompt: "Choose the best connected narrative.", options: ["كُنْت مَضْغُوط عَشَان الشُّغُل، فَأَخَدْت رَاحَة وَبَعْدِين حَسِّيت حَالِي أَحْسَن.", "مَضْغُوط، شُغُل، رَاحَة، أَحْسَن.", "بُكْرَا اِمْبَارِح كُنْت."], correctIndex: 0, skill: "Narration" },
            { prompt: "Choose the sentence where a completed event interrupts an action in progress.", options: ["كنت عم بحكي مع الموظف لما انقطعت المكالمة.", "كل يوم بحكي مع الموظف.", "بكرة راح أحكي مع الموظف."], correctIndex: 0, skill: "Past continuous transfer" },
            { prompt: "Read: بعتنالهم الصور ورجّعولنا المصاري. What happened?", options: ["We sent them the photos, and they returned the money to us.", "They sent us the photos, and we returned their money.", "I sent her a photo, and she promised me money."], correctIndex: 0, skill: "Two-way object pronouns" },
            { prompt: "Choose the sentence with a logical cause and result.", options: ["ما حدا ردّ عليّ، عشان هيك رجعت اتصلت.", "رجعت اتصلت لأنه عشان هيك.", "ما حدا ردّ عليّ مع إنه لذلك."], correctIndex: 0, skill: "Cause-result transfer" },
            { prompt: "The appointment is confirmed for tomorrow at ten. Choose the most natural scheduled form.", options: ["بكرة بقابل المدير عالعشرة.", "بدّي يمكن أقابل المدير يوم.", "امبارح راح بقابل المدير."], correctIndex: 0, skill: "Scheduled future" },
            { prompt: "Read: بالبداية كانت خايفة، ولما حكولها الخبر صارت أهدى. What changed?", options: ["She moved from fear to feeling calmer after they told her the news.", "She was calm before they spoke and then became afraid.", "She plans to tell them the news tomorrow."], correctIndex: 0, skill: "Emotional change in narrative" },
        ],
        speaking: { prompt: "Tell one connected 90-second story. You compared two options and chose one, but a problem happened while you were doing something else. Explain whom you contacted, what they told or promised you, how your feeling changed, and what you will do if the problem happens again.", criteria: ["Complete timeline with a clear outcome", "Past and past-continuous control", "Accurate direct or indirect object pronouns", "Opinion, cause, contrast, and result connectors", "Future condition and natural comprehensibility"], maxScore: 10 },
        quiz: [], rolePlays: [], translation: [], sections: [],
    },
    homework: { instructions: "No homework. Use the result to choose advanced review topics." }, teacherNotes: { myNotes: "" },
};
