export const lessonId = "Assessment-PreIntermediate-Final";
export const lesson = {
    meta: { level: "Pre-Intermediate", unit: "Pre-Intermediate Final", lessonTitle: "Pre-Intermediate Final Assessment", contentVersion: 2026071501, availableTabs: ["overview", "practice"] },
    overview: { title: "Pre-Intermediate Final", description: "A scored assessment of Units 6-10. Answers are submitted together and speaking is teacher-scored.", goals: ["Measure grammar in context.", "Measure practical dialogue control.", "Identify readiness for Intermediate."], speakingOutcomes: ["The learner can manage a multi-part practical situation." ] },
    vocabulary: { core: [], extra: [] }, dialogue: { title: "Assessment", setting: "Complete Practice.", lines: [] }, microChecks: { enabled: false, every: 5, items: [] },
    practice: {
        assessmentMode: true, assessmentTitle: "Pre-Intermediate Final",
        questions: [
            { prompt: "Choose: They work in an office.", options: ["هُمَّ بِشْتِغْلُوا فِي مَكْتَب.", "هُوَّ بِشْتِغِل فِي مَكْتَب.", "إِحْنَا بِنْدْرُس."], correctIndex: 0, skill: "Present plural" },
            { prompt: "Choose the feminine form of busy.", options: ["مَشْغُولَة", "مَشْغُولِين", "شَاغِل"], correctIndex: 0, skill: "Agreement" },
            { prompt: "Choose the correct comparison.", options: ["اليَوم أَلْطَف مِن اِمْبَارِح.", "اليَوم أَلْطَف عَلَى اِمْبَارِح.", "اليَوم أَلْطَف مَع اِمْبَارِح."], correctIndex: 0, skill: "Comparison" },
            { prompt: "Choose non-human plural agreement.", options: ["السَّيَّارَات غَالْيَة.", "السَّيَّارَات غَالْيِين.", "السَّيَّارَات غَالِي."], correctIndex: 0, skill: "Non-human agreement" },
            { prompt: "Choose: Tomorrow the weather will be better.", options: ["بُكْرَا الجَوّ رَاح يِكُون أَحْسَن.", "بُكْرَا الجَوّ كَان أَحْسَن.", "بُكْرَا الجَوّ بِكُون اِمْبَارِح."], correctIndex: 0, skill: "Future exposure" },
            { prompt: "Choose the correct demonstrative agreement.", options: ["هَادِي الشَّنْطَة السُّودَا.", "هَادَا الشَّنْطَة الأَسْوَد.", "هَادِي القَمِيص الأَسْوَد."], correctIndex: 0, skill: "Shopping agreement" },
            { prompt: "Choose the quantity: half a kilo.", options: ["نُصّ كِيلُو", "تَلَات كِيلُو", "نُصّ شِيكِل"], correctIndex: 0, skill: "Numbers" },
            { prompt: "Choose the polite bargaining phrase.", options: ["مُمْكِن تْنَزِّل شُوَيّ؟", "هَادَا مِش حَلّ.", "مَا تِخَاف."], correctIndex: 0, skill: "Shopping dialogue" },
            { prompt: "Choose the direct object suffix: The doctor asked me.", options: ["الدُّكْتُور سَأَلْنِي.", "الدُّكْتُور سَأَلَك.", "الدُّكْتُور سَأَلُه."], correctIndex: 0, skill: "Direct object" },
            { prompt: "Choose the command to a woman.", options: ["خُدِي حَبَّة.", "خُد حَبَّة.", "خُدُوا حَبَّة."], correctIndex: 0, skill: "Imperative" },
            { prompt: "Choose the emergency sentence.", options: ["مَا بَقْدَر أَتْنَفَّس مْنِيح.", "مَا بَحِبّ الشُّوب.", "مَا عِنْدِي خَوَات."], correctIndex: 0, skill: "Health" },
            { prompt: "Choose the compound location: behind the closet.", options: ["وَرَا الخِزَانَة", "قُدَّام الخِزَانَة", "مَع الخِزَانَة"], correctIndex: 0, skill: "Location" },
            { prompt: "Choose the passive state for a feminine noun.", options: ["المَغْسَلَة مَسْدُودَة.", "المَغْسَلَة مَسْدُود.", "المَغْسَلَة بِسُدّ."], correctIndex: 0, skill: "Passive state" },
            { prompt: "Choose the past sentence.", options: ["المُمَرِّضَة قَاسَت الحَرَارَة.", "المُمَرِّضَة بِتْقِيس الحَرَارَة.", "المُمَرِّضَة رَاح تْقِيس الحَرَارَة."], correctIndex: 0, skill: "Past exposure" },
            { prompt: "Choose the polite repair request.", options: ["مُمْكِن تِبْعَت فَنِّي؟", "إِنْتَ غَلَط.", "مَا بَدِّي أَحْكِي."], correctIndex: 0, skill: "Pragmatics" },
            { prompt: "The female students have class from nine to one. Choose the sentence with correct human agreement.", options: ["الطالبات مشغولات من التسعة للواحدة.", "الطالبات مشغولة من التسعة للواحدة.", "الطالبات مشغول من التسعة للواحدة."], correctIndex: 0, skill: "Human plural agreement" },
            { prompt: "The streets are closed because of heavy rain. Choose the natural Palestinian agreement.", options: ["الشوارع مسكّرة عشان المطر القوي.", "الشوارع مسكّرين عشان المطر القوي.", "الشوارع مسكّر عشان المطر القوي."], correctIndex: 0, skill: "Non-human plural in context" },
            { prompt: "A seller says the jacket is 180 shekels. You want a lower price. Choose the best response.", options: ["ممكن تعملها مية وخمسين؟", "وين بوجعك؟", "المغسلة مسدودة."], correctIndex: 0, skill: "Bargaining response" },
            { prompt: "A woman has a fever and asks what to do. Choose the correctly addressed advice.", options: ["خدي هالدوا واشربي ميّ كتير.", "خد هالدوا واشرب ميّ كتير.", "خدوا هالدوا واشربوا ميّ كتير."], correctIndex: 0, skill: "Health instruction transfer" },
            { prompt: "Water is coming from the pipe below the kitchen sink. Choose the clearest repair report.", options: ["الماسورة اللي تحت مغسلة المطبخ بتنقّط.", "المطبخ أحسن من امبارح.", "أنا بدرس بالماسورة."], correctIndex: 0, skill: "Housing problem transfer" },
        ],
        speaking: { prompt: "You are moving closer to a new course. Explain your weekly schedule and transport, compare two possible areas, ask a seller about one household item, then call the landlord to report a new repair problem and request a specific solution.", criteria: ["Complete the connected situation", "Present tense and pronoun control", "Agreement, quantity, and comparison", "Clear questions and location language", "Polite but specific practical request"], maxScore: 10 },
        quiz: [], rolePlays: [], translation: [], sections: [],
    },
    homework: { instructions: "No homework. Use the score to plan review." }, teacherNotes: { myNotes: "" },
};
